# See https://packit.dev/docs/configuration/

specfile_path: tmp/rpm/selinux-policy.spec
upstream_tag_template: "v{version}"

actions:
  post-upstream-clone:
    - mkdir -p tmp/rpm
    - scripts/make-sources.sh tmp/rpm
  create-archive: sh -c 'ls tmp/rpm/selinux-policy*.tar.gz'

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - fedora-development
    - fedora-latest-stable

  # run tests for packages which test SELinux policy well, see plans/ with `revdeps == yes`
  - job: tests
    identifier: revdeps
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Cockpit tests failed for commit {commit_sha}. @martinpitt, @jelly, @mvollmer please check."
    targets:
    - fedora-development
    - fedora-latest-stable
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/repo/fedora-$releasever/group_cockpit-main-builds-fedora-$releasever.repo
          tmt:
            context:
              revdeps: "yes"
