# See https://packit.dev/docs/configuration/

specfile_path: tmp/rpm/selinux-policy.spec

actions:
  post-upstream-clone:
    - mkdir -p tmp/rpm
    - scripts/make-sources.sh tmp/rpm
  create-archive: sh -c 'ls tmp/rpm/selinux-policy*.tar.gz'

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - fedora-development
    - fedora-latest-stable

  - job: tests
    trigger: pull_request
    targets:
    - fedora-development
    - fedora-latest-stable
