#!/bin/sh
status=0
for i in *.log;do 
	name=`echo $i | cut -d'.' -f1`
	plugin=`sealert -a $i | grep "Plugin Name" | cut -d'.' -f2`
	if [ $name != $plugin ]; then
	    echo "$i incorrectly matched plugin $plugin"
	    status=1
	fi
done 
exit $status
