.TH  "admin_crontab_selinux"  "8"  "13-01-16" "admin_crontab" "SELinux Policy documentation for admin_crontab"
.SH "NAME"
admin_crontab_selinux \- Security Enhanced Linux Policy for the admin_crontab processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the admin_crontab processes via flexible mandatory access control.

The admin_crontab processes execute with the admin_crontab_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep admin_crontab_t


.SH "ENTRYPOINTS"

The admin_crontab_t SELinux type can be entered via the \fBcrontab_exec_t\fP file type.

The default entrypoint paths for the admin_crontab_t domain are the following:

/usr/bin/(f)?crontab, /usr/bin/at, /usr/sbin/fcronsighup
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux admin_crontab policy is very flexible allowing users to setup their admin_crontab processes in as secure a method as possible.
.PP
The following process types are defined for admin_crontab:

.EX
.B admin_crontab_t
.EE
.PP
Note:
.B semanage permissive -a admin_crontab_t
can be used to make the process type admin_crontab_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  admin_crontab policy is extremely flexible and has several booleans that allow you to manipulate the policy and run admin_crontab with the tightest access possible.


.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server, you must turn on the authlogin_nsswitch_use_ldap boolean. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to enable extra rules in the cron domain to support fcron, you must turn on the fcron_crond boolean. Disabled by default.

.EX
.B setsebool -P fcron_crond 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to run with kerberos, you must turn on the kerberos_enabled boolean. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you want to allow system to run with NIS, you must turn on the nis_enabled boolean. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.PP
If you want to support ecryptfs home directories, you must turn on the use_ecryptfs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_ecryptfs_home_dirs 1

.EE

.PP
If you want to support fusefs home directories, you must turn on the use_fusefs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_fusefs_home_dirs 1

.EE

.PP
If you want to support NFS home directories, you must turn on the use_nfs_home_dirs boolean. Enabled by default.

.EX
.B setsebool -P use_nfs_home_dirs 1

.EE

.PP
If you want to support SAMBA home directories, you must turn on the use_samba_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_samba_home_dirs 1

.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server for the admin_crontab_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the admin_crontab_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "MANAGED FILES"

The SELinux process type admin_crontab_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B admin_crontab_tmp_t


.br
.B cgroup_t

	/cgroup
.br
	/sys/fs/cgroup
.br

.br
.B faillog_t

	/var/log/btmp.*
.br
	/var/log/faillog.*
.br
	/var/log/tallylog.*
.br
	/var/run/faillock(/.*)?
.br

.br
.B security_t

	/selinux
.br

.br
.B user_cron_spool_t

	/var/spool/at(/.*)?
.br
	/var/spool/cron
.br

.br
.B user_tmp_t

	/var/run/user(/.*)?
.br
	/tmp/gconfd-.*
.br
	/tmp/gconfd-pwalsh
.br
	/tmp/gconfd-dwalsh
.br
	/tmp/gconfd-xguest
.br

.br
.B var_auth_t

	/var/ace(/.*)?
.br
	/var/rsa(/.*)?
.br
	/var/lib/abl(/.*)?
.br
	/var/lib/rsa(/.*)?
.br
	/var/lib/pam_ssh(/.*)?
.br
	/var/run/pam_ssh(/.*)?
.br
	/var/lib/pam_shield(/.*)?
.br
	/var/opt/quest/vas/vasd(/.*)?
.br
	/var/lib/google-authenticator(/.*)?
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), admin_crontab(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8)