.TH  "afs_fsserver_selinux"  "8"  "afs_fsserver" "dwalsh@redhat.com" "afs_fsserver SELinux Policy documentation"
.SH "NAME"
afs_fsserver_selinux \- Security Enhanced Linux Policy for the afs_fsserver processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the afs_fsserver processes via flexible mandatory access control.

The afs_fsserver processes execute with the afs_fsserver_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep afs_fsserver_t


.SH "ENTRYPOINTS"

The afs_fsserver_t SELinux type can be entered via the "afs_fsserver_exec_t" file type.  The default entrypoint paths for the afs_fsserver_t domain are the following:"

/usr/afs/bin/volserver, /usr/afs/bin/fileserver, /usr/afs/bin/salvager
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux afs_fsserver policy is very flexible allowing users to setup their afs_fsserver processes in as secure a method as possible.
.PP 
The following process types are defined for afs_fsserver:

.EX
.B afs_fsserver_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux afs_fsserver policy is very flexible allowing users to setup their afs_fsserver processes in as secure a method as possible.
.PP 
The following file types are defined for afs_fsserver:


.EX
.PP
.B afs_fsserver_exec_t 
.EE

- Set files with the afs_fsserver_exec_t type, if you want to transition an executable to the afs_fsserver_t domain.

.br
.TP 5
Paths: 
/usr/afs/bin/volserver, /usr/afs/bin/fileserver, /usr/afs/bin/salvager

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type afs_fsserver_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B afs_config_t

	/usr/afs/etc(/.*)?
.br
	/usr/afs/local(/.*)?
.br

.br
.B afs_files_t

	/vicepa
.br
	/vicepb
.br
	/vicepc
.br

.br
.B afs_logfile_t

	/usr/afs/logs(/.*)?
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), afs_fsserver(8), semanage(8), restorecon(8), chcon(1)
, afs_selinux(8), afs_selinux(8), afs_bosserver_selinux(8), afs_kaserver_selinux(8), afs_ptserver_selinux(8), afs_vlserver_selinux(8)