.TH  "afs_ptserver_selinux"  "8"  "afs_ptserver" "dwalsh@redhat.com" "afs_ptserver SELinux Policy documentation"
.SH "NAME"
afs_ptserver_selinux \- Security Enhanced Linux Policy for the afs_ptserver processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the afs_ptserver processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux afs_ptserver policy is very flexible allowing users to setup their afs_ptserver processes in as secure a method as possible.
.PP 
The following file types are defined for afs_ptserver:


.EX
.PP
.B afs_ptserver_exec_t 
.EE

- Set files with the afs_ptserver_exec_t type, if you want to transition an executable to the afs_ptserver_t domain.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux afs_ptserver policy is very flexible allowing users to setup their afs_ptserver processes in as secure a method as possible.
.PP 
The following process types are defined for afs_ptserver:

.EX
.B afs_ptserver_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type afs_ptserver_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B afs_logfile_t

	/usr/afs/logs(/.*)?
.br

.br
.B afs_pt_db_t

	/usr/afs/db/pr.*
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), afs_ptserver(8), semanage(8), restorecon(8), chcon(1)
, afs_selinux(8)