.TH  "apcupsd_selinux"  "8"  "apcupsd" "dwalsh@redhat.com" "apcupsd SELinux Policy documentation"
.SH "NAME"
apcupsd_selinux \- Security Enhanced Linux Policy for the apcupsd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the apcupsd processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux apcupsd policy is very flexible allowing users to setup their apcupsd processes in as secure a method as possible.
.PP 
The following file types are defined for apcupsd:


.EX
.B apcupsd_exec_t 
.EE

- Set files with the apcupsd_exec_t type, if you want to transition an executable to the apcupsd_t domain.

.br
Paths: 
/sbin/apcupsd, /usr/sbin/apcupsd
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B apcupsd_initrc_exec_t 
.EE

- Set files with the apcupsd_initrc_exec_t type, if you want to transition an executable to the apcupsd_initrc_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B apcupsd_lock_t 
.EE

- Set files with the apcupsd_lock_t type, if you want to treat the files as apcupsd lock data, stored under the /var/lock directory

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B apcupsd_log_t 
.EE

- Set files with the apcupsd_log_t type, if you want to treat the data as apcupsd log data, usually stored under the /var/log directory.

.br
Paths: 
/var/log/apcupsd\.status.*, /var/log/apcupsd\.events.*
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B apcupsd_tmp_t 
.EE

- Set files with the apcupsd_tmp_t type, if you want to store apcupsd temporary files in the /tmp directories.


.EX
.B apcupsd_var_run_t 
.EE

- Set files with the apcupsd_var_run_t type, if you want to store the apcupsd files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux apcupsd policy is very flexible allowing users to setup their apcupsd processes in as secure a method as possible.
.PP 
The following port types are defined for apcupsd:
.EX

.B apcupsd_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 3551
.EE
.B udp 3551
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), apcupsd(8), semanage(8), restorecon(8), chcon(1)
