.TH  "apmd_selinux"  "8"  "apmd" "dwalsh@redhat.com" "apmd SELinux Policy documentation"
.SH "NAME"
apmd_selinux \- Security Enhanced Linux Policy for the apmd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the apmd processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to login using a sssd serve for the apmd_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the apmd_t, you must turn on the allow_kerberos boolean.

.EX
setsebool -P allow_kerberos 1
.EE

.PP
If you want to allow system to run with NI for the apmd_t, you must turn on the allow_ypbind boolean.

.EX
setsebool -P allow_ypbind 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux apmd policy is very flexible allowing users to setup their apmd processes in as secure a method as possible.
.PP 
The following file types are defined for apmd:


.EX
.PP
.B apmd_exec_t 
.EE

- Set files with the apmd_exec_t type, if you want to transition an executable to the apmd_t domain.

.br
.TP 5
Paths: 
/usr/sbin/powersaved, /usr/sbin/acpid, /usr/sbin/apmd

.EX
.PP
.B apmd_lock_t 
.EE

- Set files with the apmd_lock_t type, if you want to treat the files as apmd lock data, stored under the /var/lock directory


.EX
.PP
.B apmd_log_t 
.EE

- Set files with the apmd_log_t type, if you want to treat the data as apmd log data, usually stored under the /var/log directory.


.EX
.PP
.B apmd_tmp_t 
.EE

- Set files with the apmd_tmp_t type, if you want to store apmd temporary files in the /tmp directories.


.EX
.PP
.B apmd_unit_file_t 
.EE

- Set files with the apmd_unit_file_t type, if you want to treat the files as apmd unit content.


.EX
.PP
.B apmd_var_run_t 
.EE

- Set files with the apmd_var_run_t type, if you want to store the apmd files under the /run directory.

.br
.TP 5
Paths: 
/var/run/\.?acpid\.socket, /var/run/apmd\.pid, /var/run/powersaved\.pid, /var/run/powersave_socket

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux apmd policy is very flexible allowing users to setup their apmd processes in as secure a method as possible.
.PP 
The following process types are defined for apmd:

.EX
.B apm_t, apmd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), apmd(8), semanage(8), restorecon(8), chcon(1)
