.TH  "apmd_selinux"  "8"  "apmd" "dwalsh@redhat.com" "apmd SELinux Policy documentation"
.SH "NAME"
apmd_selinux \- Security Enhanced Linux Policy for the apmd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the apmd processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux apmd policy is very flexible allowing users to setup their apmd processes in as secure a method as possible.
.PP 
The following file types are defined for apmd:


.EX
.B apmd_exec_t 
.EE

- Set files with the apmd_exec_t type, if you want to transition an executable to the apmd_t domain.

.br
Paths: 
/usr/sbin/powersaved, /usr/sbin/acpid, /usr/sbin/apmd
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B apmd_lock_t 
.EE

- Set files with the apmd_lock_t type, if you want to treat the files as apmd lock data, stored under the /var/lock directory


.EX
.B apmd_log_t 
.EE

- Set files with the apmd_log_t type, if you want to treat the data as apmd log data, usually stored under the /var/log directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B apmd_tmp_t 
.EE

- Set files with the apmd_tmp_t type, if you want to store apmd temporary files in the /tmp directories.


.EX
.B apmd_var_run_t 
.EE

- Set files with the apmd_var_run_t type, if you want to store the apmd files under the /run directory.

.br
Paths: 
/var/run/\.?acpid\.socket, /var/run/apmd\.pid, /var/run/powersaved\.pid, /var/run/powersave_socket
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), apmd(8), semanage(8), restorecon(8), chcon(1)
