.TH  "arpwatch_selinux"  "8"  "arpwatch" "dwalsh@redhat.com" "arpwatch SELinux Policy documentation"
.SH "NAME"
arpwatch_selinux \- Security Enhanced Linux Policy for the arpwatch processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the arpwatch processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux arpwatch policy is very flexible allowing users to setup their arpwatch processes in as secure a method as possible.
.PP 
The following file types are defined for arpwatch:


.EX
.B arpwatch_data_t 
.EE

- Set files with the arpwatch_data_t type, if you want to treat the files as arpwatch content.

.br
Paths: 
/var/arpwatch(/.*)?, /var/lib/arpwatch(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B arpwatch_exec_t 
.EE

- Set files with the arpwatch_exec_t type, if you want to transition an executable to the arpwatch_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B arpwatch_initrc_exec_t 
.EE

- Set files with the arpwatch_initrc_exec_t type, if you want to transition an executable to the arpwatch_initrc_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B arpwatch_tmp_t 
.EE

- Set files with the arpwatch_tmp_t type, if you want to store arpwatch temporary files in the /tmp directories.


.EX
.B arpwatch_var_run_t 
.EE

- Set files with the arpwatch_var_run_t type, if you want to store the arpwatch files under the /run directory.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), arpwatch(8), semanage(8), restorecon(8), chcon(1)
