.TH  "asterisk_selinux"  "8"  "asterisk" "dwalsh@redhat.com" "asterisk SELinux Policy documentation"
.SH "NAME"
asterisk_selinux \- Security Enhanced Linux Policy for the asterisk processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the asterisk processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux asterisk policy is very flexible allowing users to setup their asterisk processes in as secure a method as possible.
.PP 
The following file types are defined for asterisk:


.EX
.B asterisk_etc_t 
.EE

- Set files with the asterisk_etc_t type, if you want to store asterisk files in the /etc directories.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B asterisk_exec_t 
.EE

- Set files with the asterisk_exec_t type, if you want to transition an executable to the asterisk_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B asterisk_initrc_exec_t 
.EE

- Set files with the asterisk_initrc_exec_t type, if you want to transition an executable to the asterisk_initrc_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B asterisk_log_t 
.EE

- Set files with the asterisk_log_t type, if you want to treat the data as asterisk log data, usually stored under the /var/log directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B asterisk_spool_t 
.EE

- Set files with the asterisk_spool_t type, if you want to store the asterisk files under the /var/spool directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B asterisk_tmp_t 
.EE

- Set files with the asterisk_tmp_t type, if you want to store asterisk temporary files in the /tmp directories.


.EX
.B asterisk_tmpfs_t 
.EE

- Set files with the asterisk_tmpfs_t type, if you want to store asterisk files on a tmpfs file system.


.EX
.B asterisk_var_lib_t 
.EE

- Set files with the asterisk_var_lib_t type, if you want to store the asterisk files under the /var/lib directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B asterisk_var_run_t 
.EE

- Set files with the asterisk_var_run_t type, if you want to store the asterisk files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux asterisk policy is very flexible allowing users to setup their asterisk processes in as secure a method as possible.
.PP 
The following port types are defined for asterisk:
.EX

.B asterisk_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 1720
.EE
.B udp 2427,2727,4569
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), asterisk(8), semanage(8), restorecon(8), chcon(1)
