.TH  "auditadm_selinux"  "8"  "auditadm" "mgrepl@redhat.com" "auditadm SELinux Policy documentation"
.SH "NAME"
auditadm_r \- \fBAudit administrator role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

SELinux supports Roles Based Access Control (RBAC), some Linux roles are login roles, while other roles need to be transition into. 

.I Note: 
Examples in this man page will use the 
.B staff_u 
SELinux user.

Non login roles are usually used for administrative tasks. For example, tasks that require root privileges.  Roles control which types a user can run processes with. Roles often have default types assigned to them. 

The default type for the auditadm_r role is auditadm_t.

The 
.B newrole 
program to transition directly to this role.

.B newrole -r auditadm_r -t auditadm_t

.B sudo 
is the preferred method to do transition from one role to another.  You setup sudo to transition to auditadm_r by adding a similar line to the /etc/sudoers file.

USERNAME ALL=(ALL) ROLE=auditadm_r TYPE=auditadm_t COMMAND

.br
sudo will run COMMAND as staff_u:auditadm_r:auditadm_t:LEVEL

When using a a non login role, you need to setup SELinux so that your SELinux user can reach auditadm_r role.

Execute the following to see all of the assigned SELinux roles:

.B semanage user -l

You need to add auditadm_r to the staff_u user.  You could setup the staff_u user to be able to use the auditadm_r role with a command like:

.B $ semanage user -m -R 'staff_r system_r auditadm_r' staff_u 



SELinux policy also controls which roles can transition to a different role.  
You can list these rules using the following command.

.B sesearch --role_allow

SELinux policy allows the sysadm_r, secadm_r, staff_r roles can transition to the auditadm_r role.


.SH "MANAGED FILES"

The SELinux user type auditadm_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B anon_inodefs_t


.br
.B auditd_etc_t

	/etc/audit(/.*)?
.br

.br
.B auditd_log_t

	/var/log/audit(/.*)?
.br
	/var/log/audit\.log
.br

.br
.B auth_cache_t

	/var/cache/coolkey(/.*)?
.br

.br
.B cgroup_t

	/cgroup
.br
	/sys/fs/cgroup
.br

.br
.B chrome_sandbox_tmpfs_t


.br
.B games_data_t

	/var/games(/.*)?
.br
	/var/lib/games(/.*)?
.br

.br
.B gpg_agent_tmp_t

	/home/[^/]*/\.gnupg/log-socket
.br

.br
.B mail_spool_t

	/var/mail(/.*)?
.br
	/var/spool/imap(/.*)?
.br
	/var/spool/mail(/.*)?
.br

.br
.B mqueue_spool_t

	/var/spool/(client)?mqueue(/.*)?
.br
	/var/spool/mqueue\.in(/.*)?
.br

.br
.B nfsd_rw_t


.br
.B noxattrfs

	all files on file systems which do not support extended attributes
.br

.br
.B screen_home_t

	/root/\.screen(/.*)?
.br
	/home/[^/]*/\.screen(/.*)?
.br
	/home/[^/]*/\.screenrc
.br

.br
.B security_t

	/selinux
.br

.br
.B usbfs_t


.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br

.br
.B user_home_type

	all user home files
.br

.br
.B user_tmp_type

	all user tmp files
.br

.br
.B user_tmpfs_type

	all user content in tmpfs file systems
.br

.br
.B xdm_tmp_t

	/tmp/\.X11-unix(/.*)?
.br
	/tmp/\.ICE-unix(/.*)?
.br
	/tmp/\.X0-lock
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), auditadm(8), semanage(8), restorecon(8), chcon(1)
