.TH  "auditadm_gkeyringd_selinux"  "8"  "13-01-16" "auditadm_gkeyringd" "SELinux Policy documentation for auditadm_gkeyringd"
.SH "NAME"
auditadm_gkeyringd_selinux \- Security Enhanced Linux Policy for the auditadm_gkeyringd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the auditadm_gkeyringd processes via flexible mandatory access control.

The auditadm_gkeyringd processes execute with the auditadm_gkeyringd_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep auditadm_gkeyringd_t


.SH "ENTRYPOINTS"

The auditadm_gkeyringd_t SELinux type can be entered via the \fBgkeyringd_exec_t\fP file type.

The default entrypoint paths for the auditadm_gkeyringd_t domain are the following:

/usr/bin/gnome-keyring-daemon
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux auditadm_gkeyringd policy is very flexible allowing users to setup their auditadm_gkeyringd processes in as secure a method as possible.
.PP
The following process types are defined for auditadm_gkeyringd:

.EX
.B auditadm_gkeyringd_t
.EE
.PP
Note:
.B semanage permissive -a auditadm_gkeyringd_t
can be used to make the process type auditadm_gkeyringd_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  auditadm_gkeyringd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run auditadm_gkeyringd with the tightest access possible.


.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server, you must turn on the authlogin_nsswitch_use_ldap boolean. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to run with kerberos, you must turn on the kerberos_enabled boolean. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you want to allow system to run with NIS, you must turn on the nis_enabled boolean. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.PP
If you want to support ecryptfs home directories, you must turn on the use_ecryptfs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_ecryptfs_home_dirs 1

.EE

.PP
If you want to support fusefs home directories, you must turn on the use_fusefs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_fusefs_home_dirs 1

.EE

.PP
If you want to support NFS home directories, you must turn on the use_nfs_home_dirs boolean. Enabled by default.

.EX
.B setsebool -P use_nfs_home_dirs 1

.EE

.PP
If you want to support SAMBA home directories, you must turn on the use_samba_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_samba_home_dirs 1

.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server for the auditadm_gkeyringd_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the auditadm_gkeyringd_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "MANAGED FILES"

The SELinux process type auditadm_gkeyringd_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B cache_home_t

	/root/\.cache(/.*)?
.br
	/home/[^/]*/\.nv(/.*)?
.br
	/home/[^/]*/\.cache(/.*)?
.br
	/home/pwalsh/\.nv(/.*)?
.br
	/home/pwalsh/\.cache(/.*)?
.br
	/home/dwalsh/\.nv(/.*)?
.br
	/home/dwalsh/\.cache(/.*)?
.br
	/var/lib/xguest/home/xguest/\.nv(/.*)?
.br
	/var/lib/xguest/home/xguest/\.cache(/.*)?
.br

.br
.B cifs_t


.br
.B config_home_t

	/root/\.kde(/.*)?
.br
	/root/\.xine(/.*)?
.br
	/root/\.config(/.*)?
.br
	/var/run/user/[^/]*/dconf(/.*)?
.br
	/root/\.Xdefaults
.br
	/home/[^/]*/\.kde(/.*)?
.br
	/home/[^/]*/\.xine(/.*)?
.br
	/home/[^/]*/\.config(/.*)?
.br
	/home/[^/]*/\.Xdefaults
.br
	/home/pwalsh/\.kde(/.*)?
.br
	/home/pwalsh/\.xine(/.*)?
.br
	/home/pwalsh/\.config(/.*)?
.br
	/home/pwalsh/\.Xdefaults
.br
	/home/dwalsh/\.kde(/.*)?
.br
	/home/dwalsh/\.xine(/.*)?
.br
	/home/dwalsh/\.config(/.*)?
.br
	/home/dwalsh/\.Xdefaults
.br
	/var/lib/xguest/home/xguest/\.kde(/.*)?
.br
	/var/lib/xguest/home/xguest/\.xine(/.*)?
.br
	/var/lib/xguest/home/xguest/\.config(/.*)?
.br
	/var/lib/xguest/home/xguest/\.Xdefaults
.br

.br
.B ecryptfs_t

	/home/[^/]*/\.Private(/.*)?
.br
	/home/[^/]*/\.ecryptfs(/.*)?
.br
	/home/pwalsh/\.Private(/.*)?
.br
	/home/pwalsh/\.ecryptfs(/.*)?
.br
	/home/dwalsh/\.Private(/.*)?
.br
	/home/dwalsh/\.ecryptfs(/.*)?
.br
	/var/lib/xguest/home/xguest/\.Private(/.*)?
.br
	/var/lib/xguest/home/xguest/\.ecryptfs(/.*)?
.br

.br
.B fusefs_t


.br
.B gkeyringd_gnome_home_t

	/root/\.gnome2/keyrings(/.*)?
.br
	/home/[^/]*/\.gnome2/keyrings(/.*)?
.br
	/home/[^/]*/\.local/share/keyrings(/.*)?
.br
	/home/pwalsh/\.gnome2/keyrings(/.*)?
.br
	/home/pwalsh/\.local/share/keyrings(/.*)?
.br
	/home/dwalsh/\.gnome2/keyrings(/.*)?
.br
	/home/dwalsh/\.local/share/keyrings(/.*)?
.br
	/var/lib/xguest/home/xguest/\.gnome2/keyrings(/.*)?
.br
	/var/lib/xguest/home/xguest/\.local/share/keyrings(/.*)?
.br

.br
.B nfs_t


.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), auditadm_gkeyringd(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), auditadm_selinux(8), auditadm_selinux(8), auditadm_dbusd_selinux(8), auditadm_screen_selinux(8), auditadm_seunshare_selinux(8), auditadm_su_selinux(8), auditadm_sudo_selinux(8), auditadm_wine_selinux(8)