.TH  "boinc_selinux"  "8"  "boinc" "dwalsh@redhat.com" "boinc SELinux Policy documentation"
.SH "NAME"
boinc_selinux \- Security Enhanced Linux Policy for the boinc processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the boinc processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux boinc policy is very flexible allowing users to setup their boinc processes in as secure a method as possible.
.PP 
The following file types are defined for boinc:


.EX
.B boinc_exec_t 
.EE

- Set files with the boinc_exec_t type, if you want to transition an executable to the boinc_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B boinc_initrc_exec_t 
.EE

- Set files with the boinc_initrc_exec_t type, if you want to transition an executable to the boinc_initrc_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B boinc_project_tmp_t 
.EE

- Set files with the boinc_project_tmp_t type, if you want to store boinc project temporary files in the /tmp directories.


.EX
.B boinc_project_var_lib_t 
.EE

- Set files with the boinc_project_var_lib_t type, if you want to store the boinc project files under the /var/lib directory.

.br
Paths: 
/var/lib/boinc/projects(/.*)?, /var/lib/boinc/slots(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B boinc_tmp_t 
.EE

- Set files with the boinc_tmp_t type, if you want to store boinc temporary files in the /tmp directories.


.EX
.B boinc_tmpfs_t 
.EE

- Set files with the boinc_tmpfs_t type, if you want to store boinc files on a tmpfs file system.


.EX
.B boinc_var_lib_t 
.EE

- Set files with the boinc_var_lib_t type, if you want to store the boinc files under the /var/lib directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux boinc policy is very flexible allowing users to setup their boinc processes in as secure a method as possible.
.PP 
The following port types are defined for boinc:
.EX

.B boinc_client_ctrl_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 1043
.EE
.EX

.B boinc_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 31416
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), boinc(8), semanage(8), restorecon(8), chcon(1)
