.TH  "boinc_selinux"  "8"  "13-01-16" "boinc" "SELinux Policy documentation for boinc"
.SH "NAME"
boinc_selinux \- Security Enhanced Linux Policy for the boinc processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the boinc processes via flexible mandatory access control.

The boinc processes execute with the boinc_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep boinc_t


.SH "ENTRYPOINTS"

The boinc_t SELinux type can be entered via the \fBboinc_exec_t\fP file type.

The default entrypoint paths for the boinc_t domain are the following:

/usr/bin/boinc_client
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux boinc policy is very flexible allowing users to setup their boinc processes in as secure a method as possible.
.PP
The following process types are defined for boinc:

.EX
.B boinc_t, boinc_project_t
.EE
.PP
Note:
.B semanage permissive -a boinc_t
can be used to make the process type boinc_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  boinc policy is extremely flexible and has several booleans that allow you to manipulate the policy and run boinc with the tightest access possible.


.PP
If you want to allow all daemons to write corefiles to /, you must turn on the daemons_dump_core boolean. Disabled by default.

.EX
.B setsebool -P daemons_dump_core 1

.EE

.PP
If you want to allow all daemons to use tcp wrappers, you must turn on the daemons_use_tcp_wrapper boolean. Disabled by default.

.EX
.B setsebool -P daemons_use_tcp_wrapper 1

.EE

.PP
If you want to allow all daemons the ability to read/write terminals, you must turn on the daemons_use_tty boolean. Disabled by default.

.EX
.B setsebool -P daemons_use_tty 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports.
.PP
You can see the types associated with a port by using the following command:

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports.
SELinux boinc policy is very flexible allowing users to setup their boinc processes in as secure a method as possible.
.PP
The following port types are defined for boinc:

.EX
.TP 5
.B boinc_client_port_t
.TP 10
.EE


Default Defined Ports:
tcp 1043
.EE
udp 1034
.EE

.EX
.TP 5
.B boinc_port_t
.TP 10
.EE


Default Defined Ports:
tcp 31416
.EE
.SH "MANAGED FILES"

The SELinux process type boinc_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B boinc_log_t

	/var/log/boinc\.log.*
.br

.br
.B boinc_project_var_lib_t

	/var/lib/boinc/slots(/.*)?
.br
	/var/lib/boinc/projects(/.*)?
.br

.br
.B boinc_tmp_t


.br
.B boinc_tmpfs_t


.br
.B boinc_var_lib_t

	/var/lib/boinc(/.*)?
.br

.br
.B root_t

	/
.br
	/initrd
.br

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux boinc policy is very flexible allowing users to setup their boinc processes in as secure a method as possible.
.PP

.PP
.B EQUIVALENCE DIRECTORIES

.PP
boinc policy stores data with multiple different file context types under the /var/lib/boinc directory.  If you would like to store the data in a different directory you can use the semanage command to create an equivalence mapping.  If you wanted to store this data under the /srv dirctory you would execute the following command:
.PP
.B semanage fcontext -a -e /var/lib/boinc /srv/boinc
.br
.B restorecon -R -v /srv/boinc
.PP

.PP
.B STANDARD FILE CONTEXT

SELinux defines the file context types for the boinc, if you wanted to
store files with these types in a diffent paths, you need to execute the semanage command to sepecify alternate labeling and then use restorecon to put the labels on disk.

.B semanage fcontext -a -t boinc_exec_t '/srv/boinc/content(/.*)?'
.br
.B restorecon -R -v /srv/myboinc_content

Note: SELinux often uses regular expressions to specify labels that match multiple files.

.I The following file types are defined for boinc:


.EX
.PP
.B boinc_exec_t
.EE

- Set files with the boinc_exec_t type, if you want to transition an executable to the boinc_t domain.


.EX
.PP
.B boinc_initrc_exec_t
.EE

- Set files with the boinc_initrc_exec_t type, if you want to transition an executable to the boinc_initrc_t domain.


.EX
.PP
.B boinc_log_t
.EE

- Set files with the boinc_log_t type, if you want to treat the data as boinc log data, usually stored under the /var/log directory.


.EX
.PP
.B boinc_project_tmp_t
.EE

- Set files with the boinc_project_tmp_t type, if you want to store boinc project temporary files in the /tmp directories.


.EX
.PP
.B boinc_project_var_lib_t
.EE

- Set files with the boinc_project_var_lib_t type, if you want to store the boinc project files under the /var/lib directory.

.br
.TP 5
Paths:
/var/lib/boinc/slots(/.*)?, /var/lib/boinc/projects(/.*)?

.EX
.PP
.B boinc_tmp_t
.EE

- Set files with the boinc_tmp_t type, if you want to store boinc temporary files in the /tmp directories.


.EX
.PP
.B boinc_tmpfs_t
.EE

- Set files with the boinc_tmpfs_t type, if you want to store boinc files on a tmpfs file system.


.EX
.PP
.B boinc_unit_file_t
.EE

- Set files with the boinc_unit_file_t type, if you want to treat the files as boinc unit content.


.EX
.PP
.B boinc_var_lib_t
.EE

- Set files with the boinc_var_lib_t type, if you want to store the boinc files under the /var/lib directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), boinc(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), boinc_project_selinux(8)