.TH  "bootloader_selinux"  "8"  "bootloader" "dwalsh@redhat.com" "bootloader SELinux Policy documentation"
.SH "NAME"
bootloader_selinux \- Security Enhanced Linux Policy for the bootloader processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the bootloader processes via flexible mandatory access control.

The bootloader processes execute with the bootloader_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep bootloader_t


.SH "ENTRYPOINTS"

The bootloader_t SELinux type can be entered via the "bootloader_exec_t" file type.  The default entrypoint paths for the bootloader_t domain are the following:"

/usr/sbin/ybin.*, /usr/sbin/zipl, /sbin/lilo.*, /sbin/ybin.*, /usr/sbin/lilo.*, /sbin/grub.*, /sbin/zipl, /usr/sbin/grub.*
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux bootloader policy is very flexible allowing users to setup their bootloader processes in as secure a method as possible.
.PP 
The following process types are defined for bootloader:

.EX
.B bootloader_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  bootloader policy is extremely flexible and has several booleans that allow you to manipulate the policy and run bootloader with the tightest access possible.


.PP
If you want to allow the graphical login program to execute bootloader, you must turn on the xdm_exec_bootloader boolean.

.EX
.B setsebool -P xdm_exec_bootloader 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux bootloader policy is very flexible allowing users to setup their bootloader processes in as secure a method as possible.
.PP 
The following file types are defined for bootloader:


.EX
.PP
.B bootloader_etc_t 
.EE

- Set files with the bootloader_etc_t type, if you want to store bootloader files in the /etc directories.

.br
.TP 5
Paths: 
/etc/zipl\.conf.*, /etc/yaboot\.conf.*, /etc/default/grub, /etc/lilo\.conf.*

.EX
.PP
.B bootloader_exec_t 
.EE

- Set files with the bootloader_exec_t type, if you want to transition an executable to the bootloader_t domain.

.br
.TP 5
Paths: 
/usr/sbin/ybin.*, /usr/sbin/zipl, /sbin/lilo.*, /sbin/ybin.*, /usr/sbin/lilo.*, /sbin/grub.*, /sbin/zipl, /usr/sbin/grub.*

.EX
.PP
.B bootloader_tmp_t 
.EE

- Set files with the bootloader_tmp_t type, if you want to store bootloader temporary files in the /tmp directories.


.EX
.PP
.B bootloader_var_run_t 
.EE

- Set files with the bootloader_var_run_t type, if you want to store the bootloader files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type bootloader_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B boot_t

	/boot/.*
.br
	/vmlinuz.*
.br
	/initrd\.img.*
.br
	/boot
.br

.br
.B bootloader_tmp_t


.br
.B bootloader_var_run_t


.br
.B dosfs_t


.br
.B etc_runtime_t

	/[^/]+
.br
	/etc/mtab.*
.br
	/etc/blkid(/.*)?
.br
	/etc/nologin.*
.br
	/etc/\.fstab\.hal\..+
.br
	/halt
.br
	/fastboot
.br
	/poweroff
.br
	/etc/cmtab
.br
	/forcefsck
.br
	/\.autofsck
.br
	/\.suspended
.br
	/fsckoptions
.br
	/\.autorelabel
.br
	/etc/securetty
.br
	/etc/nohotplug
.br
	/etc/killpower
.br
	/etc/ioctl\.save
.br
	/etc/fstab\.REVOKE
.br
	/etc/network/ifstate
.br
	/etc/sysconfig/hwconf
.br
	/etc/ptal/ptal-printd-like
.br
	/etc/sysconfig/iptables\.save
.br
	/etc/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br
	/etc/X11/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br

.br
.B file_t


.br
.B fsadm_var_run_t

	/var/run/blkid(/.*)?
.br

.br
.B modules_object_t

	/lib/modules(/.*)?
.br
	/usr/lib/modules(/.*)?
.br

.br
.B var_log_t

	/var/log/.*
.br
	/nsr/logs(/.*)?
.br
	/var/webmin(/.*)?
.br
	/var/log/cron[^/]*
.br
	/var/log/secure[^/]*
.br
	/opt/zimbra/log(/.*)?
.br
	/var/log/maillog[^/]*
.br
	/var/log/spooler[^/]*
.br
	/var/log/messages[^/]*
.br
	/usr/centreon/log(/.*)?
.br
	/var/spool/rsyslog(/.*)?
.br
	/var/axfrdns/log/main(/.*)?
.br
	/var/spool/bacula/log(/.*)?
.br
	/var/tinydns/log/main(/.*)?
.br
	/var/dnscache/log/main(/.*)?
.br
	/var/stockmaniac/templates_cache(/.*)?
.br
	/opt/Symantec/scspagent/IDS/system(/.*)?
.br
	/var/log
.br
	/var/log/dmesg
.br
	/var/log/syslog
.br
	/var/log/boot\.log
.br
	/var/named/chroot/var/log
.br
	/var/spool/plymouth/boot\.log
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the bootloader_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the bootloader_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), bootloader(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)