.TH  "cachefiles_kernel_selinux"  "8"  "13-01-16" "cachefiles_kernel" "SELinux Policy documentation for cachefiles_kernel"
.SH "NAME"
cachefiles_kernel_selinux \- Security Enhanced Linux Policy for the cachefiles_kernel processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the cachefiles_kernel processes via flexible mandatory access control.

The cachefiles_kernel processes execute with the cachefiles_kernel_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep cachefiles_kernel_t


.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux cachefiles_kernel policy is very flexible allowing users to setup their cachefiles_kernel processes in as secure a method as possible.
.PP
The following process types are defined for cachefiles_kernel:

.EX
.B cachefiles_kernel_t
.EE
.PP
Note:
.B semanage permissive -a cachefiles_kernel_t
can be used to make the process type cachefiles_kernel_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  cachefiles_kernel policy is extremely flexible and has several booleans that allow you to manipulate the policy and run cachefiles_kernel with the tightest access possible.


.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.SH "MANAGED FILES"

The SELinux process type cachefiles_kernel_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B cachefiles_var_t

	/var/fscache(/.*)?
.br
	/var/cache/fscache(/.*)?
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), cachefiles_kernel(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), cachefilesd_selinux(8)