.TH  "calamaris_selinux"  "8"  "calamaris" "dwalsh@redhat.com" "calamaris SELinux Policy documentation"
.SH "NAME"
calamaris_selinux \- Security Enhanced Linux Policy for the calamaris processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the calamaris processes via flexible mandatory access control.

The calamaris processes execute with the calamaris_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep calamaris_t


.SH "ENTRYPOINTS"

The calamaris_t SELinux type can be entered via the "calamaris_exec_t" file type.  The default entrypoint paths for the calamaris_t domain are the following:"

/etc/cron\.daily/calamaris
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux calamaris policy is very flexible allowing users to setup their calamaris processes in as secure a method as possible.
.PP 
The following process types are defined for calamaris:

.EX
.B calamaris_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux calamaris policy is very flexible allowing users to setup their calamaris processes in as secure a method as possible.
.PP 
The following file types are defined for calamaris:


.EX
.PP
.B calamaris_exec_t 
.EE

- Set files with the calamaris_exec_t type, if you want to transition an executable to the calamaris_t domain.


.EX
.PP
.B calamaris_log_t 
.EE

- Set files with the calamaris_log_t type, if you want to treat the data as calamaris log data, usually stored under the /var/log directory.


.EX
.PP
.B calamaris_www_t 
.EE

- Set files with the calamaris_www_t type, if you want to treat the files as calamaris www data.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type calamaris_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B calamaris_log_t

	/var/log/calamaris(/.*)?
.br

.br
.B calamaris_www_t

	/var/www/calamaris(/.*)?
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the calamaris_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the calamaris_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), calamaris(8), semanage(8), restorecon(8), chcon(1)
