.TH  "cardmgr_selinux"  "8"  "cardmgr" "dwalsh@redhat.com" "cardmgr SELinux Policy documentation"
.SH "NAME"
cardmgr_selinux \- Security Enhanced Linux Policy for the cardmgr processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the cardmgr processes via flexible mandatory access control.

The cardmgr processes execute with the cardmgr_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep cardmgr_t


.SH "ENTRYPOINTS"

The cardmgr_t SELinux type can be entered via the "cardmgr_exec_t,cardctl_exec_t" file types.  The default entrypoint paths for the cardmgr_t domain are the following:"

/sbin/cardmgr, /etc/apm/event\.d/pcmcia, /usr/sbin/cardmgr, /sbin/cardctl, /usr/sbin/cardctl
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux cardmgr policy is very flexible allowing users to setup their cardmgr processes in as secure a method as possible.
.PP 
The following process types are defined for cardmgr:

.EX
.B cardmgr_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux cardmgr policy is very flexible allowing users to setup their cardmgr processes in as secure a method as possible.
.PP 
The following file types are defined for cardmgr:


.EX
.PP
.B cardmgr_dev_t 
.EE

- Set files with the cardmgr_dev_t type, if you want to treat the files as cardmgr dev data.


.EX
.PP
.B cardmgr_exec_t 
.EE

- Set files with the cardmgr_exec_t type, if you want to transition an executable to the cardmgr_t domain.

.br
.TP 5
Paths: 
/sbin/cardmgr, /etc/apm/event\.d/pcmcia, /usr/sbin/cardmgr

.EX
.PP
.B cardmgr_lnk_t 
.EE

- Set files with the cardmgr_lnk_t type, if you want to treat the files as cardmgr lnk data.


.EX
.PP
.B cardmgr_var_lib_t 
.EE

- Set files with the cardmgr_var_lib_t type, if you want to store the cardmgr files under the /var/lib directory.


.EX
.PP
.B cardmgr_var_run_t 
.EE

- Set files with the cardmgr_var_run_t type, if you want to store the cardmgr files under the /run directory.

.br
.TP 5
Paths: 
/var/run/cardmgr\.pid, /var/run/stab, /var/lib/pcmcia(/.*)?

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type cardmgr_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B cardmgr_var_lib_t


.br
.B cardmgr_var_run_t

	/var/lib/pcmcia(/.*)?
.br
	/var/run/stab
.br
	/var/run/cardmgr\.pid
.br

.br
.B net_conf_t

	/etc/ntpd?\.conf.*
.br
	/etc/hosts[^/]*
.br
	/etc/yp\.conf.*
.br
	/etc/denyhosts.*
.br
	/etc/hosts\.deny.*
.br
	/etc/resolv\.conf.*
.br
	/etc/ntp/step-tickers.*
.br
	/etc/sysconfig/networking(/.*)?
.br
	/etc/sysconfig/network-scripts(/.*)?
.br
	/etc/sysconfig/network-scripts/.*resolv\.conf
.br
	/etc/ethers
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), cardmgr(8), semanage(8), restorecon(8), chcon(1)
