.TH  "ccs_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "ccs Selinux Policy documentation"
.SH "NAME"
ccs_selinux \- Security Enhanced Linux Policy for the ccs processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ccs processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux ccs policy is very flexible allowing users to setup their ccs processes in as secure a method as possible.
.PP 
The following file types are defined for ccs:


.EX
.B ccs_exec_t 
.EE

- Set files with the ccs_exec_t context, if you want to a executable to transition to the ccs_t domain.


.EX
.B ccs_tmp_t 
.EE

- Set files with the ccs_tmp_t context, if you want to store ccs temporary files in the /tmp directories.


.EX
.B ccs_tmpfs_t 
.EE

- Set files with the ccs_tmpfs_t context, if you want to store ccs files on a tmpfs file system.


.EX
.B ccs_var_lib_t 
.EE

- Set files with the ccs_var_lib_t context, if you want to store the ccs files under the /var/lib directory.


.EX
.B ccs_var_log_t 
.EE

- Set files with the ccs_var_log_t context, if you want to treat the data as ccs var log data, usually stored in /var/log.


.EX
.B ccs_var_run_t 
.EE

- Set files with the ccs_var_run_t context, if you want to store the ccs files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  ccs policy is extremely flexible and has several booleans that allow you to manipulate the policy and run ccs with the tightest access possible.


.PP
If you want to allow ftp servers to login to local users and read/write all files on the system, governed by DAC., you must turn on the allow_ftpd_full_access boolean.

.EX
.B setsebool -P allow_ftpd_full_access 1
.EE

.PP
If you want to allow sftp-internal to login to local users and read/write all files on the system, governed by DAC., you must turn on the sftpd_full_access boolean.

.EX
.B setsebool -P sftpd_full_access 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), ccs(8), semanage(8), restorecon(8), chcon(1), setsebool(8)