.TH  "certmaster_selinux"  "8"  "certmaster" "dwalsh@redhat.com" "certmaster Selinux Policy documentation"
.SH "NAME"
certmaster_selinux \- Security Enhanced Linux Policy for the certmaster processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the certmaster processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux certmaster policy is very flexible allowing users to setup their certmaster processes in as secure a method as possible.
.PP 
The following file types are defined for certmaster:


.EX
.B certmaster_etc_rw_t 
.EE

- Set files with the certmaster_etc_rw_t context, if you want to treat the files as certmaster etc read/write content.

.br
Path: 
/etc/certmaster(/.*)?

.EX
.B certmaster_exec_t 
.EE

- Set files with the certmaster_exec_t context, if you want to a executable to transition to the certmaster_t domain.

.br
Path: 
/usr/bin/certmaster

.EX
.B certmaster_initrc_exec_t 
.EE

- Set files with the certmaster_initrc_exec_t context, if you want to a executable to transition to the certmaster_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/certmaster

.EX
.B certmaster_var_lib_t 
.EE

- Set files with the certmaster_var_lib_t context, if you want to store the certmaster files under the /var/lib directory.

.br
Path: 
/var/lib/certmaster(/.*)?

.EX
.B certmaster_var_log_t 
.EE

- Set files with the certmaster_var_log_t context, if you want to treat the data as certmaster var log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/certmaster(/.*)?

.EX
.B certmaster_var_run_t 
.EE

- Set files with the certmaster_var_run_t context, if you want to store the certmaster files under the /run directory.

.br
Path: 
/var/run/certmaster.*
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), certmaster(8), semanage(8), restorecon(8), chcon(1)
