.TH  "chroot_user_selinux"  "8"  "13-01-16" "chroot_user" "SELinux Policy documentation for chroot_user"
.SH "NAME"
chroot_user_selinux \- Security Enhanced Linux Policy for the chroot_user processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the chroot_user processes via flexible mandatory access control.

The chroot_user processes execute with the chroot_user_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep chroot_user_t


.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux chroot_user policy is very flexible allowing users to setup their chroot_user processes in as secure a method as possible.
.PP
The following process types are defined for chroot_user:

.EX
.B chroot_user_t
.EE
.PP
Note:
.B semanage permissive -a chroot_user_t
can be used to make the process type chroot_user_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  chroot_user policy is extremely flexible and has several booleans that allow you to manipulate the policy and run chroot_user with the tightest access possible.


.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow ssh with chroot env to read and write files in the user home directories, you must turn on the ssh_chroot_rw_homedirs boolean. Disabled by default.

.EX
.B setsebool -P ssh_chroot_rw_homedirs 1

.EE

.PP
If you want to support ecryptfs home directories, you must turn on the use_ecryptfs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_ecryptfs_home_dirs 1

.EE

.PP
If you want to support fusefs home directories, you must turn on the use_fusefs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_fusefs_home_dirs 1

.EE

.PP
If you want to support NFS home directories, you must turn on the use_nfs_home_dirs boolean. Enabled by default.

.EX
.B setsebool -P use_nfs_home_dirs 1

.EE

.PP
If you want to support SAMBA home directories, you must turn on the use_samba_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_samba_home_dirs 1

.EE

.SH "MANAGED FILES"

The SELinux process type chroot_user_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B cifs_t


.br
.B ecryptfs_t

	/home/[^/]*/\.Private(/.*)?
.br
	/home/[^/]*/\.ecryptfs(/.*)?
.br
	/home/pwalsh/\.Private(/.*)?
.br
	/home/pwalsh/\.ecryptfs(/.*)?
.br
	/home/dwalsh/\.Private(/.*)?
.br
	/home/dwalsh/\.ecryptfs(/.*)?
.br
	/var/lib/xguest/home/xguest/\.Private(/.*)?
.br
	/var/lib/xguest/home/xguest/\.ecryptfs(/.*)?
.br

.br
.B fusefs_t


.br
.B nfs_t


.br
.B user_home_type

	all user home files
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), chroot_user(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8)