.TH  "cobblerd_selinux"  "8"  "cobblerd" "dwalsh@redhat.com" "cobblerd SELinux Policy documentation"
.SH "NAME"
cobblerd_selinux \- Security Enhanced Linux Policy for the cobblerd processes
.SH "DESCRIPTION"




.SH BOOLEANS
SELinux policy is customizable based on least access required.  cobblerd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run cobblerd with the tightest access possible.


.PP
If you want to allow Cobbler to connect to the network using TCP, you must turn on the cobbler_can_network_connect boolean.

.EX
.B setsebool -P cobbler_can_network_connect 1
.EE

.PP
If you want to allow Cobbler to access nfs file systems, you must turn on the cobbler_use_nfs boolean.

.EX
.B setsebool -P cobbler_use_nfs 1
.EE

.PP
If you want to allow HTTPD scripts and modules to connect to cobbler over the network, you must turn on the httpd_can_network_connect_cobbler boolean.

.EX
.B setsebool -P httpd_can_network_connect_cobbler 1
.EE

.PP
If you want to allow Cobbler to access cifs file systems, you must turn on the cobbler_use_cifs boolean.

.EX
.B setsebool -P cobbler_use_cifs 1
.EE

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow cobblerd servers to read the /var/cobblerd directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/cobblerd(/.*)?"
.br
.B restorecon -F -R -v /var/cobblerd
.pp
.TP
Allow cobblerd servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_cobblerd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/cobblerd/incoming(/.*)?"
.br
.B restorecon -F -R -v /var/cobblerd/incoming


.PP
If you want to allow Cobbler to modify public files used for public file transfer services., you must turn on the cobbler_anon_write boolean.

.EX
.B setsebool -P cobbler_anon_write 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux cobblerd policy is very flexible allowing users to setup their cobblerd processes in as secure a method as possible.
.PP 
The following file types are defined for cobblerd:


.EX
.PP
.B cobbler_etc_t 
.EE

- Set files with the cobbler_etc_t type, if you want to store cobbler files in the /etc directories.


.EX
.PP
.B cobbler_tmp_t 
.EE

- Set files with the cobbler_tmp_t type, if you want to store cobbler temporary files in the /tmp directories.


.EX
.PP
.B cobbler_var_lib_t 
.EE

- Set files with the cobbler_var_lib_t type, if you want to store the cobbler files under the /var/lib directory.

.br
.TP 5
Paths: 
/var/lib/cobbler(/.*)?, /var/www/cobbler/images(/.*)?, /var/www/cobbler/repo_mirror(/.*)?, /var/lib/tftpboot/pxelinux\.cfg(/.*)?, /var/lib/tftpboot/memdisk, /var/lib/tftpboot/s390x(/.*)?, /var/www/cobbler/links(/.*)?, /var/lib/tftpboot/menu\.c32, /var/lib/tftpboot/yaboot, /var/www/cobbler/localmirror(/.*)?, /var/www/cobbler/ks_mirror(/.*)?, /var/lib/tftpboot/grub(/.*)?, /var/www/cobbler/pub(/.*)?, /var/lib/tftpboot/ppc(/.*)?, /var/lib/tftpboot/pxelinux\.0, /var/lib/tftpboot/images(/.*)?, /var/lib/tftpboot/etc(/.*)?, /var/www/cobbler/rendered(/.*)?

.EX
.PP
.B cobbler_var_log_t 
.EE

- Set files with the cobbler_var_log_t type, if you want to treat the data as cobbler var log data, usually stored under the /var/log directory.


.EX
.PP
.B cobblerd_exec_t 
.EE

- Set files with the cobblerd_exec_t type, if you want to transition an executable to the cobblerd_t domain.


.EX
.PP
.B cobblerd_initrc_exec_t 
.EE

- Set files with the cobblerd_initrc_exec_t type, if you want to transition an executable to the cobblerd_initrc_t domain.


.EX
.PP
.B cobblerd_unit_file_t 
.EE

- Set files with the cobblerd_unit_file_t type, if you want to treat the files as cobblerd unit content.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux cobblerd policy is very flexible allowing users to setup their cobblerd processes in as secure a method as possible.
.PP 
The following port types are defined for cobblerd:

.EX
.TP 5
.B cobbler_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux cobblerd policy is very flexible allowing users to setup their cobblerd processes in as secure a method as possible.
.PP 
The following process types are defined for cobblerd:

.EX
.B cobblerd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), cobblerd(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)