.TH  "collectd_selinux"  "8"  "collectd" "dwalsh@redhat.com" "collectd SELinux Policy documentation"
.SH "NAME"
collectd_selinux \- Security Enhanced Linux Policy for the collectd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the collectd processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  collectd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run collectd with the tightest access possible.


.PP
If you want to allow collectd to connect to the network using TCP, you must turn on the collectd_can_network_connect boolean.

.EX
.B setsebool -P collectd_can_network_connect 1
.EE

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux collectd policy is very flexible allowing users to setup their collectd processes in as secure a method as possible.
.PP 
The following file types are defined for collectd:


.EX
.PP
.B collectd_exec_t 
.EE

- Set files with the collectd_exec_t type, if you want to transition an executable to the collectd_t domain.


.EX
.PP
.B collectd_initrc_exec_t 
.EE

- Set files with the collectd_initrc_exec_t type, if you want to transition an executable to the collectd_initrc_t domain.


.EX
.PP
.B collectd_unit_file_t 
.EE

- Set files with the collectd_unit_file_t type, if you want to treat the files as collectd unit content.


.EX
.PP
.B collectd_var_lib_t 
.EE

- Set files with the collectd_var_lib_t type, if you want to store the collectd files under the /var/lib directory.


.EX
.PP
.B collectd_var_run_t 
.EE

- Set files with the collectd_var_run_t type, if you want to store the collectd files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux collectd policy is very flexible allowing users to setup their collectd processes in as secure a method as possible.
.PP 
The following process types are defined for collectd:

.EX
.B collectd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type collectd_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B collectd_var_lib_t

	/var/lib/collectd(/.*)?
.br

.br
.B collectd_var_run_t

	/var/run/collectd\.pid
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), collectd(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)