.TH  "cupsd_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "cupsd Selinux Policy documentation"
.SH "NAME"
cupsd_selinux \- Security Enhanced Linux Policy for the cupsd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the cupsd processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux cupsd policy is very flexible allowing users to setup their cupsd processes in as secure a method as possible.
.PP 
The following file types are defined for cupsd:


.EX
.B cupsd_config_exec_t 
.EE

- Set files with the cupsd_config_exec_t context, if you want to a executable to transition to the cupsd_config_t domain.


.EX
.B cupsd_config_var_run_t 
.EE

- Set files with the cupsd_config_var_run_t context, if you want to store the cupsd config files under the /run directory.


.EX
.B cupsd_etc_t 
.EE

- Set files with the cupsd_etc_t context, if you want to store cupsd files in the /etc directories.


.EX
.B cupsd_exec_t 
.EE

- Set files with the cupsd_exec_t context, if you want to a executable to transition to the cupsd_t domain.


.EX
.B cupsd_initrc_exec_t 
.EE

- Set files with the cupsd_initrc_exec_t context, if you want to a executable to transition to the cupsd_initrc_t domain.


.EX
.B cupsd_interface_t 
.EE

- Set files with the cupsd_interface_t context, if you want to treat the files as cupsd interface data.


.EX
.B cupsd_lock_t 
.EE

- Set files with the cupsd_lock_t context, if you want to treat the files as cupsd lock data, stored under the /var/lock directory


.EX
.B cupsd_log_t 
.EE

- Set files with the cupsd_log_t context, if you want to treat the data as cupsd log data, usually stored under the /var/log directory.


.EX
.B cupsd_lpd_exec_t 
.EE

- Set files with the cupsd_lpd_exec_t context, if you want to a executable to transition to the cupsd_lpd_t domain.


.EX
.B cupsd_lpd_tmp_t 
.EE

- Set files with the cupsd_lpd_tmp_t context, if you want to store cupsd lpd temporary files in the /tmp directories.


.EX
.B cupsd_lpd_var_run_t 
.EE

- Set files with the cupsd_lpd_var_run_t context, if you want to store the cupsd lpd files under the /run directory.


.EX
.B cupsd_rw_etc_t 
.EE

- Set files with the cupsd_rw_etc_t context, if you want to store cupsd rw files in the /etc directories.


.EX
.B cupsd_tmp_t 
.EE

- Set files with the cupsd_tmp_t context, if you want to store cupsd temporary files in the /tmp directories.


.EX
.B cupsd_var_run_t 
.EE

- Set files with the cupsd_var_run_t context, if you want to store the cupsd files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), cupsd(8), semanage(8), restorecon(8), chcon(1)
