.TH  "dbadm_selinux"  "8"  "dbadm" "mgrepl@redhat.com" "dbadm SELinux Policy documentation"
.SH "NAME"
dbadm_r \- \fBDatabase administrator role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

SELinux supports Roles Based Access Control (RBAC), some Linux roles are login roles, while other roles need to be transition into. 

.I Note: 
Examples in this man page will use the 
.B staff_u 
SELinux user.

Non login roles are usually used for administrative tasks. For example, tasks that require root privileges.  Roles control which types a user can run processes with. Roles often have default types assigned to them. 

The default type for the dbadm_r role is dbadm_t.

The 
.B newrole 
program to transition directly to this role.

.B newrole -r dbadm_r -t dbadm_t

.B sudo 
is the preferred method to do transition from one role to another.  You setup sudo to transition to dbadm_r by adding a similar line to the /etc/sudoers file.

USERNAME ALL=(ALL) ROLE=dbadm_r TYPE=dbadm_t COMMAND

.br
sudo will run COMMAND as staff_u:dbadm_r:dbadm_t:LEVEL

When using a a non login role, you need to setup SELinux so that your SELinux user can reach dbadm_r role.

Execute the following to see all of the assigned SELinux roles:

.B semanage user -l

You need to add dbadm_r to the staff_u user.  You could setup the staff_u user to be able to use the dbadm_r role with a command like:

.B $ semanage user -m -R 'staff_r system_r dbadm_r' staff_u 


.SH BOOLEANS
SELinux policy is customizable based on least access required.  dbadm policy is extremely flexible and has several booleans that allow you to manipulate the policy and run dbadm with the tightest access possible.


.PP
If you want to allow dbadm to manage files in users home directories, you must turn on the dbadm_manage_user_files boolean.

.EX
.B setsebool -P dbadm_manage_user_files 1
.EE

.PP
If you want to allow database admins to execute DML statement, you must turn on the postgresql_selinux_unconfined_dbadm boolean.

.EX
.B setsebool -P postgresql_selinux_unconfined_dbadm 1
.EE

.PP
If you want to allow dbadm to read files in users home directories, you must turn on the dbadm_read_user_files boolean.

.EX
.B setsebool -P dbadm_read_user_files 1
.EE

.SH "MANAGED FILES"

The SELinux process type dbadm_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B mysqld_db_t

	/var/lib/mysql(/.*)?
.br

.br
.B mysqld_etc_t

	/etc/mysql(/.*)?
.br
	/etc/my\.cnf
.br

.br
.B mysqld_home_t

	/root/\.my\.cnf
.br
	/home/[^/]*/\.my\.cnf
.br
	/home/dwalsh/\.my\.cnf
.br
	/var/lib/xguest/home/xguest/\.my\.cnf
.br

.br
.B mysqld_log_t

	/var/log/mysql.*
.br

.br
.B mysqld_tmp_t


.br
.B mysqld_unit_file_t

	/usr/lib/systemd/system/mysqld.*
.br

.br
.B mysqld_var_run_t

	/var/run/mysqld(/.*)?
.br
	/var/lib/mysql/mysql\.sock
.br

.br
.B postgresql_db_t

	/var/lib/pgsql(/.*)?
.br
	/var/lib/sepgsql(/.*)?
.br
	/var/lib/postgres(ql)?(/.*)?
.br
	/usr/share/jonas/pgsql(/.*)?
.br
	/usr/lib/pgsql/test/regress(/.*)?
.br

.br
.B postgresql_etc_t

	/etc/postgresql(/.*)?
.br
	/etc/sysconfig/pgsql(/.*)?
.br

.br
.B postgresql_log_t

	/var/lib/pgsql/.*\.log
.br
	/var/log/rhdb/rhdb(/.*)?
.br
	/var/log/postgresql(/.*)?
.br
	/var/log/postgres\.log.*
.br
	/var/lib/pgsql/logfile(/.*)?
.br
	/var/log/sepostgresql\.log.*
.br
	/var/lib/sepgsql/pgstartup\.log
.br

.br
.B postgresql_tmp_t


.br
.B postgresql_var_run_t

	/var/run/postgresql(/.*)?
.br

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), dbadm(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)