.TH  "dcc_client_selinux"  "8"  "dcc_client" "dwalsh@redhat.com" "dcc_client SELinux Policy documentation"
.SH "NAME"
dcc_client_selinux \- Security Enhanced Linux Policy for the dcc_client processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the dcc_client processes via flexible mandatory access control.

The dcc_client processes execute with the dcc_client_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep dcc_client_t


.SH "ENTRYPOINTS"

The dcc_client_t SELinux type can be entered via the "dcc_client_exec_t" file type.  The default entrypoint paths for the dcc_client_t domain are the following:"

/usr/bin/dccproc
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux dcc_client policy is very flexible allowing users to setup their dcc_client processes in as secure a method as possible.
.PP 
The following process types are defined for dcc_client:

.EX
.B dcc_client_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux dcc_client policy is very flexible allowing users to setup their dcc_client processes in as secure a method as possible.
.PP 
The following file types are defined for dcc_client:


.EX
.PP
.B dcc_client_exec_t 
.EE

- Set files with the dcc_client_exec_t type, if you want to transition an executable to the dcc_client_t domain.


.EX
.PP
.B dcc_client_map_t 
.EE

- Set files with the dcc_client_map_t type, if you want to treat the files as dcc client map data.

.br
.TP 5
Paths: 
/var/lib/dcc/map, /etc/dcc/map, /var/run/dcc/map, /var/dcc/map

.EX
.PP
.B dcc_client_tmp_t 
.EE

- Set files with the dcc_client_tmp_t type, if you want to store dcc client temporary files in the /tmp directories.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type dcc_client_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B dcc_client_map_t

	/etc/dcc/map
.br
	/var/dcc/map
.br
	/var/lib/dcc/map
.br
	/var/run/dcc/map
.br

.br
.B dcc_client_tmp_t


.br
.B dcc_var_t

	/etc/dcc(/.*)?
.br
	/var/dcc(/.*)?
.br
	/var/lib/dcc(/.*)?
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the dcc_client_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the dcc_client_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), dcc_client(8), semanage(8), restorecon(8), chcon(1)
, dcc_dbclean_selinux(8), dccd_selinux(8), dccifd_selinux(8), dccm_selinux(8)