.TH  "devicekit_selinux"  "8"  "devicekit" "dwalsh@redhat.com" "devicekit SELinux Policy documentation"
.SH "NAME"
devicekit_selinux \- Security Enhanced Linux Policy for the devicekit processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the devicekit processes via flexible mandatory access control.

The devicekit processes execute with the devicekit_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep devicekit_t


.SH "ENTRYPOINTS"

The devicekit_t SELinux type can be entered via the "devicekit_exec_t" file type.  The default entrypoint paths for the devicekit_t domain are the following:"

/usr/libexec/devkit-daemon
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux devicekit policy is very flexible allowing users to setup their devicekit processes in as secure a method as possible.
.PP 
The following process types are defined for devicekit:

.EX
.B devicekit_power_t, devicekit_disk_t, devicekit_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux devicekit policy is very flexible allowing users to setup their devicekit processes in as secure a method as possible.
.PP 
The following file types are defined for devicekit:


.EX
.PP
.B devicekit_disk_exec_t 
.EE

- Set files with the devicekit_disk_exec_t type, if you want to transition an executable to the devicekit_disk_t domain.

.br
.TP 5
Paths: 
/usr/lib/udisks/udisks-daemon, /usr/lib/udev/udisks-part-id, /usr/libexec/devkit-disks-daemon, /lib/udisks2/udisksd, /usr/lib/udisks2/udisksd, /lib/udev/udisks-part-id, /usr/libexec/udisks-daemon

.EX
.PP
.B devicekit_exec_t 
.EE

- Set files with the devicekit_exec_t type, if you want to transition an executable to the devicekit_t domain.


.EX
.PP
.B devicekit_power_exec_t 
.EE

- Set files with the devicekit_power_exec_t type, if you want to transition an executable to the devicekit_power_t domain.

.br
.TP 5
Paths: 
/usr/libexec/upowerd, /usr/libexec/devkit-power-daemon

.EX
.PP
.B devicekit_tmp_t 
.EE

- Set files with the devicekit_tmp_t type, if you want to store devicekit temporary files in the /tmp directories.


.EX
.PP
.B devicekit_var_lib_t 
.EE

- Set files with the devicekit_var_lib_t type, if you want to store the devicekit files under the /var/lib directory.

.br
.TP 5
Paths: 
/var/lib/udisks.*, /var/lib/DeviceKit-.*, /var/lib/upower(/.*)?

.EX
.PP
.B devicekit_var_log_t 
.EE

- Set files with the devicekit_var_log_t type, if you want to treat the data as devicekit var log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/log/pm-suspend\.log.*, /var/log/pm-powersave\.log.*

.EX
.PP
.B devicekit_var_run_t 
.EE

- Set files with the devicekit_var_run_t type, if you want to store the devicekit files under the /run directory.

.br
.TP 5
Paths: 
/var/run/upower(/.*)?, /var/run/udisks.*, /var/run/devkit(/.*)?, /var/run/DeviceKit-disks(/.*)?, /var/run/pm-utils(/.*)?

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type devicekit_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B devicekit_var_run_t

	/var/run/udisks.*
.br
	/var/run/devkit(/.*)?
.br
	/var/run/upower(/.*)?
.br
	/var/run/pm-utils(/.*)?
.br
	/var/run/DeviceKit-disks(/.*)?
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the devicekit_disk_t, devicekit_power_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the devicekit_disk_t, devicekit_power_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), devicekit(8), semanage(8), restorecon(8), chcon(1)
, devicekit_disk_selinux(8), devicekit_power_selinux(8)