.TH  "dhcpd_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "dhcpd Selinux Policy documentation"
.SH "NAME"
dhcpd_selinux \- Security Enhanced Linux Policy for the dhcpd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the dhcpd processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux dhcpd policy is very flexible allowing users to setup their dhcpd processes in as secure a method as possible.
.PP 
The following file types are defined for dhcpd:


.EX
.B dhcpd_exec_t 
.EE

- Set files with the dhcpd_exec_t context, if you want to a executable to transition to the dhcpd_t domain.


.EX
.B dhcpd_initrc_exec_t 
.EE

- Set files with the dhcpd_initrc_exec_t context, if you want to a executable to transition to the dhcpd_initrc_t domain.


.EX
.B dhcpd_state_t 
.EE

- Set files with the dhcpd_state_t context, if you want to treat the files as dhcpd state data.


.EX
.B dhcpd_tmp_t 
.EE

- Set files with the dhcpd_tmp_t context, if you want to store dhcpd temporary files in the /tmp directories.


.EX
.B dhcpd_unit_file_t 
.EE

- Set files with the dhcpd_unit_file_t context, if you want to treat the files as dhcpd unit content.


.EX
.B dhcpd_var_run_t 
.EE

- Set files with the dhcpd_var_run_t context, if you want to store the dhcpd files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  dhcpd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run dhcpd with the tightest access possible.


.PP
If you want to allow dhcpc client applications to execute iptables command, you must turn on the dhcpc_exec_iptables boolean.

.EX
.B setsebool -P dhcpc_exec_iptables 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), dhcpd(8), semanage(8), restorecon(8), chcon(1), setsebool(8)