.TH  "dhcpc_selinux"  "8"  "dhcpc" "dwalsh@redhat.com" "dhcpc SELinux Policy documentation"
.SH "NAME"
dhcpc_selinux \- Security Enhanced Linux Policy for the dhcpc processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the dhcpc processes via flexible mandatory access control.

The dhcpc processes execute with the dhcpc_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep dhcpc_t


.SH "ENTRYPOINTS"

The dhcpc_t SELinux type can be entered via the "dhcpc_exec_t" file type.  The default entrypoint paths for the dhcpc_t domain are the following:"

/usr/sbin/dhcpcd, /sbin/dhcpcd, /usr/sbin/pump, /sbin/dhclient.*, /usr/sbin/dhclient.*, /sbin/pump, /usr/sbin/dhcdbd, /sbin/dhcdbd
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux dhcpc policy is very flexible allowing users to setup their dhcpc processes in as secure a method as possible.
.PP 
The following process types are defined for dhcpc:

.EX
.B dhcpc_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  dhcpc policy is extremely flexible and has several booleans that allow you to manipulate the policy and run dhcpc with the tightest access possible.


.PP
If you want to allow dhcpc client applications to execute iptables commands, you must turn on the dhcpc_exec_iptables boolean.

.EX
.B setsebool -P dhcpc_exec_iptables 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux dhcpc policy is very flexible allowing users to setup their dhcpc processes in as secure a method as possible.
.PP 
The following file types are defined for dhcpc:


.EX
.PP
.B dhcpc_exec_t 
.EE

- Set files with the dhcpc_exec_t type, if you want to transition an executable to the dhcpc_t domain.

.br
.TP 5
Paths: 
/usr/sbin/dhcpcd, /sbin/dhcpcd, /usr/sbin/pump, /sbin/dhclient.*, /usr/sbin/dhclient.*, /sbin/pump, /usr/sbin/dhcdbd, /sbin/dhcdbd

.EX
.PP
.B dhcpc_helper_exec_t 
.EE

- Set files with the dhcpc_helper_exec_t type, if you want to transition an executable to the dhcpc_helper_t domain.


.EX
.PP
.B dhcpc_state_t 
.EE

- Set files with the dhcpc_state_t type, if you want to treat the files as dhcpc state data.

.br
.TP 5
Paths: 
/var/lib/dhclient(/.*)?, /var/lib/dhcp3?/dhclient.*, /var/lib/wifiroamd(/.*)?, /var/lib/dhcpcd(/.*)?

.EX
.PP
.B dhcpc_tmp_t 
.EE

- Set files with the dhcpc_tmp_t type, if you want to store dhcpc temporary files in the /tmp directories.


.EX
.PP
.B dhcpc_var_run_t 
.EE

- Set files with the dhcpc_var_run_t type, if you want to store the dhcpc files under the /run directory.

.br
.TP 5
Paths: 
/var/run/dhclient.*, /var/run/dhcpcd(/.*)?

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux dhcpc policy is very flexible allowing users to setup their dhcpc processes in as secure a method as possible.
.PP 
The following port types are defined for dhcpc:

.EX
.TP 5
.B dhcpc_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 68,546
.EE
udp 68,546
.EE
.SH "MANAGED FILES"

The SELinux process type dhcpc_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B dhcpc_state_t

	/var/lib/dhcp3?/dhclient.*
.br
	/var/lib/dhcpcd(/.*)?
.br
	/var/lib/dhclient(/.*)?
.br
	/var/lib/wifiroamd(/.*)?
.br

.br
.B dhcpc_tmp_t


.br
.B dhcpc_var_run_t

	/var/run/dhcpcd(/.*)?
.br
	/var/run/dhclient.*
.br

.br
.B initrc_var_run_t

	/var/run/utmp
.br
	/var/run/random-seed
.br
	/var/run/runlevel\.dir
.br
	/var/run/setmixer_flag
.br

.br
.B net_conf_t

	/etc/ntpd?\.conf.*
.br
	/etc/hosts[^/]*
.br
	/etc/yp\.conf.*
.br
	/etc/denyhosts.*
.br
	/etc/hosts\.deny.*
.br
	/etc/resolv\.conf.*
.br
	/etc/ntp/step-tickers.*
.br
	/etc/sysconfig/networking(/.*)?
.br
	/etc/sysconfig/network-scripts(/.*)?
.br
	/etc/sysconfig/network-scripts/.*resolv\.conf
.br
	/etc/ethers
.br

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the dhcpc_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the dhcpc_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), dhcpc(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)