.TH  "dictd_selinux"  "8"  "dictd" "dwalsh@redhat.com" "dictd Selinux Policy documentation"
.SH "NAME"
dictd_selinux \- Security Enhanced Linux Policy for the dictd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the dictd processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux dictd policy is very flexible allowing users to setup their dictd processes in as secure a method as possible.
.PP 
The following file types are defined for dictd:


.EX
.B dictd_etc_t 
.EE

- Set files with the dictd_etc_t context, if you want to store dictd files in the /etc directories.

.br
Path: 
/etc/dictd\.conf

.EX
.B dictd_exec_t 
.EE

- Set files with the dictd_exec_t context, if you want to a executable to transition to the dictd_t domain.

.br
Path: 
/usr/sbin/dictd

.EX
.B dictd_initrc_exec_t 
.EE

- Set files with the dictd_initrc_exec_t context, if you want to a executable to transition to the dictd_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/dictd

.EX
.B dictd_var_lib_t 
.EE

- Set files with the dictd_var_lib_t context, if you want to store the dictd files under the /var/lib directory.

.br
Path: 
/var/lib/dictd(/.*)?

.EX
.B dictd_var_run_t 
.EE

- Set files with the dictd_var_run_t context, if you want to store the dictd files under the /run directory.

.br
Path: 
/var/run/dictd\.pid
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), dictd(8), semanage(8), restorecon(8), chcon(1)
