.TH  "dirsrv_selinux"  "8"  "dirsrv" "dwalsh@redhat.com" "dirsrv SELinux Policy documentation"
.SH "NAME"
dirsrv_selinux \- Security Enhanced Linux Policy for the dirsrv processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the dirsrv processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the dirsrv_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the dirsrv_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux dirsrv policy is very flexible allowing users to setup their dirsrv processes in as secure a method as possible.
.PP 
The following file types are defined for dirsrv:


.EX
.PP
.B dirsrv_config_t 
.EE

- Set files with the dirsrv_config_t type, if you want to treat the files as dirsrv configuration data, usually stored under the /etc directory.


.EX
.PP
.B dirsrv_exec_t 
.EE

- Set files with the dirsrv_exec_t type, if you want to transition an executable to the dirsrv_t domain.


.EX
.PP
.B dirsrv_share_t 
.EE

- Set files with the dirsrv_share_t type, if you want to treat the files as dirsrv share data.


.EX
.PP
.B dirsrv_snmp_exec_t 
.EE

- Set files with the dirsrv_snmp_exec_t type, if you want to transition an executable to the dirsrv_snmp_t domain.


.EX
.PP
.B dirsrv_snmp_var_log_t 
.EE

- Set files with the dirsrv_snmp_var_log_t type, if you want to treat the data as dirsrv snmp var log data, usually stored under the /var/log directory.


.EX
.PP
.B dirsrv_snmp_var_run_t 
.EE

- Set files with the dirsrv_snmp_var_run_t type, if you want to store the dirsrv snmp files under the /run directory.


.EX
.PP
.B dirsrv_tmp_t 
.EE

- Set files with the dirsrv_tmp_t type, if you want to store dirsrv temporary files in the /tmp directories.


.EX
.PP
.B dirsrv_tmpfs_t 
.EE

- Set files with the dirsrv_tmpfs_t type, if you want to store dirsrv files on a tmpfs file system.


.EX
.PP
.B dirsrv_var_lib_t 
.EE

- Set files with the dirsrv_var_lib_t type, if you want to store the dirsrv files under the /var/lib directory.


.EX
.PP
.B dirsrv_var_lock_t 
.EE

- Set files with the dirsrv_var_lock_t type, if you want to treat the files as dirsrv var lock data, stored under the /var/lock directory


.EX
.PP
.B dirsrv_var_log_t 
.EE

- Set files with the dirsrv_var_log_t type, if you want to treat the data as dirsrv var log data, usually stored under the /var/log directory.


.EX
.PP
.B dirsrv_var_run_t 
.EE

- Set files with the dirsrv_var_run_t type, if you want to store the dirsrv files under the /run directory.


.EX
.PP
.B dirsrvadmin_config_t 
.EE

- Set files with the dirsrvadmin_config_t type, if you want to treat the files as dirsrvadmin configuration data, usually stored under the /etc directory.

.br
.TP 5
Paths: 
/etc/dirsrv/admin-serv(/.*)?, /etc/dirsrv/dsgw(/.*)?

.EX
.PP
.B dirsrvadmin_exec_t 
.EE

- Set files with the dirsrvadmin_exec_t type, if you want to transition an executable to the dirsrvadmin_t domain.

.br
.TP 5
Paths: 
/usr/sbin/start-ds-admin, /usr/sbin/stop-ds-admin, /usr/sbin/restart-ds-admin

.EX
.PP
.B dirsrvadmin_lock_t 
.EE

- Set files with the dirsrvadmin_lock_t type, if you want to treat the files as dirsrvadmin lock data, stored under the /var/lock directory


.EX
.PP
.B dirsrvadmin_tmp_t 
.EE

- Set files with the dirsrvadmin_tmp_t type, if you want to store dirsrvadmin temporary files in the /tmp directories.


.EX
.PP
.B dirsrvadmin_unconfined_script_exec_t 
.EE

- Set files with the dirsrvadmin_unconfined_script_exec_t type, if you want to transition an executable to the dirsrvadmin_unconfined_script_t domain.

.br
.TP 5
Paths: 
/usr/lib/dirsrv/cgi-bin/ds_remove, /usr/lib/dirsrv/cgi-bin/ds_create

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux dirsrv policy is very flexible allowing users to setup their dirsrv processes in as secure a method as possible.
.PP 
The following process types are defined for dirsrv:

.EX
.B dirsrvadmin_unconfined_script_t, dirsrv_snmp_t, dirsrvadmin_t, dirsrv_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type dirsrv_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B dirsrv_config_t

	/etc/dirsrv(/.*)?
.br

.br
.B dirsrv_tmp_t


.br
.B dirsrv_tmpfs_t


.br
.B dirsrv_var_lib_t

	/var/lib/dirsrv(/.*)?
.br

.br
.B dirsrv_var_lock_t

	/var/lock/dirsrv(/.*)?
.br

.br
.B dirsrv_var_log_t

	/var/log/dirsrv(/.*)?
.br

.br
.B dirsrv_var_run_t

	/var/run/dirsrv(/.*)?
.br

.br
.B faillog_t

	/var/log/btmp.*
.br
	/var/run/faillock(/.*)?
.br
	/var/log/faillog
.br
	/var/log/tallylog
.br

.br
.B krb5_host_rcache_t

	/var/cache/krb5rcache(/.*)?
.br
	/var/tmp/nfs_0
.br
	/var/tmp/host_0
.br
	/var/tmp/imap_0
.br
	/var/tmp/HTTP_23
.br
	/var/tmp/HTTP_48
.br
	/var/tmp/ldap_55
.br
	/var/tmp/ldap_487
.br
	/var/tmp/ldapmap1_0
.br

.br
.B lastlog_t

	/var/log/lastlog
.br

.br
.B pcscd_var_run_t

	/var/run/pcscd(/.*)?
.br
	/var/run/pcscd\.events(/.*)?
.br
	/var/run/pcscd\.pid
.br
	/var/run/pcscd\.pub
.br
	/var/run/pcscd\.comm
.br

.br
.B security_t

	/selinux
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), dirsrv(8), semanage(8), restorecon(8), chcon(1)
, dirsrv_snmp_selinux(8), dirsrvadmin_selinux(8), dirsrvadmin_unconfined_script_selinux(8)