.TH  "dirsrv_selinux"  "8"  "dirsrv" "dwalsh@redhat.com" "dirsrv SELinux Policy documentation"
.SH "NAME"
dirsrv_selinux \- Security Enhanced Linux Policy for the dirsrv processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the dirsrv processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux dirsrv policy is very flexible allowing users to setup their dirsrv processes in as secure a method as possible.
.PP 
The following file types are defined for dirsrv:


.EX
.B dirsrv_config_t 
.EE

- Set files with the dirsrv_config_t context, if you want to treat the files as dirsrv configuration data, usually stored under the /etc directory.

.br
Path: 
/etc/dirsrv(/.*)?

.EX
.B dirsrv_exec_t 
.EE

- Set files with the dirsrv_exec_t context, if you want to a executable to transition to the dirsrv_t domain.

.br
Path: 
/usr/sbin/ns-slapd

.EX
.B dirsrv_share_t 
.EE

- Set files with the dirsrv_share_t context, if you want to treat the files as dirsrv share data.

.br
Path: 
/usr/share/dirsrv(/.*)?

.EX
.B dirsrv_snmp_exec_t 
.EE

- Set files with the dirsrv_snmp_exec_t context, if you want to a executable to transition to the dirsrv_snmp_t domain.

.br
Path: 
/usr/sbin/ldap-agent-bin

.EX
.B dirsrv_snmp_var_log_t 
.EE

- Set files with the dirsrv_snmp_var_log_t context, if you want to treat the data as dirsrv snmp var log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/dirsrv/ldap-agent.log

.EX
.B dirsrv_snmp_var_run_t 
.EE

- Set files with the dirsrv_snmp_var_run_t context, if you want to store the dirsrv snmp files under the /run directory.

.br
Path: 
/var/run/ldap-agent\.pid

.EX
.B dirsrv_tmp_t 
.EE

- Set files with the dirsrv_tmp_t context, if you want to store dirsrv temporary files in the /tmp directories.


.EX
.B dirsrv_tmpfs_t 
.EE

- Set files with the dirsrv_tmpfs_t context, if you want to store dirsrv files on a tmpfs file system.


.EX
.B dirsrv_var_lib_t 
.EE

- Set files with the dirsrv_var_lib_t context, if you want to store the dirsrv files under the /var/lib directory.

.br
Path: 
/var/lib/dirsrv(/.*)?

.EX
.B dirsrv_var_lock_t 
.EE

- Set files with the dirsrv_var_lock_t context, if you want to treat the files as dirsrv var lock data, stored under the /var/lock directory

.br
Path: 
/var/lock/dirsrv(/.*)?

.EX
.B dirsrv_var_log_t 
.EE

- Set files with the dirsrv_var_log_t context, if you want to treat the data as dirsrv var log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/dirsrv(/.*)?

.EX
.B dirsrv_var_run_t 
.EE

- Set files with the dirsrv_var_run_t context, if you want to store the dirsrv files under the /run directory.

.br
Path: 
/var/run/dirsrv(/.*)?

.EX
.B dirsrvadmin_config_t 
.EE

- Set files with the dirsrvadmin_config_t context, if you want to treat the files as dirsrvadmin configuration data, usually stored under the /etc directory.

.br
Paths: 
/etc/dirsrv/admin-serv(/.*)?, /etc/dirsrv/dsgw(/.*)?

.EX
.B dirsrvadmin_exec_t 
.EE

- Set files with the dirsrvadmin_exec_t context, if you want to a executable to transition to the dirsrvadmin_t domain.

.br
Paths: 
/usr/sbin/start-ds-admin, /usr/sbin/stop-ds-admin, /usr/sbin/restart-ds-admin

.EX
.B dirsrvadmin_lock_t 
.EE

- Set files with the dirsrvadmin_lock_t context, if you want to treat the files as dirsrvadmin lock data, stored under the /var/lock directory

.br
Path: 
/var/lock/subsys/dirsrv

.EX
.B dirsrvadmin_tmp_t 
.EE

- Set files with the dirsrvadmin_tmp_t context, if you want to store dirsrvadmin temporary files in the /tmp directories.


.EX
.B dirsrvadmin_unconfined_script_exec_t 
.EE

- Set files with the dirsrvadmin_unconfined_script_exec_t context, if you want to a executable to transition to the dirsrvadmin_unconfined_script_t domain.

.br
Paths: 
/usr/lib/dirsrv/cgi-bin/ds_remove, /usr/lib/dirsrv/cgi-bin/ds_create
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), dirsrv(8), semanage(8), restorecon(8), chcon(1)
