.TH  "disk_munin_plugin_selinux"  "8"  "disk_munin_plugin" "dwalsh@redhat.com" "disk_munin_plugin SELinux Policy documentation"
.SH "NAME"
disk_munin_plugin_selinux \- Security Enhanced Linux Policy for the disk_munin_plugin processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the disk_munin_plugin processes via flexible mandatory access control.

The disk_munin_plugin processes execute with the disk_munin_plugin_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep disk_munin_plugin_t


.SH "ENTRYPOINTS"

The disk_munin_plugin_t SELinux type can be entered via the "disk_munin_plugin_exec_t" file type.  The default entrypoint paths for the disk_munin_plugin_t domain are the following:"

/usr/share/munin/plugins/diskstat.*, /usr/share/munin/plugins/hddtemp.*, /usr/share/munin/plugins/smart_.*, /usr/share/munin/plugins/df.*
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux disk_munin_plugin policy is very flexible allowing users to setup their disk_munin_plugin processes in as secure a method as possible.
.PP 
The following process types are defined for disk_munin_plugin:

.EX
.B disk_munin_plugin_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux disk_munin_plugin policy is very flexible allowing users to setup their disk_munin_plugin processes in as secure a method as possible.
.PP 
The following file types are defined for disk_munin_plugin:


.EX
.PP
.B disk_munin_plugin_exec_t 
.EE

- Set files with the disk_munin_plugin_exec_t type, if you want to transition an executable to the disk_munin_plugin_t domain.

.br
.TP 5
Paths: 
/usr/share/munin/plugins/diskstat.*, /usr/share/munin/plugins/hddtemp.*, /usr/share/munin/plugins/smart_.*, /usr/share/munin/plugins/df.*

.EX
.PP
.B disk_munin_plugin_tmp_t 
.EE

- Set files with the disk_munin_plugin_tmp_t type, if you want to store disk munin plugin temporary files in the /tmp directories.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type disk_munin_plugin_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B disk_munin_plugin_tmp_t


.br
.B munin_plugin_state_t

	/var/lib/munin/plugin-state(/.*)?
.br

.br
.B munin_var_lib_t

	/var/lib/munin(/.*)?
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), disk_munin_plugin(8), semanage(8), restorecon(8), chcon(1)
