.TH  "dnsmasq_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "dnsmasq Selinux Policy documentation"
.SH "NAME"
dnsmasq_selinux \- Security Enhanced Linux Policy for the dnsmasq processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the dnsmasq processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux dnsmasq policy is very flexible allowing users to setup their dnsmasq processes in as secure a method as possible.
.PP 
The following file types are defined for dnsmasq:


.EX
.B dnsmasq_etc_t 
.EE

- Set files with the dnsmasq_etc_t context, if you want to store dnsmasq files in the /etc directories.


.EX
.B dnsmasq_exec_t 
.EE

- Set files with the dnsmasq_exec_t context, if you want to a executable to transition to the dnsmasq_t domain.


.EX
.B dnsmasq_initrc_exec_t 
.EE

- Set files with the dnsmasq_initrc_exec_t context, if you want to a executable to transition to the dnsmasq_initrc_t domain.


.EX
.B dnsmasq_lease_t 
.EE

- Set files with the dnsmasq_lease_t context, if you want to treat the files as dnsmasq lease data.


.EX
.B dnsmasq_unit_file_t 
.EE

- Set files with the dnsmasq_unit_file_t context, if you want to treat the files as dnsmasq unit content.


.EX
.B dnsmasq_var_log_t 
.EE

- Set files with the dnsmasq_var_log_t context, if you want to treat the data as dnsmasq var log data, usually stored under the /var/log directory.


.EX
.B dnsmasq_var_run_t 
.EE

- Set files with the dnsmasq_var_run_t context, if you want to store the dnsmasq files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), dnsmasq(8), semanage(8), restorecon(8), chcon(1)
