.TH  "dnssec_selinux"  "8"  "dnssec" "dwalsh@redhat.com" "dnssec SELinux Policy documentation"
.SH "NAME"
dnssec_selinux \- Security Enhanced Linux Policy for the dnssec processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the dnssec processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux dnssec policy is very flexible allowing users to setup their dnssec processes in as secure a method as possible.
.PP 
The following file types are defined for dnssec:


.EX
.PP
.B dnssec_t 
.EE

- Set files with the dnssec_t type, if you want to treat the files as dnssec data.

.br
.TP 5
Paths: 
/etc/unbound/.*\.key, /var/named/chroot/etc/rndc\.key, /etc/dnssec-trigger/dnssec_trigger_server\.key, /etc/rndc\.key

.EX
.PP
.B dnssec_trigger_exec_t 
.EE

- Set files with the dnssec_trigger_exec_t type, if you want to transition an executable to the dnssec_trigger_t domain.


.EX
.PP
.B dnssec_trigger_var_run_t 
.EE

- Set files with the dnssec_trigger_var_run_t type, if you want to store the dnssec trigger files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux dnssec policy is very flexible allowing users to setup their dnssec processes in as secure a method as possible.
.PP 
The following port types are defined for dnssec:

.EX
.TP 5
.B dnssec_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux dnssec policy is very flexible allowing users to setup their dnssec processes in as secure a method as possible.
.PP 
The following process types are defined for dnssec:

.EX
.B dnssec_trigger_t 
.EE
.PP
Note: 
.B semanage permississive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), dnssec(8), semanage(8), restorecon(8), chcon(1)
