.TH  "fail2ban_selinux"  "8"  "fail2ban" "dwalsh@redhat.com" "fail2ban SELinux Policy documentation"
.SH "NAME"
fail2ban_selinux \- Security Enhanced Linux Policy for the fail2ban processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the fail2ban processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the fail2ban_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the fail2ban_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux fail2ban policy is very flexible allowing users to setup their fail2ban processes in as secure a method as possible.
.PP 
The following file types are defined for fail2ban:


.EX
.PP
.B fail2ban_client_exec_t 
.EE

- Set files with the fail2ban_client_exec_t type, if you want to transition an executable to the fail2ban_client_t domain.


.EX
.PP
.B fail2ban_exec_t 
.EE

- Set files with the fail2ban_exec_t type, if you want to transition an executable to the fail2ban_t domain.

.br
.TP 5
Paths: 
/usr/bin/fail2ban-server, /usr/bin/fail2ban

.EX
.PP
.B fail2ban_initrc_exec_t 
.EE

- Set files with the fail2ban_initrc_exec_t type, if you want to transition an executable to the fail2ban_initrc_t domain.


.EX
.PP
.B fail2ban_log_t 
.EE

- Set files with the fail2ban_log_t type, if you want to treat the data as fail2ban log data, usually stored under the /var/log directory.


.EX
.PP
.B fail2ban_tmp_t 
.EE

- Set files with the fail2ban_tmp_t type, if you want to store fail2ban temporary files in the /tmp directories.


.EX
.PP
.B fail2ban_var_lib_t 
.EE

- Set files with the fail2ban_var_lib_t type, if you want to store the fail2ban files under the /var/lib directory.


.EX
.PP
.B fail2ban_var_run_t 
.EE

- Set files with the fail2ban_var_run_t type, if you want to store the fail2ban files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux fail2ban policy is very flexible allowing users to setup their fail2ban processes in as secure a method as possible.
.PP 
The following process types are defined for fail2ban:

.EX
.B fail2ban_client_t, fail2ban_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type fail2ban_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B fail2ban_log_t

	/var/log/fail2ban\.log.*
.br

.br
.B fail2ban_tmp_t


.br
.B fail2ban_var_lib_t

	/var/lib/fail2ban(/.*)?
.br

.br
.B fail2ban_var_run_t

	/var/run/fail2ban.*
.br

.br
.B net_conf_t

	/etc/ntpd?\.conf.*
.br
	/etc/hosts[^/]*
.br
	/etc/yp\.conf.*
.br
	/etc/denyhosts.*
.br
	/etc/hosts\.deny.*
.br
	/etc/resolv\.conf.*
.br
	/etc/ntp/step-tickers.*
.br
	/etc/sysconfig/networking(/.*)?
.br
	/etc/sysconfig/network-scripts(/.*)?
.br
	/etc/sysconfig/network-scripts/.*resolv\.conf
.br
	/etc/ethers
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), fail2ban(8), semanage(8), restorecon(8), chcon(1)
, fail2ban_client_selinux(8)