.TH  "fcoemon_selinux"  "8"  "fcoemon" "dwalsh@redhat.com" "fcoemon SELinux Policy documentation"
.SH "NAME"
fcoemon_selinux \- Security Enhanced Linux Policy for the fcoemon processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the fcoemon processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux fcoemon policy is very flexible allowing users to setup their fcoemon processes in as secure a method as possible.
.PP 
The following file types are defined for fcoemon:


.EX
.B fcoemon_exec_t 
.EE

- Set files with the fcoemon_exec_t type, if you want to transition an executable to the fcoemon_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B fcoemon_var_run_t 
.EE

- Set files with the fcoemon_var_run_t type, if you want to store the fcoemon files under the /run directory.

.br
Paths: 
/var/run/fcm(/.*)?, /var/run/fcoemon\.pid
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), fcoemon(8), semanage(8), restorecon(8), chcon(1)
