.TH  "fetchmail_selinux"  "8"  "fetchmail" "dwalsh@redhat.com" "fetchmail SELinux Policy documentation"
.SH "NAME"
fetchmail_selinux \- Security Enhanced Linux Policy for the fetchmail processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the fetchmail processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux fetchmail policy is very flexible allowing users to setup their fetchmail processes in as secure a method as possible.
.PP 
The following file types are defined for fetchmail:


.EX
.B fetchmail_etc_t 
.EE

- Set files with the fetchmail_etc_t type, if you want to store fetchmail files in the /etc directories.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B fetchmail_exec_t 
.EE

- Set files with the fetchmail_exec_t type, if you want to transition an executable to the fetchmail_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B fetchmail_home_t 
.EE

- Set files with the fetchmail_home_t type, if you want to store fetchmail files in the users home directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B fetchmail_uidl_cache_t 
.EE

- Set files with the fetchmail_uidl_cache_t type, if you want to store the files under the /var/cache directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B fetchmail_var_run_t 
.EE

- Set files with the fetchmail_var_run_t type, if you want to store the fetchmail files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), fetchmail(8), semanage(8), restorecon(8), chcon(1)
