.TH  "ftpd_selinux"  "8"  "ftpd" "dwalsh@redhat.com" "ftpd SELinux Policy documentation"
.SH "NAME"
ftpd_selinux \- Security Enhanced Linux Policy for the ftpd processes
.SH "DESCRIPTION"




.SH BOOLEANS
SELinux policy is customizable based on least access required.  ftpd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run ftpd with the tightest access possible.


.PP
If you want to allow ftp to read and write files in the user home directorie, you must turn on the ftp_home_dir boolean.

.EX
.B setsebool -P ftp_home_dir 1
.EE

.PP
If you want to allow ftp servers to login to local users and read/write all files on the system, governed by DAC, you must turn on the allow_ftpd_full_access boolean.

.EX
.B setsebool -P allow_ftpd_full_access 1
.EE

.PP
If you want to allow ftp servers to connect to mysql database port, you must turn on the ftpd_connect_db boolean.

.EX
.B setsebool -P ftpd_connect_db 1
.EE

.PP
If you want to allow ftp servers to use cifs used for public file transfer services, you must turn on the allow_ftpd_use_cifs boolean.

.EX
.B setsebool -P allow_ftpd_use_cifs 1
.EE

.PP
If you want to allow ftp servers to use nfs used for public file transfer services, you must turn on the allow_ftpd_use_nfs boolean.

.EX
.B setsebool -P allow_ftpd_use_nfs 1
.EE

.PP
If you want to allow sftp-internal to read and write files in the user home directorie, you must turn on the sftpd_enable_homedirs boolean.

.EX
.B setsebool -P sftpd_enable_homedirs 1
.EE

.PP
If you want to allow httpd to act as a FTP client connecting to the ftp port and ephemeral port, you must turn on the httpd_can_connect_ftp boolean.

.EX
.B setsebool -P httpd_can_connect_ftp 1
.EE

.PP
If you want to allow sftp-internal to login to local users and read/write all files on the system, governed by DAC, you must turn on the sftpd_full_access boolean.

.EX
.B setsebool -P sftpd_full_access 1
.EE

.PP
If you want to allow ftp servers to connect to all ports > 102, you must turn on the ftpd_connect_all_unreserved boolean.

.EX
.B setsebool -P ftpd_connect_all_unreserved 1
.EE

.PP
If you want to allow httpd to act as a FTP server by listening on the ftp port, you must turn on the httpd_enable_ftp_server boolean.

.EX
.B setsebool -P httpd_enable_ftp_server 1
.EE

.PP
If you want to allow internal-sftp to read and write files in the user ssh home directories, you must turn on the sftpd_write_ssh_home boolean.

.EX
.B setsebool -P sftpd_write_ssh_home 1
.EE

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow ftpd servers to read the /var/ftpd directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/ftpd(/.*)?"
.br
.B restorecon -F -R -v /var/ftpd
.pp
.TP
Allow ftpd servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_ftpd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/ftpd/incoming(/.*)?"
.br
.B restorecon -F -R -v /var/ftpd/incoming


.PP
If you want to allow tftp to modify public files used for public file transfer services., you must turn on the tftp_anon_write boolean.

.EX
.B setsebool -P tftp_anon_write 1
.EE

.PP
If you want to allow ftp servers to upload files,  used for public file transfer services. Directories must be labeled public_content_rw_t., you must turn on the allow_ftpd_anon_write boolean.

.EX
.B setsebool -P allow_ftpd_anon_write 1
.EE

.PP
If you want to allow anon internal-sftp to upload files, used for public file transfer services, directories must be labeled public_content_rw_t., you must turn on the sftpd_anon_write boolean.

.EX
.B setsebool -P sftpd_anon_write 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux ftpd policy is very flexible allowing users to setup their ftpd processes in as secure a method as possible.
.PP 
The following file types are defined for ftpd:


.EX
.PP
.B ftpd_etc_t 
.EE

- Set files with the ftpd_etc_t type, if you want to store ftpd files in the /etc directories.


.EX
.PP
.B ftpd_exec_t 
.EE

- Set files with the ftpd_exec_t type, if you want to transition an executable to the ftpd_t domain.

.br
.TP 5
Paths: 
/usr/sbin/ftpwho, /etc/cron\.monthly/proftpd, /usr/sbin/in\.ftpd, /usr/sbin/proftpd, /usr/kerberos/sbin/ftpd, /usr/sbin/muddleftpd, /usr/sbin/vsftpd

.EX
.PP
.B ftpd_initrc_exec_t 
.EE

- Set files with the ftpd_initrc_exec_t type, if you want to transition an executable to the ftpd_initrc_t domain.

.br
.TP 5
Paths: 
/etc/rc\.d/init\.d/proftpd, /etc/rc\.d/init\.d/vsftpd

.EX
.PP
.B ftpd_keytab_t 
.EE

- Set files with the ftpd_keytab_t type, if you want to treat the files as kerberos keytab files.


.EX
.PP
.B ftpd_lock_t 
.EE

- Set files with the ftpd_lock_t type, if you want to treat the files as ftpd lock data, stored under the /var/lock directory


.EX
.PP
.B ftpd_tmp_t 
.EE

- Set files with the ftpd_tmp_t type, if you want to store ftpd temporary files in the /tmp directories.


.EX
.PP
.B ftpd_tmpfs_t 
.EE

- Set files with the ftpd_tmpfs_t type, if you want to store ftpd files on a tmpfs file system.


.EX
.PP
.B ftpd_unit_file_t 
.EE

- Set files with the ftpd_unit_file_t type, if you want to treat the files as ftpd unit content.


.EX
.PP
.B ftpd_var_run_t 
.EE

- Set files with the ftpd_var_run_t type, if you want to store the ftpd files under the /run directory.


.EX
.PP
.B ftpdctl_exec_t 
.EE

- Set files with the ftpdctl_exec_t type, if you want to transition an executable to the ftpdctl_t domain.


.EX
.PP
.B ftpdctl_tmp_t 
.EE

- Set files with the ftpdctl_tmp_t type, if you want to store ftpdctl temporary files in the /tmp directories.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux ftpd policy is very flexible allowing users to setup their ftpd processes in as secure a method as possible.
.PP 
The following port types are defined for ftpd:

.EX
.TP 5
.B ftp_data_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE

.EX
.TP 5
.B ftp_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux ftpd policy is very flexible allowing users to setup their ftpd processes in as secure a method as possible.
.PP 
The following process types are defined for ftpd:

.EX
.B ftpd_t, ftpdctl_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), ftpd(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)