.TH  "git_shell_selinux"  "8"  "git_shell" "mgrepl@redhat.com" "git_shell SELinux Policy documentation"
.SH "NAME"
git_shell_u \- \fBgit_shell user role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

\fBgit_shell_u\fP is an SELinux User defined in the SELinux
policy. SELinux users have default roles, \fBgit_shell_r\fP.  The
default role has a default type, \fBgit_shell_t\fP, associated with it.

The SELinux user will usually login to a system with a context that looks like:

.B git_shell_u:git_shell_r:git_shell_t:s0-s0:c0.c1023

Linux users are automatically assigned an SELinux users at login.  
Login programs use the SELinux User to assign initial context to the user's shell.

SELinux policy uses the context to control the user's access.

By default all users are assigned to the SELinux user via the \fB__default__\fP flag

On Targeted policy systems the \fB__default__\fP user is assigned to the \fBunconfined_u\fP SELinux user.

You can list all Linux User to SELinux user mapping using:

.B semanage login -l

If you wanted to change the default user mapping to use the git_shell_u user, you would execute:

.B semanage login -m -s git_shell_u __default__


.SH USER DESCRIPTION

The SELinux user git_shell_u is defined in policy as a unprivileged user. SELinux prevents unprivileged users from doing administration tasks without transitioning to a different role.

.SH SUDO

.SH X WINDOWS LOGIN

The SELinux user git_shell_u is not able to X Windows login.

.SH NETWORK

.TP
The SELinux user git_shell_u is able to connect to the following tcp ports.

.B dns_port_t: 53

.B ocsp_port_t: 9080

.B kerberos_port_t: 88,750,4444

.TP
The SELinux user git_shell_u is able to connect to the following tcp ports.

.B dns_port_t: 53

.B ocsp_port_t: 9080

.B kerberos_port_t: 88,750,4444

.SH HOME_EXEC

The SELinux user git_shell_u is able execute home content files.

.SH TRANSITIONS

Three things can happen when git_shell_t attempts to execute a program.

\fB1.\fP SELinux Policy can deny git_shell_t from executing the program.

.TP

\fB2.\fP SELinux Policy can allow git_shell_t to execute the program in the current user type.

Execute the following to see the types that the SELinux user git_shell_t can execute without transitioning:

.B sesearch -A -s git_shell_t -c file -p execute_no_trans

.TP

\fB3.\fP SELinux can allow git_shell_t to execute the program and transition to a new type.

Execute the following to see the types that the SELinux user git_shell_t can execute and transition:

.B $ sesearch -A -s git_shell_t -c process -p transition


.SH "MANAGED FILES"

The SELinux user type git_shell_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B alsa_home_t

	/home/[^/]*/\.asoundrc
.br

.br
.B git_sys_content_t

	/srv/git(/.*)?
.br
	/var/lib/git(/.*)?
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), git_shell(8), semanage(8), restorecon(8), chcon(1)
