.TH  "glance_registry_selinux"  "8"  "glance_registry" "dwalsh@redhat.com" "glance_registry SELinux Policy documentation"
.SH "NAME"
glance_registry_selinux \- Security Enhanced Linux Policy for the glance_registry processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the glance_registry processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux glance_registry policy is very flexible allowing users to setup their glance_registry processes in as secure a method as possible.
.PP 
The following file types are defined for glance_registry:


.EX
.PP
.B glance_registry_exec_t 
.EE

- Set files with the glance_registry_exec_t type, if you want to transition an executable to the glance_registry_t domain.


.EX
.PP
.B glance_registry_initrc_exec_t 
.EE

- Set files with the glance_registry_initrc_exec_t type, if you want to transition an executable to the glance_registry_initrc_t domain.


.EX
.PP
.B glance_registry_tmp_t 
.EE

- Set files with the glance_registry_tmp_t type, if you want to store glance registry temporary files in the /tmp directories.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux glance_registry policy is very flexible allowing users to setup their glance_registry processes in as secure a method as possible.
.PP 
The following port types are defined for glance_registry:

.EX
.TP 5
.B glance_registry_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 9191
.EE
udp 9191
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux glance_registry policy is very flexible allowing users to setup their glance_registry processes in as secure a method as possible.
.PP 
The following process types are defined for glance_registry:

.EX
.B glance_registry_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type glance_registry_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B glance_log_t

	/var/log/glance(/.*)?
.br

.br
.B glance_registry_tmp_t


.br
.B glance_var_lib_t

	/var/lib/glance(/.*)?
.br

.br
.B glance_var_run_t

	/var/run/glance(/.*)?
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), glance_registry(8), semanage(8), restorecon(8), chcon(1)
