.TH  "glance_selinux"  "8"  "glance" "dwalsh@redhat.com" "glance SELinux Policy documentation"
.SH "NAME"
glance_selinux \- Security Enhanced Linux Policy for the glance processes
.SH "DESCRIPTION"


SELinux Linux secures
.B glance
(policy for glance)
processes via flexible mandatory access
control.  



.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux glance policy is very flexible allowing users to setup their glance processes in as secure a method as possible.
.PP 
The following file types are defined for glance:


.EX
.PP
.B glance_api_exec_t 
.EE

- Set files with the glance_api_exec_t type, if you want to transition an executable to the glance_api_t domain.


.EX
.PP
.B glance_api_initrc_exec_t 
.EE

- Set files with the glance_api_initrc_exec_t type, if you want to transition an executable to the glance_api_initrc_t domain.


.EX
.PP
.B glance_log_t 
.EE

- Set files with the glance_log_t type, if you want to treat the data as glance log data, usually stored under the /var/log directory.


.EX
.PP
.B glance_registry_exec_t 
.EE

- Set files with the glance_registry_exec_t type, if you want to transition an executable to the glance_registry_t domain.


.EX
.PP
.B glance_registry_initrc_exec_t 
.EE

- Set files with the glance_registry_initrc_exec_t type, if you want to transition an executable to the glance_registry_initrc_t domain.


.EX
.PP
.B glance_registry_tmp_t 
.EE

- Set files with the glance_registry_tmp_t type, if you want to store glance registry temporary files in the /tmp directories.


.EX
.PP
.B glance_tmp_t 
.EE

- Set files with the glance_tmp_t type, if you want to store glance temporary files in the /tmp directories.


.EX
.PP
.B glance_var_lib_t 
.EE

- Set files with the glance_var_lib_t type, if you want to store the glance files under the /var/lib directory.


.EX
.PP
.B glance_var_run_t 
.EE

- Set files with the glance_var_run_t type, if you want to store the glance files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux glance policy is very flexible allowing users to setup their glance processes in as secure a method as possible.
.PP 
The following port types are defined for glance:

.EX
.TP 5
.B glance_registry_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux glance policy is very flexible allowing users to setup their glance processes in as secure a method as possible.
.PP 
The following process types are defined for glance:

.EX
.B glance_registry_t, glance_api_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), glance(8), semanage(8), restorecon(8), chcon(1)
