.TH  "gpg_web_selinux"  "8"  "13-01-16" "gpg_web" "SELinux Policy documentation for gpg_web"
.SH "NAME"
gpg_web_selinux \- Security Enhanced Linux Policy for the gpg_web processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the gpg_web processes via flexible mandatory access control.

The gpg_web processes execute with the gpg_web_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep gpg_web_t


.SH "ENTRYPOINTS"

The gpg_web_t SELinux type can be entered via the \fBgpg_exec_t\fP file type.

The default entrypoint paths for the gpg_web_t domain are the following:

/usr/bin/gpg(2)?, /usr/lib/gnupg/.*, /usr/bin/gpgsm
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux gpg_web policy is very flexible allowing users to setup their gpg_web processes in as secure a method as possible.
.PP
The following process types are defined for gpg_web:

.EX
.B gpg_web_t
.EE
.PP
Note:
.B semanage permissive -a gpg_web_t
can be used to make the process type gpg_web_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  gpg_web policy is extremely flexible and has several booleans that allow you to manipulate the policy and run gpg_web with the tightest access possible.


.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow httpd cgi support, you must turn on the httpd_enable_cgi boolean. Disabled by default.

.EX
.B setsebool -P httpd_enable_cgi 1

.EE

.PP
If you want to allow httpd to run gpg, you must turn on the httpd_use_gpg boolean. Disabled by default.

.EX
.B setsebool -P httpd_use_gpg 1

.EE

.SH "MANAGED FILES"

The SELinux process type gpg_web_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B httpd_sys_rw_content_t

	/etc/horde(/.*)?
.br
	/etc/drupal.*
.br
	/etc/z-push(/.*)?
.br
	/var/lib/svn(/.*)?
.br
	/var/www/svn(/.*)?
.br
	/etc/mock/koji(/.*)?
.br
	/var/www/html/[^/]*/sites/default/files(/.*)?
.br
	/var/www/html/[^/]*/sites/default/settings\.php
.br
	/var/lib/drupal.*
.br
	/etc/zabbix/web(/.*)?
.br
	/var/log/z-push(/.*)?
.br
	/var/spool/gosa(/.*)?
.br
	/etc/WebCalendar(/.*)?
.br
	/var/lib/dokuwiki(/.*)?
.br
	/var/spool/viewvc(/.*)?
.br
	/var/lib/pootle/po(/.*)?
.br
	/var/www/moodledata(/.*)?
.br
	/var/www/gallery/albums(/.*)?
.br
	/var/www/html/wp-content(/.*)?
.br
	/usr/share/wordpress-mu/wp-content(/.*)?
.br
	/usr/share/wordpress/wp-content/uploads(/.*)?
.br
	/usr/share/wordpress/wp-content/upgrade(/.*)?
.br
	/etc/owncloud/config\.php
.br
	/var/www/html/configuration\.php
.br

.br
.B public_content_rw_t

	/var/spool/abrt-upload(/.*)?
.br

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow gpg_web servers to read the /var/gpg_web directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/gpg_web(/.*)?"
.br
.B restorecon -F -R -v /var/gpg_web
.pp
.TP
Allow gpg_web servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_gpg_webd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/gpg_web/incoming(/.*)?"
.br
.B restorecon -F -R -v /var/gpg_web/incoming


.PP
If you want to allow gpg web domain to modify public files used for public file transfer services., you must turn on the gpg_web_anon_write boolean.

.EX
.B setsebool -P gpg_web_anon_write 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), gpg_web(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), gpg_selinux(8), gpg_selinux(8), gpg_agent_selinux(8), gpg_helper_selinux(8), gpg_pinentry_selinux(8)