.TH  "gpg_selinux"  "8"  "gpg" "dwalsh@redhat.com" "gpg SELinux Policy documentation"
.SH "NAME"
gpg_selinux \- Security Enhanced Linux Policy for the gpg processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the gpg processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux gpg policy is very flexible allowing users to setup their gpg processes in as secure a method as possible.
.PP 
The following file types are defined for gpg:


.EX
.B gpg_agent_exec_t 
.EE

- Set files with the gpg_agent_exec_t context, if you want to a executable to transition to the gpg_agent_t domain.

.br
Path: 
/usr/bin/gpg-agent

.EX
.B gpg_agent_tmp_t 
.EE

- Set files with the gpg_agent_tmp_t context, if you want to store gpg agent temporary files in the /tmp directories.


.EX
.B gpg_exec_t 
.EE

- Set files with the gpg_exec_t context, if you want to a executable to transition to the gpg_t domain.

.br
Paths: 
/usr/bin/gpg(2)?, /usr/bin/kgpg, /usr/lib/gnupg/.*

.EX
.B gpg_helper_exec_t 
.EE

- Set files with the gpg_helper_exec_t context, if you want to a executable to transition to the gpg_helper_t domain.

.br
Path: 
/usr/lib/gnupg/gpgkeys.*

.EX
.B gpg_pinentry_tmp_t 
.EE

- Set files with the gpg_pinentry_tmp_t context, if you want to store gpg pinentry temporary files in the /tmp directories.


.EX
.B gpg_pinentry_tmpfs_t 
.EE

- Set files with the gpg_pinentry_tmpfs_t context, if you want to store gpg pinentry files on a tmpfs file system.


.EX
.B gpg_secret_t 
.EE

- Set files with the gpg_secret_t context, if you want to treat the files as gpg se secret data.

.br
Path: 
/root/\.gnupg(/.+)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  gpg policy is extremely flexible and has several booleans that allow you to manipulate the policy and run gpg with the tightest access possible.


.PP
If you want to allow usage of the gpg-agent --write-env-file option. This also allows gpg-agent to manage user files, you must turn on the gpg_agent_env_file boolean.

.EX
.B setsebool -P gpg_agent_env_file 1
.EE

.PP
If you want to allow httpd to run gpg in gpg-web domai, you must turn on the httpd_use_gpg boolean.

.EX
.B setsebool -P httpd_use_gpg 1
.EE

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow gpg servers to read the /var/gpg directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/gpg(/.*)?"
.TP
.B
restorecon -F -R -v /var/gpg
.pp
.TP
Allow gpg servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_gpgd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/gpg/incoming(/.*)?"
.TP
.B
restorecon -F -R -v /var/gpg/incoming


.PP
If you want to allow gpg web domain to modify public files used for public file transfer services., you must turn on the gpg_web_anon_write boolean.

.EX
.B setsebool -P gpg_web_anon_write 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), gpg(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)