.TH  "gpsd_selinux"  "8"  "gpsd" "dwalsh@redhat.com" "gpsd SELinux Policy documentation"
.SH "NAME"
gpsd_selinux \- Security Enhanced Linux Policy for the gpsd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the gpsd processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux gpsd policy is very flexible allowing users to setup their gpsd processes in as secure a method as possible.
.PP 
The following file types are defined for gpsd:


.EX
.B gpsd_exec_t 
.EE

- Set files with the gpsd_exec_t type, if you want to transition an executable to the gpsd_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B gpsd_initrc_exec_t 
.EE

- Set files with the gpsd_initrc_exec_t type, if you want to transition an executable to the gpsd_initrc_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B gpsd_tmpfs_t 
.EE

- Set files with the gpsd_tmpfs_t type, if you want to store gpsd files on a tmpfs file system.


.EX
.B gpsd_var_run_t 
.EE

- Set files with the gpsd_var_run_t type, if you want to store the gpsd files under the /run directory.

.br
Paths: 
/var/run/gpsd\.sock, /var/run/gpsd\.pid
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux gpsd policy is very flexible allowing users to setup their gpsd processes in as secure a method as possible.
.PP 
The following port types are defined for gpsd:
.EX

.B gpsd_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 2947
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), gpsd(8), semanage(8), restorecon(8), chcon(1)
