.TH  "httpd_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "httpd Selinux Policy documentation"
.SH "NAME"
httpd_selinux \- Security Enhanced Linux Policy for the httpd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the httpd processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux httpd policy is very flexible allowing users to setup their httpd processes in as secure a method as possible.
.PP 
The following file types are defined for httpd:


.EX
.B httpd_apcupsd_cgi_content_t 
.EE

- Set files with the httpd_apcupsd_cgi_content_t context, if you want to treat the files as httpd apcupsd cgi content.


.EX
.B httpd_apcupsd_cgi_htaccess_t 
.EE

- Set files with the httpd_apcupsd_cgi_htaccess_t context, if you want to treat the file as a httpd apcupsd cgi access file.


.EX
.B httpd_apcupsd_cgi_ra_content_t 
.EE

- Set files with the httpd_apcupsd_cgi_ra_content_t context, if you want to treat the files as httpd apcupsd cgi  read/append content.


.EX
.B httpd_apcupsd_cgi_rw_content_t 
.EE

- Set files with the httpd_apcupsd_cgi_rw_content_t context, if you want to treat the files as httpd apcupsd cgi read/write content.


.EX
.B httpd_apcupsd_cgi_script_exec_t 
.EE

- Set files with the httpd_apcupsd_cgi_script_exec_t context, if you want to a executable to transition to the httpd_apcupsd_cgi_script_t domain.


.EX
.B httpd_awstats_content_t 
.EE

- Set files with the httpd_awstats_content_t context, if you want to treat the files as httpd awstats content.


.EX
.B httpd_awstats_htaccess_t 
.EE

- Set files with the httpd_awstats_htaccess_t context, if you want to treat the file as a httpd awstats access file.


.EX
.B httpd_awstats_ra_content_t 
.EE

- Set files with the httpd_awstats_ra_content_t context, if you want to treat the files as httpd awstats  read/append content.


.EX
.B httpd_awstats_rw_content_t 
.EE

- Set files with the httpd_awstats_rw_content_t context, if you want to treat the files as httpd awstats read/write content.


.EX
.B httpd_awstats_script_exec_t 
.EE

- Set files with the httpd_awstats_script_exec_t context, if you want to a executable to transition to the httpd_awstats_script_t domain.


.EX
.B httpd_bugzilla_content_t 
.EE

- Set files with the httpd_bugzilla_content_t context, if you want to treat the files as httpd bugzilla content.


.EX
.B httpd_bugzilla_htaccess_t 
.EE

- Set files with the httpd_bugzilla_htaccess_t context, if you want to treat the file as a httpd bugzilla access file.


.EX
.B httpd_bugzilla_ra_content_t 
.EE

- Set files with the httpd_bugzilla_ra_content_t context, if you want to treat the files as httpd bugzilla  read/append content.


.EX
.B httpd_bugzilla_rw_content_t 
.EE

- Set files with the httpd_bugzilla_rw_content_t context, if you want to treat the files as httpd bugzilla read/write content.


.EX
.B httpd_bugzilla_script_exec_t 
.EE

- Set files with the httpd_bugzilla_script_exec_t context, if you want to a executable to transition to the httpd_bugzilla_script_t domain.


.EX
.B httpd_bugzilla_tmp_t 
.EE

- Set files with the httpd_bugzilla_tmp_t context, if you want to store httpd bugzilla temporary files in the /tmp directories.


.EX
.B httpd_cache_t 
.EE

- Set files with the httpd_cache_t context, if you want to store the files under the /var/cache directory.


.EX
.B httpd_cobbler_content_t 
.EE

- Set files with the httpd_cobbler_content_t context, if you want to treat the files as httpd cobbler content.


.EX
.B httpd_cobbler_htaccess_t 
.EE

- Set files with the httpd_cobbler_htaccess_t context, if you want to treat the file as a httpd cobbler access file.


.EX
.B httpd_cobbler_ra_content_t 
.EE

- Set files with the httpd_cobbler_ra_content_t context, if you want to treat the files as httpd cobbler  read/append content.


.EX
.B httpd_cobbler_rw_content_t 
.EE

- Set files with the httpd_cobbler_rw_content_t context, if you want to treat the files as httpd cobbler read/write content.


.EX
.B httpd_cobbler_script_exec_t 
.EE

- Set files with the httpd_cobbler_script_exec_t context, if you want to a executable to transition to the httpd_cobbler_script_t domain.


.EX
.B httpd_collectd_content_t 
.EE

- Set files with the httpd_collectd_content_t context, if you want to treat the files as httpd collectd content.


.EX
.B httpd_collectd_htaccess_t 
.EE

- Set files with the httpd_collectd_htaccess_t context, if you want to treat the file as a httpd collectd access file.


.EX
.B httpd_collectd_ra_content_t 
.EE

- Set files with the httpd_collectd_ra_content_t context, if you want to treat the files as httpd collectd  read/append content.


.EX
.B httpd_collectd_rw_content_t 
.EE

- Set files with the httpd_collectd_rw_content_t context, if you want to treat the files as httpd collectd read/write content.


.EX
.B httpd_collectd_script_exec_t 
.EE

- Set files with the httpd_collectd_script_exec_t context, if you want to a executable to transition to the httpd_collectd_script_t domain.


.EX
.B httpd_config_t 
.EE

- Set files with the httpd_config_t context, if you want to treat the files as httpd configuration data, usually stored under the /etc directory.


.EX
.B httpd_cvs_content_t 
.EE

- Set files with the httpd_cvs_content_t context, if you want to treat the files as httpd cvs content.


.EX
.B httpd_cvs_htaccess_t 
.EE

- Set files with the httpd_cvs_htaccess_t context, if you want to treat the file as a httpd cvs access file.


.EX
.B httpd_cvs_ra_content_t 
.EE

- Set files with the httpd_cvs_ra_content_t context, if you want to treat the files as httpd cvs  read/append content.


.EX
.B httpd_cvs_rw_content_t 
.EE

- Set files with the httpd_cvs_rw_content_t context, if you want to treat the files as httpd cvs read/write content.


.EX
.B httpd_cvs_script_exec_t 
.EE

- Set files with the httpd_cvs_script_exec_t context, if you want to a executable to transition to the httpd_cvs_script_t domain.


.EX
.B httpd_dirsrvadmin_content_t 
.EE

- Set files with the httpd_dirsrvadmin_content_t context, if you want to treat the files as httpd dirsrvadmin content.


.EX
.B httpd_dirsrvadmin_htaccess_t 
.EE

- Set files with the httpd_dirsrvadmin_htaccess_t context, if you want to treat the file as a httpd dirsrvadmin access file.


.EX
.B httpd_dirsrvadmin_ra_content_t 
.EE

- Set files with the httpd_dirsrvadmin_ra_content_t context, if you want to treat the files as httpd dirsrvadmin  read/append content.


.EX
.B httpd_dirsrvadmin_rw_content_t 
.EE

- Set files with the httpd_dirsrvadmin_rw_content_t context, if you want to treat the files as httpd dirsrvadmin read/write content.


.EX
.B httpd_dirsrvadmin_script_exec_t 
.EE

- Set files with the httpd_dirsrvadmin_script_exec_t context, if you want to a executable to transition to the httpd_dirsrvadmin_script_t domain.


.EX
.B httpd_dspam_content_t 
.EE

- Set files with the httpd_dspam_content_t context, if you want to treat the files as httpd dspam content.


.EX
.B httpd_dspam_htaccess_t 
.EE

- Set files with the httpd_dspam_htaccess_t context, if you want to treat the file as a httpd dspam access file.


.EX
.B httpd_dspam_ra_content_t 
.EE

- Set files with the httpd_dspam_ra_content_t context, if you want to treat the files as httpd dspam  read/append content.


.EX
.B httpd_dspam_rw_content_t 
.EE

- Set files with the httpd_dspam_rw_content_t context, if you want to treat the files as httpd dspam read/write content.


.EX
.B httpd_dspam_script_exec_t 
.EE

- Set files with the httpd_dspam_script_exec_t context, if you want to a executable to transition to the httpd_dspam_script_t domain.


.EX
.B httpd_exec_t 
.EE

- Set files with the httpd_exec_t context, if you want to a executable to transition to the httpd_t domain.


.EX
.B httpd_git_content_t 
.EE

- Set files with the httpd_git_content_t context, if you want to treat the files as httpd git content.


.EX
.B httpd_git_htaccess_t 
.EE

- Set files with the httpd_git_htaccess_t context, if you want to treat the file as a httpd git access file.


.EX
.B httpd_git_ra_content_t 
.EE

- Set files with the httpd_git_ra_content_t context, if you want to treat the files as httpd git  read/append content.


.EX
.B httpd_git_rw_content_t 
.EE

- Set files with the httpd_git_rw_content_t context, if you want to treat the files as httpd git read/write content.


.EX
.B httpd_git_script_exec_t 
.EE

- Set files with the httpd_git_script_exec_t context, if you want to a executable to transition to the httpd_git_script_t domain.


.EX
.B httpd_helper_exec_t 
.EE

- Set files with the httpd_helper_exec_t context, if you want to a executable to transition to the httpd_helper_t domain.


.EX
.B httpd_initrc_exec_t 
.EE

- Set files with the httpd_initrc_exec_t context, if you want to a executable to transition to the httpd_initrc_t domain.


.EX
.B httpd_keytab_t 
.EE

- Set files with the httpd_keytab_t context, if you want to treat the files as kerberos keytab files.


.EX
.B httpd_libra_content_t 
.EE

- Set files with the httpd_libra_content_t context, if you want to treat the files as httpd libra content.


.EX
.B httpd_libra_htaccess_t 
.EE

- Set files with the httpd_libra_htaccess_t context, if you want to treat the file as a httpd libra access file.


.EX
.B httpd_libra_ra_content_t 
.EE

- Set files with the httpd_libra_ra_content_t context, if you want to treat the files as httpd libra  read/append content.


.EX
.B httpd_libra_rw_content_t 
.EE

- Set files with the httpd_libra_rw_content_t context, if you want to treat the files as httpd libra read/write content.


.EX
.B httpd_libra_script_exec_t 
.EE

- Set files with the httpd_libra_script_exec_t context, if you want to a executable to transition to the httpd_libra_script_t domain.


.EX
.B httpd_lock_t 
.EE

- Set files with the httpd_lock_t context, if you want to treat the files as httpd lock data, stored under the /var/lock directory


.EX
.B httpd_log_t 
.EE

- Set files with the httpd_log_t context, if you want to treat the data as httpd log data, usually stored under the /var/log directory.


.EX
.B httpd_mediawiki_content_t 
.EE

- Set files with the httpd_mediawiki_content_t context, if you want to treat the files as httpd mediawiki content.


.EX
.B httpd_mediawiki_htaccess_t 
.EE

- Set files with the httpd_mediawiki_htaccess_t context, if you want to treat the file as a httpd mediawiki access file.


.EX
.B httpd_mediawiki_ra_content_t 
.EE

- Set files with the httpd_mediawiki_ra_content_t context, if you want to treat the files as httpd mediawiki  read/append content.


.EX
.B httpd_mediawiki_rw_content_t 
.EE

- Set files with the httpd_mediawiki_rw_content_t context, if you want to treat the files as httpd mediawiki read/write content.


.EX
.B httpd_mediawiki_script_exec_t 
.EE

- Set files with the httpd_mediawiki_script_exec_t context, if you want to a executable to transition to the httpd_mediawiki_script_t domain.


.EX
.B httpd_modules_t 
.EE

- Set files with the httpd_modules_t context, if you want to treat the files as httpd modules.


.EX
.B httpd_mojomojo_content_t 
.EE

- Set files with the httpd_mojomojo_content_t context, if you want to treat the files as httpd mojomojo content.


.EX
.B httpd_mojomojo_htaccess_t 
.EE

- Set files with the httpd_mojomojo_htaccess_t context, if you want to treat the file as a httpd mojomojo access file.


.EX
.B httpd_mojomojo_ra_content_t 
.EE

- Set files with the httpd_mojomojo_ra_content_t context, if you want to treat the files as httpd mojomojo  read/append content.


.EX
.B httpd_mojomojo_rw_content_t 
.EE

- Set files with the httpd_mojomojo_rw_content_t context, if you want to treat the files as httpd mojomojo read/write content.


.EX
.B httpd_mojomojo_script_exec_t 
.EE

- Set files with the httpd_mojomojo_script_exec_t context, if you want to a executable to transition to the httpd_mojomojo_script_t domain.


.EX
.B httpd_mojomojo_tmp_t 
.EE

- Set files with the httpd_mojomojo_tmp_t context, if you want to store httpd mojomojo temporary files in the /tmp directories.


.EX
.B httpd_munin_content_t 
.EE

- Set files with the httpd_munin_content_t context, if you want to treat the files as httpd munin content.


.EX
.B httpd_munin_htaccess_t 
.EE

- Set files with the httpd_munin_htaccess_t context, if you want to treat the file as a httpd munin access file.


.EX
.B httpd_munin_ra_content_t 
.EE

- Set files with the httpd_munin_ra_content_t context, if you want to treat the files as httpd munin  read/append content.


.EX
.B httpd_munin_rw_content_t 
.EE

- Set files with the httpd_munin_rw_content_t context, if you want to treat the files as httpd munin read/write content.


.EX
.B httpd_munin_script_exec_t 
.EE

- Set files with the httpd_munin_script_exec_t context, if you want to a executable to transition to the httpd_munin_script_t domain.


.EX
.B httpd_nagios_content_t 
.EE

- Set files with the httpd_nagios_content_t context, if you want to treat the files as httpd nagios content.


.EX
.B httpd_nagios_htaccess_t 
.EE

- Set files with the httpd_nagios_htaccess_t context, if you want to treat the file as a httpd nagios access file.


.EX
.B httpd_nagios_ra_content_t 
.EE

- Set files with the httpd_nagios_ra_content_t context, if you want to treat the files as httpd nagios  read/append content.


.EX
.B httpd_nagios_rw_content_t 
.EE

- Set files with the httpd_nagios_rw_content_t context, if you want to treat the files as httpd nagios read/write content.


.EX
.B httpd_nagios_script_exec_t 
.EE

- Set files with the httpd_nagios_script_exec_t context, if you want to a executable to transition to the httpd_nagios_script_t domain.


.EX
.B httpd_nutups_cgi_content_t 
.EE

- Set files with the httpd_nutups_cgi_content_t context, if you want to treat the files as httpd nutups cgi content.


.EX
.B httpd_nutups_cgi_htaccess_t 
.EE

- Set files with the httpd_nutups_cgi_htaccess_t context, if you want to treat the file as a httpd nutups cgi access file.


.EX
.B httpd_nutups_cgi_ra_content_t 
.EE

- Set files with the httpd_nutups_cgi_ra_content_t context, if you want to treat the files as httpd nutups cgi  read/append content.


.EX
.B httpd_nutups_cgi_rw_content_t 
.EE

- Set files with the httpd_nutups_cgi_rw_content_t context, if you want to treat the files as httpd nutups cgi read/write content.


.EX
.B httpd_nutups_cgi_script_exec_t 
.EE

- Set files with the httpd_nutups_cgi_script_exec_t context, if you want to a executable to transition to the httpd_nutups_cgi_script_t domain.


.EX
.B httpd_passwd_exec_t 
.EE

- Set files with the httpd_passwd_exec_t context, if you want to a executable to transition to the httpd_passwd_t domain.


.EX
.B httpd_php_exec_t 
.EE

- Set files with the httpd_php_exec_t context, if you want to a executable to transition to the httpd_php_t domain.


.EX
.B httpd_php_tmp_t 
.EE

- Set files with the httpd_php_tmp_t context, if you want to store httpd php temporary files in the /tmp directories.


.EX
.B httpd_prewikka_content_t 
.EE

- Set files with the httpd_prewikka_content_t context, if you want to treat the files as httpd prewikka content.


.EX
.B httpd_prewikka_htaccess_t 
.EE

- Set files with the httpd_prewikka_htaccess_t context, if you want to treat the file as a httpd prewikka access file.


.EX
.B httpd_prewikka_ra_content_t 
.EE

- Set files with the httpd_prewikka_ra_content_t context, if you want to treat the files as httpd prewikka  read/append content.


.EX
.B httpd_prewikka_rw_content_t 
.EE

- Set files with the httpd_prewikka_rw_content_t context, if you want to treat the files as httpd prewikka read/write content.


.EX
.B httpd_prewikka_script_exec_t 
.EE

- Set files with the httpd_prewikka_script_exec_t context, if you want to a executable to transition to the httpd_prewikka_script_t domain.


.EX
.B httpd_rotatelogs_exec_t 
.EE

- Set files with the httpd_rotatelogs_exec_t context, if you want to a executable to transition to the httpd_rotatelogs_t domain.


.EX
.B httpd_smokeping_cgi_content_t 
.EE

- Set files with the httpd_smokeping_cgi_content_t context, if you want to treat the files as httpd smokeping cgi content.


.EX
.B httpd_smokeping_cgi_htaccess_t 
.EE

- Set files with the httpd_smokeping_cgi_htaccess_t context, if you want to treat the file as a httpd smokeping cgi access file.


.EX
.B httpd_smokeping_cgi_ra_content_t 
.EE

- Set files with the httpd_smokeping_cgi_ra_content_t context, if you want to treat the files as httpd smokeping cgi  read/append content.


.EX
.B httpd_smokeping_cgi_rw_content_t 
.EE

- Set files with the httpd_smokeping_cgi_rw_content_t context, if you want to treat the files as httpd smokeping cgi read/write content.


.EX
.B httpd_smokeping_cgi_script_exec_t 
.EE

- Set files with the httpd_smokeping_cgi_script_exec_t context, if you want to a executable to transition to the httpd_smokeping_cgi_script_t domain.


.EX
.B httpd_squid_content_t 
.EE

- Set files with the httpd_squid_content_t context, if you want to treat the files as httpd squid content.


.EX
.B httpd_squid_htaccess_t 
.EE

- Set files with the httpd_squid_htaccess_t context, if you want to treat the file as a httpd squid access file.


.EX
.B httpd_squid_ra_content_t 
.EE

- Set files with the httpd_squid_ra_content_t context, if you want to treat the files as httpd squid  read/append content.


.EX
.B httpd_squid_rw_content_t 
.EE

- Set files with the httpd_squid_rw_content_t context, if you want to treat the files as httpd squid read/write content.


.EX
.B httpd_squid_script_exec_t 
.EE

- Set files with the httpd_squid_script_exec_t context, if you want to a executable to transition to the httpd_squid_script_t domain.


.EX
.B httpd_squirrelmail_t 
.EE

- Set files with the httpd_squirrelmail_t context, if you want to treat the files as httpd squirrelmail data.


.EX
.B httpd_suexec_exec_t 
.EE

- Set files with the httpd_suexec_exec_t context, if you want to a executable to transition to the httpd_suexec_t domain.


.EX
.B httpd_suexec_tmp_t 
.EE

- Set files with the httpd_suexec_tmp_t context, if you want to store httpd suexec temporary files in the /tmp directories.


.EX
.B httpd_sys_content_t 
.EE

- Set files with the httpd_sys_content_t context, if you want to treat the files as httpd sys content.


.EX
.B httpd_sys_htaccess_t 
.EE

- Set files with the httpd_sys_htaccess_t context, if you want to treat the file as a httpd sys access file.


.EX
.B httpd_sys_ra_content_t 
.EE

- Set files with the httpd_sys_ra_content_t context, if you want to treat the files as httpd sys  read/append content.


.EX
.B httpd_sys_rw_content_t 
.EE

- Set files with the httpd_sys_rw_content_t context, if you want to treat the files as httpd sys read/write content.


.EX
.B httpd_sys_script_exec_t 
.EE

- Set files with the httpd_sys_script_exec_t context, if you want to a executable to transition to the httpd_sys_script_t domain.


.EX
.B httpd_tmp_t 
.EE

- Set files with the httpd_tmp_t context, if you want to store httpd temporary files in the /tmp directories.


.EX
.B httpd_tmpfs_t 
.EE

- Set files with the httpd_tmpfs_t context, if you want to store httpd files on a tmpfs file system.


.EX
.B httpd_unit_file_t 
.EE

- Set files with the httpd_unit_file_t context, if you want to treat the files as httpd unit content.


.EX
.B httpd_user_content_t 
.EE

- Set files with the httpd_user_content_t context, if you want to treat the files as httpd user content.


.EX
.B httpd_user_htaccess_t 
.EE

- Set files with the httpd_user_htaccess_t context, if you want to treat the file as a httpd user access file.


.EX
.B httpd_user_ra_content_t 
.EE

- Set files with the httpd_user_ra_content_t context, if you want to treat the files as httpd user  read/append content.


.EX
.B httpd_user_rw_content_t 
.EE

- Set files with the httpd_user_rw_content_t context, if you want to treat the files as httpd user read/write content.


.EX
.B httpd_user_script_exec_t 
.EE

- Set files with the httpd_user_script_exec_t context, if you want to a executable to transition to the httpd_user_script_t domain.


.EX
.B httpd_var_lib_t 
.EE

- Set files with the httpd_var_lib_t context, if you want to store the httpd files under the /var/lib directory.


.EX
.B httpd_var_run_t 
.EE

- Set files with the httpd_var_run_t context, if you want to store the httpd files under the /run directory.


.EX
.B httpd_w3c_validator_content_t 
.EE

- Set files with the httpd_w3c_validator_content_t context, if you want to treat the files as httpd w3c validator content.


.EX
.B httpd_w3c_validator_htaccess_t 
.EE

- Set files with the httpd_w3c_validator_htaccess_t context, if you want to treat the file as a httpd w3c validator access file.


.EX
.B httpd_w3c_validator_ra_content_t 
.EE

- Set files with the httpd_w3c_validator_ra_content_t context, if you want to treat the files as httpd w3c validator  read/append content.


.EX
.B httpd_w3c_validator_rw_content_t 
.EE

- Set files with the httpd_w3c_validator_rw_content_t context, if you want to treat the files as httpd w3c validator read/write content.


.EX
.B httpd_w3c_validator_script_exec_t 
.EE

- Set files with the httpd_w3c_validator_script_exec_t context, if you want to a executable to transition to the httpd_w3c_validator_script_t domain.


.EX
.B httpd_w3c_validator_tmp_t 
.EE

- Set files with the httpd_w3c_validator_tmp_t context, if you want to store httpd w3c validator temporary files in the /tmp directories.


.EX
.B httpd_zoneminder_content_t 
.EE

- Set files with the httpd_zoneminder_content_t context, if you want to treat the files as httpd zoneminder content.


.EX
.B httpd_zoneminder_htaccess_t 
.EE

- Set files with the httpd_zoneminder_htaccess_t context, if you want to treat the file as a httpd zoneminder access file.


.EX
.B httpd_zoneminder_ra_content_t 
.EE

- Set files with the httpd_zoneminder_ra_content_t context, if you want to treat the files as httpd zoneminder  read/append content.


.EX
.B httpd_zoneminder_rw_content_t 
.EE

- Set files with the httpd_zoneminder_rw_content_t context, if you want to treat the files as httpd zoneminder read/write content.


.EX
.B httpd_zoneminder_script_exec_t 
.EE

- Set files with the httpd_zoneminder_script_exec_t context, if you want to a executable to transition to the httpd_zoneminder_script_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  httpd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run httpd with the tightest access possible.


.PP
If you want to allow httpd to act as a rela, you must turn on the httpd_can_network_relay boolean.

.EX
.B setsebool -P httpd_can_network_relay 1
.EE

.PP
If you want to allow HTTPD scripts and modules to connect to databases over the network, you must turn on the httpd_can_network_connect_db boolean.

.EX
.B setsebool -P httpd_can_network_connect_db 1
.EE

.PP
If you want to allow httpd to run gpg in gpg-web domai, you must turn on the httpd_use_gpg boolean.

.EX
.B setsebool -P httpd_use_gpg 1
.EE

.PP
If you want to allow httpd to execute cgi script, you must turn on the httpd_enable_cgi boolean.

.EX
.B setsebool -P httpd_enable_cgi 1
.EE

.PP
If you want to allow httpd to access cifs file system, you must turn on the httpd_use_cifs boolean.

.EX
.B setsebool -P httpd_use_cifs 1
.EE

.PP
If you want to allow Apache to use mod_auth_pa, you must turn on the allow_httpd_mod_auth_pam boolean.

.EX
.B setsebool -P allow_httpd_mod_auth_pam 1
.EE

.PP
If you want to allow httpd to read home directorie, you must turn on the httpd_enable_homedirs boolean.

.EX
.B setsebool -P httpd_enable_homedirs 1
.EE

.PP
If you want to allow Apache to communicate with avahi service via dbu, you must turn on the httpd_dbus_avahi boolean.

.EX
.B setsebool -P httpd_dbus_avahi 1
.EE

.PP
If you want to unify HTTPD handling of all content files, you must turn on the httpd_unified boolean.

.EX
.B setsebool -P httpd_unified 1
.EE

.PP
If you want to allow HTTPD scripts and modules to connect to the network using any TCP port, you must turn on the httpd_can_network_connect boolean.

.EX
.B setsebool -P httpd_can_network_connect 1
.EE

.PP
If you want to allow httpd scripts and modules execmem/execstac, you must turn on the httpd_execmem boolean.

.EX
.B setsebool -P httpd_execmem 1
.EE

.PP
If you want to allow httpd to connect to the ldap por, you must turn on the httpd_can_connect_ldap boolean.

.EX
.B setsebool -P httpd_can_connect_ldap 1
.EE

.PP
If you want to allow Apache to use mod_auth_ntlm_winbin, you must turn on the allow_httpd_mod_auth_ntlm_winbind boolean.

.EX
.B setsebool -P allow_httpd_mod_auth_ntlm_winbind 1
.EE

.PP
If you want to unify HTTPD to communicate with the terminal. Needed for entering the passphrase for certificates at the terminal, you must turn on the httpd_tty_comm boolean.

.EX
.B setsebool -P httpd_tty_comm 1
.EE

.PP
If you want to allow httpd to act as a FTP client connecting to the ftp port and ephemeral port, you must turn on the httpd_can_connect_ftp boolean.

.EX
.B setsebool -P httpd_can_connect_ftp 1
.EE

.PP
If you want to allow httpd to read user conten, you must turn on the httpd_read_user_content boolean.

.EX
.B setsebool -P httpd_read_user_content 1
.EE

.PP
If you want to allow httpd to access nfs file system, you must turn on the httpd_use_nfs boolean.

.EX
.B setsebool -P httpd_use_nfs 1
.EE

.PP
If you want to allow Apache to execute tmp content, you must turn on the httpd_tmp_exec boolean.

.EX
.B setsebool -P httpd_tmp_exec 1
.EE

.PP
If you want to allow httpd processes to manage IPA conten, you must turn on the httpd_manage_ipa boolean.

.EX
.B setsebool -P httpd_manage_ipa 1
.EE

.PP
If you want to allow http daemon to send mai, you must turn on the httpd_can_sendmail boolean.

.EX
.B setsebool -P httpd_can_sendmail 1
.EE

.PP
If you want to allow httpd to use built in scripting (usually php, you must turn on the httpd_builtin_scripting boolean.

.EX
.B setsebool -P httpd_builtin_scripting 1
.EE

.PP
If you want to allow http daemon to check spa, you must turn on the httpd_can_check_spam boolean.

.EX
.B setsebool -P httpd_can_check_spam 1
.EE

.PP
If you want to allow BIND to bind apache port, you must turn on the named_bind_http_port boolean.

.EX
.B setsebool -P named_bind_http_port 1
.EE

.PP
If you want to allow httpd to connect to memcache serve, you must turn on the httpd_can_network_memcache boolean.

.EX
.B setsebool -P httpd_can_network_memcache 1
.EE

.PP
If you want to allow HTTPD scripts and modules to connect to cobbler over the network, you must turn on the httpd_can_network_connect_cobbler boolean.

.EX
.B setsebool -P httpd_can_network_connect_cobbler 1
.EE

.PP
If you want to allow HTTPD to run SSI executables in the same domain as system CGI scripts, you must turn on the httpd_ssi_exec boolean.

.EX
.B setsebool -P httpd_ssi_exec 1
.EE

.PP
If you want to allow httpd to act as a FTP server by listening on the ftp port, you must turn on the httpd_enable_ftp_server boolean.

.EX
.B setsebool -P httpd_enable_ftp_server 1
.EE

.PP
If you want to allow http daemon to connect to zabbi, you must turn on the httpd_can_connect_zabbix boolean.

.EX
.B setsebool -P httpd_can_connect_zabbix 1
.EE

.PP
If you want to allow httpd daemon to change system limit, you must turn on the httpd_setrlimit boolean.

.EX
.B setsebool -P httpd_setrlimit 1
.EE

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow httpd servers to read the /var/httpd directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/httpd(/.*)?"
.TP
.B
restorecon -F -R -v /var/httpd
.pp
.TP
Allow httpd servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_httpdd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/httpd/incoming(/.*)?"
.TP
.B
restorecon -F -R -v /var/httpd/incoming


.PP
If you want to allow apache scripts to write to public content.  Directories/Files must be labeled public_rw_content_t., you must turn on the allow_httpd_sys_script_anon_write boolean.

.EX
.B setsebool -P allow_httpd_sys_script_anon_write 1
.EE

.PP
If you want to allow Apache to modify public files used for public file transfer services. Directories/Files must be labeled public_content_rw_t., you must turn on the allow_httpd_anon_write boolean.

.EX
.B setsebool -P allow_httpd_anon_write 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), httpd(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)