.TH  "iceauth_selinux"  "8"  "iceauth" "dwalsh@redhat.com" "iceauth Selinux Policy documentation"
.SH "NAME"
iceauth_selinux \- Security Enhanced Linux Policy for the iceauth processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the iceauth processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux iceauth policy is very flexible allowing users to setup their iceauth processes in as secure a method as possible.
.PP 
The following file types are defined for iceauth:


.EX
.B iceauth_exec_t 
.EE

- Set files with the iceauth_exec_t context, if you want to a executable to transition to the iceauth_t domain.

.br
Paths: 
/usr/bin/iceauth, /usr/X11R6/bin/iceauth

.EX
.B iceauth_home_t 
.EE

- Set files with the iceauth_home_t context, if you want to store iceauth files in the users home directory.

.br
Paths: 
/root/\.DCOP.*, /root/\.ICEauthority.*
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), iceauth(8), semanage(8), restorecon(8), chcon(1)
