.TH  "insmod_selinux"  "8"  "insmod" "dwalsh@redhat.com" "insmod SELinux Policy documentation"
.SH "NAME"
insmod_selinux \- Security Enhanced Linux Policy for the insmod processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the insmod processes via flexible mandatory access control.

The insmod processes execute with the insmod_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep insmod_t


.SH "ENTRYPOINTS"

The insmod_t SELinux type can be entered via the "insmod_exec_t" file type.  The default entrypoint paths for the insmod_t domain are the following:"

/sbin/rmmod.*, /sbin/modprobe.*, /sbin/insmod.*, /usr/sbin/modprobe.*, /usr/bin/kmod, /usr/sbin/insmod.*, /usr/sbin/rmmod.*
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux insmod policy is very flexible allowing users to setup their insmod processes in as secure a method as possible.
.PP 
The following process types are defined for insmod:

.EX
.B insmod_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  insmod policy is extremely flexible and has several booleans that allow you to manipulate the policy and run insmod with the tightest access possible.


.PP
If you want to disable kernel module loading, you must turn on the secure_mode_insmod boolean.

.EX
.B setsebool -P secure_mode_insmod 1
.EE

.PP
If you want to allow pppd to load kernel modules for certain modems, you must turn on the pppd_can_insmod boolean.

.EX
.B setsebool -P pppd_can_insmod 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux insmod policy is very flexible allowing users to setup their insmod processes in as secure a method as possible.
.PP 
The following file types are defined for insmod:


.EX
.PP
.B insmod_exec_t 
.EE

- Set files with the insmod_exec_t type, if you want to transition an executable to the insmod_t domain.

.br
.TP 5
Paths: 
/sbin/rmmod.*, /sbin/modprobe.*, /sbin/insmod.*, /usr/sbin/modprobe.*, /usr/bin/kmod, /usr/sbin/insmod.*, /usr/sbin/rmmod.*

.EX
.PP
.B insmod_tmpfs_t 
.EE

- Set files with the insmod_tmpfs_t type, if you want to store insmod files on a tmpfs file system.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type insmod_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B initrc_tmp_t


.br
.B insmod_tmpfs_t


.br
.B kdumpctl_tmp_t


.br
.B modules_dep_t

	/lib/modules/[^/]+/modules\..+
.br

.br
.B modules_object_t

	/lib/modules(/.*)?
.br
	/usr/lib/modules(/.*)?
.br

.br
.B mtrr_device_t

	/dev/cpu/mtrr
.br

.br
.B ramfs_t


.br
.B rpm_script_tmp_t


.br
.B sysfs_t

	/sys(/.*)?
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the insmod_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the insmod_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), insmod(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)