.TH  "ipsec_mgmt_selinux"  "8"  "ipsec_mgmt" "dwalsh@redhat.com" "ipsec_mgmt SELinux Policy documentation"
.SH "NAME"
ipsec_mgmt_selinux \- Security Enhanced Linux Policy for the ipsec_mgmt processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ipsec_mgmt processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the ipsec_mgmt_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the ipsec_mgmt_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux ipsec_mgmt policy is very flexible allowing users to setup their ipsec_mgmt processes in as secure a method as possible.
.PP 
The following file types are defined for ipsec_mgmt:


.EX
.PP
.B ipsec_mgmt_exec_t 
.EE

- Set files with the ipsec_mgmt_exec_t type, if you want to transition an executable to the ipsec_mgmt_t domain.

.br
.TP 5
Paths: 
/usr/lib/ipsec/_plutorun, /usr/libexec/ipsec/_plutoload, /usr/libexec/nm-openswan-service, /usr/sbin/ipsec, /usr/lib/ipsec/_plutoload, /usr/libexec/ipsec/_plutorun

.EX
.PP
.B ipsec_mgmt_lock_t 
.EE

- Set files with the ipsec_mgmt_lock_t type, if you want to treat the files as ipsec mgmt lock data, stored under the /var/lock directory


.EX
.PP
.B ipsec_mgmt_var_run_t 
.EE

- Set files with the ipsec_mgmt_var_run_t type, if you want to store the ipsec mgmt files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux ipsec_mgmt policy is very flexible allowing users to setup their ipsec_mgmt processes in as secure a method as possible.
.PP 
The following process types are defined for ipsec_mgmt:

.EX
.B ipsec_mgmt_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type ipsec_mgmt_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B ipsec_key_file_t

	/etc/ipsec\.d(/.*)?
.br
	/etc/racoon/certs(/.*)?
.br
	/etc/ipsec\.secrets
.br
	/etc/racoon/psk\.txt
.br

.br
.B ipsec_log_t

	/var/log/pluto\.log
.br

.br
.B ipsec_mgmt_lock_t

	/var/lock/subsys/ipsec
.br

.br
.B ipsec_mgmt_var_run_t


.br
.B ipsec_tmp_t


.br
.B ipsec_var_run_t

	/var/racoon(/.*)?
.br
	/var/run/pluto(/.*)?
.br
	/var/run/racoon\.pid
.br

.br
.B net_conf_t

	/etc/ntpd?\.conf.*
.br
	/etc/hosts[^/]*
.br
	/etc/yp\.conf.*
.br
	/etc/denyhosts.*
.br
	/etc/hosts\.deny.*
.br
	/etc/resolv\.conf.*
.br
	/etc/ntp/step-tickers.*
.br
	/etc/sysconfig/networking(/.*)?
.br
	/etc/sysconfig/network-scripts(/.*)?
.br
	/etc/sysconfig/network-scripts/.*resolv\.conf
.br
	/etc/ethers
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), ipsec_mgmt(8), semanage(8), restorecon(8), chcon(1)
, ipsec_selinux(8)