.TH  "irc_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "irc Selinux Policy documentation"
.SH "NAME"
irc_selinux \- Security Enhanced Linux Policy for the irc processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the irc processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux irc policy is very flexible allowing users to setup their irc processes in as secure a method as possible.
.PP 
The following file types are defined for irc:


.EX
.B irc_exec_t 
.EE

- Set files with the irc_exec_t context, if you want to a executable to transition to the irc_t domain.


.EX
.B irc_home_t 
.EE

- Set files with the irc_home_t context, if you want to store irc files in the users home directory.


.EX
.B irc_tmp_t 
.EE

- Set files with the irc_tmp_t context, if you want to store irc temporary files in the /tmp directories.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  irc policy is extremely flexible and has several booleans that allow you to manipulate the policy and run irc with the tightest access possible.


.PP
If you want to allow ftp to read and write files in the user home directorie, you must turn on the ftp_home_dir boolean.

.EX
.B setsebool -P ftp_home_dir 1
.EE

.PP
If you want to allow openvpn to read home directorie, you must turn on the openvpn_enable_homedirs boolean.

.EX
.B setsebool -P openvpn_enable_homedirs 1
.EE

.PP
If you want to allow confined virtual guests to read fuse file, you must turn on the virt_use_fusefs boolean.

.EX
.B setsebool -P virt_use_fusefs 1
.EE

.PP
If you want to allow ssh with chroot env to read and write files in the user home directorie, you must turn on the ssh_chroot_rw_homedirs boolean.

.EX
.B setsebool -P ssh_chroot_rw_homedirs 1
.EE

.PP
If you want to allow confined virtual guests to manage nfs file, you must turn on the virt_use_nfs boolean.

.EX
.B setsebool -P virt_use_nfs 1
.EE

.PP
If you want to allow confined virtual guests to use serial/parallel communication port, you must turn on the virt_use_comm boolean.

.EX
.B setsebool -P virt_use_comm 1
.EE

.PP
If you want to allow piranha-lvs domain to connect to the network using TCP, you must turn on the piranha_lvs_can_network_connect boolean.

.EX
.B setsebool -P piranha_lvs_can_network_connect 1
.EE

.PP
If you want to allow Git daemon system to search home directories, you must turn on the git_system_enable_homedirs boolean.

.EX
.B setsebool -P git_system_enable_homedirs 1
.EE

.PP
If you want to support SAMBA home directorie, you must turn on the use_samba_home_dirs boolean.

.EX
.B setsebool -P use_samba_home_dirs 1
.EE

.PP
If you want to allow mock to read files in home directories, you must turn on the mock_enable_homedirs boolean.

.EX
.B setsebool -P mock_enable_homedirs 1
.EE

.PP
If you want to allow samba to create new home directories (e.g. via PAM, you must turn on the samba_create_home_dirs boolean.

.EX
.B setsebool -P samba_create_home_dirs 1
.EE

.PP
If you want to allow the Irssi IRC Client to connect to any port, and to bind to any unreserved port, you must turn on the irssi_use_full_network boolean.

.EX
.B setsebool -P irssi_use_full_network 1
.EE

.PP
If you want to allow httpd to read home directorie, you must turn on the httpd_enable_homedirs boolean.

.EX
.B setsebool -P httpd_enable_homedirs 1
.EE

.PP
If you want to allow samba to share users home directories, you must turn on the samba_enable_home_dirs boolean.

.EX
.B setsebool -P samba_enable_home_dirs 1
.EE

.PP
If you want to allow confined virtual guests to interact with the xserve, you must turn on the virt_use_xserver boolean.

.EX
.B setsebool -P virt_use_xserver 1
.EE

.PP
If you want to allow confined virtual guests to manage device configuration, (pci, you must turn on the virt_use_sysfs boolean.

.EX
.B setsebool -P virt_use_sysfs 1
.EE

.PP
If you want to allow spamd to read/write user home directories, you must turn on the spamd_enable_home_dirs boolean.

.EX
.B setsebool -P spamd_enable_home_dirs 1
.EE

.PP
If you want to allow sftp-internal to read and write files in the user home directorie, you must turn on the sftpd_enable_homedirs boolean.

.EX
.B setsebool -P sftpd_enable_homedirs 1
.EE

.PP
If you want to support fusefs home directorie, you must turn on the use_fusefs_home_dirs boolean.

.EX
.B setsebool -P use_fusefs_home_dirs 1
.EE

.PP
If you want to allow regular users direct dri device acces, you must turn on the user_direct_dri boolean.

.EX
.B setsebool -P user_direct_dri 1
.EE

.PP
If you want to allow confined virtual guests to use executable memory and executable stac, you must turn on the virt_use_execmem boolean.

.EX
.B setsebool -P virt_use_execmem 1
.EE

.PP
If you want to allow regular users direct mouse acces, you must turn on the user_direct_mouse boolean.

.EX
.B setsebool -P user_direct_mouse 1
.EE

.PP
If you want to allow confined virtual guests to interact with the sanloc, you must turn on the virt_use_sanlock boolean.

.EX
.B setsebool -P virt_use_sanlock 1
.EE

.PP
If you want to allow confined virtual guests to use usb device, you must turn on the virt_use_usb boolean.

.EX
.B setsebool -P virt_use_usb 1
.EE

.PP
If you want to support NFS home directorie, you must turn on the use_nfs_home_dirs boolean.

.EX
.B setsebool -P use_nfs_home_dirs 1
.EE

.PP
If you want to allow confined virtual guests to manage cifs file, you must turn on the virt_use_samba boolean.

.EX
.B setsebool -P virt_use_samba 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), irc(8), semanage(8), restorecon(8), chcon(1), setsebool(8)