.TH  "isnsd_selinux"  "8"  "12-11-01" "isnsd" "SELinux Policy documentation for isnsd"
.SH "NAME"
isnsd_selinux \- Security Enhanced Linux Policy for the isnsd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the isnsd processes via flexible mandatory access control.

The isnsd processes execute with the isnsd_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep isnsd_t


.SH "ENTRYPOINTS"

The isnsd_t SELinux type can be entered via the "isnsd_exec_t" file type.  The default entrypoint paths for the isnsd_t domain are the following:"

/usr/sbin/isnsd
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux isnsd policy is very flexible allowing users to setup their isnsd processes in as secure a method as possible.
.PP
The following process types are defined for isnsd:

.EX
.B isnsd_t
.EE
.PP
Note:
.B semanage permissive -a PROCESS_TYPE
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux isnsd policy is very flexible allowing users to setup their isnsd processes in as secure a method as possible.
.PP
The following file types are defined for isnsd:


.EX
.PP
.B isnsd_exec_t
.EE

- Set files with the isnsd_exec_t type, if you want to transition an executable to the isnsd_t domain.


.EX
.PP
.B isnsd_initrc_exec_t
.EE

- Set files with the isnsd_initrc_exec_t type, if you want to transition an executable to the isnsd_initrc_t domain.


.EX
.PP
.B isnsd_var_lib_t
.EE

- Set files with the isnsd_var_lib_t type, if you want to store the isnsd files under the /var/lib directory.


.EX
.PP
.B isnsd_var_run_t
.EE

- Set files with the isnsd_var_run_t type, if you want to store the isnsd files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports.
.PP
You can see the types associated with a port by using the following command:

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports.
SELinux isnsd policy is very flexible allowing users to setup their isnsd processes in as secure a method as possible.
.PP
The following port types are defined for isnsd:

.EX
.TP 5
.B isns_port_t
.TP 10
.EE


Default Defined Ports:
tcp 3205
.EE
udp 3205
.EE
.SH "MANAGED FILES"

The SELinux process type isnsd_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B isnsd_var_lib_t

	/var/lib/isns(/.*)?
.br

.br
.B isnsd_var_run_t

	/var/run/isnsctl
.br
	/var/run/isnsd\.pid
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), isnsd(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
