.TH  "jabberd_router_selinux"  "8"  "jabberd_router" "dwalsh@redhat.com" "jabberd_router SELinux Policy documentation"
.SH "NAME"
jabberd_router_selinux \- Security Enhanced Linux Policy for the jabberd_router processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the jabberd_router processes via flexible mandatory access control.

The jabberd_router processes execute with the jabberd_router_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep jabberd_router_t


.SH "ENTRYPOINTS"

The jabberd_router_t SELinux type can be entered via the "jabberd_router_exec_t" file type.  The default entrypoint paths for the jabberd_router_t domain are the following:"

/usr/bin/c2s, /usr/bin/router
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux jabberd_router policy is very flexible allowing users to setup their jabberd_router processes in as secure a method as possible.
.PP 
The following process types are defined for jabberd_router:

.EX
.B jabberd_router_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux jabberd_router policy is very flexible allowing users to setup their jabberd_router processes in as secure a method as possible.
.PP 
The following file types are defined for jabberd_router:


.EX
.PP
.B jabberd_router_exec_t 
.EE

- Set files with the jabberd_router_exec_t type, if you want to transition an executable to the jabberd_router_t domain.

.br
.TP 5
Paths: 
/usr/bin/c2s, /usr/bin/router

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type jabberd_router_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B jabberd_var_lib_t

	/var/lib/jabberd(/.*)?
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), jabberd_router(8), semanage(8), restorecon(8), chcon(1)
, jabberd_selinux(8), jabberd_selinux(8)