.TH  "kadmind_selinux"  "8"  "kadmind" "dwalsh@redhat.com" "kadmind SELinux Policy documentation"
.SH "NAME"
kadmind_selinux \- Security Enhanced Linux Policy for the kadmind processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the kadmind processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux kadmind policy is very flexible allowing users to setup their kadmind processes in as secure a method as possible.
.PP 
The following file types are defined for kadmind:


.EX
.B kadmind_exec_t 
.EE

- Set files with the kadmind_exec_t context, if you want to a executable to transition to the kadmind_t domain.

.br
Paths: 
/usr/(local/)?(kerberos/)?sbin/kadmind, /usr/kerberos/sbin/kadmin\.local

.EX
.B kadmind_log_t 
.EE

- Set files with the kadmind_log_t context, if you want to treat the data as kadmind log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/kadmin(d)?\.log

.EX
.B kadmind_tmp_t 
.EE

- Set files with the kadmind_tmp_t context, if you want to store kadmind temporary files in the /tmp directories.


.EX
.B kadmind_var_run_t 
.EE

- Set files with the kadmind_var_run_t context, if you want to store the kadmind files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), kadmind(8), semanage(8), restorecon(8), chcon(1)
