.TH  "kismet_selinux"  "8"  "kismet" "dwalsh@redhat.com" "kismet SELinux Policy documentation"
.SH "NAME"
kismet_selinux \- Security Enhanced Linux Policy for the kismet processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the kismet processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux kismet policy is very flexible allowing users to setup their kismet processes in as secure a method as possible.
.PP 
The following file types are defined for kismet:


.EX
.B kismet_exec_t 
.EE

- Set files with the kismet_exec_t type, if you want to transition an executable to the kismet_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B kismet_home_t 
.EE

- Set files with the kismet_home_t type, if you want to store kismet files in the users home directory.


.EX
.B kismet_log_t 
.EE

- Set files with the kismet_log_t type, if you want to treat the data as kismet log data, usually stored under the /var/log directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B kismet_tmp_t 
.EE

- Set files with the kismet_tmp_t type, if you want to store kismet temporary files in the /tmp directories.


.EX
.B kismet_tmpfs_t 
.EE

- Set files with the kismet_tmpfs_t type, if you want to store kismet files on a tmpfs file system.


.EX
.B kismet_var_lib_t 
.EE

- Set files with the kismet_var_lib_t type, if you want to store the kismet files under the /var/lib directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B kismet_var_run_t 
.EE

- Set files with the kismet_var_run_t type, if you want to store the kismet files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux kismet policy is very flexible allowing users to setup their kismet processes in as secure a method as possible.
.PP 
The following port types are defined for kismet:
.EX

.B kismet_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 2501
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), kismet(8), semanage(8), restorecon(8), chcon(1)
