.TH  "ldconfig_selinux"  "8"  "ldconfig" "dwalsh@redhat.com" "ldconfig SELinux Policy documentation"
.SH "NAME"
ldconfig_selinux \- Security Enhanced Linux Policy for the ldconfig processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ldconfig processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux ldconfig policy is very flexible allowing users to setup their ldconfig processes in as secure a method as possible.
.PP 
The following file types are defined for ldconfig:


.EX
.PP
.B ldconfig_cache_t 
.EE

- Set files with the ldconfig_cache_t type, if you want to store the files under the /var/cache directory.


.EX
.PP
.B ldconfig_exec_t 
.EE

- Set files with the ldconfig_exec_t type, if you want to transition an executable to the ldconfig_t domain.

.br
.TP 5
Paths: 
/usr/sbin/ldconfig, /sbin/ldconfig

.EX
.PP
.B ldconfig_tmp_t 
.EE

- Set files with the ldconfig_tmp_t type, if you want to store ldconfig temporary files in the /tmp directories.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux ldconfig policy is very flexible allowing users to setup their ldconfig processes in as secure a method as possible.
.PP 
The following process types are defined for ldconfig:

.EX
.B ldconfig_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type ldconfig_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B kdumpctl_tmp_t


.br
.B ld_so_cache_t

	/etc/ld\.so\.cache
.br
	/etc/ld\.so\.cache~
.br
	/etc/ld\.so\.preload
.br
	/etc/ld\.so\.preload~
.br

.br
.B ldconfig_cache_t

	/var/cache/ldconfig(/.*)?
.br

.br
.B ldconfig_tmp_t


.br
.B rpm_script_tmp_t


.br
.B user_home_t

	/home/[^/]*/.+
.br

.br
.B user_tmp_t

	/var/run/user(/.*)?
.br
	/tmp/gconfd-.*
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), ldconfig(8), semanage(8), restorecon(8), chcon(1)
