.TH  "loadkeys_selinux"  "8"  "loadkeys" "dwalsh@redhat.com" "loadkeys SELinux Policy documentation"
.SH "NAME"
loadkeys_selinux \- Security Enhanced Linux Policy for the loadkeys processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the loadkeys processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux loadkeys policy is very flexible allowing users to setup their loadkeys processes in as secure a method as possible.
.PP 
The following file types are defined for loadkeys:


.EX
.PP
.B loadkeys_exec_t 
.EE

- Set files with the loadkeys_exec_t type, if you want to transition an executable to the loadkeys_t domain.

.br
.TP 5
Paths: 
/bin/unikeys, /bin/loadkeys, /usr/bin/unikeys, /usr/bin/loadkeys

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux loadkeys policy is very flexible allowing users to setup their loadkeys processes in as secure a method as possible.
.PP 
The following process types are defined for loadkeys:

.EX
.B loadkeys_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), loadkeys(8), semanage(8), restorecon(8), chcon(1)
