.TH  "lockdev_selinux"  "8"  "lockdev" "dwalsh@redhat.com" "lockdev SELinux Policy documentation"
.SH "NAME"
lockdev_selinux \- Security Enhanced Linux Policy for the lockdev processes
.SH "DESCRIPTION"


SELinux Linux secures
.B lockdev
(device locking policy for lockdev)
processes via flexible mandatory access
control.  



.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux lockdev policy is very flexible allowing users to setup their lockdev processes in as secure a method as possible.
.PP 
The following file types are defined for lockdev:


.EX
.PP
.B lockdev_exec_t 
.EE

- Set files with the lockdev_exec_t type, if you want to transition an executable to the lockdev_t domain.


.EX
.PP
.B lockdev_lock_t 
.EE

- Set files with the lockdev_lock_t type, if you want to treat the files as lockdev lock data, stored under the /var/lock directory


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux lockdev policy is very flexible allowing users to setup their lockdev processes in as secure a method as possible.
.PP 
The following process types are defined for lockdev:

.EX
.B lockdev_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), lockdev(8), semanage(8), restorecon(8), chcon(1)
