.TH  "logadm_selinux"  "8"  "logadm" "mgrepl@redhat.com" "logadm SELinux Policy documentation"
.SH "NAME"
logadm_r \- \fBLog administrator role\fP - Security Enhanced Linux Policy

.SH DESCRIPTION

SELinux supports Roles Based Access Control (RBAC), some Linux roles are login roles, while other roles need to be transition into.

.I Note:
Examples in this man page will use the
.B staff_u
SELinux user.

Non login roles are usually used for administrative tasks. For example, tasks that require root privileges.  Roles control which types a user can run processes with. Roles often have default types assigned to them.

The default type for the logadm_r role is logadm_t.

The
.B newrole
program to transition directly to this role.

.B newrole -r logadm_r -t logadm_t

.B sudo
is the preferred method to do transition from one role to another.  You setup sudo to transition to logadm_r by adding a similar line to the /etc/sudoers file.

USERNAME ALL=(ALL) ROLE=logadm_r TYPE=logadm_t COMMAND

.br
sudo will run COMMAND as staff_u:logadm_r:logadm_t:LEVEL

When using a a non login role, you need to setup SELinux so that your SELinux user can reach logadm_r role.

Execute the following to see all of the assigned SELinux roles:

.B semanage user -l

You need to add logadm_r to the staff_u user.  You could setup the staff_u user to be able to use the logadm_r role with a command like:

.B $ semanage user -m -R 'staff_r system_r logadm_r' staff_u


.SH BOOLEANS
SELinux policy is customizable based on least access required.  logadm policy is extremely flexible and has several booleans that allow you to manipulate the policy and run logadm with the tightest access possible.


.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server, you must turn on the authlogin_nsswitch_use_ldap boolean. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you want to deny user domains applications to map a memory region as both executable and writable, this is dangerous and the executable should be reported in bugzilla, you must turn on the deny_execmem boolean. Enabled by default.

.EX
.B setsebool -P deny_execmem 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to run with kerberos, you must turn on the kerberos_enabled boolean. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you want to allow logging in and using the system from /dev/console, you must turn on the login_console_enabled boolean. Enabled by default.

.EX
.B setsebool -P login_console_enabled 1

.EE

.PP
If you want to allow system to run with NIS, you must turn on the nis_enabled boolean. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.PP
If you want to disallow programs, such as newrole, from transitioning to administrative user domains, you must turn on the secure_mode boolean. Enabled by default.

.EX
.B setsebool -P secure_mode 1

.EE

.PP
If you want to allow unconfined executables to make their stack executable.  This should never, ever be necessary. Probably indicates a badly coded executable, but could indicate an attack. This executable should be reported in bugzilla, you must turn on the selinuxuser_execstack boolean. Enabled by default.

.EX
.B setsebool -P selinuxuser_execstack 1

.EE

.PP
If you want to allow ssh logins as sysadm_r:sysadm_t, you must turn on the ssh_sysadm_login boolean. Disabled by default.

.EX
.B setsebool -P ssh_sysadm_login 1

.EE

.PP
If you want to allow the graphical login program to login directly as sysadm_r:sysadm_t, you must turn on the xdm_sysadm_login boolean. Disabled by default.

.EX
.B setsebool -P xdm_sysadm_login 1

.EE

.SH "MANAGED FILES"

The SELinux process type logadm_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B auditd_etc_t

	/etc/audit(/.*)?
.br

.br
.B auditd_log_t

	/var/log/audit(/.*)?
.br
	/var/log/audit\.log
.br

.br
.B auditd_unit_file_t

	/usr/lib/systemd/system/auditd.*
.br

.br
.B auditd_var_run_t

	/var/run/auditd\.pid
.br
	/var/run/auditd_sock
.br
	/var/run/audit_events
.br

.br
.B klogd_tmp_t


.br
.B klogd_var_run_t

	/var/run/klogd\.pid
.br

.br
.B logfile

	all log files
.br

.br
.B syslog_conf_t

	/etc/syslog.conf
.br
	/etc/rsyslog.conf
.br
	/etc/rsyslog.d(/.*)?
.br

.br
.B syslogd_tmp_t


.br
.B syslogd_var_lib_t

	/var/lib/r?syslog(/.*)?
.br
	/var/lib/syslog-ng(/.*)?
.br
	/var/lib/syslog-ng.persist
.br
	/var/lib/misc/syslog-ng.persist-?
.br

.br
.B syslogd_var_run_t

	/var/run/log(/.*)?
.br
	/var/run/syslog-ng.ctl
.br
	/var/log/syslog-ng(/.*)?
.br
	/var/run/syslog-ng(/.*)?
.br
	/var/run/systemd/journal(/.*)?
.br
	/var/run/metalog\.pid
.br
	/var/run/syslogd\.pid
.br

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), logadm(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8)