.TH  "logadm_selinux"  "8"  "logadm" "mgrepl@redhat.com" "logadm SELinux Policy documentation"
.SH "NAME"
logadm_r \- \fBLog administrator role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

SELinux supports Roles Based Access Control (RBAC), some Linux roles are login roles, while other roles need to be transition into. 

.I Note: 
Examples in this man page will use the 
.B staff_u 
SELinux user.

Non login roles are usually used for administrative tasks. For example, tasks that require root privileges.  Roles control which types a user can run processes with. Roles often have default types assigned to them. 

The default type for the logadm_r role is logadm_t.

The 
.B newrole 
program to transition directly to this role.

.B newrole -r logadm_r -t logadm_t

.B sudo 
is the preferred method to do transition from one role to another.  You setup sudo to transition to logadm_r by adding a similar line to the /etc/sudoers file.

USERNAME ALL=(ALL) ROLE=logadm_r TYPE=logadm_t COMMAND

.br
sudo will run COMMAND as staff_u:logadm_r:logadm_t:LEVEL

When using a a non login role, you need to setup SELinux so that your SELinux user can reach logadm_r role.

Execute the following to see all of the assigned SELinux roles:

.B semanage user -l

You need to add logadm_r to the staff_u user.  You could setup the staff_u user to be able to use the logadm_r role with a command like:

.B $ semanage user -m -R 'staff_r system_r logadm_r' staff_u 


.SH "MANAGED FILES"

The SELinux user type logadm_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B auditd_etc_t

	/etc/audit(/.*)?
.br

.br
.B auditd_log_t

	/var/log/audit(/.*)?
.br
	/var/log/audit\.log
.br

.br
.B auditd_unit_file_t

	/usr/lib/systemd/system/auditd.*
.br

.br
.B auditd_var_run_t

	/var/run/auditd\.pid
.br
	/var/run/auditd_sock
.br
	/var/run/audit_events
.br

.br
.B klogd_tmp_t


.br
.B klogd_var_run_t

	/var/run/klogd\.pid
.br

.br
.B logfile

	all log files
.br

.br
.B syslog_conf_t

	/etc/syslog.conf
.br
	/etc/rsyslog.conf
.br

.br
.B syslogd_tmp_t


.br
.B syslogd_var_lib_t

	/var/lib/r?syslog(/.*)?
.br
	/var/lib/syslog-ng(/.*)?
.br
	/var/lib/syslog-ng.persist
.br

.br
.B syslogd_var_run_t

	/var/run/log(/.*)?
.br
	/var/run/syslog-ng.ctl
.br
	/var/log/syslog-ng(/.*)?
.br
	/var/run/syslog-ng(/.*)?
.br
	/var/run/systemd/journal(/.*)?
.br
	/var/run/metalog\.pid
.br
	/var/run/syslogd\.pid
.br

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), logadm(8), semanage(8), restorecon(8), chcon(1)
