.TH  "logrotate_selinux"  "8"  "logrotate" "dwalsh@redhat.com" "logrotate SELinux Policy documentation"
.SH "NAME"
logrotate_selinux \- Security Enhanced Linux Policy for the logrotate processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the logrotate processes via flexible mandatory access control.

The logrotate processes execute with the logrotate_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep logrotate_t


.SH "ENTRYPOINTS"

The logrotate_t SELinux type can be entered via the "logrotate_exec_t" file type.  The default entrypoint paths for the logrotate_t domain are the following:"

/usr/sbin/logrotate, /etc/cron\.(daily|weekly)/sysklogd
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux logrotate policy is very flexible allowing users to setup their logrotate processes in as secure a method as possible.
.PP 
The following process types are defined for logrotate:

.EX
.B logrotate_t, logrotate_mail_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux logrotate policy is very flexible allowing users to setup their logrotate processes in as secure a method as possible.
.PP 
The following file types are defined for logrotate:


.EX
.PP
.B logrotate_exec_t 
.EE

- Set files with the logrotate_exec_t type, if you want to transition an executable to the logrotate_t domain.

.br
.TP 5
Paths: 
/usr/sbin/logrotate, /etc/cron\.(daily|weekly)/sysklogd

.EX
.PP
.B logrotate_lock_t 
.EE

- Set files with the logrotate_lock_t type, if you want to treat the files as logrotate lock data, stored under the /var/lock directory


.EX
.PP
.B logrotate_mail_tmp_t 
.EE

- Set files with the logrotate_mail_tmp_t type, if you want to store logrotate mail temporary files in the /tmp directories.


.EX
.PP
.B logrotate_tmp_t 
.EE

- Set files with the logrotate_tmp_t type, if you want to store logrotate temporary files in the /tmp directories.


.EX
.PP
.B logrotate_var_lib_t 
.EE

- Set files with the logrotate_var_lib_t type, if you want to store the logrotate files under the /var/lib directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type logrotate_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B abrt_var_cache_t

	/var/cache/abrt(/.*)?
.br
	/var/spool/abrt(/.*)?
.br
	/var/cache/abrt-di(/.*)?
.br

.br
.B logfile

	all log files
.br

.br
.B logrotate_lock_t


.br
.B logrotate_tmp_t


.br
.B logrotate_var_lib_t

	/var/lib/logrotate\.status
.br

.br
.B named_cache_t

	/var/named/data(/.*)?
.br
	/var/named/slaves(/.*)?
.br
	/var/named/dynamic(/.*)?
.br
	/var/named/chroot/var/tmp(/.*)?
.br
	/var/named/chroot/var/named/data(/.*)?
.br
	/var/named/chroot/var/named/slaves(/.*)?
.br
	/var/named/chroot/var/named/dynamic(/.*)?
.br

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.br
.B var_spool_t

	/var/spool(/.*)?
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the logrotate_t, logrotate_mail_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the logrotate_t, logrotate_mail_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), logrotate(8), semanage(8), restorecon(8), chcon(1)
