.TH  "logrotate_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "logrotate Selinux Policy documentation"
.SH "NAME"
logrotate_selinux \- Security Enhanced Linux Policy for the logrotate processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the logrotate processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux logrotate policy is very flexible allowing users to setup their logrotate processes in as secure a method as possible.
.PP 
The following file types are defined for logrotate:


.EX
.B logrotate_exec_t 
.EE

- Set files with the logrotate_exec_t context, if you want to a executable to transition to the logrotate_t domain.


.EX
.B logrotate_lock_t 
.EE

- Set files with the logrotate_lock_t context, if you want to treat the files as logrotate lock data.


.EX
.B logrotate_mail_tmp_t 
.EE

- Set files with the logrotate_mail_tmp_t context, if you want to store logrotate mail temporary files in the /tmp directories.


.EX
.B logrotate_tmp_t 
.EE

- Set files with the logrotate_tmp_t context, if you want to store logrotate temporary files in the /tmp directories.


.EX
.B logrotate_var_lib_t 
.EE

- Set files with the logrotate_var_lib_t context, if you want to store the logrotate files under the /var/lib directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), logrotate(8), semanage(8), restorecon(8), chcon(1)