.TH  "lpd_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "lpd Selinux Policy documentation"
.SH "NAME"
lpd_selinux \- Security Enhanced Linux Policy for the lpd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the lpd processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux lpd policy is very flexible allowing users to setup their lpd processes in as secure a method as possible.
.PP 
The following file types are defined for lpd:


.EX
.B lpd_exec_t 
.EE

- Set files with the lpd_exec_t context, if you want to a executable to transition to the lpd_t domain.


.EX
.B lpd_tmp_t 
.EE

- Set files with the lpd_tmp_t context, if you want to store lpd temporary files in the /tmp directories.


.EX
.B lpd_var_run_t 
.EE

- Set files with the lpd_var_run_t context, if you want to store the lpd files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  lpd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run lpd with the tightest access possible.


.PP
If you want to use lpd server instead of cup, you must turn on the use_lpd_server boolean.

.EX
.B setsebool -P use_lpd_server 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), lpd(8), semanage(8), restorecon(8), chcon(1), setsebool(8)