.TH  "lsassd_selinux"  "8"  "lsassd" "dwalsh@redhat.com" "lsassd Selinux Policy documentation"
.SH "NAME"
lsassd_selinux \- Security Enhanced Linux Policy for the lsassd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the lsassd processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux lsassd policy is very flexible allowing users to setup their lsassd processes in as secure a method as possible.
.PP 
The following file types are defined for lsassd:


.EX
.B lsassd_exec_t 
.EE

- Set files with the lsassd_exec_t context, if you want to a executable to transition to the lsassd_t domain.

.br
Path: 
/usr/sbin/lsassd

.EX
.B lsassd_tmp_t 
.EE

- Set files with the lsassd_tmp_t context, if you want to store lsassd temporary files in the /tmp directories.


.EX
.B lsassd_var_lib_t 
.EE

- Set files with the lsassd_var_lib_t context, if you want to store the lsassd files under the /var/lib directory.

.br
Paths: 
/var/lib/likewise-open/krb5ccr_lsass, /var/lib/likewise-open/db/lsass-adstate\.filedb, /var/lib/likewise-open/lsasd\.err, /var/lib/likewise-open/db/lsass-adcache\.db, /var/lib/likewise-open/db/sam\.db

.EX
.B lsassd_var_run_t 
.EE

- Set files with the lsassd_var_run_t context, if you want to store the lsassd files under the /run directory.

.br
Path: 
/var/run/lsassd.pid

.EX
.B lsassd_var_socket_t 
.EE

- Set files with the lsassd_var_socket_t context, if you want to treat the files as lsassd var socket data.

.br
Paths: 
/var/lib/likewise-open/rpc/lsass, /var/lib/likewise-open/\.lsassd, /var/lib/likewise-open/\.ntlmd
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), lsassd(8), semanage(8), restorecon(8), chcon(1)
