.TH  "lsassd_selinux"  "8"  "lsassd" "dwalsh@redhat.com" "lsassd SELinux Policy documentation"
.SH "NAME"
lsassd_selinux \- Security Enhanced Linux Policy for the lsassd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the lsassd processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux lsassd policy is very flexible allowing users to setup their lsassd processes in as secure a method as possible.
.PP 
The following file types are defined for lsassd:


.EX
.PP
.B lsassd_exec_t 
.EE

- Set files with the lsassd_exec_t type, if you want to transition an executable to the lsassd_t domain.


.EX
.PP
.B lsassd_tmp_t 
.EE

- Set files with the lsassd_tmp_t type, if you want to store lsassd temporary files in the /tmp directories.


.EX
.PP
.B lsassd_var_lib_t 
.EE

- Set files with the lsassd_var_lib_t type, if you want to store the lsassd files under the /var/lib directory.

.br
.TP 5
Paths: 
/var/lib/likewise-open/krb5ccr_lsass, /var/lib/likewise-open/db/lsass-adstate\.filedb, /var/lib/likewise-open/lsasd\.err, /var/lib/likewise-open/db/lsass-adcache\.db, /var/lib/likewise-open/db/sam\.db

.EX
.PP
.B lsassd_var_run_t 
.EE

- Set files with the lsassd_var_run_t type, if you want to store the lsassd files under the /run directory.


.EX
.PP
.B lsassd_var_socket_t 
.EE

- Set files with the lsassd_var_socket_t type, if you want to treat the files as lsassd var socket data.

.br
.TP 5
Paths: 
/var/lib/likewise-open/rpc/lsass, /var/lib/likewise-open/\.lsassd, /var/lib/likewise-open/\.ntlmd

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux lsassd policy is very flexible allowing users to setup their lsassd processes in as secure a method as possible.
.PP 
The following process types are defined for lsassd:

.EX
.B lsassd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), lsassd(8), semanage(8), restorecon(8), chcon(1)
