.TH  "lwregd_selinux"  "8"  "lwregd" "dwalsh@redhat.com" "lwregd SELinux Policy documentation"
.SH "NAME"
lwregd_selinux \- Security Enhanced Linux Policy for the lwregd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the lwregd processes via flexible mandatory access control.

The lwregd processes execute with the lwregd_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep lwregd_t


.SH "ENTRYPOINTS"

The lwregd_t SELinux type can be entered via the "lwregd_exec_t" file type.  The default entrypoint paths for the lwregd_t domain are the following:"

/usr/sbin/lwregd
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux lwregd policy is very flexible allowing users to setup their lwregd processes in as secure a method as possible.
.PP 
The following process types are defined for lwregd:

.EX
.B lwregd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux lwregd policy is very flexible allowing users to setup their lwregd processes in as secure a method as possible.
.PP 
The following file types are defined for lwregd:


.EX
.PP
.B lwregd_exec_t 
.EE

- Set files with the lwregd_exec_t type, if you want to transition an executable to the lwregd_t domain.


.EX
.PP
.B lwregd_var_lib_t 
.EE

- Set files with the lwregd_var_lib_t type, if you want to store the lwregd files under the /var/lib directory.

.br
.TP 5
Paths: 
/var/lib/likewise-open/db/registry\.db, /var/lib/likewise-open/regsd\.err

.EX
.PP
.B lwregd_var_run_t 
.EE

- Set files with the lwregd_var_run_t type, if you want to store the lwregd files under the /run directory.


.EX
.PP
.B lwregd_var_socket_t 
.EE

- Set files with the lwregd_var_socket_t type, if you want to treat the files as lwregd var socket data.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type lwregd_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B lwregd_var_lib_t

	/var/lib/likewise-open/regsd\.err
.br
	/var/lib/likewise-open/db/registry\.db
.br

.br
.B lwregd_var_run_t

	/var/run/lwregd.pid
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), lwregd(8), semanage(8), restorecon(8), chcon(1)
