.TH  "memcached_selinux"  "8"  "memcached" "dwalsh@redhat.com" "memcached SELinux Policy documentation"
.SH "NAME"
memcached_selinux \- Security Enhanced Linux Policy for the memcached processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the memcached processes via flexible mandatory access control.

The memcached processes execute with the memcached_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep memcached_t


.SH "ENTRYPOINTS"

The memcached_t SELinux type can be entered via the "memcached_exec_t" file type.  The default entrypoint paths for the memcached_t domain are the following:"

/usr/bin/memcached
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux memcached policy is very flexible allowing users to setup their memcached processes in as secure a method as possible.
.PP 
The following process types are defined for memcached:

.EX
.B memcached_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  memcached policy is extremely flexible and has several booleans that allow you to manipulate the policy and run memcached with the tightest access possible.


.PP
If you want to allow httpd to connect to memcache server, you must turn on the httpd_can_network_memcache boolean.

.EX
.B setsebool -P httpd_can_network_memcache 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux memcached policy is very flexible allowing users to setup their memcached processes in as secure a method as possible.
.PP 
The following file types are defined for memcached:


.EX
.PP
.B memcached_exec_t 
.EE

- Set files with the memcached_exec_t type, if you want to transition an executable to the memcached_t domain.


.EX
.PP
.B memcached_initrc_exec_t 
.EE

- Set files with the memcached_initrc_exec_t type, if you want to transition an executable to the memcached_initrc_t domain.


.EX
.PP
.B memcached_var_run_t 
.EE

- Set files with the memcached_var_run_t type, if you want to store the memcached files under the /run directory.

.br
.TP 5
Paths: 
/var/run/ipa_memcached(/.*)?, /var/run/memcached(/.*)?

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux memcached policy is very flexible allowing users to setup their memcached processes in as secure a method as possible.
.PP 
The following port types are defined for memcached:

.EX
.TP 5
.B memcache_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 11211
.EE
udp 11211
.EE
.SH "MANAGED FILES"

The SELinux process type memcached_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B memcached_var_run_t

	/var/run/memcached(/.*)?
.br
	/var/run/ipa_memcached(/.*)?
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the memcached_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the memcached_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), memcached(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)