.TH  "memcached_selinux"  "8"  "memcached" "dwalsh@redhat.com" "memcached SELinux Policy documentation"
.SH "NAME"
memcached_selinux \- Security Enhanced Linux Policy for the memcached processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the memcached processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux memcached policy is very flexible allowing users to setup their memcached processes in as secure a method as possible.
.PP 
The following file types are defined for memcached:


.EX
.B memcached_exec_t 
.EE

- Set files with the memcached_exec_t context, if you want to a executable to transition to the memcached_t domain.

.br
Path: 
/usr/bin/memcached

.EX
.B memcached_initrc_exec_t 
.EE

- Set files with the memcached_initrc_exec_t context, if you want to a executable to transition to the memcached_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/memcached

.EX
.B memcached_var_run_t 
.EE

- Set files with the memcached_var_run_t context, if you want to store the memcached files under the /run directory.

.br
Paths: 
/var/run/ipa_memcached(/.*)?, /var/run/memcached(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  memcached policy is extremely flexible and has several booleans that allow you to manipulate the policy and run memcached with the tightest access possible.


.PP
If you want to allow httpd to connect to memcache serve, you must turn on the httpd_can_network_memcache boolean.

.EX
.B setsebool -P httpd_can_network_memcache 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), memcached(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)