.TH  "mozilla_selinux"  "8"  "mozilla" "dwalsh@redhat.com" "mozilla SELinux Policy documentation"
.SH "NAME"
mozilla_selinux \- Security Enhanced Linux Policy for the mozilla processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the mozilla processes via flexible mandatory access control.

The mozilla processes execute with the mozilla_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep mozilla_t


.SH "ENTRYPOINTS"

The mozilla_t SELinux type can be entered via the "mozilla_exec_t" file type.  The default entrypoint paths for the mozilla_t domain are the following:"

/usr/lib/[^/]*firefox[^/]*/firefox, /usr/lib/galeon/galeon, /usr/lib/netscape/.+/communicator/communicator-smotif\.real, /usr/bin/netscape, /usr/bin/mozilla-bin-[0-9].*, /usr/bin/epiphany-bin, /usr/lib/mozilla[^/]*/reg.+, /usr/lib/netscape/base-4/wrapper, /usr/bin/mozilla-snapshot, /usr/lib/[^/]*firefox[^/]*/firefox-bin, /usr/bin/mozilla-[0-9].*, /usr/lib/firefox[^/]*/mozilla-.*, /usr/lib/mozilla[^/]*/mozilla-.*, /usr/bin/mozilla, /usr/bin/epiphany
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux mozilla policy is very flexible allowing users to setup their mozilla processes in as secure a method as possible.
.PP 
The following process types are defined for mozilla:

.EX
.B mozilla_t, mozilla_plugin_config_t, mozilla_plugin_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  mozilla policy is extremely flexible and has several booleans that allow you to manipulate the policy and run mozilla with the tightest access possible.


.PP
If you want to allow confined web browsers to read home directory content, you must turn on the mozilla_read_content boolean.

.EX
.B setsebool -P mozilla_read_content 1
.EE

.PP
If you want to allow unconfined users to transition to the Mozilla plugin domain when running xulrunner plugin-container, you must turn on the unconfined_mozilla_plugin_transition boolean.

.EX
.B setsebool -P unconfined_mozilla_plugin_transition 1
.EE

.PP
If you want to allow mozilla_plugins to create random content in the users home directory, you must turn on the mozilla_plugin_enable_homedirs boolean.

.EX
.B setsebool -P mozilla_plugin_enable_homedirs 1
.EE

.PP
If you want to allow mozilla plugin domain to connect to the network using TCP, you must turn on the mozilla_plugin_can_network_connect boolean.

.EX
.B setsebool -P mozilla_plugin_can_network_connect 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux mozilla policy is very flexible allowing users to setup their mozilla processes in as secure a method as possible.
.PP 
The following file types are defined for mozilla:


.EX
.PP
.B mozilla_conf_t 
.EE

- Set files with the mozilla_conf_t type, if you want to treat the files as mozilla configuration data, usually stored under the /etc directory.


.EX
.PP
.B mozilla_exec_t 
.EE

- Set files with the mozilla_exec_t type, if you want to transition an executable to the mozilla_t domain.

.br
.TP 5
Paths: 
/usr/lib/[^/]*firefox[^/]*/firefox, /usr/lib/galeon/galeon, /usr/lib/netscape/.+/communicator/communicator-smotif\.real, /usr/bin/netscape, /usr/bin/mozilla-bin-[0-9].*, /usr/bin/epiphany-bin, /usr/lib/mozilla[^/]*/reg.+, /usr/lib/netscape/base-4/wrapper, /usr/bin/mozilla-snapshot, /usr/lib/[^/]*firefox[^/]*/firefox-bin, /usr/bin/mozilla-[0-9].*, /usr/lib/firefox[^/]*/mozilla-.*, /usr/lib/mozilla[^/]*/mozilla-.*, /usr/bin/mozilla, /usr/bin/epiphany

.EX
.PP
.B mozilla_home_t 
.EE

- Set files with the mozilla_home_t type, if you want to store mozilla files in the users home directory.


.EX
.PP
.B mozilla_plugin_config_exec_t 
.EE

- Set files with the mozilla_plugin_config_exec_t type, if you want to transition an executable to the mozilla_plugin_config_t domain.


.EX
.PP
.B mozilla_plugin_exec_t 
.EE

- Set files with the mozilla_plugin_exec_t type, if you want to transition an executable to the mozilla_plugin_t domain.

.br
.TP 5
Paths: 
/usr/bin/nspluginscan, /usr/lib/nspluginwrapper/npviewer.bin, /usr/lib/xulrunner[^/]*/plugin-container, /usr/bin/nspluginviewer

.EX
.PP
.B mozilla_plugin_rw_t 
.EE

- Set files with the mozilla_plugin_rw_t type, if you want to treat the files as mozilla plugin read/write content.


.EX
.PP
.B mozilla_plugin_tmp_t 
.EE

- Set files with the mozilla_plugin_tmp_t type, if you want to store mozilla plugin temporary files in the /tmp directories.


.EX
.PP
.B mozilla_plugin_tmpfs_t 
.EE

- Set files with the mozilla_plugin_tmpfs_t type, if you want to store mozilla plugin files on a tmpfs file system.


.EX
.PP
.B mozilla_tmp_t 
.EE

- Set files with the mozilla_tmp_t type, if you want to store mozilla temporary files in the /tmp directories.


.EX
.PP
.B mozilla_tmpfs_t 
.EE

- Set files with the mozilla_tmpfs_t type, if you want to store mozilla files on a tmpfs file system.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type mozilla_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B gconf_home_t

	/root/\.local.*
.br
	/root/\.gconf(d)?(/.*)?
.br
	/home/[^/]*/\.local.*
.br
	/home/[^/]*/\.gconf(d)?(/.*)?
.br
	/home/dwalsh/\.local.*
.br
	/home/dwalsh/\.gconf(d)?(/.*)?
.br
	/var/lib/xguest/home/xguest/\.local.*
.br
	/var/lib/xguest/home/xguest/\.gconf(d)?(/.*)?
.br

.br
.B gnome_home_type


.br
.B mozilla_home_t

	/home/[^/]*/\.java(/.*)?
.br
	/home/[^/]*/\.adobe(/.*)?
.br
	/home/[^/]*/\.gnash(/.*)?
.br
	/home/[^/]*/\.galeon(/.*)?
.br
	/home/[^/]*/\.spicec(/.*)?
.br
	/home/[^/]*/\.mozilla(/.*)?
.br
	/home/[^/]*/\.phoenix(/.*)?
.br
	/home/[^/]*/\.netscape(/.*)?
.br
	/home/[^/]*/\.ICAClient(/.*)?
.br
	/home/[^/]*/\.macromedia(/.*)?
.br
	/home/[^/]*/\.thunderbird(/.*)?
.br
	/home/[^/]*/\.gcjwebplugin(/.*)?
.br
	/home/[^/]*/\.icedteaplugin(/.*)?
.br
	/home/[^/]*/zimbrauserdata(/.*)?
.br
	/home/[^/]*/\.config/chromium(/.*)?
.br
	/home/dwalsh/\.java(/.*)?
.br
	/home/dwalsh/\.adobe(/.*)?
.br
	/home/dwalsh/\.gnash(/.*)?
.br
	/home/dwalsh/\.galeon(/.*)?
.br
	/home/dwalsh/\.spicec(/.*)?
.br
	/home/dwalsh/\.mozilla(/.*)?
.br
	/home/dwalsh/\.phoenix(/.*)?
.br
	/home/dwalsh/\.netscape(/.*)?
.br
	/home/dwalsh/\.ICAClient(/.*)?
.br
	/home/dwalsh/\.macromedia(/.*)?
.br
	/home/dwalsh/\.thunderbird(/.*)?
.br
	/home/dwalsh/\.gcjwebplugin(/.*)?
.br
	/home/dwalsh/\.icedteaplugin(/.*)?
.br
	/home/dwalsh/zimbrauserdata(/.*)?
.br
	/home/dwalsh/\.config/chromium(/.*)?
.br
	/var/lib/xguest/home/xguest/\.java(/.*)?
.br
	/var/lib/xguest/home/xguest/\.adobe(/.*)?
.br
	/var/lib/xguest/home/xguest/\.gnash(/.*)?
.br
	/var/lib/xguest/home/xguest/\.galeon(/.*)?
.br
	/var/lib/xguest/home/xguest/\.spicec(/.*)?
.br
	/var/lib/xguest/home/xguest/\.mozilla(/.*)?
.br
	/var/lib/xguest/home/xguest/\.phoenix(/.*)?
.br
	/var/lib/xguest/home/xguest/\.netscape(/.*)?
.br
	/var/lib/xguest/home/xguest/\.ICAClient(/.*)?
.br
	/var/lib/xguest/home/xguest/\.macromedia(/.*)?
.br
	/var/lib/xguest/home/xguest/\.thunderbird(/.*)?
.br
	/var/lib/xguest/home/xguest/\.gcjwebplugin(/.*)?
.br
	/var/lib/xguest/home/xguest/\.icedteaplugin(/.*)?
.br
	/var/lib/xguest/home/xguest/zimbrauserdata(/.*)?
.br
	/var/lib/xguest/home/xguest/\.config/chromium(/.*)?
.br

.br
.B mozilla_tmp_t


.br
.B mozilla_tmpfs_t


.br
.B pulseaudio_home_t

	/root/\.pulse(/.*)?
.br
	/root/\.esd_auth
.br
	/root/\.pulse-cookie
.br
	/home/[^/]*/\.pulse(/.*)?
.br
	/home/[^/]*/\.esd_auth
.br
	/home/[^/]*/\.pulse-cookie
.br
	/home/dwalsh/\.pulse(/.*)?
.br
	/home/dwalsh/\.esd_auth
.br
	/home/dwalsh/\.pulse-cookie
.br
	/var/lib/xguest/home/xguest/\.pulse(/.*)?
.br
	/var/lib/xguest/home/xguest/\.esd_auth
.br
	/var/lib/xguest/home/xguest/\.pulse-cookie
.br

.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br
	/home/dwalsh/\.fontconfig(/.*)?
.br
	/home/dwalsh/\.fonts/auto(/.*)?
.br
	/home/dwalsh/\.fonts\.cache-.*
.br
	/var/lib/xguest/home/xguest/\.fontconfig(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts/auto(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts\.cache-.*
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the mozilla_plugin_config_t, mozilla_t, mozilla_plugin_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the mozilla_plugin_config_t, mozilla_t, mozilla_plugin_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), mozilla(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8), mozilla_plugin_selinux(8), mozilla_plugin_config_selinux(8)