.TH  "mozilla_plugin_config_selinux"  "8"  "mozilla_plugin_config" "dwalsh@redhat.com" "mozilla_plugin_config SELinux Policy documentation"
.SH "NAME"
mozilla_plugin_config_selinux \- Security Enhanced Linux Policy for the mozilla_plugin_config processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the mozilla_plugin_config processes via flexible mandatory access control.

The mozilla_plugin_config processes execute with the mozilla_plugin_config_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep mozilla_plugin_config_t


.SH "ENTRYPOINTS"

The mozilla_plugin_config_t SELinux type can be entered via the "mozilla_plugin_config_exec_t" file type.  The default entrypoint paths for the mozilla_plugin_config_t domain are the following:"

/usr/lib/nspluginwrapper/plugin-config
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux mozilla_plugin_config policy is very flexible allowing users to setup their mozilla_plugin_config processes in as secure a method as possible.
.PP 
The following process types are defined for mozilla_plugin_config:

.EX
.B mozilla_plugin_config_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux mozilla_plugin_config policy is very flexible allowing users to setup their mozilla_plugin_config processes in as secure a method as possible.
.PP 
The following file types are defined for mozilla_plugin_config:


.EX
.PP
.B mozilla_plugin_config_exec_t 
.EE

- Set files with the mozilla_plugin_config_exec_t type, if you want to transition an executable to the mozilla_plugin_config_t domain.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type mozilla_plugin_config_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B mozilla_home_t

	/home/[^/]*/\.java(/.*)?
.br
	/home/[^/]*/\.adobe(/.*)?
.br
	/home/[^/]*/\.gnash(/.*)?
.br
	/home/[^/]*/\.galeon(/.*)?
.br
	/home/[^/]*/\.spicec(/.*)?
.br
	/home/[^/]*/\.mozilla(/.*)?
.br
	/home/[^/]*/\.phoenix(/.*)?
.br
	/home/[^/]*/\.netscape(/.*)?
.br
	/home/[^/]*/\.ICAClient(/.*)?
.br
	/home/[^/]*/\.macromedia(/.*)?
.br
	/home/[^/]*/\.thunderbird(/.*)?
.br
	/home/[^/]*/\.gcjwebplugin(/.*)?
.br
	/home/[^/]*/\.icedteaplugin(/.*)?
.br
	/home/[^/]*/zimbrauserdata(/.*)?
.br
	/home/[^/]*/\.config/chromium(/.*)?
.br
	/home/dwalsh/\.java(/.*)?
.br
	/home/dwalsh/\.adobe(/.*)?
.br
	/home/dwalsh/\.gnash(/.*)?
.br
	/home/dwalsh/\.galeon(/.*)?
.br
	/home/dwalsh/\.spicec(/.*)?
.br
	/home/dwalsh/\.mozilla(/.*)?
.br
	/home/dwalsh/\.phoenix(/.*)?
.br
	/home/dwalsh/\.netscape(/.*)?
.br
	/home/dwalsh/\.ICAClient(/.*)?
.br
	/home/dwalsh/\.macromedia(/.*)?
.br
	/home/dwalsh/\.thunderbird(/.*)?
.br
	/home/dwalsh/\.gcjwebplugin(/.*)?
.br
	/home/dwalsh/\.icedteaplugin(/.*)?
.br
	/home/dwalsh/zimbrauserdata(/.*)?
.br
	/home/dwalsh/\.config/chromium(/.*)?
.br
	/var/lib/xguest/home/xguest/\.java(/.*)?
.br
	/var/lib/xguest/home/xguest/\.adobe(/.*)?
.br
	/var/lib/xguest/home/xguest/\.gnash(/.*)?
.br
	/var/lib/xguest/home/xguest/\.galeon(/.*)?
.br
	/var/lib/xguest/home/xguest/\.spicec(/.*)?
.br
	/var/lib/xguest/home/xguest/\.mozilla(/.*)?
.br
	/var/lib/xguest/home/xguest/\.phoenix(/.*)?
.br
	/var/lib/xguest/home/xguest/\.netscape(/.*)?
.br
	/var/lib/xguest/home/xguest/\.ICAClient(/.*)?
.br
	/var/lib/xguest/home/xguest/\.macromedia(/.*)?
.br
	/var/lib/xguest/home/xguest/\.thunderbird(/.*)?
.br
	/var/lib/xguest/home/xguest/\.gcjwebplugin(/.*)?
.br
	/var/lib/xguest/home/xguest/\.icedteaplugin(/.*)?
.br
	/var/lib/xguest/home/xguest/zimbrauserdata(/.*)?
.br
	/var/lib/xguest/home/xguest/\.config/chromium(/.*)?
.br

.br
.B mozilla_plugin_rw_t

	/usr/lib/mozilla/plugins-wrapped(/.*)?
.br

.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br
	/home/dwalsh/\.fontconfig(/.*)?
.br
	/home/dwalsh/\.fonts/auto(/.*)?
.br
	/home/dwalsh/\.fonts\.cache-.*
.br
	/var/lib/xguest/home/xguest/\.fontconfig(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts/auto(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts\.cache-.*
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the mozilla_plugin_config_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the mozilla_plugin_config_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), mozilla_plugin_config(8), semanage(8), restorecon(8), chcon(1)
, mozilla_selinux(8), mozilla_selinux(8), mozilla_plugin_selinux(8), mozilla_plugin_selinux(8)