.TH  "mozilla_selinux"  "8"  "mozilla" "dwalsh@redhat.com" "mozilla SELinux Policy documentation"
.SH "NAME"
mozilla_selinux \- Security Enhanced Linux Policy for the mozilla processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the mozilla processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  mozilla policy is extremely flexible and has several booleans that allow you to manipulate the policy and run mozilla with the tightest access possible.


.PP
If you want to allow confined web browsers to read home directory conten, you must turn on the mozilla_read_content boolean.

.EX
.B setsebool -P mozilla_read_content 1
.EE

.PP
If you want to allow unconfined users to transition to the Mozilla plugin domain when running xulrunner plugin-container, you must turn on the unconfined_mozilla_plugin_transition boolean.

.EX
.B setsebool -P unconfined_mozilla_plugin_transition 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux mozilla policy is very flexible allowing users to setup their mozilla processes in as secure a method as possible.
.PP 
The following file types are defined for mozilla:


.EX
.B mozilla_conf_t 
.EE

- Set files with the mozilla_conf_t type, if you want to treat the files as mozilla configuration data, usually stored under the /etc directory.


.EX
.B mozilla_exec_t 
.EE

- Set files with the mozilla_exec_t type, if you want to transition an executable to the mozilla_t domain.

.br
Paths: 
/usr/lib/[^/]*firefox[^/]*/firefox, /usr/lib/galeon/galeon, /usr/lib/netscape/.+/communicator/communicator-smotif\.real, /usr/bin/mozilla-bin-[0-9].*, /usr/bin/epiphany-bin, /usr/lib/mozilla[^/]*/reg.+, /usr/lib/netscape/base-4/wrapper, /usr/bin/mozilla-snapshot, /usr/lib/[^/]*firefox[^/]*/firefox-bin, /usr/bin/netscape, /usr/bin/mozilla-[0-9].*, /usr/lib/firefox[^/]*/mozilla-.*, /usr/lib/mozilla[^/]*/mozilla-.*, /usr/bin/mozilla, /usr/bin/epiphany
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B mozilla_home_t 
.EE

- Set files with the mozilla_home_t type, if you want to store mozilla files in the users home directory.


.EX
.B mozilla_plugin_config_exec_t 
.EE

- Set files with the mozilla_plugin_config_exec_t type, if you want to transition an executable to the mozilla_plugin_config_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B mozilla_plugin_exec_t 
.EE

- Set files with the mozilla_plugin_exec_t type, if you want to transition an executable to the mozilla_plugin_t domain.

.br
Paths: 
/usr/bin/nspluginscan, /usr/lib/nspluginwrapper/npviewer.bin, /usr/lib/xulrunner[^/]*/plugin-container, /usr/bin/nspluginviewer
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B mozilla_plugin_rw_t 
.EE

- Set files with the mozilla_plugin_rw_t type, if you want to treat the files as mozilla plugin read/write content.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B mozilla_plugin_tmp_t 
.EE

- Set files with the mozilla_plugin_tmp_t type, if you want to store mozilla plugin temporary files in the /tmp directories.


.EX
.B mozilla_plugin_tmpfs_t 
.EE

- Set files with the mozilla_plugin_tmpfs_t type, if you want to store mozilla plugin files on a tmpfs file system.


.EX
.B mozilla_tmp_t 
.EE

- Set files with the mozilla_tmp_t type, if you want to store mozilla temporary files in the /tmp directories.


.EX
.B mozilla_tmpfs_t 
.EE

- Set files with the mozilla_tmpfs_t type, if you want to store mozilla files on a tmpfs file system.

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), mozilla(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)