.TH  "mrtg_selinux"  "8"  "mrtg" "dwalsh@redhat.com" "mrtg SELinux Policy documentation"
.SH "NAME"
mrtg_selinux \- Security Enhanced Linux Policy for the mrtg processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the mrtg processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux mrtg policy is very flexible allowing users to setup their mrtg processes in as secure a method as possible.
.PP 
The following file types are defined for mrtg:


.EX
.B mrtg_etc_t 
.EE

- Set files with the mrtg_etc_t context, if you want to store mrtg files in the /etc directories.

.br
Path: 
/etc/mrtg.*

.EX
.B mrtg_exec_t 
.EE

- Set files with the mrtg_exec_t context, if you want to a executable to transition to the mrtg_t domain.

.br
Path: 
/usr/bin/mrtg

.EX
.B mrtg_lock_t 
.EE

- Set files with the mrtg_lock_t context, if you want to treat the files as mrtg lock data, stored under the /var/lock directory

.br
Paths: 
/var/lock/mrtg(/.*)?, /etc/mrtg/mrtg\.ok

.EX
.B mrtg_log_t 
.EE

- Set files with the mrtg_log_t context, if you want to treat the data as mrtg log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/mrtg(/.*)?

.EX
.B mrtg_var_lib_t 
.EE

- Set files with the mrtg_var_lib_t context, if you want to store the mrtg files under the /var/lib directory.

.br
Path: 
/var/lib/mrtg(/.*)?

.EX
.B mrtg_var_run_t 
.EE

- Set files with the mrtg_var_run_t context, if you want to store the mrtg files under the /run directory.

.br
Path: 
/var/run/mrtg\.pid
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), mrtg(8), semanage(8), restorecon(8), chcon(1)
