.TH  "mysqld_selinux"  "8"  "mysqld" "dwalsh@redhat.com" "mysqld SELinux Policy documentation"
.SH "NAME"
mysqld_selinux \- Security Enhanced Linux Policy for the mysqld processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the mysqld processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux mysqld policy is very flexible allowing users to setup their mysqld processes in as secure a method as possible.
.PP 
The following file types are defined for mysqld:


.EX
.B mysqld_db_t 
.EE

- Set files with the mysqld_db_t context, if you want to treat the files as mysqld database content.

.br
Path: 
/var/lib/mysql(/.*)?

.EX
.B mysqld_etc_t 
.EE

- Set files with the mysqld_etc_t context, if you want to store mysqld files in the /etc directories.

.br
Paths: 
/etc/my\.cnf, /etc/mysql(/.*)?

.EX
.B mysqld_exec_t 
.EE

- Set files with the mysqld_exec_t context, if you want to a executable to transition to the mysqld_t domain.

.br
Paths: 
/usr/libexec/mysqld, /usr/sbin/mysqld(-max)?

.EX
.B mysqld_home_t 
.EE

- Set files with the mysqld_home_t context, if you want to store mysqld files in the users home directory.

.br
Path: 
/root/\.my\.cnf

.EX
.B mysqld_initrc_exec_t 
.EE

- Set files with the mysqld_initrc_exec_t context, if you want to a executable to transition to the mysqld_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/mysqld

.EX
.B mysqld_log_t 
.EE

- Set files with the mysqld_log_t context, if you want to treat the data as mysqld log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/mysql.*

.EX
.B mysqld_safe_exec_t 
.EE

- Set files with the mysqld_safe_exec_t context, if you want to a executable to transition to the mysqld_safe_t domain.

.br
Path: 
/usr/bin/mysqld_safe

.EX
.B mysqld_tmp_t 
.EE

- Set files with the mysqld_tmp_t context, if you want to store mysqld temporary files in the /tmp directories.


.EX
.B mysqld_unit_file_t 
.EE

- Set files with the mysqld_unit_file_t context, if you want to treat the files as mysqld unit content.

.br
Path: 
/lib/systemd/system/mysqld\.service

.EX
.B mysqld_var_run_t 
.EE

- Set files with the mysqld_var_run_t context, if you want to store the mysqld files under the /run directory.

.br
Paths: 
/var/run/mysqld(/.*)?, /var/lib/mysql/mysql\.sock
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  mysqld policy is extremely flexible and has several booleans that allow you to manipulate the policy and run mysqld with the tightest access possible.


.PP
If you want to allow users to connect to the local mysql serve, you must turn on the allow_user_mysql_connect boolean.

.EX
.B setsebool -P allow_user_mysql_connect 1
.EE

.PP
If you want to allow mysqld to connect to all port, you must turn on the mysql_connect_any boolean.

.EX
.B setsebool -P mysql_connect_any 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), mysqld(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)