.TH  "namespace_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "namespace Selinux Policy documentation"
.SH "NAME"
namespace_selinux \- Security Enhanced Linux Policy for the namespace processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the namespace processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux namespace policy is very flexible allowing users to setup their namespace processes in as secure a method as possible.
.PP 
The following file types are defined for namespace:


.EX
.B namespace_init_exec_t 
.EE

- Set files with the namespace_init_exec_t context, if you want to a executable to transition to the namespace_init_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), namespace(8), semanage(8), restorecon(8), chcon(1)