.TH  "named_selinux"  "8"  "named" "dwalsh@redhat.com" "named SELinux Policy documentation"
.SH "NAME"
named_selinux \- Security Enhanced Linux Policy for the named processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the named processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  named policy is extremely flexible and has several booleans that allow you to manipulate the policy and run named with the tightest access possible.


.PP
If you want to allow BIND to write the master zone files. Generally this is used for dynamic DNS or zone transfers, you must turn on the named_write_master_zones boolean.

.EX
.B setsebool -P named_write_master_zones 1
.EE

.PP
If you want to allow BIND to bind apache port, you must turn on the named_bind_http_port boolean.

.EX
.B setsebool -P named_bind_http_port 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux named policy is very flexible allowing users to setup their named processes in as secure a method as possible.
.PP 
The following file types are defined for named:


.EX
.B named_cache_t 
.EE

- Set files with the named_cache_t type, if you want to store the files under the /var/cache directory.

.br
Paths: 
/var/named/chroot/var/named/data(/.*)?, /var/named/chroot/var/tmp(/.*)?, /var/named/data(/.*)?, /var/named/chroot/var/named/slaves(/.*)?, /var/named/dynamic(/.*)?, /var/named/slaves(/.*)?, /var/named/chroot/var/named/dynamic(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B named_checkconf_exec_t 
.EE

- Set files with the named_checkconf_exec_t type, if you want to transition an executable to the named_checkconf_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B named_conf_t 
.EE

- Set files with the named_conf_t type, if you want to treat the files as named configuration data, usually stored under the /etc directory.

.br
Paths: 
/var/named/chroot/etc/named\.root\.hints, /etc/named\.root\.hints, /var/named/chroot(/.*)?, /var/named/named\.ca, /etc/unbound(/.*)?, /var/named/chroot/etc/named\.caching-nameserver\.conf, /etc/named\.rfc1912.zones, /etc/named\.caching-nameserver\.conf, /etc/named\.conf, /var/named/chroot/var/named/named\.ca, /var/named/chroot/etc/named\.conf, /etc/rndc.*, /var/named/chroot/etc/named\.rfc1912.zones
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B named_exec_t 
.EE

- Set files with the named_exec_t type, if you want to transition an executable to the named_t domain.

.br
Paths: 
/usr/sbin/lwresd, /usr/sbin/named, /usr/sbin/unbound
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B named_initrc_exec_t 
.EE

- Set files with the named_initrc_exec_t type, if you want to transition an executable to the named_initrc_t domain.

.br
Paths: 
/etc/rc\.d/init\.d/named, /etc/rc\.d/init\.d/unbound
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B named_keytab_t 
.EE

- Set files with the named_keytab_t type, if you want to treat the files as kerberos keytab files.


.EX
.B named_log_t 
.EE

- Set files with the named_log_t type, if you want to treat the data as named log data, usually stored under the /var/log directory.

.br
Paths: 
/var/log/named.*, /var/named/chroot/var/log/named.*
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B named_tmp_t 
.EE

- Set files with the named_tmp_t type, if you want to store named temporary files in the /tmp directories.


.EX
.B named_unit_file_t 
.EE

- Set files with the named_unit_file_t type, if you want to treat the files as named unit content.

.br
Paths: 
/lib/systemd/system/named.service, /usr/lib/systemd/system/named.service
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B named_var_run_t 
.EE

- Set files with the named_var_run_t type, if you want to store the named files under the /run directory.

.br
Paths: 
/var/named/chroot/var/run/named.*, /var/run/ndc, /var/run/bind(/.*)?, /var/run/named(/.*)?, /var/run/unbound(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B named_zone_t 
.EE

- Set files with the named_zone_t type, if you want to treat the files as named zone data.

.br
Paths: 
/var/named/chroot/var/named(/.*)?, /var/named(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), named(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)