.TH  "NetworkManager_selinux"  "8"  "NetworkManager" "dwalsh@redhat.com" "NetworkManager SELinux Policy documentation"
.SH "NAME"
NetworkManager_selinux \- Security Enhanced Linux Policy for the NetworkManager processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the NetworkManager processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux NetworkManager policy is very flexible allowing users to setup their NetworkManager processes in as secure a method as possible.
.PP 
The following file types are defined for NetworkManager:


.EX
.B NetworkManager_etc_rw_t 
.EE

- Set files with the NetworkManager_etc_rw_t context, if you want to treat the files as NetworkManager etc read/write content.

.br
Paths: 
/etc/NetworkManager/system-connections(/.*)?, /etc/NetworkManager/NetworkManager\.conf

.EX
.B NetworkManager_etc_t 
.EE

- Set files with the NetworkManager_etc_t context, if you want to store NetworkManager files in the /etc directories.

.br
Path: 
/etc/NetworkManager(/.*)?

.EX
.B NetworkManager_exec_t 
.EE

- Set files with the NetworkManager_exec_t context, if you want to a executable to transition to the NetworkManager_t domain.

.br
Paths: 
/usr/s?bin/wpa_supplicant, /usr/sbin/wpa_supplicant, /sbin/wpa_supplicant, /usr/sbin/nm-system-settings, /usr/sbin/wicd, /usr/s?bin/NetworkManager, /usr/sbin/NetworkManagerDispatcher

.EX
.B NetworkManager_initrc_exec_t 
.EE

- Set files with the NetworkManager_initrc_exec_t context, if you want to a executable to transition to the NetworkManager_initrc_t domain.

.br
Paths: 
/etc/rc\.d/init\.d/wicd, /etc/NetworkManager/dispatcher\.d(/.*)?, /usr/libexec/nm-dispatcher.action

.EX
.B NetworkManager_log_t 
.EE

- Set files with the NetworkManager_log_t context, if you want to treat the data as NetworkManager log data, usually stored under the /var/log directory.

.br
Paths: 
/var/log/wpa_supplicant.*, /var/log/wicd.*

.EX
.B NetworkManager_tmp_t 
.EE

- Set files with the NetworkManager_tmp_t context, if you want to store NetworkManager temporary files in the /tmp directories.


.EX
.B NetworkManager_unit_file_t 
.EE

- Set files with the NetworkManager_unit_file_t context, if you want to treat the files as NetworkManager unit content.

.br
Paths: 
/usr/lib/systemd/system/NetworkManager\.service, /lib/systemd/system/NetworkManager\.service

.EX
.B NetworkManager_var_lib_t 
.EE

- Set files with the NetworkManager_var_lib_t context, if you want to store the NetworkManager files under the /var/lib directory.

.br
Paths: 
/etc/wicd/wired-settings.conf, /var/lib/wicd(/.*)?, /etc/wicd/manager-settings.conf, /etc/wicd/wireless-settings.conf, /var/lib/NetworkManager(/.*)?

.EX
.B NetworkManager_var_run_t 
.EE

- Set files with the NetworkManager_var_run_t context, if you want to store the NetworkManager files under the /run directory.

.br
Paths: 
/var/run/wpa_supplicant-global, /var/run/nm-dhclient.*, /var/run/wpa_supplicant(/.*)?, /var/run/NetworkManager\.pid, /var/run/nm-dns-dnsmasq\.conf, /var/run/NetworkManager(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), NetworkManager(8), semanage(8), restorecon(8), chcon(1)
