.TH  "NetworkManager_selinux"  "8"  "13-01-16" "NetworkManager" "SELinux Policy documentation for NetworkManager"
.SH "NAME"
NetworkManager_selinux \- Security Enhanced Linux Policy for the NetworkManager processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the NetworkManager processes via flexible mandatory access control.

The NetworkManager processes execute with the NetworkManager_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep NetworkManager_t


.SH "ENTRYPOINTS"

The NetworkManager_t SELinux type can be entered via the \fBNetworkManager_exec_t\fP file type.

The default entrypoint paths for the NetworkManager_t domain are the following:

/usr/s?bin/NetworkManager, /usr/s?bin/wpa_supplicant, /usr/sbin/wicd, /sbin/wpa_supplicant, /usr/sbin/wpa_supplicant, /usr/sbin/nm-system-settings, /usr/sbin/NetworkManagerDispatcher
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux NetworkManager policy is very flexible allowing users to setup their NetworkManager processes in as secure a method as possible.
.PP
The following process types are defined for NetworkManager:

.EX
.B NetworkManager_t
.EE
.PP
Note:
.B semanage permissive -a NetworkManager_t
can be used to make the process type NetworkManager_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  NetworkManager policy is extremely flexible and has several booleans that allow you to manipulate the policy and run NetworkManager with the tightest access possible.


.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server, you must turn on the authlogin_nsswitch_use_ldap boolean. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you want to allow all daemons to write corefiles to /, you must turn on the daemons_dump_core boolean. Disabled by default.

.EX
.B setsebool -P daemons_dump_core 1

.EE

.PP
If you want to allow all daemons to use tcp wrappers, you must turn on the daemons_use_tcp_wrapper boolean. Disabled by default.

.EX
.B setsebool -P daemons_use_tcp_wrapper 1

.EE

.PP
If you want to allow all daemons the ability to read/write terminals, you must turn on the daemons_use_tty boolean. Disabled by default.

.EX
.B setsebool -P daemons_use_tty 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to run with kerberos, you must turn on the kerberos_enabled boolean. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you want to allow system to run with NIS, you must turn on the nis_enabled boolean. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.PP
If you want to support NFS home directories, you must turn on the use_nfs_home_dirs boolean. Enabled by default.

.EX
.B setsebool -P use_nfs_home_dirs 1

.EE

.PP
If you want to support SAMBA home directories, you must turn on the use_samba_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_samba_home_dirs 1

.EE

.PP
If you want to allow xguest users to configure Network Manager and connect to apache ports, you must turn on the xguest_connect_network boolean. Enabled by default.

.EX
.B setsebool -P xguest_connect_network 1

.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server for the NetworkManager_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the NetworkManager_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "MANAGED FILES"

The SELinux process type NetworkManager_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B NetworkManager_etc_rw_t

	/etc/NetworkManager/system-connections(/.*)?
.br
	/etc/NetworkManager/NetworkManager\.conf
.br

.br
.B NetworkManager_tmp_t


.br
.B NetworkManager_var_lib_t

	/var/lib/wicd(/.*)?
.br
	/var/lib/NetworkManager(/.*)?
.br
	/etc/dhcp/wired-settings.conf
.br
	/etc/wicd/wired-settings.conf
.br
	/etc/dhcp/manager-settings.conf
.br
	/etc/wicd/manager-settings.conf
.br
	/etc/dhcp/wireless-settings.conf
.br
	/etc/wicd/wireless-settings.conf
.br

.br
.B NetworkManager_var_run_t

	/var/run/nm-dhclient.*
.br
	/var/run/NetworkManager(/.*)?
.br
	/var/run/wpa_supplicant(/.*)?
.br
	/var/run/NetworkManager\.pid
.br
	/var/run/nm-dns-dnsmasq\.conf
.br
	/var/run/wpa_supplicant-global
.br

.br
.B named_cache_t

	/var/named/data(/.*)?
.br
	/var/lib/unbound(/.*)?
.br
	/var/named/slaves(/.*)?
.br
	/var/named/dynamic(/.*)?
.br
	/var/named/chroot/var/tmp(/.*)?
.br
	/var/named/chroot/var/named/data(/.*)?
.br
	/var/named/chroot/var/named/slaves(/.*)?
.br
	/var/named/chroot/var/named/dynamic(/.*)?
.br

.br
.B net_conf_t

	/etc/hosts[^/]*
.br
	/etc/yp\.conf.*
.br
	/etc/denyhosts.*
.br
	/etc/hosts\.deny.*
.br
	/etc/resolv\.conf.*
.br
	/etc/sysconfig/networking(/.*)?
.br
	/etc/sysconfig/network-scripts(/.*)?
.br
	/etc/sysconfig/network-scripts/.*resolv\.conf
.br
	/etc/ethers
.br

.br
.B pppd_var_run_t

	/var/run/(i)?ppp.*pid[^/]*
.br
	/var/run/ppp(/.*)?
.br
	/var/run/pppd[0-9]*\.tdb
.br

.br
.B root_t

	/
.br
	/initrd
.br

.br
.B sysfs_t

	/sys(/.*)?
.br

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux NetworkManager policy is very flexible allowing users to setup their NetworkManager processes in as secure a method as possible.
.PP

.PP
.B EQUIVALENCE DIRECTORIES

.PP
NetworkManager policy stores data with multiple different file context types under the /var/run/wpa_supplicant directory.  If you would like to store the data in a different directory you can use the semanage command to create an equivalence mapping.  If you wanted to store this data under the /srv dirctory you would execute the following command:
.PP
.B semanage fcontext -a -e /var/run/wpa_supplicant /srv/wpa_supplicant
.br
.B restorecon -R -v /srv/wpa_supplicant
.PP

.PP
NetworkManager policy stores data with multiple different file context types under the /var/run/NetworkManager directory.  If you would like to store the data in a different directory you can use the semanage command to create an equivalence mapping.  If you wanted to store this data under the /srv dirctory you would execute the following command:
.PP
.B semanage fcontext -a -e /var/run/NetworkManager /srv/NetworkManager
.br
.B restorecon -R -v /srv/NetworkManager
.PP

.PP
.B STANDARD FILE CONTEXT

SELinux defines the file context types for the NetworkManager, if you wanted to
store files with these types in a diffent paths, you need to execute the semanage command to sepecify alternate labeling and then use restorecon to put the labels on disk.

.B semanage fcontext -a -t NetworkManager_etc_rw_t '/srv/NetworkManager/content(/.*)?'
.br
.B restorecon -R -v /srv/myNetworkManager_content

Note: SELinux often uses regular expressions to specify labels that match multiple files.

.I The following file types are defined for NetworkManager:


.EX
.PP
.B NetworkManager_etc_rw_t
.EE

- Set files with the NetworkManager_etc_rw_t type, if you want to treat the files as NetworkManager etc read/write content.

.br
.TP 5
Paths:
/etc/NetworkManager/system-connections(/.*)?, /etc/NetworkManager/NetworkManager\.conf

.EX
.PP
.B NetworkManager_etc_t
.EE

- Set files with the NetworkManager_etc_t type, if you want to store NetworkManager files in the /etc directories.


.EX
.PP
.B NetworkManager_exec_t
.EE

- Set files with the NetworkManager_exec_t type, if you want to transition an executable to the NetworkManager_t domain.

.br
.TP 5
Paths:
/usr/s?bin/NetworkManager, /usr/s?bin/wpa_supplicant, /usr/sbin/wicd, /sbin/wpa_supplicant, /usr/sbin/wpa_supplicant, /usr/sbin/nm-system-settings, /usr/sbin/NetworkManagerDispatcher

.EX
.PP
.B NetworkManager_initrc_exec_t
.EE

- Set files with the NetworkManager_initrc_exec_t type, if you want to transition an executable to the NetworkManager_initrc_t domain.

.br
.TP 5
Paths:
/usr/libexec/nm-dispatcher.action, /etc/NetworkManager/dispatcher\.d(/.*)?, /etc/rc\.d/init\.d/wicd

.EX
.PP
.B NetworkManager_log_t
.EE

- Set files with the NetworkManager_log_t type, if you want to treat the data as NetworkManager log data, usually stored under the /var/log directory.

.br
.TP 5
Paths:
/var/log/wicd.*, /var/log/wpa_supplicant.*

.EX
.PP
.B NetworkManager_tmp_t
.EE

- Set files with the NetworkManager_tmp_t type, if you want to store NetworkManager temporary files in the /tmp directories.


.EX
.PP
.B NetworkManager_unit_file_t
.EE

- Set files with the NetworkManager_unit_file_t type, if you want to treat the files as NetworkManager unit content.


.EX
.PP
.B NetworkManager_var_lib_t
.EE

- Set files with the NetworkManager_var_lib_t type, if you want to store the NetworkManager files under the /var/lib directory.

.br
.TP 5
Paths:
/var/lib/wicd(/.*)?, /var/lib/NetworkManager(/.*)?, /etc/dhcp/wired-settings.conf, /etc/wicd/wired-settings.conf, /etc/dhcp/manager-settings.conf, /etc/wicd/manager-settings.conf, /etc/dhcp/wireless-settings.conf, /etc/wicd/wireless-settings.conf

.EX
.PP
.B NetworkManager_var_run_t
.EE

- Set files with the NetworkManager_var_run_t type, if you want to store the NetworkManager files under the /run or /var/run directory.

.br
.TP 5
Paths:
/var/run/nm-dhclient.*, /var/run/NetworkManager(/.*)?, /var/run/wpa_supplicant(/.*)?, /var/run/NetworkManager\.pid, /var/run/nm-dns-dnsmasq\.conf, /var/run/wpa_supplicant-global

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), NetworkManager(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8)