.TH  "nfsd_selinux"  "8"  "nfsd" "dwalsh@redhat.com" "nfsd SELinux Policy documentation"
.SH "NAME"
nfsd_selinux \- Security Enhanced Linux Policy for the nfsd processes
.SH "DESCRIPTION"




.SH BOOLEANS
SELinux policy is customizable based on least access required.  nfsd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run nfsd with the tightest access possible.


.PP
If you want to allow xen to manage nfs file, you must turn on the xen_use_nfs boolean.

.EX
.B setsebool -P xen_use_nfs 1
.EE

.PP
If you want to allow confined virtual guests to manage nfs file, you must turn on the virt_use_nfs boolean.

.EX
.B setsebool -P virt_use_nfs 1
.EE

.PP
If you want to allow ftp servers to use nfs used for public file transfer services, you must turn on the allow_ftpd_use_nfs boolean.

.EX
.B setsebool -P allow_ftpd_use_nfs 1
.EE

.PP
If you want to allow Git daemon system to access nfs file systems, you must turn on the git_system_use_nfs boolean.

.EX
.B setsebool -P git_system_use_nfs 1
.EE

.PP
If you want to allow qemu to use nfs file system, you must turn on the qemu_use_nfs boolean.

.EX
.B setsebool -P qemu_use_nfs 1
.EE

.PP
If you want to allow rsync servers to share nfs files system, you must turn on the rsync_use_nfs boolean.

.EX
.B setsebool -P rsync_use_nfs 1
.EE

.PP
If you want to allow Cobbler to access nfs file systems, you must turn on the cobbler_use_nfs boolean.

.EX
.B setsebool -P cobbler_use_nfs 1
.EE

.PP
If you want to allow httpd to access nfs file system, you must turn on the httpd_use_nfs boolean.

.EX
.B setsebool -P httpd_use_nfs 1
.EE

.PP
If you want to allow sge to access nfs file systems, you must turn on the sge_use_nfs boolean.

.EX
.B setsebool -P sge_use_nfs 1
.EE

.PP
If you want to allow any files/directories to be exported read/write via NFS, you must turn on the nfs_export_all_rw boolean.

.EX
.B setsebool -P nfs_export_all_rw 1
.EE

.PP
If you want to allow confined virtual guests to manage nfs file, you must turn on the sanlock_use_nfs boolean.

.EX
.B setsebool -P sanlock_use_nfs 1
.EE

.PP
If you want to allow samba to export NFS volumes, you must turn on the samba_share_nfs boolean.

.EX
.B setsebool -P samba_share_nfs 1
.EE

.PP
If you want to determine whether Polipo can access nfs file systems, you must turn on the polipo_use_nfs boolean.

.EX
.B setsebool -P polipo_use_nfs 1
.EE

.PP
If you want to support NFS home directorie, you must turn on the use_nfs_home_dirs boolean.

.EX
.B setsebool -P use_nfs_home_dirs 1
.EE

.PP
If you want to allow any files/directories to be exported read/only via NFS, you must turn on the nfs_export_all_ro boolean.

.EX
.B setsebool -P nfs_export_all_ro 1
.EE

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow nfsd servers to read the /var/nfsd directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/nfsd(/.*)?"
.br
.B restorecon -F -R -v /var/nfsd
.pp
.TP
Allow nfsd servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_nfsd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/nfsd/incoming(/.*)?"
.br
.B restorecon -F -R -v /var/nfsd/incoming


.PP
If you want to allow nfs servers to modify public files used for public file transfer services.  Files/Directories must be labeled public_content_rw_t., you must turn on the allow_nfsd_anon_write boolean.

.EX
.B setsebool -P allow_nfsd_anon_write 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux nfsd policy is very flexible allowing users to setup their nfsd processes in as secure a method as possible.
.PP 
The following file types are defined for nfsd:


.EX
.PP
.B nfsd_exec_t 
.EE

- Set files with the nfsd_exec_t type, if you want to transition an executable to the nfsd_t domain.

.br
.TP 5
Paths: 
/usr/sbin/rpc\.mountd, /usr/sbin/rpc\.nfsd

.EX
.PP
.B nfsd_initrc_exec_t 
.EE

- Set files with the nfsd_initrc_exec_t type, if you want to transition an executable to the nfsd_initrc_t domain.


.EX
.PP
.B nfsd_ro_t 
.EE

- Set files with the nfsd_ro_t type, if you want to treat the files as nfsd read/only content.


.EX
.PP
.B nfsd_rw_t 
.EE

- Set files with the nfsd_rw_t type, if you want to treat the files as nfsd read/write content.


.EX
.PP
.B nfsd_unit_file_t 
.EE

- Set files with the nfsd_unit_file_t type, if you want to treat the files as nfsd unit content.

.br
.TP 5
Paths: 
/lib/systemd/system/nfs.*, /usr/lib/systemd/system/nfs.*

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux nfsd policy is very flexible allowing users to setup their nfsd processes in as secure a method as possible.
.PP 
The following port types are defined for nfsd:

.EX
.TP 5
.B nfs_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux nfsd policy is very flexible allowing users to setup their nfsd processes in as secure a method as possible.
.PP 
The following process types are defined for nfsd:

.EX
.B nfsd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), nfsd(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)