.TH  "nmbd_selinux"  "8"  "nmbd" "dwalsh@redhat.com" "nmbd SELinux Policy documentation"
.SH "NAME"
nmbd_selinux \- Security Enhanced Linux Policy for the nmbd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the nmbd processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux nmbd policy is very flexible allowing users to setup their nmbd processes in as secure a method as possible.
.PP 
The following file types are defined for nmbd:


.EX
.PP
.B nmbd_exec_t 
.EE

- Set files with the nmbd_exec_t type, if you want to transition an executable to the nmbd_t domain.


.EX
.PP
.B nmbd_var_run_t 
.EE

- Set files with the nmbd_var_run_t type, if you want to store the nmbd files under the /run directory.

.br
.TP 5
Paths: 
/var/run/samba/messages\.tdb, /var/run/samba/namelist\.debug, /var/run/nmbd(/.*)?, /var/run/samba/unexpected\.tdb, /var/run/samba/nmbd\.pid

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux nmbd policy is very flexible allowing users to setup their nmbd processes in as secure a method as possible.
.PP 
The following port types are defined for nmbd:

.EX
.TP 5
.B nmbd_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux nmbd policy is very flexible allowing users to setup their nmbd processes in as secure a method as possible.
.PP 
The following process types are defined for nmbd:

.EX
.B nmbd_t 
.EE
.PP
Note: 
.B semanage permississive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), nmbd(8), semanage(8), restorecon(8), chcon(1)
