.TH  "nova_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "nova Selinux Policy documentation"
.SH "NAME"
nova_selinux \- Security Enhanced Linux Policy for the nova processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the nova processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux nova policy is very flexible allowing users to setup their nova processes in as secure a method as possible.
.PP 
The following file types are defined for nova:


.EX
.B nova_ajax_exec_t 
.EE

- Set files with the nova_ajax_exec_t context, if you want to a executable to transition to the nova_ajax_t domain.


.EX
.B nova_ajax_tmp_t 
.EE

- Set files with the nova_ajax_tmp_t context, if you want to store nova ajax temporary files in the /tmp directories.


.EX
.B nova_api_exec_t 
.EE

- Set files with the nova_api_exec_t context, if you want to a executable to transition to the nova_api_t domain.


.EX
.B nova_api_tmp_t 
.EE

- Set files with the nova_api_tmp_t context, if you want to store nova api temporary files in the /tmp directories.


.EX
.B nova_compute_exec_t 
.EE

- Set files with the nova_compute_exec_t context, if you want to a executable to transition to the nova_compute_t domain.


.EX
.B nova_compute_tmp_t 
.EE

- Set files with the nova_compute_tmp_t context, if you want to store nova compute temporary files in the /tmp directories.


.EX
.B nova_direct_exec_t 
.EE

- Set files with the nova_direct_exec_t context, if you want to a executable to transition to the nova_direct_t domain.


.EX
.B nova_direct_tmp_t 
.EE

- Set files with the nova_direct_tmp_t context, if you want to store nova direct temporary files in the /tmp directories.


.EX
.B nova_log_t 
.EE

- Set files with the nova_log_t context, if you want to treat the data as nova log data, usually stored in /var/log.


.EX
.B nova_network_exec_t 
.EE

- Set files with the nova_network_exec_t context, if you want to a executable to transition to the nova_network_t domain.


.EX
.B nova_network_tmp_t 
.EE

- Set files with the nova_network_tmp_t context, if you want to store nova network temporary files in the /tmp directories.


.EX
.B nova_objectstore_exec_t 
.EE

- Set files with the nova_objectstore_exec_t context, if you want to a executable to transition to the nova_objectstore_t domain.


.EX
.B nova_objectstore_tmp_t 
.EE

- Set files with the nova_objectstore_tmp_t context, if you want to store nova objectstore temporary files in the /tmp directories.


.EX
.B nova_scheduler_exec_t 
.EE

- Set files with the nova_scheduler_exec_t context, if you want to a executable to transition to the nova_scheduler_t domain.


.EX
.B nova_scheduler_tmp_t 
.EE

- Set files with the nova_scheduler_tmp_t context, if you want to store nova scheduler temporary files in the /tmp directories.


.EX
.B nova_var_lib_t 
.EE

- Set files with the nova_var_lib_t context, if you want to store the nova files under the /var/lib directory.


.EX
.B nova_var_run_t 
.EE

- Set files with the nova_var_run_t context, if you want to store the nova files under the /run directory.


.EX
.B nova_vncproxy_exec_t 
.EE

- Set files with the nova_vncproxy_exec_t context, if you want to a executable to transition to the nova_vncproxy_t domain.


.EX
.B nova_vncproxy_tmp_t 
.EE

- Set files with the nova_vncproxy_tmp_t context, if you want to store nova vncproxy temporary files in the /tmp directories.


.EX
.B nova_volume_exec_t 
.EE

- Set files with the nova_volume_exec_t context, if you want to a executable to transition to the nova_volume_t domain.


.EX
.B nova_volume_tmp_t 
.EE

- Set files with the nova_volume_tmp_t context, if you want to store nova volume temporary files in the /tmp directories.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), nova(8), semanage(8), restorecon(8), chcon(1)