.TH  "nx_server_selinux"  "8"  "nx_server" "mgrepl@redhat.com" "nx_server SELinux Policy documentation"
.SH "NAME"
nx_server_r \- \fBnx_server user role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

SELinux supports Roles Based Access Control (RBAC), some Linux roles are login roles, while other roles need to be transition into. 

.I Note: 
Examples in this man page will use the 
.B staff_u 
SELinux user.

Non login roles are usually used for administrative tasks. For example, tasks that require root privileges.  Roles control which types a user can run processes with. Roles often have default types assigned to them. 

The default type for the nx_server_r role is nx_server_t.

The 
.B newrole 
program to transition directly to this role.

.B newrole -r nx_server_r -t nx_server_t

.B sudo 
is the preferred method to do transition from one role to another.  You setup sudo to transition to nx_server_r by adding a similar line to the /etc/sudoers file.

USERNAME ALL=(ALL) ROLE=nx_server_r TYPE=nx_server_t COMMAND

.br
sudo will run COMMAND as staff_u:nx_server_r:nx_server_t:LEVEL

When using a a non login role, you need to setup SELinux so that your SELinux user can reach nx_server_r role.

Execute the following to see all of the assigned SELinux roles:

.B semanage user -l

You need to add nx_server_r to the staff_u user.  You could setup the staff_u user to be able to use the nx_server_r role with a command like:

.B $ semanage user -m -R 'staff_r system_r nx_server_r' staff_u 


.SH "MANAGED FILES"

The SELinux process type nx_server_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B nx_server_home_ssh_t

	/opt/NX/home/nx/\.ssh(/.*)?
.br
	/usr/NX/home/nx/\.ssh(/.*)?
.br
	/var/lib/nxserver/home/.ssh(/.*)?
.br

.br
.B nx_server_tmp_t


.br
.B nx_server_var_lib_t

	/opt/NX/home(/.*)?
.br
	/usr/NX/home(/.*)?
.br
	/var/lib/nxserver(/.*)?
.br

.br
.B nx_server_var_run_t

	/opt/NX/var(/.*)?
.br

.br
.B ssh_home_t

	/root/\.ssh(/.*)?
.br
	/var/lib/amanda/\.ssh(/.*)?
.br
	/var/lib/stickshift/[^/]+/\.ssh(/.*)?
.br
	/var/lib/gitolite/\.ssh(/.*)?
.br
	/var/lib/nocpulse/\.ssh(/.*)?
.br
	/var/lib/gitolite3/\.ssh(/.*)?
.br
	/root/\.shosts
.br
	/home/[^/]*/\.ssh(/.*)?
.br
	/home/[^/]*/\.shosts
.br
	/home/dwalsh/\.ssh(/.*)?
.br
	/home/dwalsh/\.shosts
.br
	/var/lib/xguest/home/xguest/\.ssh(/.*)?
.br
	/var/lib/xguest/home/xguest/\.shosts
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), nx_server(8), semanage(8), restorecon(8), chcon(1)
