.TH  "nx_selinux"  "8"  "nx" "dwalsh@redhat.com" "nx SELinux Policy documentation"
.SH "NAME"
nx_selinux \- Security Enhanced Linux Policy for the nx processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the nx processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux nx policy is very flexible allowing users to setup their nx processes in as secure a method as possible.
.PP 
The following file types are defined for nx:


.EX
.B nx_server_exec_t 
.EE

- Set files with the nx_server_exec_t context, if you want to a executable to transition to the nx_server_t domain.

.br
Paths: 
/opt/NX/bin/nxserver, /usr/NX/bin/nxserver, /usr/libexec/nx/nxserver

.EX
.B nx_server_home_ssh_t 
.EE

- Set files with the nx_server_home_ssh_t context, if you want to treat the files as nx server home ssh data.

.br
Paths: 
/opt/NX/home/nx/\.ssh(/.*)?, /usr/NX/home/nx/\.ssh(/.*)?, /var/lib/nxserver/home/.ssh(/.*)?

.EX
.B nx_server_tmp_t 
.EE

- Set files with the nx_server_tmp_t context, if you want to store nx server temporary files in the /tmp directories.


.EX
.B nx_server_var_lib_t 
.EE

- Set files with the nx_server_var_lib_t context, if you want to store the nx server files under the /var/lib directory.

.br
Paths: 
/usr/NX/home(/.*)?, /opt/NX/home(/.*)?, /var/lib/nxserver(/.*)?

.EX
.B nx_server_var_run_t 
.EE

- Set files with the nx_server_var_run_t context, if you want to store the nx server files under the /run directory.

.br
Path: 
/opt/NX/var(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), nx(8), semanage(8), restorecon(8), chcon(1)
