.TH  "nx_server_selinux"  "8"  "nx_server" "mgrepl@redhat.com" "nx_server SELinux Policy documentation"
.SH "NAME"
nx_server_r \- \fBnx_server user role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

SELinux supports Roles Based Access Control, some Linux roles are login roles, while other roles need to be transition to. 

Note: The examples in the man page will user the staff_u user.

Non login roles are usually used for administrative tasks.

Roles usually have default types assigned to them. 

The default type for the nx_server_r role is nx_server_t.

You can use the 
.B newrole 
program to transition directly to this role.

.B newrole -r nx_server_r -t nx_server_t

.B sudo 
can also be setup to transition to this role using the visudo command.

USERNAME ALL=(ALL) ROLE=nx_server_r TYPE=nx_server_t COMMAND
.br
sudo will run COMMAND as staff_u:nx_server_r:nx_server_t:LEVEL

If you want to use a non login role, you need to make sure the SELinux user you are using can reach this role.

You can see all of the assigned SELinux roles using the following

.B semanage user -l

If you wanted to add nx_server_r to the staff_u user, you would execute:

.B $ semanage user -m -R 'staff_r nx_server_r' staff_u 


.SH "COMMANDS"

.B semanage login
can also be used to manipulate the Linux User to SELinux User mappings

.B semanage user
can also be used to manipulate SELinux user definitions.

.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genuserman.py.

.SH "SEE ALSO"
selinux(8), semanage(8).
