.TH  "openshift_min_app_selinux"  "8"  "13-01-16" "openshift_min_app" "SELinux Policy documentation for openshift_min_app"
.SH "NAME"
openshift_min_app_selinux \- Security Enhanced Linux Policy for the openshift_min_app processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the openshift_min_app processes via flexible mandatory access control.

The openshift_min_app processes execute with the openshift_min_app_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep openshift_min_app_t


.SH "ENTRYPOINTS"

The openshift_min_app_t SELinux type can be entered via the \fBopenshift_file_type, shell_exec_t, httpd_exec_t, user_cron_spool_t, gpg_exec_t, bin_t\fP file types.

The default entrypoint paths for the openshift_min_app_t domain are the following:

All executeables with the default executable label, usually stored in /usr/bin and /usr/sbin.
/bin/d?ash, /bin/zsh.*, /bin/ksh.*, /usr/bin/d?ash, /usr/bin/ksh.*, /usr/bin/zsh.*, /bin/esh, /bin/mksh, /bin/sash, /bin/tcsh, /bin/yash, /bin/bash, /bin/fish, /bin/bash2, /usr/bin/esh, /usr/bin/fish, /usr/bin/bash, /usr/bin/mksh, /usr/bin/sash, /usr/bin/tcsh, /usr/bin/yash, /sbin/nologin, /usr/sbin/sesh, /usr/bin/bash2, /usr/sbin/smrsh, /usr/bin/scponly, /usr/sbin/nologin, /usr/libexec/sesh, /usr/sbin/scponlyc, /usr/bin/git-shell, /usr/libexec/git-core/git-shell, /usr/sbin/httpd(\.worker)?, /usr/sbin/apache(2)?, /usr/lib/apache-ssl/.+, /usr/sbin/apache-ssl(2)?, /usr/share/jetty/bin/jetty.sh, /usr/sbin/php-fpm, /usr/sbin/cherokee, /usr/sbin/lighttpd, /usr/sbin/httpd\.event, /usr/bin/mongrel_rails, /var/spool/at(/.*)?, /var/spool/cron, /usr/bin/gpg(2)?, /usr/lib/gnupg/.*, /usr/bin/gpgsm
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux openshift_min_app policy is very flexible allowing users to setup their openshift_min_app processes in as secure a method as possible.
.PP
The following process types are defined for openshift_min_app:

.EX
.B openshift_min_app_t
.EE
.PP
Note:
.B semanage permissive -a openshift_min_app_t
can be used to make the process type openshift_min_app_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  openshift_min_app policy is extremely flexible and has several booleans that allow you to manipulate the policy and run openshift_min_app with the tightest access possible.


.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.SH "MANAGED FILES"

The SELinux process type openshift_min_app_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B anon_inodefs_t


.br
.B hugetlbfs_t

	/dev/hugepages
.br
	/lib/udev/devices/hugepages
.br
	/usr/lib/udev/devices/hugepages
.br

.br
.B openshift_rw_file_t

	/var/lib/openshift/.*/data(/.*)?
.br
	/var/lib/stickshift/.*/data(/.*)?
.br

.br
.B openshift_tmp_t

	/var/lib/openshift/.*/\.tmp(/.*)?
.br
	/var/lib/openshift/.*/\.sandbox(/.*)?
.br
	/var/lib/stickshift/.*/\.tmp(/.*)?
.br
	/var/lib/stickshift/.*/\.sandbox(/.*)?
.br

.br
.B openshift_tmpfs_t


.br
.B security_t

	/selinux
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), openshift_min_app(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), openshift_selinux(8), openshift_selinux(8), openshift_app_selinux(8), openshift_cgroup_read_selinux(8), openshift_initrc_selinux(8), openshift_mail_selinux(8), openshift_min_selinux(8), openshift_min_selinux(8), openshift_net_selinux(8), openshift_net_app_selinux(8)