.TH  "ping_selinux"  "8"  "ping" "dwalsh@redhat.com" "ping SELinux Policy documentation"
.SH "NAME"
ping_selinux \- Security Enhanced Linux Policy for the ping processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ping processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  ping policy is extremely flexible and has several booleans that allow you to manipulate the policy and run ping with the tightest access possible.


.PP
If you want to control users use of ping and traceroute, you must turn on the selinuxuser_ping boolean.

.EX
.B setsebool -P selinuxuser_ping 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the pingd_t, ping_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the pingd_t, ping_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux ping policy is very flexible allowing users to setup their ping processes in as secure a method as possible.
.PP 
The following file types are defined for ping:


.EX
.PP
.B ping_exec_t 
.EE

- Set files with the ping_exec_t type, if you want to transition an executable to the ping_t domain.

.br
.TP 5
Paths: 
/usr/bin/ping.*, /usr/sbin/hping2, /usr/sbin/fping.*, /bin/ping.*, /usr/sbin/send_arp

.EX
.PP
.B pingd_etc_t 
.EE

- Set files with the pingd_etc_t type, if you want to store pingd files in the /etc directories.


.EX
.PP
.B pingd_exec_t 
.EE

- Set files with the pingd_exec_t type, if you want to transition an executable to the pingd_t domain.


.EX
.PP
.B pingd_initrc_exec_t 
.EE

- Set files with the pingd_initrc_exec_t type, if you want to transition an executable to the pingd_initrc_t domain.


.EX
.PP
.B pingd_modules_t 
.EE

- Set files with the pingd_modules_t type, if you want to treat the files as pingd modules.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux ping policy is very flexible allowing users to setup their ping processes in as secure a method as possible.
.PP 
The following port types are defined for ping:

.EX
.TP 5
.B pingd_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 9125
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux ping policy is very flexible allowing users to setup their ping processes in as secure a method as possible.
.PP 
The following process types are defined for ping:

.EX
.B ping_t, pingd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type ping_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), ping(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8), pingd_selinux(8)