.TH  "ping_selinux"  "8"  "ping" "dwalsh@redhat.com" "ping SELinux Policy documentation"
.SH "NAME"
ping_selinux \- Security Enhanced Linux Policy for the ping processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ping processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux ping policy is very flexible allowing users to setup their ping processes in as secure a method as possible.
.PP 
The following file types are defined for ping:


.EX
.B ping_exec_t 
.EE

- Set files with the ping_exec_t context, if you want to a executable to transition to the ping_t domain.

.br
Paths: 
/usr/bin/ping.*, /usr/sbin/hping2, /usr/sbin/fping.*, /bin/ping.*, /usr/sbin/send_arp

.EX
.B pingd_etc_t 
.EE

- Set files with the pingd_etc_t context, if you want to store pingd files in the /etc directories.

.br
Path: 
/etc/pingd.conf

.EX
.B pingd_exec_t 
.EE

- Set files with the pingd_exec_t context, if you want to a executable to transition to the pingd_t domain.

.br
Path: 
/usr/sbin/pingd

.EX
.B pingd_initrc_exec_t 
.EE

- Set files with the pingd_initrc_exec_t context, if you want to a executable to transition to the pingd_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/whatsup-pingd

.EX
.B pingd_modules_t 
.EE

- Set files with the pingd_modules_t context, if you want to treat the files as pingd modules.

.br
Path: 
/usr/lib/pingd(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  ping policy is extremely flexible and has several booleans that allow you to manipulate the policy and run ping with the tightest access possible.


.PP
If you want to control users use of ping and tracerout, you must turn on the user_ping boolean.

.EX
.B setsebool -P user_ping 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), ping(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)