.TH  "pki_tomcat_selinux"  "8"  "12-11-01" "pki_tomcat" "SELinux Policy documentation for pki_tomcat"
.SH "NAME"
pki_tomcat_selinux \- Security Enhanced Linux Policy for the pki_tomcat processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the pki_tomcat processes via flexible mandatory access control.

The pki_tomcat processes execute with the pki_tomcat_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep pki_tomcat_t


.SH "ENTRYPOINTS"

The pki_tomcat_t SELinux type can be entered via the "pki_tomcat_exec_t" file type.  The default entrypoint paths for the pki_tomcat_t domain are the following:"

/usr/bin/pkidaemon
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux pki_tomcat policy is very flexible allowing users to setup their pki_tomcat processes in as secure a method as possible.
.PP
The following process types are defined for pki_tomcat:

.EX
.B pki_tomcat_t, pki_tomcat_script_t
.EE
.PP
Note:
.B semanage permissive -a PROCESS_TYPE
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux pki_tomcat policy is very flexible allowing users to setup their pki_tomcat processes in as secure a method as possible.
.PP
The following file types are defined for pki_tomcat:


.EX
.PP
.B pki_tomcat_cache_t
.EE

- Set files with the pki_tomcat_cache_t type, if you want to store the files under the /var/cache directory.


.EX
.PP
.B pki_tomcat_cert_t
.EE

- Set files with the pki_tomcat_cert_t type, if you want to treat the files as pki tomcat certificate data.


.EX
.PP
.B pki_tomcat_etc_rw_t
.EE

- Set files with the pki_tomcat_etc_rw_t type, if you want to treat the files as pki tomcat etc read/write content.


.EX
.PP
.B pki_tomcat_exec_t
.EE

- Set files with the pki_tomcat_exec_t type, if you want to transition an executable to the pki_tomcat_t domain.


.EX
.PP
.B pki_tomcat_lock_t
.EE

- Set files with the pki_tomcat_lock_t type, if you want to treat the files as pki tomcat lock data, stored under the /var/lock directory


.EX
.PP
.B pki_tomcat_log_t
.EE

- Set files with the pki_tomcat_log_t type, if you want to treat the data as pki tomcat log data, usually stored under the /var/log directory.


.EX
.PP
.B pki_tomcat_tmp_t
.EE

- Set files with the pki_tomcat_tmp_t type, if you want to store pki tomcat temporary files in the /tmp directories.


.EX
.PP
.B pki_tomcat_unit_file_t
.EE

- Set files with the pki_tomcat_unit_file_t type, if you want to treat the files as pki tomcat unit content.


.EX
.PP
.B pki_tomcat_var_lib_t
.EE

- Set files with the pki_tomcat_var_lib_t type, if you want to store the pki tomcat files under the /var/lib directory.


.EX
.PP
.B pki_tomcat_var_run_t
.EE

- Set files with the pki_tomcat_var_run_t type, if you want to store the pki tomcat files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type pki_tomcat_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B dirsrv_var_lib_t

	/var/lib/dirsrv(/.*)?
.br

.br
.B pki_common_t

	/opt/nfast(/.*)?
.br

.br
.B pki_tomcat_cache_t


.br
.B pki_tomcat_cert_t

	/var/lib/pki-ca/alias(/.*)?
.br
	/var/lib/pki-kra/alias(/.*)?
.br
	/var/lib/pki-tks/alias(/.*)?
.br
	/var/lib/pki-ocsp/alias(/.*)?
.br
	/etc/pki/pki-tomcat/alias(/.*)?
.br

.br
.B pki_tomcat_etc_rw_t

	/etc/pki-ca(/.*)?
.br
	/etc/pki-kra(/.*)?
.br
	/etc/pki-tks(/.*)?
.br
	/etc/pki-ocsp(/.*)?
.br
	/etc/pki/pki-tomcat(/.*)?
.br
	/etc/sysconfig/pki/tomcat(/.*)?
.br

.br
.B pki_tomcat_lock_t

	/var/lock/subsys/pkidaemon
.br

.br
.B pki_tomcat_log_t

	/var/log/pki-ca(/.*)?
.br
	/var/log/pki-kra(/.*)?
.br
	/var/log/pki-tks(/.*)?
.br
	/var/log/pki-ocsp(/.*)?
.br
	/var/log/pki/pki-tomcat(/.*)?
.br

.br
.B pki_tomcat_tmp_t


.br
.B pki_tomcat_var_lib_t

	/var/lib/pki-ca(/.*)?
.br
	/var/lib/pki-kra(/.*)?
.br
	/var/lib/pki-tks(/.*)?
.br
	/var/lib/pki-ocsp(/.*)?
.br
	/var/lib/pki/pki-tomcat(/.*)?
.br

.br
.B pki_tomcat_var_run_t

	/var/run/pki-ca.pid
.br
	/var/run/pki-kra.pid
.br
	/var/run/pki-tks.pid
.br
	/var/run/pki-ocsp.pid
.br
	/var/run/pki/tomcat(/.*)?
.br

.br
.B user_tmp_t

	/var/run/user(/.*)?
.br
	/tmp/gconfd-.*
.br
	/tmp/gconfd-dwalsh
.br
	/tmp/gconfd-xguest
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), pki_tomcat(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, pki_ra_selinux(8), pki_tps_selinux(8)