.TH  "pki_selinux"  "8"  "pki" "dwalsh@redhat.com" "pki SELinux Policy documentation"
.SH "NAME"
pki_selinux \- Security Enhanced Linux Policy for the pki processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the pki processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux pki policy is very flexible allowing users to setup their pki processes in as secure a method as possible.
.PP 
The following file types are defined for pki:


.EX
.B pki_ca_etc_rw_t 
.EE

- Set files with the pki_ca_etc_rw_t context, if you want to treat the files as pki ca etc read/write content.

.br
Paths: 
/etc/pki-ca(/.*)?, /etc/sysconfig/pki/ca(/.*)?

.EX
.B pki_ca_exec_t 
.EE

- Set files with the pki_ca_exec_t context, if you want to a executable to transition to the pki_ca_t domain.

.br
Path: 
/usr/bin/dtomcat5-pki-ca

.EX
.B pki_ca_log_t 
.EE

- Set files with the pki_ca_log_t context, if you want to treat the data as pki ca log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/pki-ca(/.*)?

.EX
.B pki_ca_tomcat_exec_t 
.EE

- Set files with the pki_ca_tomcat_exec_t context, if you want to a executable to transition to the pki_ca_tomcat_t domain.

.br
Path: 
/etc/pki-ca/tomcat5.conf

.EX
.B pki_ca_var_lib_t 
.EE

- Set files with the pki_ca_var_lib_t context, if you want to store the pki ca files under the /var/lib directory.

.br
Path: 
/var/lib/pki-ca(/.*)?

.EX
.B pki_ca_var_run_t 
.EE

- Set files with the pki_ca_var_run_t context, if you want to store the pki ca files under the /run directory.

.br
Paths: 
/var/run/pki-ca.pid, /var/run/pki/ca(/.*)?

.EX
.B pki_common_dev_t 
.EE

- Set files with the pki_common_dev_t context, if you want to treat the files as pki common dev data.

.br
Path: 
/dev/nfast(/.*)?

.EX
.B pki_common_t 
.EE

- Set files with the pki_common_t context, if you want to treat the files as pki common data.

.br
Path: 
/opt/nfast(/.*)?

.EX
.B pki_kra_etc_rw_t 
.EE

- Set files with the pki_kra_etc_rw_t context, if you want to treat the files as pki kra etc read/write content.

.br
Paths: 
/etc/pki-kra(/.*)?, /etc/sysconfig/pki/kra(/.*)?

.EX
.B pki_kra_exec_t 
.EE

- Set files with the pki_kra_exec_t context, if you want to a executable to transition to the pki_kra_t domain.

.br
Path: 
/usr/bin/dtomcat5-pki-kra

.EX
.B pki_kra_log_t 
.EE

- Set files with the pki_kra_log_t context, if you want to treat the data as pki kra log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/pki-kra(/.*)?

.EX
.B pki_kra_tomcat_exec_t 
.EE

- Set files with the pki_kra_tomcat_exec_t context, if you want to a executable to transition to the pki_kra_tomcat_t domain.

.br
Path: 
/etc/pki-kra/tomcat5.conf

.EX
.B pki_kra_var_lib_t 
.EE

- Set files with the pki_kra_var_lib_t context, if you want to store the pki kra files under the /var/lib directory.

.br
Path: 
/var/lib/pki-kra(/.*)?

.EX
.B pki_kra_var_run_t 
.EE

- Set files with the pki_kra_var_run_t context, if you want to store the pki kra files under the /run directory.

.br
Paths: 
/var/run/pki-kra.pid, /var/run/pki/kra(/.*)?

.EX
.B pki_ocsp_etc_rw_t 
.EE

- Set files with the pki_ocsp_etc_rw_t context, if you want to treat the files as pki ocsp etc read/write content.

.br
Paths: 
/etc/pki-ocsp(/.*)?, /etc/sysconfig/pki/ocsp(/.*)?

.EX
.B pki_ocsp_exec_t 
.EE

- Set files with the pki_ocsp_exec_t context, if you want to a executable to transition to the pki_ocsp_t domain.

.br
Path: 
/usr/bin/dtomcat5-pki-ocsp

.EX
.B pki_ocsp_log_t 
.EE

- Set files with the pki_ocsp_log_t context, if you want to treat the data as pki ocsp log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/pki-ocsp(/.*)?

.EX
.B pki_ocsp_tomcat_exec_t 
.EE

- Set files with the pki_ocsp_tomcat_exec_t context, if you want to a executable to transition to the pki_ocsp_tomcat_t domain.

.br
Path: 
/etc/pki-ocsp/tomcat5.conf

.EX
.B pki_ocsp_var_lib_t 
.EE

- Set files with the pki_ocsp_var_lib_t context, if you want to store the pki ocsp files under the /var/lib directory.

.br
Path: 
/var/lib/pki-ocsp(/.*)?

.EX
.B pki_ocsp_var_run_t 
.EE

- Set files with the pki_ocsp_var_run_t context, if you want to store the pki ocsp files under the /run directory.

.br
Paths: 
/var/run/pki-ocsp.pid, /var/run/pki/ocsp(/.*)?

.EX
.B pki_ra_etc_rw_t 
.EE

- Set files with the pki_ra_etc_rw_t context, if you want to treat the files as pki ra etc read/write content.

.br
Paths: 
/etc/sysconfig/pki/ra(/.*)?, /etc/pki-ra(/.*)?

.EX
.B pki_ra_exec_t 
.EE

- Set files with the pki_ra_exec_t context, if you want to a executable to transition to the pki_ra_t domain.

.br
Path: 
/usr/sbin/httpd.worker

.EX
.B pki_ra_log_t 
.EE

- Set files with the pki_ra_log_t context, if you want to treat the data as pki ra log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/pki-ra(/.*)?

.EX
.B pki_ra_script_exec_t 
.EE

- Set files with the pki_ra_script_exec_t context, if you want to a executable to transition to the pki_ra_script_t domain.


.EX
.B pki_ra_tomcat_exec_t 
.EE

- Set files with the pki_ra_tomcat_exec_t context, if you want to a executable to transition to the pki_ra_tomcat_t domain.


.EX
.B pki_ra_var_lib_t 
.EE

- Set files with the pki_ra_var_lib_t context, if you want to store the pki ra files under the /var/lib directory.

.br
Path: 
/var/lib/pki-ra(/.*)?

.EX
.B pki_ra_var_run_t 
.EE

- Set files with the pki_ra_var_run_t context, if you want to store the pki ra files under the /run directory.

.br
Path: 
/var/run/pki/ra(/.*)?

.EX
.B pki_tks_etc_rw_t 
.EE

- Set files with the pki_tks_etc_rw_t context, if you want to treat the files as pki tks etc read/write content.

.br
Paths: 
/etc/sysconfig/pki/tks(/.*)?, /etc/pki-tks(/.*)?

.EX
.B pki_tks_exec_t 
.EE

- Set files with the pki_tks_exec_t context, if you want to a executable to transition to the pki_tks_t domain.

.br
Path: 
/usr/bin/dtomcat5-pki-tks

.EX
.B pki_tks_log_t 
.EE

- Set files with the pki_tks_log_t context, if you want to treat the data as pki tks log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/pki-tks(/.*)?

.EX
.B pki_tks_tomcat_exec_t 
.EE

- Set files with the pki_tks_tomcat_exec_t context, if you want to a executable to transition to the pki_tks_tomcat_t domain.

.br
Path: 
/etc/pki-tks/tomcat5.conf

.EX
.B pki_tks_var_lib_t 
.EE

- Set files with the pki_tks_var_lib_t context, if you want to store the pki tks files under the /var/lib directory.

.br
Path: 
/var/lib/pki-tks(/.*)?

.EX
.B pki_tks_var_run_t 
.EE

- Set files with the pki_tks_var_run_t context, if you want to store the pki tks files under the /run directory.

.br
Paths: 
/var/run/pki-tks.pid, /var/run/pki/tks(/.*)?

.EX
.B pki_tps_etc_rw_t 
.EE

- Set files with the pki_tps_etc_rw_t context, if you want to treat the files as pki tps etc read/write content.

.br
Paths: 
/etc/sysconfig/pki/tps(/.*)?, /etc/pki-tps(/.*)?

.EX
.B pki_tps_exec_t 
.EE

- Set files with the pki_tps_exec_t context, if you want to a executable to transition to the pki_tps_t domain.


.EX
.B pki_tps_log_t 
.EE

- Set files with the pki_tps_log_t context, if you want to treat the data as pki tps log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/pki-tps(/.*)?

.EX
.B pki_tps_script_exec_t 
.EE

- Set files with the pki_tps_script_exec_t context, if you want to a executable to transition to the pki_tps_script_t domain.


.EX
.B pki_tps_tomcat_exec_t 
.EE

- Set files with the pki_tps_tomcat_exec_t context, if you want to a executable to transition to the pki_tps_tomcat_t domain.


.EX
.B pki_tps_var_lib_t 
.EE

- Set files with the pki_tps_var_lib_t context, if you want to store the pki tps files under the /var/lib directory.

.br
Path: 
/var/lib/pki-tps(/.*)?

.EX
.B pki_tps_var_run_t 
.EE

- Set files with the pki_tps_var_run_t context, if you want to store the pki tps files under the /run directory.

.br
Path: 
/var/run/pki/tps(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), pki(8), semanage(8), restorecon(8), chcon(1)
