.TH  "plymouth_selinux"  "8"  "13-01-16" "plymouth" "SELinux Policy documentation for plymouth"
.SH "NAME"
plymouth_selinux \- Security Enhanced Linux Policy for the plymouth processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the plymouth processes via flexible mandatory access control.

The plymouth processes execute with the plymouth_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep plymouth_t


.SH "ENTRYPOINTS"

The plymouth_t SELinux type can be entered via the \fBplymouth_exec_t\fP file type.

The default entrypoint paths for the plymouth_t domain are the following:

/bin/plymouth, /usr/bin/plymouth
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux plymouth policy is very flexible allowing users to setup their plymouth processes in as secure a method as possible.
.PP
The following process types are defined for plymouth:

.EX
.B plymouth_t, plymouthd_t
.EE
.PP
Note:
.B semanage permissive -a plymouth_t
can be used to make the process type plymouth_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  plymouth policy is extremely flexible and has several booleans that allow you to manipulate the policy and run plymouth with the tightest access possible.


.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux plymouth policy is very flexible allowing users to setup their plymouth processes in as secure a method as possible.
.PP

.PP
.B STANDARD FILE CONTEXT

SELinux defines the file context types for the plymouth, if you wanted to
store files with these types in a diffent paths, you need to execute the semanage command to sepecify alternate labeling and then use restorecon to put the labels on disk.

.B semanage fcontext -a -t plymouth_exec_t '/srv/plymouth/content(/.*)?'
.br
.B restorecon -R -v /srv/myplymouth_content

Note: SELinux often uses regular expressions to specify labels that match multiple files.

.I The following file types are defined for plymouth:


.EX
.PP
.B plymouth_exec_t
.EE

- Set files with the plymouth_exec_t type, if you want to transition an executable to the plymouth_t domain.

.br
.TP 5
Paths:
/bin/plymouth, /usr/bin/plymouth

.EX
.PP
.B plymouthd_exec_t
.EE

- Set files with the plymouthd_exec_t type, if you want to transition an executable to the plymouthd_t domain.

.br
.TP 5
Paths:
/sbin/plymouthd, /usr/sbin/plymouthd

.EX
.PP
.B plymouthd_spool_t
.EE

- Set files with the plymouthd_spool_t type, if you want to store the plymouthd files under the /var/spool directory.


.EX
.PP
.B plymouthd_var_lib_t
.EE

- Set files with the plymouthd_var_lib_t type, if you want to store the plymouthd files under the /var/lib directory.


.EX
.PP
.B plymouthd_var_log_t
.EE

- Set files with the plymouthd_var_log_t type, if you want to treat the data as plymouthd var log data, usually stored under the /var/log directory.


.EX
.PP
.B plymouthd_var_run_t
.EE

- Set files with the plymouthd_var_run_t type, if you want to store the plymouthd files under the /run or /var/run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), plymouth(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), plymouthd_selinux(8)