.TH  "plymouth_selinux"  "8"  "plymouth" "dwalsh@redhat.com" "plymouth SELinux Policy documentation"
.SH "NAME"
plymouth_selinux \- Security Enhanced Linux Policy for the plymouth processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the plymouth processes via flexible mandatory access control.

The plymouth processes execute with the plymouth_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep plymouth_t


.SH "ENTRYPOINTS"

The plymouth_t SELinux type can be entered via the "plymouth_exec_t" file type.  The default entrypoint paths for the plymouth_t domain are the following:"

/bin/plymouth, /usr/bin/plymouth
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux plymouth policy is very flexible allowing users to setup their plymouth processes in as secure a method as possible.
.PP 
The following process types are defined for plymouth:

.EX
.B plymouth_t, plymouthd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux plymouth policy is very flexible allowing users to setup their plymouth processes in as secure a method as possible.
.PP 
The following file types are defined for plymouth:


.EX
.PP
.B plymouth_exec_t 
.EE

- Set files with the plymouth_exec_t type, if you want to transition an executable to the plymouth_t domain.

.br
.TP 5
Paths: 
/bin/plymouth, /usr/bin/plymouth

.EX
.PP
.B plymouthd_exec_t 
.EE

- Set files with the plymouthd_exec_t type, if you want to transition an executable to the plymouthd_t domain.

.br
.TP 5
Paths: 
/sbin/plymouthd, /usr/sbin/plymouthd

.EX
.PP
.B plymouthd_spool_t 
.EE

- Set files with the plymouthd_spool_t type, if you want to store the plymouthd files under the /var/spool directory.


.EX
.PP
.B plymouthd_var_lib_t 
.EE

- Set files with the plymouthd_var_lib_t type, if you want to store the plymouthd files under the /var/lib directory.


.EX
.PP
.B plymouthd_var_log_t 
.EE

- Set files with the plymouthd_var_log_t type, if you want to treat the data as plymouthd var log data, usually stored under the /var/log directory.


.EX
.PP
.B plymouthd_var_run_t 
.EE

- Set files with the plymouthd_var_run_t type, if you want to store the plymouthd files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type plymouth_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), plymouth(8), semanage(8), restorecon(8), chcon(1)
, plymouthd_selinux(8)