.TH  "polipo_selinux"  "8"  "polipo" "dwalsh@redhat.com" "polipo SELinux Policy documentation"
.SH "NAME"
polipo_selinux \- Security Enhanced Linux Policy for the polipo processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the polipo processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  polipo policy is extremely flexible and has several booleans that allow you to manipulate the policy and run polipo with the tightest access possible.


.PP
If you want to allow polipo to connect to all ports > 1023, you must turn on the polipo_connect_all_unreserved boolean.

.EX
.B setsebool -P polipo_connect_all_unreserved 1
.EE

.PP
If you want to determine whether polipo can access cifs file systems, you must turn on the polipo_use_cifs boolean.

.EX
.B setsebool -P polipo_use_cifs 1
.EE

.PP
If you want to determine whether Polipo session daemon can send syslog messages, you must turn on the polipo_session_send_syslog_msg boolean.

.EX
.B setsebool -P polipo_session_send_syslog_msg 1
.EE

.PP
If you want to determine whether Polipo session daemon can bind tcp sockets to all unreserved ports, you must turn on the polipo_session_bind_all_unreserved_ports boolean.

.EX
.B setsebool -P polipo_session_bind_all_unreserved_ports 1
.EE

.PP
If you want to determine whether calling user domains can execute Polipo daemon in the polipo_session_t domain, you must turn on the polipo_session_users boolean.

.EX
.B setsebool -P polipo_session_users 1
.EE

.PP
If you want to determine whether Polipo can access nfs file systems, you must turn on the polipo_use_nfs boolean.

.EX
.B setsebool -P polipo_use_nfs 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the polipo_t, polipo_session_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the polipo_t, polipo_session_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux polipo policy is very flexible allowing users to setup their polipo processes in as secure a method as possible.
.PP 
The following file types are defined for polipo:


.EX
.PP
.B polipo_cache_home_t 
.EE

- Set files with the polipo_cache_home_t type, if you want to store polipo cache files in the users home directory.


.EX
.PP
.B polipo_cache_t 
.EE

- Set files with the polipo_cache_t type, if you want to store the files under the /var/cache directory.


.EX
.PP
.B polipo_config_home_t 
.EE

- Set files with the polipo_config_home_t type, if you want to store polipo config files in the users home directory.


.EX
.PP
.B polipo_etc_t 
.EE

- Set files with the polipo_etc_t type, if you want to store polipo files in the /etc directories.


.EX
.PP
.B polipo_exec_t 
.EE

- Set files with the polipo_exec_t type, if you want to transition an executable to the polipo_t domain.


.EX
.PP
.B polipo_initrc_exec_t 
.EE

- Set files with the polipo_initrc_exec_t type, if you want to transition an executable to the polipo_initrc_t domain.


.EX
.PP
.B polipo_log_t 
.EE

- Set files with the polipo_log_t type, if you want to treat the data as polipo log data, usually stored under the /var/log directory.


.EX
.PP
.B polipo_pid_t 
.EE

- Set files with the polipo_pid_t type, if you want to store the polipo files under the /run directory.


.EX
.PP
.B polipo_unit_file_t 
.EE

- Set files with the polipo_unit_file_t type, if you want to treat the files as polipo unit content.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux polipo policy is very flexible allowing users to setup their polipo processes in as secure a method as possible.
.PP 
The following process types are defined for polipo:

.EX
.B polipo_t, polipo_session_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type polipo_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B polipo_cache_t

	/var/cache/polipo(/.*)?
.br

.br
.B polipo_log_t

	/var/log/polipo.*
.br

.br
.B polipo_pid_t

	/var/run/polipo(/.*)?
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), polipo(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)