.TH  "postgresql_selinux"  "8"  "postgresql" "dwalsh@redhat.com" "postgresql SELinux Policy documentation"
.SH "NAME"
postgresql_selinux \- Security Enhanced Linux Policy for the postgresql processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the postgresql processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  postgresql policy is extremely flexible and has several booleans that allow you to manipulate the policy and run postgresql with the tightest access possible.


.PP
If you want to allow postgresql to use ssh and rsync for point-in-time recovery, you must turn on the postgresql_can_rsync boolean.

.EX
.B setsebool -P postgresql_can_rsync 1
.EE

.PP
If you want to allow unprivileged users to execute DDL statement, you must turn on the postgresql_selinux_users_ddl boolean.

.EX
.B setsebool -P postgresql_selinux_users_ddl 1
.EE

.PP
If you want to allow database admins to execute DML statement, you must turn on the postgresql_selinux_unconfined_dbadm boolean.

.EX
.B setsebool -P postgresql_selinux_unconfined_dbadm 1
.EE

.PP
If you want to allow users to connect to PostgreSQL, you must turn on the user_postgresql_connect boolean.

.EX
.B setsebool -P user_postgresql_connect 1
.EE

.PP
If you want to allow transmit client label to foreign database, you must turn on the postgresql_selinux_transmit_client_label boolean.

.EX
.B setsebool -P postgresql_selinux_transmit_client_label 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the postgresql_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the postgresql_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux postgresql policy is very flexible allowing users to setup their postgresql processes in as secure a method as possible.
.PP 
The following file types are defined for postgresql:


.EX
.PP
.B postgresql_db_t 
.EE

- Set files with the postgresql_db_t type, if you want to treat the files as postgresql database content.

.br
.TP 5
Paths: 
/usr/share/jonas/pgsql(/.*)?, /var/lib/postgres(ql)?(/.*)?, /var/lib/sepgsql(/.*)?, /usr/lib/pgsql/test/regress(/.*)?, /var/lib/pgsql(/.*)?

.EX
.PP
.B postgresql_etc_t 
.EE

- Set files with the postgresql_etc_t type, if you want to store postgresql files in the /etc directories.

.br
.TP 5
Paths: 
/etc/sysconfig/pgsql(/.*)?, /etc/postgresql(/.*)?

.EX
.PP
.B postgresql_exec_t 
.EE

- Set files with the postgresql_exec_t type, if you want to transition an executable to the postgresql_t domain.

.br
.TP 5
Paths: 
/usr/bin/(se)?postgres, /usr/lib/postgresql/bin/.*, /usr/lib/pgsql/test/regress/pg_regress, /usr/bin/initdb(\.sepgsql)?

.EX
.PP
.B postgresql_initrc_exec_t 
.EE

- Set files with the postgresql_initrc_exec_t type, if you want to transition an executable to the postgresql_initrc_t domain.


.EX
.PP
.B postgresql_lock_t 
.EE

- Set files with the postgresql_lock_t type, if you want to treat the files as postgresql lock data, stored under the /var/lock directory


.EX
.PP
.B postgresql_log_t 
.EE

- Set files with the postgresql_log_t type, if you want to treat the data as postgresql log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/lib/pgsql/logfile(/.*)?, /var/log/postgresql(/.*)?, /var/log/postgres\.log.*, /var/lib/sepgsql/pgstartup\.log, /var/log/rhdb/rhdb(/.*)?, /var/lib/pgsql/.*\.log, /var/log/sepostgresql\.log.*

.EX
.PP
.B postgresql_tmp_t 
.EE

- Set files with the postgresql_tmp_t type, if you want to store postgresql temporary files in the /tmp directories.


.EX
.PP
.B postgresql_var_run_t 
.EE

- Set files with the postgresql_var_run_t type, if you want to store the postgresql files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux postgresql policy is very flexible allowing users to setup their postgresql processes in as secure a method as possible.
.PP 
The following port types are defined for postgresql:

.EX
.TP 5
.B postgresql_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 5432
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux postgresql policy is very flexible allowing users to setup their postgresql processes in as secure a method as possible.
.PP 
The following process types are defined for postgresql:

.EX
.B postgresql_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type postgresql_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B faillog_t

	/var/log/btmp.*
.br
	/var/run/faillock(/.*)?
.br
	/var/log/faillog
.br
	/var/log/tallylog
.br

.br
.B hugetlbfs_t

	/dev/hugepages
.br
	/lib/udev/devices/hugepages
.br
	/usr/lib/udev/devices/hugepages
.br

.br
.B krb5_host_rcache_t

	/var/cache/krb5rcache(/.*)?
.br
	/var/tmp/nfs_0
.br
	/var/tmp/host_0
.br
	/var/tmp/imap_0
.br
	/var/tmp/HTTP_23
.br
	/var/tmp/HTTP_48
.br
	/var/tmp/ldap_55
.br
	/var/tmp/ldap_487
.br
	/var/tmp/ldapmap1_0
.br

.br
.B lastlog_t

	/var/log/lastlog
.br

.br
.B pcscd_var_run_t

	/var/run/pcscd(/.*)?
.br
	/var/run/pcscd\.events(/.*)?
.br
	/var/run/pcscd\.pid
.br
	/var/run/pcscd\.pub
.br
	/var/run/pcscd\.comm
.br

.br
.B postgresql_db_t

	/var/lib/pgsql(/.*)?
.br
	/var/lib/sepgsql(/.*)?
.br
	/var/lib/postgres(ql)?(/.*)?
.br
	/usr/share/jonas/pgsql(/.*)?
.br
	/usr/lib/pgsql/test/regress(/.*)?
.br

.br
.B postgresql_lock_t


.br
.B postgresql_log_t

	/var/lib/pgsql/.*\.log
.br
	/var/log/rhdb/rhdb(/.*)?
.br
	/var/log/postgresql(/.*)?
.br
	/var/log/postgres\.log.*
.br
	/var/lib/pgsql/logfile(/.*)?
.br
	/var/log/sepostgresql\.log.*
.br
	/var/lib/sepgsql/pgstartup\.log
.br

.br
.B postgresql_tmp_t


.br
.B postgresql_var_run_t

	/var/run/postgresql(/.*)?
.br

.br
.B security_t

	/selinux
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), postgresql(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)