.TH  "postgresql_selinux"  "8"  "postgresql" "dwalsh@redhat.com" "postgresql SELinux Policy documentation"
.SH "NAME"
postgresql_selinux \- Security Enhanced Linux Policy for the postgresql processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the postgresql processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  postgresql policy is extremely flexible and has several booleans that allow you to manipulate the policy and run postgresql with the tightest access possible.


.PP
If you want to allow users to connect to PostgreSQ, you must turn on the allow_user_postgresql_connect boolean.

.EX
.B setsebool -P allow_user_postgresql_connect 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux postgresql policy is very flexible allowing users to setup their postgresql processes in as secure a method as possible.
.PP 
The following file types are defined for postgresql:


.EX
.B postgresql_db_t 
.EE

- Set files with the postgresql_db_t type, if you want to treat the files as postgresql database content.

.br
Paths: 
/var/lib/pgsql/data(/.*)?, /usr/share/jonas/pgsql(/.*)?, /var/lib/postgres(ql)?(/.*)?, /var/lib/sepgsql(/.*)?, /usr/lib/pgsql/test/regress(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B postgresql_etc_t 
.EE

- Set files with the postgresql_etc_t type, if you want to store postgresql files in the /etc directories.

.br
Paths: 
/etc/sysconfig/pgsql(/.*)?, /etc/postgresql(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B postgresql_exec_t 
.EE

- Set files with the postgresql_exec_t type, if you want to transition an executable to the postgresql_t domain.

.br
Paths: 
/usr/bin/(se)?postgres, /usr/lib/postgresql/bin/.*, /usr/lib/pgsql/test/regress/pg_regress, /usr/bin/initdb(\.sepgsql)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B postgresql_initrc_exec_t 
.EE

- Set files with the postgresql_initrc_exec_t type, if you want to transition an executable to the postgresql_initrc_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B postgresql_lock_t 
.EE

- Set files with the postgresql_lock_t type, if you want to treat the files as postgresql lock data, stored under the /var/lock directory


.EX
.B postgresql_log_t 
.EE

- Set files with the postgresql_log_t type, if you want to treat the data as postgresql log data, usually stored under the /var/log directory.

.br
Paths: 
/var/lib/pgsql/logfile(/.*)?, /var/lib/pgsql/pgstartup\.log, /var/log/postgresql(/.*)?, /var/log/postgres\.log.*, /var/lib/sepgsql/pgstartup\.log, /var/log/rhdb/rhdb(/.*)?, /var/log/sepostgresql\.log.*
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B postgresql_tmp_t 
.EE

- Set files with the postgresql_tmp_t type, if you want to store postgresql temporary files in the /tmp directories.


.EX
.B postgresql_var_run_t 
.EE

- Set files with the postgresql_var_run_t type, if you want to store the postgresql files under the /run directory.

.br
Paths: 
/var/run/postmaster.*, /var/run/postgresql(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux postgresql policy is very flexible allowing users to setup their postgresql processes in as secure a method as possible.
.PP 
The following port types are defined for postgresql:
.EX

.B postgresql_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 5432
.EE
.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), postgresql(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)