.TH  "postfix_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "postfix Selinux Policy documentation"
.SH "NAME"
postfix_selinux \- Security Enhanced Linux Policy for the postfix processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the postfix processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux postfix policy is very flexible allowing users to setup their postfix processes in as secure a method as possible.
.PP 
The following file types are defined for postfix:


.EX
.B postfix_bounce_exec_t 
.EE

- Set files with the postfix_bounce_exec_t context, if you want to a executable to transition to the postfix_bounce_t domain.


.EX
.B postfix_bounce_tmp_t 
.EE

- Set files with the postfix_bounce_tmp_t context, if you want to store postfix bounce temporary files in the /tmp directories.


.EX
.B postfix_cleanup_exec_t 
.EE

- Set files with the postfix_cleanup_exec_t context, if you want to a executable to transition to the postfix_cleanup_t domain.


.EX
.B postfix_cleanup_tmp_t 
.EE

- Set files with the postfix_cleanup_tmp_t context, if you want to store postfix cleanup temporary files in the /tmp directories.


.EX
.B postfix_data_t 
.EE

- Set files with the postfix_data_t context, if you want to treat the files as postfix content.


.EX
.B postfix_etc_t 
.EE

- Set files with the postfix_etc_t context, if you want to store postfix files in the /etc directories.


.EX
.B postfix_exec_t 
.EE

- Set files with the postfix_exec_t context, if you want to a executable to transition to the postfix_t domain.


.EX
.B postfix_initrc_exec_t 
.EE

- Set files with the postfix_initrc_exec_t context, if you want to a executable to transition to the postfix_initrc_t domain.


.EX
.B postfix_keytab_t 
.EE

- Set files with the postfix_keytab_t context, if you want to treat the files as kerberos keytab files.


.EX
.B postfix_local_exec_t 
.EE

- Set files with the postfix_local_exec_t context, if you want to a executable to transition to the postfix_local_t domain.


.EX
.B postfix_local_tmp_t 
.EE

- Set files with the postfix_local_tmp_t context, if you want to store postfix local temporary files in the /tmp directories.


.EX
.B postfix_map_exec_t 
.EE

- Set files with the postfix_map_exec_t context, if you want to a executable to transition to the postfix_map_t domain.


.EX
.B postfix_map_tmp_t 
.EE

- Set files with the postfix_map_tmp_t context, if you want to store postfix map temporary files in the /tmp directories.


.EX
.B postfix_master_exec_t 
.EE

- Set files with the postfix_master_exec_t context, if you want to a executable to transition to the postfix_master_t domain.


.EX
.B postfix_pickup_exec_t 
.EE

- Set files with the postfix_pickup_exec_t context, if you want to a executable to transition to the postfix_pickup_t domain.


.EX
.B postfix_pickup_tmp_t 
.EE

- Set files with the postfix_pickup_tmp_t context, if you want to store postfix pickup temporary files in the /tmp directories.


.EX
.B postfix_pipe_exec_t 
.EE

- Set files with the postfix_pipe_exec_t context, if you want to a executable to transition to the postfix_pipe_t domain.


.EX
.B postfix_pipe_tmp_t 
.EE

- Set files with the postfix_pipe_tmp_t context, if you want to store postfix pipe temporary files in the /tmp directories.


.EX
.B postfix_postdrop_exec_t 
.EE

- Set files with the postfix_postdrop_exec_t context, if you want to a executable to transition to the postfix_postdrop_t domain.


.EX
.B postfix_postqueue_exec_t 
.EE

- Set files with the postfix_postqueue_exec_t context, if you want to a executable to transition to the postfix_postqueue_t domain.


.EX
.B postfix_private_t 
.EE

- Set files with the postfix_private_t context, if you want to treat the files as postfix private data.


.EX
.B postfix_prng_t 
.EE

- Set files with the postfix_prng_t context, if you want to treat the files as postfix prng data.


.EX
.B postfix_public_t 
.EE

- Set files with the postfix_public_t context, if you want to treat the files as postfix public data.


.EX
.B postfix_qmgr_exec_t 
.EE

- Set files with the postfix_qmgr_exec_t context, if you want to a executable to transition to the postfix_qmgr_t domain.


.EX
.B postfix_qmgr_tmp_t 
.EE

- Set files with the postfix_qmgr_tmp_t context, if you want to store postfix qmgr temporary files in the /tmp directories.


.EX
.B postfix_showq_exec_t 
.EE

- Set files with the postfix_showq_exec_t context, if you want to a executable to transition to the postfix_showq_t domain.


.EX
.B postfix_smtp_exec_t 
.EE

- Set files with the postfix_smtp_exec_t context, if you want to a executable to transition to the postfix_smtp_t domain.


.EX
.B postfix_smtp_tmp_t 
.EE

- Set files with the postfix_smtp_tmp_t context, if you want to store postfix smtp temporary files in the /tmp directories.


.EX
.B postfix_smtpd_exec_t 
.EE

- Set files with the postfix_smtpd_exec_t context, if you want to a executable to transition to the postfix_smtpd_t domain.


.EX
.B postfix_smtpd_tmp_t 
.EE

- Set files with the postfix_smtpd_tmp_t context, if you want to store postfix smtpd temporary files in the /tmp directories.


.EX
.B postfix_spool_bounce_t 
.EE

- Set files with the postfix_spool_bounce_t context, if you want to treat the files as postfix spool bounce data.


.EX
.B postfix_spool_flush_t 
.EE

- Set files with the postfix_spool_flush_t context, if you want to treat the files as postfix spool flush data.


.EX
.B postfix_spool_maildrop_t 
.EE

- Set files with the postfix_spool_maildrop_t context, if you want to treat the files as postfix spool maildrop data.


.EX
.B postfix_spool_t 
.EE

- Set files with the postfix_spool_t context, if you want to store the postfix files under the /var/spool directory.


.EX
.B postfix_var_run_t 
.EE

- Set files with the postfix_var_run_t context, if you want to store the postfix files under the /run directory.


.EX
.B postfix_virtual_exec_t 
.EE

- Set files with the postfix_virtual_exec_t context, if you want to a executable to transition to the postfix_virtual_t domain.


.EX
.B postfix_virtual_tmp_t 
.EE

- Set files with the postfix_virtual_tmp_t context, if you want to store postfix virtual temporary files in the /tmp directories.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  postfix policy is extremely flexible and has several booleans that allow you to manipulate the policy and run postfix with the tightest access possible.


.PP
If you want to allow postfix_local domain full write access to mail_spool directorie, you must turn on the allow_postfix_local_write_mail_spool boolean.

.EX
.B setsebool -P allow_postfix_local_write_mail_spool 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), postfix(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)