.TH  "pppd_selinux"  "8"  "pppd" "dwalsh@redhat.com" "pppd SELinux Policy documentation"
.SH "NAME"
pppd_selinux \- Security Enhanced Linux Policy for the pppd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the pppd processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  pppd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run pppd with the tightest access possible.


.PP
If you want to allow pppd to be run for a regular user, you must turn on the pppd_for_user boolean.

.EX
.B setsebool -P pppd_for_user 1
.EE

.PP
If you want to allow pppd to load kernel modules for certain modems, you must turn on the pppd_can_insmod boolean.

.EX
.B setsebool -P pppd_can_insmod 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the pppd_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the pppd_t, you must turn on the kerberos_enabled boolean.

.EX
setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux pppd policy is very flexible allowing users to setup their pppd processes in as secure a method as possible.
.PP 
The following file types are defined for pppd:


.EX
.PP
.B pppd_etc_rw_t 
.EE

- Set files with the pppd_etc_rw_t type, if you want to treat the files as pppd etc read/write content.

.br
.TP 5
Paths: 
/etc/ppp(/.*)?, /etc/ppp/resolv\.conf, /etc/ppp/peers(/.*)?

.EX
.PP
.B pppd_etc_t 
.EE

- Set files with the pppd_etc_t type, if you want to store pppd files in the /etc directories.

.br
.TP 5
Paths: 
/etc/ppp, /root/.ppprc

.EX
.PP
.B pppd_exec_t 
.EE

- Set files with the pppd_exec_t type, if you want to transition an executable to the pppd_t domain.

.br
.TP 5
Paths: 
/usr/sbin/pppd, /usr/sbin/ipppd, /usr/sbin/pppoe-server, /usr/sbin/ppp-watch, /sbin/pppoe-server, /sbin/ppp-watch

.EX
.PP
.B pppd_initrc_exec_t 
.EE

- Set files with the pppd_initrc_exec_t type, if you want to transition an executable to the pppd_initrc_t domain.

.br
.TP 5
Paths: 
/etc/rc\.d/init\.d/ppp, /etc/ppp/(auth|ip(v6|x)?)-(up|down)

.EX
.PP
.B pppd_lock_t 
.EE

- Set files with the pppd_lock_t type, if you want to treat the files as pppd lock data, stored under the /var/lock directory


.EX
.PP
.B pppd_log_t 
.EE

- Set files with the pppd_log_t type, if you want to treat the data as pppd log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/log/ppp(/.*)?, /var/log/ppp-connect-errors.*

.EX
.PP
.B pppd_secret_t 
.EE

- Set files with the pppd_secret_t type, if you want to treat the files as pppd se secret data.


.EX
.PP
.B pppd_tmp_t 
.EE

- Set files with the pppd_tmp_t type, if you want to store pppd temporary files in the /tmp directories.


.EX
.PP
.B pppd_unit_file_t 
.EE

- Set files with the pppd_unit_file_t type, if you want to treat the files as pppd unit content.


.EX
.PP
.B pppd_var_run_t 
.EE

- Set files with the pppd_var_run_t type, if you want to store the pppd files under the /run directory.

.br
.TP 5
Paths: 
/var/run/pppd[0-9]*\.tdb, /var/run/ppp(/.*)?, /var/run/(i)?ppp.*pid[^/]*

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux pppd policy is very flexible allowing users to setup their pppd processes in as secure a method as possible.
.PP 
The following process types are defined for pppd:

.EX
.B pppd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), pppd(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)