.TH  "pppd_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "pppd Selinux Policy documentation"
.SH "NAME"
pppd_selinux \- Security Enhanced Linux Policy for the pppd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the pppd processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux pppd policy is very flexible allowing users to setup their pppd processes in as secure a method as possible.
.PP 
The following file types are defined for pppd:


.EX
.B pppd_etc_rw_t 
.EE

- Set files with the pppd_etc_rw_t context, if you want to treat the files as pppd etc read/write content.


.EX
.B pppd_etc_t 
.EE

- Set files with the pppd_etc_t context, if you want to store pppd files in the /etc directories.


.EX
.B pppd_exec_t 
.EE

- Set files with the pppd_exec_t context, if you want to a executable to transition to the pppd_t domain.


.EX
.B pppd_initrc_exec_t 
.EE

- Set files with the pppd_initrc_exec_t context, if you want to a executable to transition to the pppd_initrc_t domain.


.EX
.B pppd_lock_t 
.EE

- Set files with the pppd_lock_t context, if you want to treat the files as pppd lock data.


.EX
.B pppd_log_t 
.EE

- Set files with the pppd_log_t context, if you want to treat the data as pppd log data, usually stored in /var/log.


.EX
.B pppd_secret_t 
.EE

- Set files with the pppd_secret_t context, if you want to treat the files as pppd se secret data.


.EX
.B pppd_tmp_t 
.EE

- Set files with the pppd_tmp_t context, if you want to store pppd temporary files in the /tmp directories.


.EX
.B pppd_unit_file_t 
.EE

- Set files with the pppd_unit_file_t context, if you want to treat the files as pppd unit content.


.EX
.B pppd_var_run_t 
.EE

- Set files with the pppd_var_run_t context, if you want to store the pppd files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  pppd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run pppd with the tightest access possible.


.PP
If you want to allow pppd to be run for a regular use, you must turn on the pppd_for_user boolean.

.EX
.B setsebool -P pppd_for_user 1
.EE

.PP
If you want to allow pppd to load kernel modules for certain modem, you must turn on the pppd_can_insmod boolean.

.EX
.B setsebool -P pppd_can_insmod 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), pppd(8), semanage(8), restorecon(8), chcon(1), setsebool(8)