.TH  "prelude_selinux"  "8"  "prelude" "dwalsh@redhat.com" "prelude SELinux Policy documentation"
.SH "NAME"
prelude_selinux \- Security Enhanced Linux Policy for the prelude processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the prelude processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux prelude policy is very flexible allowing users to setup their prelude processes in as secure a method as possible.
.PP 
The following file types are defined for prelude:


.EX
.B prelude_audisp_exec_t 
.EE

- Set files with the prelude_audisp_exec_t type, if you want to transition an executable to the prelude_audisp_t domain.

.br
Paths: 
/sbin/audisp-prelude, /usr/sbin/audisp-prelude
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_audisp_var_run_t 
.EE

- Set files with the prelude_audisp_var_run_t type, if you want to store the prelude audisp files under the /run directory.


.EX
.B prelude_correlator_config_t 
.EE

- Set files with the prelude_correlator_config_t type, if you want to treat the files as prelude correlator configuration data, usually stored under the /etc directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_correlator_exec_t 
.EE

- Set files with the prelude_correlator_exec_t type, if you want to transition an executable to the prelude_correlator_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_exec_t 
.EE

- Set files with the prelude_exec_t type, if you want to transition an executable to the prelude_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_initrc_exec_t 
.EE

- Set files with the prelude_initrc_exec_t type, if you want to transition an executable to the prelude_initrc_t domain.

.br
Paths: 
/etc/rc\.d/init\.d/prelude-correlator, /etc/rc\.d/init\.d/prelude-manager, /etc/rc\.d/init\.d/prelude-lml
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_lml_exec_t 
.EE

- Set files with the prelude_lml_exec_t type, if you want to transition an executable to the prelude_lml_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_lml_tmp_t 
.EE

- Set files with the prelude_lml_tmp_t type, if you want to store prelude lml temporary files in the /tmp directories.


.EX
.B prelude_lml_var_run_t 
.EE

- Set files with the prelude_lml_var_run_t type, if you want to store the prelude lml files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_log_t 
.EE

- Set files with the prelude_log_t type, if you want to treat the data as prelude log data, usually stored under the /var/log directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_spool_t 
.EE

- Set files with the prelude_spool_t type, if you want to store the prelude files under the /var/spool directory.

.br
Paths: 
/var/spool/prelude(/.*)?, /var/spool/prelude-manager(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_var_lib_t 
.EE

- Set files with the prelude_var_lib_t type, if you want to store the prelude files under the /var/lib directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B prelude_var_run_t 
.EE

- Set files with the prelude_var_run_t type, if you want to store the prelude files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux prelude policy is very flexible allowing users to setup their prelude processes in as secure a method as possible.
.PP 
The following port types are defined for prelude:
.EX

.B prelude_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 4690
.EE
.B udp 4690
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), prelude(8), semanage(8), restorecon(8), chcon(1)
