.TH  "prelink_selinux"  "8"  "prelink" "dwalsh@redhat.com" "prelink SELinux Policy documentation"
.SH "NAME"
prelink_selinux \- Security Enhanced Linux Policy for the prelink processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the prelink processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the prelink_cron_system_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the prelink_cron_system_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux prelink policy is very flexible allowing users to setup their prelink processes in as secure a method as possible.
.PP 
The following file types are defined for prelink:


.EX
.PP
.B prelink_cache_t 
.EE

- Set files with the prelink_cache_t type, if you want to store the files under the /var/cache directory.


.EX
.PP
.B prelink_cron_system_exec_t 
.EE

- Set files with the prelink_cron_system_exec_t type, if you want to transition an executable to the prelink_cron_system_t domain.


.EX
.PP
.B prelink_exec_t 
.EE

- Set files with the prelink_exec_t type, if you want to transition an executable to the prelink_t domain.


.EX
.PP
.B prelink_log_t 
.EE

- Set files with the prelink_log_t type, if you want to treat the data as prelink log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/log/prelink(/.*)?, /var/log/prelink\.log.*

.EX
.PP
.B prelink_tmp_t 
.EE

- Set files with the prelink_tmp_t type, if you want to store prelink temporary files in the /tmp directories.


.EX
.PP
.B prelink_tmpfs_t 
.EE

- Set files with the prelink_tmpfs_t type, if you want to store prelink files on a tmpfs file system.


.EX
.PP
.B prelink_var_lib_t 
.EE

- Set files with the prelink_var_lib_t type, if you want to store the prelink files under the /var/lib directory.

.br
.TP 5
Paths: 
/var/lib/prelink(/.*)?, /var/lib/misc/prelink.*

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux prelink policy is very flexible allowing users to setup their prelink processes in as secure a method as possible.
.PP 
The following process types are defined for prelink:

.EX
.B prelink_cron_system_t, prelink_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type prelink_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B exec_type


.br
.B ld_so_t

	/usr/(.*/)?lib(/.*)?/ld-[^/]*\.so(\.[^/]*)*
.br
	/lib/ld-[^/]*\.so(\.[^/]*)*
.br
	/usr/lib/ld-[^/]*\.so(\.[^/]*)*
.br
	/var/ftp/lib/ld[^/]*\.so(\.[^/]*)*
.br
	/emul/ia32-linux/lib(/.*)?/ld-[^/]*\.so(\.[^/]*)*
.br
	/emul/ia32-linux/usr(/.*)?/lib(/.*)?/ld-[^/]*\.so(\.[^/]*)*
.br
	/var/spool/postfix/lib/ld.*\.so.*
.br

.br
.B lib_t

	/lib/.*
.br
	/opt/.*\.so(\.[^/]*)*
.br
	/usr/.*\.so(\.[^/]*)*
.br
	/opt/(.*/)?lib(/.*)?
.br
	/usr/(.*/)?lib(/.*)?
.br
	/opt/(.*/)?jre/.+\.jar
.br
	/opt/(.*/)?java/.+\.jar
.br
	/usr/(.*/)?java/.+\.jar
.br
	/usr/(.*/)?java/.+\.jsa
.br
	/usr/lib/.*
.br
	/usr/lib/.*/program(/.*)?\.so
.br
	/var/ftp/lib(/.*)?
.br
	/opt/Acrobat[5-9]/Reader/intellinux/plugins/.*\.api
.br
	/opt/ibm/java.*/jre/.+\.jar
.br
	/usr/lib/pgsql/.*\.so.*
.br
	/usr/lib/xfce4/.*\.so.*
.br
	/opt/Adobe/Reader.?/Reader/intellinux/SPPlugins/.*\.ap[il]
.br
	/emul/ia32-linux/lib(/.*)?
.br
	/emul/ia32-linux/usr(/.*)?/lib(/.*)?
.br
	/emul/ia32-linux/usr(/.*)?/java/.*\.jar
.br
	/emul/ia32-linux/usr(/.*)?/java/.*\.jsa
.br
	/emul/ia32-linux/usr(/.*)?/java/.+\.so(\.[^/]*)*
.br
	/var/spool/postfix/lib(/.*)?
.br
	/var/spool/postfix/usr(/.*)?
.br
	/var/mailman/pythonlib(/.*)?/.+\.so(\..*)?
.br
	/var/spool/postfix/lib64(/.*)?
.br
	/usr/lib/nspluginwrapper/np.*\.so
.br
	/usr/lib/pgsql/test/regress/.*\.so.*
.br
	/usr/share/hplip/prnt/plugins(/.*)?
.br
	/var/lib/spamassassin/compiled/.*\.so.*
.br
	/lib
.br
	/lib64
.br
	/usr/lib
.br
	/etc/ppp/plugins/rp-pppoe\.so
.br
	/usr/share/rhn/rhn_applet/eggtrayiconmodule\.so
.br

.br
.B mozilla_plugin_rw_t

	/usr/lib/mozilla/plugins-wrapped(/.*)?
.br

.br
.B prelink_cache_t

	/etc/prelink\.cache
.br

.br
.B prelink_object


.br
.B prelink_tmp_t


.br
.B prelink_tmpfs_t


.br
.B prelink_var_lib_t

	/var/lib/prelink(/.*)?
.br
	/var/lib/misc/prelink.*
.br

.br
.B rpm_tmp_t


.br
.B textrel_shlib_t

	/usr/(.*/)?nprhapengine\.so.*
.br
	/usr/(.*/)?nvidia/.+\.so(\..*)?
.br
	/usr/(.*/)?java/.+\.so(\.[^/]*)*
.br
	/opt/(.*/)?jre.*/.+\.so(\.[^/]*)*
.br
	/usr/(.*/)?jre.*/.*\.so(\.[^/]*)*
.br
	/opt/(.*/)?oracle/(.*/)?libnnz.*\.so
.br
	/opt/(.*/)?/RealPlayer/.+\.so(\.[^/]*)*
.br
	/usr/(.*/)?/RealPlayer/.+\.so(\.[^/]*)*
.br
	/usr/(.*/)?/HelixPlayer/.+\.so(\.[^/]*)*
.br
	/usr/(.*/)?lib(64)?(/.*)?/nvidia/.+\.so(\..*)?
.br
	/usr/(.*/)?intellinux/SPPlugins/ADMPlugin\.apl
.br
	/usr/(.*/)?pcsc/drivers(/.*)?/lib(cm2020|cm4000|SCR24x)\.so(\.[^/]*)*
.br
	/opt/cx.*/lib/wine/.+\.so
.br
	/usr/lib.*/libmpg123\.so(\.[^/]*)*
.br
	/usr/lib(/.*)?/nvidia/.+\.so(\..*)?
.br
	/usr/lib(/.*)?/libnvidia.+\.so(\.[^/]*)*
.br
	/usr/lib(/.*)?/nvidia_drv.*\.so(\.[^/]*)*
.br
	/usr/lib/.*/nprhapengine\.so.*
.br
	/usr/lib/.*/libflashplayer\.so.*
.br
	/usr/lib/(sse2/)?libfame-.*\.so.*
.br
	/usr/lib/.*/program/libsoffice\.so
.br
	/usr/lib/.*/program/libsts645li\.so
.br
	/usr/lib/.*/program/libwrp645li\.so
.br
	/usr/lib/.*/program/libswd680li\.so
.br
	/usr/lib/.*/program/libsvx680li\.so
.br
	/usr/lib/.*/program/libicudata\.so.*
.br
	/usr/lib/(.*/)?jre.*/.*\.so(\.[^/]*)*
.br
	/usr/lib/.*/program/librecentfile\.so
.br
	/usr/lib/.*/program/libcomphelp4gcc3\.so
.br
	/usr/lib/.*/program/libvclplug_gen645li\.so
.br
	/usr/lib/(virtualbox(-ose)?/)?(components/)?VBox.*\.so
.br
	/opt/Adobe.*/libcurl\.so
.br
	/opt/Adobe(/.*?)/nppdf\.so
.br
	/usr/Adobe/.*\.api
.br
	/opt/matlab.*\.so(\.[^/]*)*
.br
	/usr/matlab.*\.so(\.[^/]*)*
.br
	/usr/Adobe/(.*/)?intellinux/nppdf\.so
.br
	/usr/Adobe/(.*/)?intellinux/sidecars/*
.br
	/usr/Adobe/(.*/)?lib/[^/]*\.so(\.[^/]*)*
.br
	/usr/matlab.*/bin/glnx86/libmwlapack\.so
.br
	/usr/matlab.*/sys/os/glnx86/libtermcap\.so
.br
	/usr/matlab.*/bin/glnx86/(libmw(lapack|mathutil|services)|lapack|libmkl)\.so
.br
	/opt/google/.*\.so.*
.br
	/opt/altera9.1/quartus/linux/libccl_err\.so
.br
	/usr/lib/nsr/(.*/)?.*\.so
.br
	/opt/ibm/java.*/jre/.+\.so(\.[^/]*)*
.br
	/opt/ibm/java.*/jre/bin/.+\.so(\.[^/]*)*
.br
	/opt/netbeans(.*/)?jdk.*/linux/.+\.so(\.[^/]*)*
.br
	/usr/lib/wine/.+\.so
.br
	/usr/lib/sse2/.*\.so.*
.br
	/usr/lib/i686/.*\.so.*
.br
	/usr/lib/libav.*\.so(\.[^/]*)*
.br
	/usr/acroread/(.*/)?intellinux/nppdf\.so
.br
	/usr/acroread/(.*/)?lib/[^/]*\.so(\.[^/]*)*
.br
	/usr/lib/libADM.*\.so.*
.br
	/opt/lampp/lib/.*\.so.*
.br
	/usr/lib/libGTL.*\.so.*
.br
	/usr/lib/win32/.*\.so(\.[^/]*)*
.br
	/usr/lib/fglrx/.*\.so(\.[^/]*)*
.br
	/usr/lib/nvidia.*\.so(\.[^/]*)*
.br
	/opt/VirtualBox(/.*)?/VBox.*\.so
.br
	/usr/lib/python.*/site-packages/pymedia/muxer\.so
.br
	/usr/lib/libmyth[^/]+\.so.*
.br
	/usr/lib/midori/.*\.so(\.[^/]*)*
.br
	/usr/lib/cedega/.+\.so(\.[^/]*)*
.br
	/usr/lib/libADM5.*\.so(\.[^/]*)*
.br
	/usr/lib/vmware/(.*/)?VmPerl\.so
.br
	/usr/lib/oracle/.*/lib/libnnz10\.so
.br
	/usr/lib/oracle/.*/lib/libnnz.*\.so
.br
	/usr/lib/oracle/.*/lib/libclntsh\.so(\.[^/]*)*
.br
	/usr/lib/python2.4/site-packages/M2Crypto/__m2crypto\.so
.br
	/usr/lib/libjs\.so.*
.br
	/usr/lib/libGL\.so(\.[^/]*)*
.br
	/usr/libmpg123\.so(\.[^/]*)*
.br
	/usr/lib/libnnz11.so(\.[^/]*)*
.br
	/opt/local/matlab.*\.so(\.[^/]*)*
.br
	/opt/lgtonmc/bin/.*\.so(\.[0-9])?
.br
	/usr/lib/allegro/(.*/)?alleg-vga\.so
.br
	/usr/lib/jvm/java(.*/)bin(/.*)?/.*\.so
.br
	/usr/lib/firefox-[^/]*/plugins/nppdf.so
.br
	/opt/Adobe/Reader.?/Reader/intellinux/plug_ins/.*\.api
.br
	/usr/lib/firefox-[^/]*/extensions(/.*)?/libqfaservices.so
.br
	/usr/lib/acroread/.+\.api
.br
	/usr/google-earth/.*\.so.*
.br
	/opt/google-earth/.*\.so.*
.br
	/usr/lib/acroread/(.*/)?nppdf\.so
.br
	/usr/lib/acroread/(.*/)?sidecars/*
.br
	/usr/lib/acroread/(.*/)?ADMPlugin\.apl
.br
	/usr/lib/acroread/(.*/)?lib/[^/]*\.so(\.[^/]*)*
.br
	/usr/lib/libFLAC\.so.*
.br
	/usr/lib/libgpac\.so.*
.br
	/opt/google/picasa/.*\.dll
.br
	/opt/google/picasa/.*\.yti
.br
	/opt/google/chrome/.*\.so.*
.br
	/usr/lib/libzvbi\.so(\.[^/]*)*
.br
	/usr/lib/libx264\.so(\.[^/]*)*
.br
	/usr/lib/ati-fglrx/.+\.so(\..*)?
.br
	/usr/lib/gstreamer-.*/[^/]*\.so.*
.br
	/usr/lib/ICAClient/.*\.so(\.[^/]*)*
.br
	/usr/lib/vmware/lib(/.*)?/HConfig\.so
.br
	/usr/lib/codecs/drv[1-9c]\.so(\.[^/]*)*
.br
	/usr/lib/vmware/lib(/.*)?/libgdk-x11-.*\.so.*
.br
	/usr/lib/vmware/lib(/.*)?/libvmware-gksu.*\.so.*
.br
	/usr/lib/libmpeg2\.so.*
.br
	/usr/lib/valgrind/vg.*\.so
.br
	/usr/lib/virtualbox/.*\.so
.br
	/usr/lib/libglide3-v[0-9]*\.so.*
.br
	/usr/lib/libglide3\.so.*
.br
	/usr/lib/libHermes\.so.*
.br
	/usr/lib/libdvdcss\.so.*
.br
	/usr/lib/libGLcore\.so.*
.br
	/usr/lib/googleearth/.*\.so.*
.br
	/usr/NX/lib/libjpeg\.so.*
.br
	/usr/lib/nx/libjpeg\.so.*
.br
	/usr/lib/libswscale\.so.*
.br
	/usr/lib/libmp3lame\.so.*
.br
	/usr/lib/nmm/liba52\.so.*
.br
	/usr/lib/xine/plugins/.+\.so
.br
	/usr/lib/google-earth/.*\.so.*
.br
	/usr/lib/helix/codecs/[^/]*\.so
.br
	/usr/lib/xorg/libGL\.so(\.[^/]*)*
.br
	/usr/X11R6/lib/libGL\.so.*
.br
	/usr/NX/lib/libXcomp\.so.*
.br
	/usr/lib/nx/libXcomp\.so.*
.br
	/usr/lib/libxvidcore\.so.*
.br
	/usr/lib/libpostproc\.so.*
.br
	/opt/lampp/lib/libct\.so.*
.br
	/opt/google/talkplugin/.*\.so.*
.br
	/usr/lib/helix/plugins/[^/]*\.so
.br
	/usr/lib/libatiadlxx\.so(\.[^/]*)*
.br
	/opt/VBoxGuestAdditions.*/lib/VBox.*\.so
.br
	/usr/lib/mythtv/filters/.*\.so.*
.br
	/usr/lib/libtfmessbsp\.so(\.[^/]*)*
.br
	/usr/lib/sse2/libx264\.so(\.[^/]*)*
.br
	/usr/lib/nvidia-graphics(-[^/]*/)?libXvMCNVIDIA\.so.*
.br
	/usr/lib/nvidia-graphics(-[^/]*/)?libnvidia.*\.so(\.[^/]*)*
.br
	/usr/lib/nvidia-graphics(-[^/]*/)?libGL(core)?\.so(\.[^/]*)*
.br
	/usr/lib/libsipphoneapi\.so.*
.br
	/usr/lib/libfglrx_gamma\.so.*
.br
	/usr/lib/chromium-browser/.*\.so
.br
	/usr/lib/catalyst/libGL\.so(\.[^/]*)*
.br
	/usr/lib/yafaray/libDarkSky.so
.br
	/opt/real/RealPlayer/codecs(/.*)?
.br
	/usr/lib/libcncpmslld328\.so(\.[^/]*)*
.br
	/opt/real/RealPlayer/plugins(/.*)?
.br
	/usr/lib/libkmplayercommon\.so.*
.br
	/usr/lib/libjavascriptcoregtk[^/]*\.so.*
.br
	/usr/games/darwinia/lib/libSDL.*\.so.*
.br
	/usr/lib/altivec/libavcodec\.so(\.[^/]*)*
.br
	/usr/lib/xorg/modules/glesx\.so(\.[^/]*)*
.br
	/usr/X11R6/lib/libXvMCNVIDIA\.so.*
.br
	/usr/lib/sane/libsane-epkowa\.so.*
.br
	/opt/AutoScan/usr/lib/libvte\.so.*
.br
	/usr/X11R6/lib/libfglrx_gamma\.so.*
.br
	/usr/lib/nero/plug-ins/libMP3\.so(\.[^/]*)*
.br
	/usr/lib/vdpau/libvdpau_nvidia\.so.*
.br
	/usr/lib/ADM_plugins/videoFilter/.*\.so(\.[^/]*)*
.br
	/opt/Unify/SQLBase/libgptsblmsui11\.so.*
.br
	/usr/share/squeezeboxserver/CPAN/arch/.+\.so
.br
	/opt/f-secure/fspms/libexec/librapi\.so(\.[^/]*)*
.br
	/usr/lib/xorg/modules/extensions/nvidia(-[^/]*)?/libglx\.so(\.[^/]*)*
.br
	/opt/Komodo-Edit-5/lib/python/lib/python2.6/lib-dynload/.*\.so(\.[^/]*)*
.br
	/usr/lib/xorg/modules/drivers/fglrx_drv\.so(\.[^/]*)*
.br
	/usr/lib/xorg/modules/extensions/libglx\.so(\.[^/]*)*
.br
	/usr/x11R6/lib/modules/extensions/libglx\.so(\.[^/]*)*
.br
	/usr/bin/bsnes
.br
	/usr/lib/VBoxVMM\.so
.br
	/usr/lib/valgrind/hp2ps
.br
	/usr/lib/libmlib_jai\.so
.br
	/usr/lib/valgrind/stage2
.br
	/lib/security/pam_poldi\.so
.br
	/usr/lib/libg\+\+\.so\.2\.7\.2\.8
.br
	/usr/lib/ladspa/gsm_1215\.so
.br
	/usr/lib/ladspa/sc1_1425\.so
.br
	/usr/lib/ladspa/sc2_1426\.so
.br
	/usr/lib/ladspa/sc3_1427\.so
.br
	/usr/lib/ladspa/sc4_1882\.so
.br
	/usr/lib/ladspa/se4_1883\.so
.br
	/usr/lib/libdivxdecore\.so\.0
.br
	/usr/lib/libdivxencore\.so\.0
.br
	/usr/lib/libstdc\+\+\.so\.2\.7\.2\.8
.br
	/usr/lib/ladspa/gverb_1216\.so
.br
	/usr/lib/security/pam_poldi\.so
.br
	/usr/lib/ladspa/fm_osc_1415\.so
.br
	/usr/zend/lib/apache2/libphp5\.so
.br
	/usr/lib/mozilla/plugins/nppdf\.so
.br
	/usr/lib/ladspa/notch_iir_1894\.so
.br
	/usr/lib/xchat/plugins/systray\.so
.br
	/usr/lib/ocaml/stublibs/dllnums\.so
.br
	/usr/lib/vlc/codec/libdmo_plugin\.so
.br
	/usr/lib/ladspa/butterworth_1902\.so
.br
	/usr/lib/ladspa/lowpass_iir_1891\.so
.br
	/usr/lib/ladspa/pitch_scale_1193\.so
.br
	/usr/lib/ladspa/pitch_scale_1194\.so
.br
	/usr/lib/ladspa/analogue_osc_1416\.so
.br
	/usr/lib/ladspa/bandpass_iir_1892\.so
.br
	/usr/lib/ladspa/highpass_iir_1890\.so
.br
	/usr/Zend/lib/ZendExtensionManager\.so
.br
	/opt/cisco-vpnclient/lib/libvpnapi\.so
.br
	/usr/lib/firefox/plugins/libractrl\.so
.br
	/usr/lib/ladspa/hermes_filter_1200\.so
.br
	/usr/lib/ladspa/bandpass_a_iir_1893\.so
.br
	/usr/lib/octagaplayer/libapplication\.so
.br
	/usr/lib/mozilla/plugins/libvlcplugin\.so
.br
	/usr/lib/vlc/codec/librealvideo_plugin\.so
.br
	/usr/lib/vlc/codec/librealaudio_plugin\.so
.br
	/usr/lib/xorg/modules/drivers/nvidia_drv\.o
.br
	/opt/novell/groupwise/client/lib/libgwapijni\.so\.1
.br
	/usr/lib/vlc/video_chroma/libi420_rgb_mmx_plugin\.so
.br
	/home/[^/]*/.*/plugins/nppdf\.so.*
.br

.br
.B user_home_type

	all user home files
.br

.br
.B usr_t

	/usr/.*
.br
	/opt/.*
.br
	/emul/.*
.br
	/export(/.*)?
.br
	/usr/doc(/.*)?/lib(/.*)?
.br
	/usr/inclu.e(/.*)?
.br
	/usr/share/doc(/.*)?/README.*
.br
	/usr
.br
	/opt
.br
	/emul
.br

.br
.B var_t

	/nsr(/.*)?
.br
	/var/.*
.br
	/srv/.*
.br
	/var
.br
	/srv
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), prelink(8), semanage(8), restorecon(8), chcon(1)
, prelink_cron_system_selinux(8)