.TH  "ptal_selinux"  "8"  "ptal" "dwalsh@redhat.com" "ptal SELinux Policy documentation"
.SH "NAME"
ptal_selinux \- Security Enhanced Linux Policy for the ptal processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ptal processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux ptal policy is very flexible allowing users to setup their ptal processes in as secure a method as possible.
.PP 
The following file types are defined for ptal:


.EX
.B ptal_etc_t 
.EE

- Set files with the ptal_etc_t context, if you want to store ptal files in the /etc directories.


.EX
.B ptal_exec_t 
.EE

- Set files with the ptal_exec_t context, if you want to a executable to transition to the ptal_t domain.

.br
Paths: 
/usr/sbin/ptal-photod, /usr/sbin/ptal-mlcd, /usr/sbin/ptal-printd

.EX
.B ptal_var_run_t 
.EE

- Set files with the ptal_var_run_t context, if you want to store the ptal files under the /run directory.

.br
Paths: 
/var/run/ptal-mlcd(/.*)?, /var/run/ptal-printd(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), ptal(8), semanage(8), restorecon(8), chcon(1)
