.TH  "ptal_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "ptal Selinux Policy documentation"
.SH "NAME"
ptal_selinux \- Security Enhanced Linux Policy for the ptal processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ptal processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux ptal policy is very flexible allowing users to setup their ptal processes in as secure a method as possible.
.PP 
The following file types are defined for ptal:


.EX
.B ptal_etc_t 
.EE

- Set files with the ptal_etc_t context, if you want to store ptal files in the /etc directories.


.EX
.B ptal_exec_t 
.EE

- Set files with the ptal_exec_t context, if you want to a executable to transition to the ptal_t domain.


.EX
.B ptal_var_run_t 
.EE

- Set files with the ptal_var_run_t context, if you want to store the ptal files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  ptal policy is extremely flexible and has several booleans that allow you to manipulate the policy and run ptal with the tightest access possible.


.PP
If you want to allow dhcpc client applications to execute iptables commands, you must turn on the dhcpc_exec_iptables boolean.

.EX
.B setsebool -P dhcpc_exec_iptables 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), ptal(8), semanage(8), restorecon(8), chcon(1), setsebool(8)