.TH  "pulseaudio_selinux"  "8"  "pulseaudio" "dwalsh@redhat.com" "pulseaudio SELinux Policy documentation"
.SH "NAME"
pulseaudio_selinux \- Security Enhanced Linux Policy for the pulseaudio processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the pulseaudio processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the pulseaudio_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the pulseaudio_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux pulseaudio policy is very flexible allowing users to setup their pulseaudio processes in as secure a method as possible.
.PP 
The following file types are defined for pulseaudio:


.EX
.PP
.B pulseaudio_exec_t 
.EE

- Set files with the pulseaudio_exec_t type, if you want to transition an executable to the pulseaudio_t domain.


.EX
.PP
.B pulseaudio_home_t 
.EE

- Set files with the pulseaudio_home_t type, if you want to store pulseaudio files in the users home directory.

.br
.TP 5
Paths: 
/root/\.pulse-cookie, /root/\.pulse(/.*)?, /root/\.esd_auth

.EX
.PP
.B pulseaudio_tmpfs_t 
.EE

- Set files with the pulseaudio_tmpfs_t type, if you want to store pulseaudio files on a tmpfs file system.


.EX
.PP
.B pulseaudio_var_lib_t 
.EE

- Set files with the pulseaudio_var_lib_t type, if you want to store the pulseaudio files under the /var/lib directory.


.EX
.PP
.B pulseaudio_var_run_t 
.EE

- Set files with the pulseaudio_var_run_t type, if you want to store the pulseaudio files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux pulseaudio policy is very flexible allowing users to setup their pulseaudio processes in as secure a method as possible.
.PP 
The following port types are defined for pulseaudio:

.EX
.TP 5
.B pulseaudio_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 4713
.EE
udp 4713
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux pulseaudio policy is very flexible allowing users to setup their pulseaudio processes in as secure a method as possible.
.PP 
The following process types are defined for pulseaudio:

.EX
.B pulseaudio_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type pulseaudio_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B anon_inodefs_t


.br
.B gstreamer_home_t

	/var/run/user/[^/]*/\.orc(/.*)?
.br
	/root/\.gstreamer-.*
.br
	/home/[^/]*/\.orc(/.*)?
.br
	/home/[^/]*/\.gstreamer-.*
.br
	/home/[^/]*/\.grl-bookmarks
.br
	/home/[^/]*/\.grl-bookmarks
.br
	/home/[^/]*/\.grl-metadata-store
.br

.br
.B pulseaudio_home_t

	/root/\.pulse(/.*)?
.br
	/root/\.esd_auth
.br
	/root/\.pulse-cookie
.br
	/home/[^/]*/\.pulse(/.*)?
.br
	/home/[^/]*/\.esd_auth
.br
	/home/[^/]*/\.pulse-cookie
.br

.br
.B pulseaudio_var_lib_t

	/var/lib/pulse(/.*)?
.br

.br
.B pulseaudio_var_run_t

	/var/run/pulse(/.*)?
.br

.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br

.br
.B user_tmp_type

	all user tmp files
.br

.br
.B user_tmpfs_type

	all user content in tmpfs file systems
.br

.br
.B virt_tmpfs_type


.br
.B xdm_tmp_t

	/tmp/\.X11-unix(/.*)?
.br
	/tmp/\.ICE-unix(/.*)?
.br
	/tmp/\.X0-lock
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), pulseaudio(8), semanage(8), restorecon(8), chcon(1)
