.TH  "pulseaudio_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "pulseaudio Selinux Policy documentation"
.SH "NAME"
pulseaudio_selinux \- Security Enhanced Linux Policy for the pulseaudio processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the pulseaudio processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux pulseaudio policy is very flexible allowing users to setup their pulseaudio processes in as secure a method as possible.
.PP 
The following file types are defined for pulseaudio:


.EX
.B pulseaudio_exec_t 
.EE

- Set files with the pulseaudio_exec_t context, if you want to a executable to transition to the pulseaudio_t domain.


.EX
.B pulseaudio_home_t 
.EE

- Set files with the pulseaudio_home_t context, if you want to store pulseaudio files in the users home directory.


.EX
.B pulseaudio_tmpfs_t 
.EE

- Set files with the pulseaudio_tmpfs_t context, if you want to store pulseaudio files on a tmpfs file system.


.EX
.B pulseaudio_var_lib_t 
.EE

- Set files with the pulseaudio_var_lib_t context, if you want to store the pulseaudio files under the /var/lib directory.


.EX
.B pulseaudio_var_run_t 
.EE

- Set files with the pulseaudio_var_run_t context, if you want to store the pulseaudio files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), pulseaudio(8), semanage(8), restorecon(8), chcon(1)