.TH  "puppet_selinux"  "8"  "puppet" "dwalsh@redhat.com" "puppet Selinux Policy documentation"
.SH "NAME"
puppet_selinux \- Security Enhanced Linux Policy for the puppet processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the puppet processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux puppet policy is very flexible allowing users to setup their puppet processes in as secure a method as possible.
.PP 
The following file types are defined for puppet:


.EX
.B puppet_etc_t 
.EE

- Set files with the puppet_etc_t context, if you want to store puppet files in the /etc directories.

.br
Path: 
/etc/puppet(/.*)?

.EX
.B puppet_exec_t 
.EE

- Set files with the puppet_exec_t context, if you want to a executable to transition to the puppet_t domain.

.br
Path: 
/usr/sbin/puppetd

.EX
.B puppet_initrc_exec_t 
.EE

- Set files with the puppet_initrc_exec_t context, if you want to a executable to transition to the puppet_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/puppet

.EX
.B puppet_log_t 
.EE

- Set files with the puppet_log_t context, if you want to treat the data as puppet log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/puppet(/.*)?

.EX
.B puppet_tmp_t 
.EE

- Set files with the puppet_tmp_t context, if you want to store puppet temporary files in the /tmp directories.


.EX
.B puppet_var_lib_t 
.EE

- Set files with the puppet_var_lib_t context, if you want to store the puppet files under the /var/lib directory.

.br
Path: 
/var/lib/puppet(/.*)?

.EX
.B puppet_var_run_t 
.EE

- Set files with the puppet_var_run_t context, if you want to store the puppet files under the /run directory.

.br
Path: 
/var/run/puppet(/.*)?

.EX
.B puppetca_exec_t 
.EE

- Set files with the puppetca_exec_t context, if you want to a executable to transition to the puppetca_t domain.

.br
Path: 
/usr/sbin/puppetca

.EX
.B puppetmaster_exec_t 
.EE

- Set files with the puppetmaster_exec_t context, if you want to a executable to transition to the puppetmaster_t domain.

.br
Path: 
/usr/sbin/puppetmasterd

.EX
.B puppetmaster_initrc_exec_t 
.EE

- Set files with the puppetmaster_initrc_exec_t context, if you want to a executable to transition to the puppetmaster_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/puppetmaster

.EX
.B puppetmaster_tmp_t 
.EE

- Set files with the puppetmaster_tmp_t context, if you want to store puppetmaster temporary files in the /tmp directories.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  puppet policy is extremely flexible and has several booleans that allow you to manipulate the policy and run puppet with the tightest access possible.


.PP
If you want to allow Puppet client to manage all file types, you must turn on the puppet_manage_all_files boolean.

.EX
.B setsebool -P puppet_manage_all_files 1
.EE

.PP
If you want to allow Puppet master to use connect to MySQL and PostgreSQL databas, you must turn on the puppetmaster_use_db boolean.

.EX
.B setsebool -P puppetmaster_use_db 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), puppet(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)