.TH  "puppet_selinux"  "8"  "puppet" "dwalsh@redhat.com" "puppet SELinux Policy documentation"
.SH "NAME"
puppet_selinux \- Security Enhanced Linux Policy for the puppet processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the puppet processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  puppet policy is extremely flexible and has several booleans that allow you to manipulate the policy and run puppet with the tightest access possible.


.PP
If you want to allow Puppet client to manage all file types, you must turn on the puppet_manage_all_files boolean.

.EX
.B setsebool -P puppet_manage_all_files 1
.EE

.PP
If you want to allow Puppet master to use connect to MySQL and PostgreSQL database, you must turn on the puppetmaster_use_db boolean.

.EX
.B setsebool -P puppetmaster_use_db 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the puppetmaster_t, puppet_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the puppetmaster_t, puppet_t, you must turn on the kerberos_enabled boolean.

.EX
setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux puppet policy is very flexible allowing users to setup their puppet processes in as secure a method as possible.
.PP 
The following file types are defined for puppet:


.EX
.PP
.B puppet_etc_t 
.EE

- Set files with the puppet_etc_t type, if you want to store puppet files in the /etc directories.


.EX
.PP
.B puppet_exec_t 
.EE

- Set files with the puppet_exec_t type, if you want to transition an executable to the puppet_t domain.


.EX
.PP
.B puppet_initrc_exec_t 
.EE

- Set files with the puppet_initrc_exec_t type, if you want to transition an executable to the puppet_initrc_t domain.


.EX
.PP
.B puppet_log_t 
.EE

- Set files with the puppet_log_t type, if you want to treat the data as puppet log data, usually stored under the /var/log directory.


.EX
.PP
.B puppet_tmp_t 
.EE

- Set files with the puppet_tmp_t type, if you want to store puppet temporary files in the /tmp directories.


.EX
.PP
.B puppet_var_lib_t 
.EE

- Set files with the puppet_var_lib_t type, if you want to store the puppet files under the /var/lib directory.


.EX
.PP
.B puppet_var_run_t 
.EE

- Set files with the puppet_var_run_t type, if you want to store the puppet files under the /run directory.


.EX
.PP
.B puppetca_exec_t 
.EE

- Set files with the puppetca_exec_t type, if you want to transition an executable to the puppetca_t domain.


.EX
.PP
.B puppetmaster_exec_t 
.EE

- Set files with the puppetmaster_exec_t type, if you want to transition an executable to the puppetmaster_t domain.


.EX
.PP
.B puppetmaster_initrc_exec_t 
.EE

- Set files with the puppetmaster_initrc_exec_t type, if you want to transition an executable to the puppetmaster_initrc_t domain.


.EX
.PP
.B puppetmaster_tmp_t 
.EE

- Set files with the puppetmaster_tmp_t type, if you want to store puppetmaster temporary files in the /tmp directories.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux puppet policy is very flexible allowing users to setup their puppet processes in as secure a method as possible.
.PP 
The following port types are defined for puppet:

.EX
.TP 5
.B puppet_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8140
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux puppet policy is very flexible allowing users to setup their puppet processes in as secure a method as possible.
.PP 
The following process types are defined for puppet:

.EX
.B puppet_t, puppetmaster_t, puppetca_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), puppet(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)