.TH  "qmail_selinux"  "8"  "qmail" "dwalsh@redhat.com" "qmail Selinux Policy documentation"
.SH "NAME"
qmail_selinux \- Security Enhanced Linux Policy for the qmail processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the qmail processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux qmail policy is very flexible allowing users to setup their qmail processes in as secure a method as possible.
.PP 
The following file types are defined for qmail:


.EX
.B qmail_alias_home_t 
.EE

- Set files with the qmail_alias_home_t context, if you want to store qmail alias files in the users home directory.

.br
Paths: 
/var/qmail/alias, /var/qmail/alias(/.*)?

.EX
.B qmail_clean_exec_t 
.EE

- Set files with the qmail_clean_exec_t context, if you want to a executable to transition to the qmail_clean_t domain.

.br
Path: 
/var/qmail/bin/qmail-clean

.EX
.B qmail_etc_t 
.EE

- Set files with the qmail_etc_t context, if you want to store qmail files in the /etc directories.

.br
Paths: 
/var/qmail/owners(/.*)?, /var/qmail/control(/.*)?

.EX
.B qmail_exec_t 
.EE

- Set files with the qmail_exec_t context, if you want to a executable to transition to the qmail_t domain.

.br
Path: 
/var/qmail/bin/qmail-getpw

.EX
.B qmail_inject_exec_t 
.EE

- Set files with the qmail_inject_exec_t context, if you want to a executable to transition to the qmail_inject_t domain.

.br
Path: 
/var/qmail/bin/qmail-inject

.EX
.B qmail_keytab_t 
.EE

- Set files with the qmail_keytab_t context, if you want to treat the files as kerberos keytab files.


.EX
.B qmail_local_exec_t 
.EE

- Set files with the qmail_local_exec_t context, if you want to a executable to transition to the qmail_local_t domain.

.br
Path: 
/var/qmail/bin/qmail-local

.EX
.B qmail_lspawn_exec_t 
.EE

- Set files with the qmail_lspawn_exec_t context, if you want to a executable to transition to the qmail_lspawn_t domain.

.br
Path: 
/var/qmail/bin/qmail-lspawn

.EX
.B qmail_queue_exec_t 
.EE

- Set files with the qmail_queue_exec_t context, if you want to a executable to transition to the qmail_queue_t domain.

.br
Path: 
/var/qmail/bin/qmail-queue

.EX
.B qmail_remote_exec_t 
.EE

- Set files with the qmail_remote_exec_t context, if you want to a executable to transition to the qmail_remote_t domain.

.br
Path: 
/var/qmail/bin/qmail-remote

.EX
.B qmail_rspawn_exec_t 
.EE

- Set files with the qmail_rspawn_exec_t context, if you want to a executable to transition to the qmail_rspawn_t domain.

.br
Path: 
/var/qmail/bin/qmail-rspawn

.EX
.B qmail_send_exec_t 
.EE

- Set files with the qmail_send_exec_t context, if you want to a executable to transition to the qmail_send_t domain.

.br
Path: 
/var/qmail/bin/qmail-send

.EX
.B qmail_smtpd_exec_t 
.EE

- Set files with the qmail_smtpd_exec_t context, if you want to a executable to transition to the qmail_smtpd_t domain.

.br
Path: 
/var/qmail/bin/qmail-smtpd

.EX
.B qmail_splogger_exec_t 
.EE

- Set files with the qmail_splogger_exec_t context, if you want to a executable to transition to the qmail_splogger_t domain.

.br
Path: 
/var/qmail/bin/splogger

.EX
.B qmail_spool_t 
.EE

- Set files with the qmail_spool_t context, if you want to store the qmail files under the /var/spool directory.

.br
Path: 
/var/qmail/queue(/.*)?

.EX
.B qmail_start_exec_t 
.EE

- Set files with the qmail_start_exec_t context, if you want to a executable to transition to the qmail_start_t domain.

.br
Path: 
/var/qmail/bin/qmail-start

.EX
.B qmail_tcp_env_exec_t 
.EE

- Set files with the qmail_tcp_env_exec_t context, if you want to a executable to transition to the qmail_tcp_env_t domain.

.br
Path: 
/var/qmail/bin/tcp-env
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), qmail(8), semanage(8), restorecon(8), chcon(1)
