.TH  "quantum_selinux"  "8"  "quantum" "dwalsh@redhat.com" "quantum SELinux Policy documentation"
.SH "NAME"
quantum_selinux \- Security Enhanced Linux Policy for the quantum processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the quantum processes via flexible mandatory access control.

The quantum processes execute with the quantum_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep quantum_t


.SH "ENTRYPOINTS"

The quantum_t SELinux type can be entered via the "quantum_exec_t" file type.  The default entrypoint paths for the quantum_t domain are the following:"

/usr/bin/quantum-openvswitch-agent, /usr/bin/quantum-server, /usr/bin/quantum-ryu-agent, /usr/bin/quantum-linuxbridge-agent
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux quantum policy is very flexible allowing users to setup their quantum processes in as secure a method as possible.
.PP 
The following process types are defined for quantum:

.EX
.B quantum_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux quantum policy is very flexible allowing users to setup their quantum processes in as secure a method as possible.
.PP 
The following file types are defined for quantum:


.EX
.PP
.B quantum_exec_t 
.EE

- Set files with the quantum_exec_t type, if you want to transition an executable to the quantum_t domain.

.br
.TP 5
Paths: 
/usr/bin/quantum-openvswitch-agent, /usr/bin/quantum-server, /usr/bin/quantum-ryu-agent, /usr/bin/quantum-linuxbridge-agent

.EX
.PP
.B quantum_log_t 
.EE

- Set files with the quantum_log_t type, if you want to treat the data as quantum log data, usually stored under the /var/log directory.


.EX
.PP
.B quantum_tmp_t 
.EE

- Set files with the quantum_tmp_t type, if you want to store quantum temporary files in the /tmp directories.


.EX
.PP
.B quantum_unit_file_t 
.EE

- Set files with the quantum_unit_file_t type, if you want to treat the files as quantum unit content.


.EX
.PP
.B quantum_var_lib_t 
.EE

- Set files with the quantum_var_lib_t type, if you want to store the quantum files under the /var/lib directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux quantum policy is very flexible allowing users to setup their quantum processes in as secure a method as possible.
.PP 
The following port types are defined for quantum:

.EX
.TP 5
.B quantum_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 9696
.EE
.SH "MANAGED FILES"

The SELinux process type quantum_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B quantum_log_t

	/var/log/quantum(/.*)?
.br

.br
.B quantum_tmp_t


.br
.B quantum_var_lib_t

	/var/lib/quantum(/.*)?
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the quantum_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the quantum_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), quantum(8), semanage(8), restorecon(8), chcon(1)
