.TH  "radiusd_selinux"  "8"  "radiusd" "dwalsh@redhat.com" "radiusd SELinux Policy documentation"
.SH "NAME"
radiusd_selinux \- Security Enhanced Linux Policy for the radiusd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the radiusd processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  radiusd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run radiusd with the tightest access possible.


.PP
If you want to allow users to login using a radius serve, you must turn on the authlogin_radius boolean.

.EX
.B setsebool -P authlogin_radius 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux radiusd policy is very flexible allowing users to setup their radiusd processes in as secure a method as possible.
.PP 
The following file types are defined for radiusd:


.EX
.PP
.B radiusd_etc_rw_t 
.EE

- Set files with the radiusd_etc_rw_t type, if you want to treat the files as radiusd etc read/write content.


.EX
.PP
.B radiusd_etc_t 
.EE

- Set files with the radiusd_etc_t type, if you want to store radiusd files in the /etc directories.


.EX
.PP
.B radiusd_exec_t 
.EE

- Set files with the radiusd_exec_t type, if you want to transition an executable to the radiusd_t domain.

.br
.TP 5
Paths: 
/usr/sbin/freeradius, /etc/cron\.(daily|monthly)/radiusd, /usr/sbin/radiusd, /etc/cron\.(daily|weekly|monthly)/freeradius

.EX
.PP
.B radiusd_initrc_exec_t 
.EE

- Set files with the radiusd_initrc_exec_t type, if you want to transition an executable to the radiusd_initrc_t domain.


.EX
.PP
.B radiusd_log_t 
.EE

- Set files with the radiusd_log_t type, if you want to treat the data as radiusd log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/log/radacct(/.*)?, /var/log/radiusd-freeradius(/.*)?, /var/log/radius\.log.*, /var/log/radutmp, /var/log/radwtmp.*, /var/log/radius(/.*)?, /var/log/freeradius(/.*)?

.EX
.PP
.B radiusd_var_lib_t 
.EE

- Set files with the radiusd_var_lib_t type, if you want to store the radiusd files under the /var/lib directory.


.EX
.PP
.B radiusd_var_run_t 
.EE

- Set files with the radiusd_var_run_t type, if you want to store the radiusd files under the /run directory.

.br
.TP 5
Paths: 
/var/run/radiusd\.pid, /var/run/radiusd(/.*)?

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux radiusd policy is very flexible allowing users to setup their radiusd processes in as secure a method as possible.
.PP 
The following port types are defined for radiusd:

.EX
.TP 5
.B radius_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux radiusd policy is very flexible allowing users to setup their radiusd processes in as secure a method as possible.
.PP 
The following process types are defined for radiusd:

.EX
.B radiusd_t 
.EE
.PP
Note: 
.B semanage permississive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), radiusd(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)