.TH  "restorecond_selinux"  "8"  "restorecond" "dwalsh@redhat.com" "restorecond Selinux Policy documentation"
.SH "NAME"
restorecond_selinux \- Security Enhanced Linux Policy for the restorecond processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the restorecond processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux restorecond policy is very flexible allowing users to setup their restorecond processes in as secure a method as possible.
.PP 
The following file types are defined for restorecond:


.EX
.B restorecond_exec_t 
.EE

- Set files with the restorecond_exec_t context, if you want to a executable to transition to the restorecond_t domain.

.br
Path: 
/usr/sbin/restorecond

.EX
.B restorecond_var_run_t 
.EE

- Set files with the restorecond_var_run_t context, if you want to store the restorecond files under the /run directory.

.br
Path: 
/var/run/restorecond\.pid
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), restorecond(8), semanage(8), restorecon(8), chcon(1)
