.TH  "rgmanager_selinux"  "8"  "rgmanager" "dwalsh@redhat.com" "rgmanager SELinux Policy documentation"
.SH "NAME"
rgmanager_selinux \- Security Enhanced Linux Policy for the rgmanager processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the rgmanager processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  rgmanager policy is extremely flexible and has several booleans that allow you to manipulate the policy and run rgmanager with the tightest access possible.


.PP
If you want to allow rgmanager domain to connect to the network using TCP, you must turn on the rgmanager_can_network_connect boolean.

.EX
.B setsebool -P rgmanager_can_network_connect 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the rgmanager_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the rgmanager_t, you must turn on the kerberos_enabled boolean.

.EX
setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux rgmanager policy is very flexible allowing users to setup their rgmanager processes in as secure a method as possible.
.PP 
The following file types are defined for rgmanager:


.EX
.PP
.B rgmanager_exec_t 
.EE

- Set files with the rgmanager_exec_t type, if you want to transition an executable to the rgmanager_t domain.


.EX
.PP
.B rgmanager_initrc_exec_t 
.EE

- Set files with the rgmanager_initrc_exec_t type, if you want to transition an executable to the rgmanager_initrc_t domain.


.EX
.PP
.B rgmanager_tmp_t 
.EE

- Set files with the rgmanager_tmp_t type, if you want to store rgmanager temporary files in the /tmp directories.


.EX
.PP
.B rgmanager_tmpfs_t 
.EE

- Set files with the rgmanager_tmpfs_t type, if you want to store rgmanager files on a tmpfs file system.


.EX
.PP
.B rgmanager_var_log_t 
.EE

- Set files with the rgmanager_var_log_t type, if you want to treat the data as rgmanager var log data, usually stored under the /var/log directory.


.EX
.PP
.B rgmanager_var_run_t 
.EE

- Set files with the rgmanager_var_run_t type, if you want to store the rgmanager files under the /run directory.

.br
.TP 5
Paths: 
/var/run/rgmanager\.pid, /var/run/cluster/rgmanager\.sk

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux rgmanager policy is very flexible allowing users to setup their rgmanager processes in as secure a method as possible.
.PP 
The following process types are defined for rgmanager:

.EX
.B rgmanager_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), rgmanager(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)