.TH  "ricci_modlog_selinux"  "8"  "ricci_modlog" "dwalsh@redhat.com" "ricci_modlog SELinux Policy documentation"
.SH "NAME"
ricci_modlog_selinux \- Security Enhanced Linux Policy for the ricci_modlog processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ricci_modlog processes via flexible mandatory access control.

The ricci_modlog processes execute with the ricci_modlog_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep ricci_modlog_t


.SH "ENTRYPOINTS"

The ricci_modlog_t SELinux type can be entered via the "ricci_modlog_exec_t" file type.  The default entrypoint paths for the ricci_modlog_t domain are the following:"

/usr/libexec/ricci-modlog
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux ricci_modlog policy is very flexible allowing users to setup their ricci_modlog processes in as secure a method as possible.
.PP 
The following process types are defined for ricci_modlog:

.EX
.B ricci_modlog_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux ricci_modlog policy is very flexible allowing users to setup their ricci_modlog processes in as secure a method as possible.
.PP 
The following file types are defined for ricci_modlog:


.EX
.PP
.B ricci_modlog_exec_t 
.EE

- Set files with the ricci_modlog_exec_t type, if you want to transition an executable to the ricci_modlog_t domain.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type ricci_modlog_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), ricci_modlog(8), semanage(8), restorecon(8), chcon(1)
, ricci_selinux(8), ricci_selinux(8), ricci_modcluster_selinux(8), ricci_modclusterd_selinux(8), ricci_modrpm_selinux(8), ricci_modservice_selinux(8), ricci_modstorage_selinux(8)