.TH  "ricci_selinux"  "8"  "ricci" "dwalsh@redhat.com" "ricci SELinux Policy documentation"
.SH "NAME"
ricci_selinux \- Security Enhanced Linux Policy for the ricci processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the ricci processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the ricci_modstorage_t, ricci_modcluster_t, ricci_modclusterd_t, ricci_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the ricci_modstorage_t, ricci_modcluster_t, ricci_modclusterd_t, ricci_t, you must turn on the kerberos_enabled boolean.

.EX
setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux ricci policy is very flexible allowing users to setup their ricci processes in as secure a method as possible.
.PP 
The following file types are defined for ricci:


.EX
.PP
.B ricci_exec_t 
.EE

- Set files with the ricci_exec_t type, if you want to transition an executable to the ricci_t domain.


.EX
.PP
.B ricci_initrc_exec_t 
.EE

- Set files with the ricci_initrc_exec_t type, if you want to transition an executable to the ricci_initrc_t domain.


.EX
.PP
.B ricci_modcluster_exec_t 
.EE

- Set files with the ricci_modcluster_exec_t type, if you want to transition an executable to the ricci_modcluster_t domain.


.EX
.PP
.B ricci_modcluster_var_lib_t 
.EE

- Set files with the ricci_modcluster_var_lib_t type, if you want to store the ricci modcluster files under the /var/lib directory.


.EX
.PP
.B ricci_modcluster_var_log_t 
.EE

- Set files with the ricci_modcluster_var_log_t type, if you want to treat the data as ricci modcluster var log data, usually stored under the /var/log directory.


.EX
.PP
.B ricci_modcluster_var_run_t 
.EE

- Set files with the ricci_modcluster_var_run_t type, if you want to store the ricci modcluster files under the /run directory.

.br
.TP 5
Paths: 
/var/run/modclusterd\.pid, /var/run/clumond\.sock

.EX
.PP
.B ricci_modclusterd_exec_t 
.EE

- Set files with the ricci_modclusterd_exec_t type, if you want to transition an executable to the ricci_modclusterd_t domain.


.EX
.PP
.B ricci_modclusterd_tmpfs_t 
.EE

- Set files with the ricci_modclusterd_tmpfs_t type, if you want to store ricci modclusterd files on a tmpfs file system.


.EX
.PP
.B ricci_modlog_exec_t 
.EE

- Set files with the ricci_modlog_exec_t type, if you want to transition an executable to the ricci_modlog_t domain.


.EX
.PP
.B ricci_modrpm_exec_t 
.EE

- Set files with the ricci_modrpm_exec_t type, if you want to transition an executable to the ricci_modrpm_t domain.


.EX
.PP
.B ricci_modservice_exec_t 
.EE

- Set files with the ricci_modservice_exec_t type, if you want to transition an executable to the ricci_modservice_t domain.


.EX
.PP
.B ricci_modstorage_exec_t 
.EE

- Set files with the ricci_modstorage_exec_t type, if you want to transition an executable to the ricci_modstorage_t domain.


.EX
.PP
.B ricci_modstorage_lock_t 
.EE

- Set files with the ricci_modstorage_lock_t type, if you want to treat the files as ricci modstorage lock data, stored under the /var/lock directory


.EX
.PP
.B ricci_tmp_t 
.EE

- Set files with the ricci_tmp_t type, if you want to store ricci temporary files in the /tmp directories.


.EX
.PP
.B ricci_var_lib_t 
.EE

- Set files with the ricci_var_lib_t type, if you want to store the ricci files under the /var/lib directory.


.EX
.PP
.B ricci_var_log_t 
.EE

- Set files with the ricci_var_log_t type, if you want to treat the data as ricci var log data, usually stored under the /var/log directory.


.EX
.PP
.B ricci_var_run_t 
.EE

- Set files with the ricci_var_run_t type, if you want to store the ricci files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux ricci policy is very flexible allowing users to setup their ricci processes in as secure a method as possible.
.PP 
The following port types are defined for ricci:

.EX
.TP 5
.B ricci_modcluster_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 16851
.EE
udp 16851
.EE

.EX
.TP 5
.B ricci_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 11111
.EE
udp 11111
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux ricci policy is very flexible allowing users to setup their ricci processes in as secure a method as possible.
.PP 
The following process types are defined for ricci:

.EX
.B ricci_t, ricci_modservice_t, ricci_modstorage_t, ricci_modclusterd_t, ricci_modlog_t, ricci_modrpm_t, ricci_modcluster_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), ricci(8), semanage(8), restorecon(8), chcon(1)
