.TH  "rlogind_selinux"  "8"  "rlogind" "dwalsh@redhat.com" "rlogind SELinux Policy documentation"
.SH "NAME"
rlogind_selinux \- Security Enhanced Linux Policy for the rlogind processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the rlogind processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux rlogind policy is very flexible allowing users to setup their rlogind processes in as secure a method as possible.
.PP 
The following file types are defined for rlogind:


.EX
.B rlogind_exec_t 
.EE

- Set files with the rlogind_exec_t type, if you want to transition an executable to the rlogind_t domain.

.br
Paths: 
/usr/lib/telnetlogin, /usr/kerberos/sbin/klogind, /usr/sbin/in\.rlogind
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B rlogind_home_t 
.EE

- Set files with the rlogind_home_t type, if you want to store rlogind files in the users home directory.

.br
Paths: 
/root/\.rlogin, /root/\.rhosts
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B rlogind_keytab_t 
.EE

- Set files with the rlogind_keytab_t type, if you want to treat the files as kerberos keytab files.


.EX
.B rlogind_tmp_t 
.EE

- Set files with the rlogind_tmp_t type, if you want to store rlogind temporary files in the /tmp directories.


.EX
.B rlogind_var_run_t 
.EE

- Set files with the rlogind_var_run_t type, if you want to store the rlogind files under the /run directory.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux rlogind policy is very flexible allowing users to setup their rlogind processes in as secure a method as possible.
.PP 
The following port types are defined for rlogind:
.EX

.B rlogind_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 513
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), rlogind(8), semanage(8), restorecon(8), chcon(1)
