.TH  "roundup_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "roundup Selinux Policy documentation"
.SH "NAME"
roundup_selinux \- Security Enhanced Linux Policy for the roundup processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the roundup processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux roundup policy is very flexible allowing users to setup their roundup processes in as secure a method as possible.
.PP 
The following file types are defined for roundup:


.EX
.B roundup_exec_t 
.EE

- Set files with the roundup_exec_t context, if you want to a executable to transition to the roundup_t domain.


.EX
.B roundup_initrc_exec_t 
.EE

- Set files with the roundup_initrc_exec_t context, if you want to a executable to transition to the roundup_initrc_t domain.


.EX
.B roundup_var_lib_t 
.EE

- Set files with the roundup_var_lib_t context, if you want to store the roundup files under the /var/lib directory.


.EX
.B roundup_var_run_t 
.EE

- Set files with the roundup_var_run_t context, if you want to store the roundup files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), roundup(8), semanage(8), restorecon(8), chcon(1)
