.TH  "rpcbind_selinux"  "8"  "rpcbind" "dwalsh@redhat.com" "rpcbind SELinux Policy documentation"
.SH "NAME"
rpcbind_selinux \- Security Enhanced Linux Policy for the rpcbind processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the rpcbind processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux rpcbind policy is very flexible allowing users to setup their rpcbind processes in as secure a method as possible.
.PP 
The following file types are defined for rpcbind:


.EX
.PP
.B rpcbind_exec_t 
.EE

- Set files with the rpcbind_exec_t type, if you want to transition an executable to the rpcbind_t domain.

.br
.TP 5
Paths: 
/usr/sbin/rpcbind, /sbin/rpcbind

.EX
.PP
.B rpcbind_initrc_exec_t 
.EE

- Set files with the rpcbind_initrc_exec_t type, if you want to transition an executable to the rpcbind_initrc_t domain.


.EX
.PP
.B rpcbind_var_lib_t 
.EE

- Set files with the rpcbind_var_lib_t type, if you want to store the rpcbind files under the /var/lib directory.

.br
.TP 5
Paths: 
/var/lib/rpcbind(/.*)?, /var/cache/rpcbind(/.*)?

.EX
.PP
.B rpcbind_var_run_t 
.EE

- Set files with the rpcbind_var_run_t type, if you want to store the rpcbind files under the /run directory.

.br
.TP 5
Paths: 
/var/run/rpcbind\.sock, /var/run/rpcbind\.lock, /var/run/rpc.statd\.pid

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux rpcbind policy is very flexible allowing users to setup their rpcbind processes in as secure a method as possible.
.PP 
The following process types are defined for rpcbind:

.EX
.B rpcbind_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), rpcbind(8), semanage(8), restorecon(8), chcon(1)
