.TH  "rpcd_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "rpcd Selinux Policy documentation"
.SH "NAME"
rpcd_selinux \- Security Enhanced Linux Policy for the rpcd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the rpcd processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux rpcd policy is very flexible allowing users to setup their rpcd processes in as secure a method as possible.
.PP 
The following file types are defined for rpcd:


.EX
.B rpcd_exec_t 
.EE

- Set files with the rpcd_exec_t context, if you want to a executable to transition to the rpcd_t domain.


.EX
.B rpcd_initrc_exec_t 
.EE

- Set files with the rpcd_initrc_exec_t context, if you want to a executable to transition to the rpcd_initrc_t domain.


.EX
.B rpcd_unit_file_t 
.EE

- Set files with the rpcd_unit_file_t context, if you want to treat the files as rpcd unit content.


.EX
.B rpcd_var_run_t 
.EE

- Set files with the rpcd_var_run_t context, if you want to store the rpcd files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), rpcd(8), semanage(8), restorecon(8), chcon(1)