.TH  "rpm_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "rpm Selinux Policy documentation"
.SH "NAME"
rpm_selinux \- Security Enhanced Linux Policy for the rpm processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the rpm processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux rpm policy is very flexible allowing users to setup their rpm processes in as secure a method as possible.
.PP 
The following file types are defined for rpm:


.EX
.B rpm_exec_t 
.EE

- Set files with the rpm_exec_t context, if you want to a executable to transition to the rpm_t domain.


.EX
.B rpm_file_t 
.EE

- Set files with the rpm_file_t context, if you want to treat the files as rpm content.


.EX
.B rpm_log_t 
.EE

- Set files with the rpm_log_t context, if you want to treat the data as rpm log data, usually stored under the /var/log directory.


.EX
.B rpm_script_exec_t 
.EE

- Set files with the rpm_script_exec_t context, if you want to a executable to transition to the rpm_script_t domain.


.EX
.B rpm_script_tmp_t 
.EE

- Set files with the rpm_script_tmp_t context, if you want to store rpm script temporary files in the /tmp directories.


.EX
.B rpm_script_tmpfs_t 
.EE

- Set files with the rpm_script_tmpfs_t context, if you want to store rpm script files on a tmpfs file system.


.EX
.B rpm_tmp_t 
.EE

- Set files with the rpm_tmp_t context, if you want to store rpm temporary files in the /tmp directories.


.EX
.B rpm_tmpfs_t 
.EE

- Set files with the rpm_tmpfs_t context, if you want to store rpm files on a tmpfs file system.


.EX
.B rpm_var_cache_t 
.EE

- Set files with the rpm_var_cache_t context, if you want to store the files under the /var/cache directory.


.EX
.B rpm_var_lib_t 
.EE

- Set files with the rpm_var_lib_t context, if you want to store the rpm files under the /var/lib directory.


.EX
.B rpm_var_run_t 
.EE

- Set files with the rpm_var_run_t context, if you want to store the rpm files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), rpm(8), semanage(8), restorecon(8), chcon(1)
