.TH  "rsync_selinux"  "8"  "rsync" "dwalsh@redhat.com" "rsync SELinux Policy documentation"
.SH "NAME"
rsync_selinux \- Security Enhanced Linux Policy for the rsync processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the rsync processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux rsync policy is very flexible allowing users to setup their rsync processes in as secure a method as possible.
.PP 
The following file types are defined for rsync:


.EX
.B rsync_data_t 
.EE

- Set files with the rsync_data_t context, if you want to treat the files as rsync content.


.EX
.B rsync_etc_t 
.EE

- Set files with the rsync_etc_t context, if you want to store rsync files in the /etc directories.

.br
Path: 
/etc/rsyncd\.conf

.EX
.B rsync_exec_t 
.EE

- Set files with the rsync_exec_t context, if you want to a executable to transition to the rsync_t domain.

.br
Path: 
/usr/bin/rsync

.EX
.B rsync_log_t 
.EE

- Set files with the rsync_log_t context, if you want to treat the data as rsync log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/rsync\.log

.EX
.B rsync_tmp_t 
.EE

- Set files with the rsync_tmp_t context, if you want to store rsync temporary files in the /tmp directories.


.EX
.B rsync_var_run_t 
.EE

- Set files with the rsync_var_run_t context, if you want to store the rsync files under the /run directory.

.br
Path: 
/var/run/rsyncd\.lock
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  rsync policy is extremely flexible and has several booleans that allow you to manipulate the policy and run rsync with the tightest access possible.


.PP
If you want to allow rsync to run as a clien, you must turn on the rsync_client boolean.

.EX
.B setsebool -P rsync_client 1
.EE

.PP
If you want to allow rsync to export any files/directories read only, you must turn on the rsync_export_all_ro boolean.

.EX
.B setsebool -P rsync_export_all_ro 1
.EE

.PP
If you want to allow rsync servers to share nfs files system, you must turn on the rsync_use_nfs boolean.

.EX
.B setsebool -P rsync_use_nfs 1
.EE

.PP
If you want to allow rsync servers to share cifs files system, you must turn on the rsync_use_cifs boolean.

.EX
.B setsebool -P rsync_use_cifs 1
.EE

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow rsync servers to read the /var/rsync directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/rsync(/.*)?"
.TP
.B
restorecon -F -R -v /var/rsync
.pp
.TP
Allow rsync servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_rsyncd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/rsync/incoming(/.*)?"
.TP
.B
restorecon -F -R -v /var/rsync/incoming


.PP
If you want to allow rsync to modify public files used for public file transfer services.  Files/Directories must be labeled public_content_rw_t., you must turn on the allow_rsync_anon_write boolean.

.EX
.B setsebool -P allow_rsync_anon_write 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), rsync(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)