.TH  "rsync_selinux"  "8"  "rsync" "dwalsh@redhat.com" "rsync SELinux Policy documentation"
.SH "NAME"
rsync_selinux \- Security Enhanced Linux Policy for the rsync processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the rsync processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  rsync policy is extremely flexible and has several booleans that allow you to manipulate the policy and run rsync with the tightest access possible.


.PP
If you want to allow postgresql to use ssh and rsync for point-in-time recovery, you must turn on the postgresql_can_rsync boolean.

.EX
.B setsebool -P postgresql_can_rsync 1
.EE

.PP
If you want to allow rsync to run as a client, you must turn on the rsync_client boolean.

.EX
.B setsebool -P rsync_client 1
.EE

.PP
If you want to allow rsync to export any files/directories read only, you must turn on the rsync_export_all_ro boolean.

.EX
.B setsebool -P rsync_export_all_ro 1
.EE

.PP
If you want to allow rsync servers to share nfs files systems, you must turn on the rsync_use_nfs boolean.

.EX
.B setsebool -P rsync_use_nfs 1
.EE

.PP
If you want to allow rsync servers to share cifs files systems, you must turn on the rsync_use_cifs boolean.

.EX
.B setsebool -P rsync_use_cifs 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the rsync_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the rsync_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow rsync servers to read the /var/rsync directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/rsync(/.*)?"
.br
.B restorecon -F -R -v /var/rsync
.pp
.TP
Allow rsync servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_rsyncd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/rsync/incoming(/.*)?"
.br
.B restorecon -F -R -v /var/rsync/incoming


.PP
If you want to allow rsync to modify public files used for public file transfer services.  Files/Directories must be labeled public_content_rw_t., you must turn on the rsync_anon_write boolean.

.EX
.B setsebool -P rsync_anon_write 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux rsync policy is very flexible allowing users to setup their rsync processes in as secure a method as possible.
.PP 
The following file types are defined for rsync:


.EX
.PP
.B rsync_data_t 
.EE

- Set files with the rsync_data_t type, if you want to treat the files as rsync content.


.EX
.PP
.B rsync_etc_t 
.EE

- Set files with the rsync_etc_t type, if you want to store rsync files in the /etc directories.


.EX
.PP
.B rsync_exec_t 
.EE

- Set files with the rsync_exec_t type, if you want to transition an executable to the rsync_t domain.


.EX
.PP
.B rsync_log_t 
.EE

- Set files with the rsync_log_t type, if you want to treat the data as rsync log data, usually stored under the /var/log directory.


.EX
.PP
.B rsync_tmp_t 
.EE

- Set files with the rsync_tmp_t type, if you want to store rsync temporary files in the /tmp directories.


.EX
.PP
.B rsync_var_run_t 
.EE

- Set files with the rsync_var_run_t type, if you want to store the rsync files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux rsync policy is very flexible allowing users to setup their rsync processes in as secure a method as possible.
.PP 
The following port types are defined for rsync:

.EX
.TP 5
.B rsync_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 873
.EE
udp 873
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux rsync policy is very flexible allowing users to setup their rsync processes in as secure a method as possible.
.PP 
The following process types are defined for rsync:

.EX
.B rsync_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type rsync_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B rsync_log_t

	/var/log/rsync\.log.*
.br

.br
.B rsync_tmp_t


.br
.B rsync_var_run_t

	/var/run/rsyncd\.lock
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), rsync(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)