.TH  "rwho_selinux"  "8"  "rwho" "dwalsh@redhat.com" "rwho SELinux Policy documentation"
.SH "NAME"
rwho_selinux \- Security Enhanced Linux Policy for the rwho processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the rwho processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux rwho policy is very flexible allowing users to setup their rwho processes in as secure a method as possible.
.PP 
The following file types are defined for rwho:


.EX
.B rwho_exec_t 
.EE

- Set files with the rwho_exec_t type, if you want to transition an executable to the rwho_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B rwho_initrc_exec_t 
.EE

- Set files with the rwho_initrc_exec_t type, if you want to transition an executable to the rwho_initrc_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B rwho_log_t 
.EE

- Set files with the rwho_log_t type, if you want to treat the data as rwho log data, usually stored under the /var/log directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B rwho_spool_t 
.EE

- Set files with the rwho_spool_t type, if you want to store the rwho files under the /var/spool directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux rwho policy is very flexible allowing users to setup their rwho processes in as secure a method as possible.
.PP 
The following port types are defined for rwho:
.EX

.B rwho_port_t 
.EE

.EX
Default Defined Ports:

.B udp 513
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), rwho(8), semanage(8), restorecon(8), chcon(1)
