.TH  "sandbox_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "sandbox Selinux Policy documentation"
.SH "NAME"
sandbox_selinux \- Security Enhanced Linux Policy for the sandbox processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the sandbox processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux sandbox policy is very flexible allowing users to setup their sandbox processes in as secure a method as possible.
.PP 
The following file types are defined for sandbox:


.EX
.B sandbox_devpts_t 
.EE

- Set files with the sandbox_devpts_t context, if you want to treat the files as sandbox devpts data.


.EX
.B sandbox_exec_t 
.EE

- Set files with the sandbox_exec_t context, if you want to a executable to transition to the sandbox_t domain.


.EX
.B sandbox_file_t 
.EE

- Set files with the sandbox_file_t context, if you want to treat the files as sandbox content.


.EX
.B sandbox_min_client_tmpfs_t 
.EE

- Set files with the sandbox_min_client_tmpfs_t context, if you want to store sandbox min client files on a tmpfs file system.


.EX
.B sandbox_net_client_tmpfs_t 
.EE

- Set files with the sandbox_net_client_tmpfs_t context, if you want to store sandbox net client files on a tmpfs file system.


.EX
.B sandbox_web_client_tmpfs_t 
.EE

- Set files with the sandbox_web_client_tmpfs_t context, if you want to store sandbox web client files on a tmpfs file system.


.EX
.B sandbox_x_client_tmpfs_t 
.EE

- Set files with the sandbox_x_client_tmpfs_t context, if you want to store sandbox x client files on a tmpfs file system.


.EX
.B sandbox_xserver_tmpfs_t 
.EE

- Set files with the sandbox_xserver_tmpfs_t context, if you want to store sandbox xserver files on a tmpfs file system.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  sandbox policy is extremely flexible and has several booleans that allow you to manipulate the policy and run sandbox with the tightest access possible.


.PP
If you want to allow unconfined users to transition to the chrome sandbox domains when running chrome-sandbo, you must turn on the unconfined_chrome_sandbox_transition boolean.

.EX
.B setsebool -P unconfined_chrome_sandbox_transition 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), sandbox(8), semanage(8), restorecon(8), chcon(1), setsebool(8)