.TH  "sandbox_x_client_selinux"  "8"  "13-01-16" "sandbox_x_client" "SELinux Policy documentation for sandbox_x_client"
.SH "NAME"
sandbox_x_client_selinux \- Security Enhanced Linux Policy for the sandbox_x_client processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the sandbox_x_client processes via flexible mandatory access control.

The sandbox_x_client processes execute with the sandbox_x_client_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep sandbox_x_client_t


.SH "ENTRYPOINTS"

The sandbox_x_client_t SELinux type can be entered via the \fBsandbox_exec_t, file_type\fP file types.

The default entrypoint paths for the sandbox_x_client_t domain are the following:

/usr/share/sandbox/start, all files on the system
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux sandbox_x_client policy is very flexible allowing users to setup their sandbox_x_client processes in as secure a method as possible.
.PP
The following process types are defined for sandbox_x_client:

.EX
.B sandbox_x_client_t
.EE
.PP
Note:
.B semanage permissive -a sandbox_x_client_t
can be used to make the process type sandbox_x_client_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  sandbox_x_client policy is extremely flexible and has several booleans that allow you to manipulate the policy and run sandbox_x_client with the tightest access possible.


.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server, you must turn on the authlogin_nsswitch_use_ldap boolean. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you want to deny user domains applications to map a memory region as both executable and writable, this is dangerous and the executable should be reported in bugzilla, you must turn on the deny_execmem boolean. Enabled by default.

.EX
.B setsebool -P deny_execmem 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to run with kerberos, you must turn on the kerberos_enabled boolean. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you want to allow system to run with NIS, you must turn on the nis_enabled boolean. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.PP
If you want to support fusefs home directories, you must turn on the use_fusefs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_fusefs_home_dirs 1

.EE

.PP
If you want to support NFS home directories, you must turn on the use_nfs_home_dirs boolean. Enabled by default.

.EX
.B setsebool -P use_nfs_home_dirs 1

.EE

.PP
If you want to support SAMBA home directories, you must turn on the use_samba_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_samba_home_dirs 1

.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server for the sandbox_x_client_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the sandbox_x_client_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "MANAGED FILES"

The SELinux process type sandbox_x_client_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B cifs_t


.br
.B fusefs_t


.br
.B nfs_t


.br
.B sandbox_file_t


.br
.B sandbox_x_client_tmpfs_t


.br
.B security_t

	/selinux
.br

.br
.B tmpfs_t

	/dev/shm
.br
	/lib/udev/devices/shm
.br
	/usr/lib/udev/devices/shm
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), sandbox_x_client(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), sandbox_selinux(8), sandbox_selinux(8), sandbox_min_selinux(8), sandbox_min_client_selinux(8), sandbox_net_selinux(8), sandbox_net_client_selinux(8), sandbox_web_selinux(8), sandbox_web_client_selinux(8), sandbox_x_selinux(8), sandbox_x_selinux(8), sandbox_xserver_selinux(8)