.TH  "semanage_selinux"  "8"  "semanage" "dwalsh@redhat.com" "semanage SELinux Policy documentation"
.SH "NAME"
semanage_selinux \- Security Enhanced Linux Policy for the semanage processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the semanage processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux semanage policy is very flexible allowing users to setup their semanage processes in as secure a method as possible.
.PP 
The following file types are defined for semanage:


.EX
.B semanage_exec_t 
.EE

- Set files with the semanage_exec_t type, if you want to transition an executable to the semanage_t domain.

.br
Paths: 
/usr/share/system-config-selinux/system-config-selinux-dbus\.py, /usr/sbin/semanage, /usr/sbin/semodule
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B semanage_read_lock_t 
.EE

- Set files with the semanage_read_lock_t type, if you want to treat the files as semanage read lock data, stored under the /var/lock directory

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B semanage_store_t 
.EE

- Set files with the semanage_store_t type, if you want to treat the files as semanage store data.

.br
Paths: 
/etc/share/selinux/mls(/.*)?, /etc/selinux/([^/]*/)?modules/(active|tmp|previous)(/.*)?, /etc/selinux/([^/]*/)?policy(/.*)?, /etc/share/selinux/targeted(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B semanage_tmp_t 
.EE

- Set files with the semanage_tmp_t type, if you want to store semanage temporary files in the /tmp directories.


.EX
.B semanage_trans_lock_t 
.EE

- Set files with the semanage_trans_lock_t type, if you want to treat the files as semanage trans lock data, stored under the /var/lock directory

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), semanage(8), semanage(8), restorecon(8), chcon(1)
