.TH  "setroubleshoot_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "setroubleshoot Selinux Policy documentation"
.SH "NAME"
setroubleshoot_selinux \- Security Enhanced Linux Policy for the setroubleshoot processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the setroubleshoot processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux setroubleshoot policy is very flexible allowing users to setup their setroubleshoot processes in as secure a method as possible.
.PP 
The following file types are defined for setroubleshoot:


.EX
.B setroubleshoot_fixit_exec_t 
.EE

- Set files with the setroubleshoot_fixit_exec_t context, if you want to a executable to transition to the setroubleshoot_fixit_t domain.


.EX
.B setroubleshoot_var_lib_t 
.EE

- Set files with the setroubleshoot_var_lib_t context, if you want to store the setroubleshoot files under the /var/lib directory.


.EX
.B setroubleshoot_var_log_t 
.EE

- Set files with the setroubleshoot_var_log_t context, if you want to treat the data as setroubleshoot var log data, usually stored in /var/log.


.EX
.B setroubleshoot_var_run_t 
.EE

- Set files with the setroubleshoot_var_run_t context, if you want to store the setroubleshoot files under the /run directory.


.EX
.B setroubleshootd_exec_t 
.EE

- Set files with the setroubleshootd_exec_t context, if you want to a executable to transition to the setroubleshootd_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), setroubleshoot(8), semanage(8), restorecon(8), chcon(1)