.TH  "sge_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "sge Selinux Policy documentation"
.SH "NAME"
sge_selinux \- Security Enhanced Linux Policy for the sge processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the sge processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux sge policy is very flexible allowing users to setup their sge processes in as secure a method as possible.
.PP 
The following file types are defined for sge:


.EX
.B sge_execd_exec_t 
.EE

- Set files with the sge_execd_exec_t context, if you want to a executable to transition to the sge_execd_t domain.


.EX
.B sge_job_exec_t 
.EE

- Set files with the sge_job_exec_t context, if you want to a executable to transition to the sge_job_t domain.


.EX
.B sge_shepherd_exec_t 
.EE

- Set files with the sge_shepherd_exec_t context, if you want to a executable to transition to the sge_shepherd_t domain.


.EX
.B sge_spool_t 
.EE

- Set files with the sge_spool_t context, if you want to store the sge files under the /var/spool directory.


.EX
.B sge_tmp_t 
.EE

- Set files with the sge_tmp_t context, if you want to store sge temporary files in the /tmp directories.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  sge policy is extremely flexible and has several booleans that allow you to manipulate the policy and run sge with the tightest access possible.


.PP
If you want to allow sge to access nfs file systems, you must turn on the sge_use_nfs boolean.

.EX
.B setsebool -P sge_use_nfs 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), sge(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)