.TH  "shorewall_selinux"  "8"  "shorewall" "dwalsh@redhat.com" "shorewall SELinux Policy documentation"
.SH "NAME"
shorewall_selinux \- Security Enhanced Linux Policy for the shorewall processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the shorewall processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux shorewall policy is very flexible allowing users to setup their shorewall processes in as secure a method as possible.
.PP 
The following file types are defined for shorewall:


.EX
.B shorewall_etc_t 
.EE

- Set files with the shorewall_etc_t type, if you want to store shorewall files in the /etc directories.

.br
Paths: 
/etc/shorewall-lite(/.*)?, /etc/shorewall(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B shorewall_exec_t 
.EE

- Set files with the shorewall_exec_t type, if you want to transition an executable to the shorewall_t domain.

.br
Paths: 
/sbin/shorewall6?, /sbin/shorewall-lite, /usr/sbin/shorewall-lite, /usr/sbin/shorewall6?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B shorewall_initrc_exec_t 
.EE

- Set files with the shorewall_initrc_exec_t type, if you want to transition an executable to the shorewall_initrc_t domain.

.br
Paths: 
/etc/rc\.d/init\.d/shorewall, /etc/rc\.d/init\.d/shorewall-lite
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B shorewall_lock_t 
.EE

- Set files with the shorewall_lock_t type, if you want to treat the files as shorewall lock data, stored under the /var/lock directory

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B shorewall_log_t 
.EE

- Set files with the shorewall_log_t type, if you want to treat the data as shorewall log data, usually stored under the /var/log directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B shorewall_tmp_t 
.EE

- Set files with the shorewall_tmp_t type, if you want to store shorewall temporary files in the /tmp directories.


.EX
.B shorewall_var_lib_t 
.EE

- Set files with the shorewall_var_lib_t type, if you want to store the shorewall files under the /var/lib directory.

.br
Paths: 
/var/lib/shorewall-lite(/.*)?, /var/lib/shorewall(/.*)?, /var/lib/shorewall6(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), shorewall(8), semanage(8), restorecon(8), chcon(1)
