.TH  "shutdown_selinux"  "8"  "shutdown" "dwalsh@redhat.com" "shutdown SELinux Policy documentation"
.SH "NAME"
shutdown_selinux \- Security Enhanced Linux Policy for the shutdown processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the shutdown processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  shutdown policy is extremely flexible and has several booleans that allow you to manipulate the policy and run shutdown with the tightest access possible.


.PP
If you want to allow HTTPD to connect to port 80 for graceful shutdow, you must turn on the httpd_graceful_shutdown boolean.

.EX
.B setsebool -P httpd_graceful_shutdown 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the shutdown_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the shutdown_t, you must turn on the kerberos_enabled boolean.

.EX
setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux shutdown policy is very flexible allowing users to setup their shutdown processes in as secure a method as possible.
.PP 
The following file types are defined for shutdown:


.EX
.PP
.B shutdown_etc_t 
.EE

- Set files with the shutdown_etc_t type, if you want to store shutdown files in the /etc directories.


.EX
.PP
.B shutdown_exec_t 
.EE

- Set files with the shutdown_exec_t type, if you want to transition an executable to the shutdown_t domain.

.br
.TP 5
Paths: 
/sbin/shutdown, /usr/sbin/shutdown, /usr/lib/upstart/shutdown, /lib/upstart/shutdown

.EX
.PP
.B shutdown_var_run_t 
.EE

- Set files with the shutdown_var_run_t type, if you want to store the shutdown files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux shutdown policy is very flexible allowing users to setup their shutdown processes in as secure a method as possible.
.PP 
The following process types are defined for shutdown:

.EX
.B shutdown_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), shutdown(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)