.TH  "smbmount_selinux"  "8"  "13-01-16" "smbmount" "SELinux Policy documentation for smbmount"
.SH "NAME"
smbmount_selinux \- Security Enhanced Linux Policy for the smbmount processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the smbmount processes via flexible mandatory access control.

The smbmount processes execute with the smbmount_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep smbmount_t


.SH "ENTRYPOINTS"

The smbmount_t SELinux type can be entered via the \fBsmbmount_exec_t\fP file type.

The default entrypoint paths for the smbmount_t domain are the following:

/usr/bin/smbmnt, /usr/bin/smbmount
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux smbmount policy is very flexible allowing users to setup their smbmount processes in as secure a method as possible.
.PP
The following process types are defined for smbmount:

.EX
.B smbmount_t
.EE
.PP
Note:
.B semanage permissive -a smbmount_t
can be used to make the process type smbmount_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  smbmount policy is extremely flexible and has several booleans that allow you to manipulate the policy and run smbmount with the tightest access possible.


.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server, you must turn on the authlogin_nsswitch_use_ldap boolean. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to run with kerberos, you must turn on the kerberos_enabled boolean. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you want to allow system to run with NIS, you must turn on the nis_enabled boolean. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server for the smbmount_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the smbmount_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "MANAGED FILES"

The SELinux process type smbmount_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B etc_runtime_t

	/[^/]+
.br
	/etc/mtab.*
.br
	/etc/blkid(/.*)?
.br
	/etc/nologin.*
.br
	/etc/\.fstab\.hal\..+
.br
	/halt
.br
	/fastboot
.br
	/poweroff
.br
	/etc/cmtab
.br
	/forcefsck
.br
	/\.autofsck
.br
	/\.suspended
.br
	/fsckoptions
.br
	/\.autorelabel
.br
	/etc/securetty
.br
	/etc/nohotplug
.br
	/etc/killpower
.br
	/etc/ioctl\.save
.br
	/etc/fstab\.REVOKE
.br
	/etc/network/ifstate
.br
	/etc/sysconfig/hwconf
.br
	/etc/ptal/ptal-printd-like
.br
	/etc/sysconfig/iptables\.save
.br
	/etc/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br
	/etc/X11/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br

.br
.B samba_log_t

	/var/log/samba(/.*)?
.br

.br
.B samba_secrets_t

	/etc/samba/smbpasswd
.br
	/etc/samba/passdb\.tdb
.br
	/etc/samba/MACHINE\.SID
.br
	/etc/samba/secrets\.tdb
.br

.br
.B samba_var_t

	/var/nmbd(/.*)?
.br
	/var/lib/samba(/.*)?
.br
	/var/cache/samba(/.*)?
.br
	/var/spool/samba(/.*)?
.br

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux smbmount policy is very flexible allowing users to setup their smbmount processes in as secure a method as possible.
.PP

.PP
.B STANDARD FILE CONTEXT

SELinux defines the file context types for the smbmount, if you wanted to
store files with these types in a diffent paths, you need to execute the semanage command to sepecify alternate labeling and then use restorecon to put the labels on disk.

.B semanage fcontext -a -t smbmount_exec_t '/srv/smbmount/content(/.*)?'
.br
.B restorecon -R -v /srv/mysmbmount_content

Note: SELinux often uses regular expressions to specify labels that match multiple files.

.I The following file types are defined for smbmount:


.EX
.PP
.B smbmount_exec_t
.EE

- Set files with the smbmount_exec_t type, if you want to transition an executable to the smbmount_t domain.

.br
.TP 5
Paths:
/usr/bin/smbmnt, /usr/bin/smbmount

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), smbmount(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8)