.TH  "snmpd_selinux"  "8"  "snmpd" "dwalsh@redhat.com" "snmpd SELinux Policy documentation"
.SH "NAME"
snmpd_selinux \- Security Enhanced Linux Policy for the snmpd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the snmpd processes via flexible mandatory access
control.  

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux snmpd policy is very flexible allowing users to setup their snmpd processes in as secure a method as possible.
.PP 
The following file types are defined for snmpd:


.EX
.B snmpd_exec_t 
.EE

- Set files with the snmpd_exec_t type, if you want to transition an executable to the snmpd_t domain.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B snmpd_initrc_exec_t 
.EE

- Set files with the snmpd_initrc_exec_t type, if you want to transition an executable to the snmpd_initrc_t domain.

.br
Paths: 
/etc/rc\.d/init\.d/snmpd, /etc/rc\.d/init\.d/snmptrapd
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B snmpd_log_t 
.EE

- Set files with the snmpd_log_t type, if you want to treat the data as snmpd log data, usually stored under the /var/log directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B snmpd_var_lib_t 
.EE

- Set files with the snmpd_var_lib_t type, if you want to store the snmpd files under the /var/lib directory.

.br
Paths: 
/var/agentx(/.*)?, /usr/share/snmp/mibs/\.index, /var/net-snmp(/.*)?, /var/lib/net-snmp(/.*)?, /var/lib/snmp(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.


.EX
.B snmpd_var_run_t 
.EE

- Set files with the snmpd_var_run_t type, if you want to store the snmpd files under the /run directory.

.br
Paths: 
/var/run/net-snmpd(/.*)?, /var/run/snmpd\.pid, /var/run/snmpd(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux snmpd policy is very flexible allowing users to setup their snmpd processes in as secure a method as possible.
.PP 
The following port types are defined for snmpd:
.EX

.B snmp_port_t 
.EE

.EX
Default Defined Ports:

.B tcp 161-162,199,1161
.EE
.B udp 161-162
.EE
.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), snmpd(8), semanage(8), restorecon(8), chcon(1)
