.TH  "sosreport_selinux"  "8"  "sosreport" "dwalsh@redhat.com" "sosreport SELinux Policy documentation"
.SH "NAME"
sosreport_selinux \- Security Enhanced Linux Policy for the sosreport processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the sosreport processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux sosreport policy is very flexible allowing users to setup their sosreport processes in as secure a method as possible.
.PP 
The following file types are defined for sosreport:


.EX
.B sosreport_exec_t 
.EE

- Set files with the sosreport_exec_t context, if you want to a executable to transition to the sosreport_t domain.

.br
Path: 
/usr/sbin/sosreport

.EX
.B sosreport_tmp_t 
.EE

- Set files with the sosreport_tmp_t context, if you want to store sosreport temporary files in the /tmp directories.

.br
Path: 
/.ismount-test-file

.EX
.B sosreport_tmpfs_t 
.EE

- Set files with the sosreport_tmpfs_t context, if you want to store sosreport files on a tmpfs file system.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), sosreport(8), semanage(8), restorecon(8), chcon(1)
