.TH  "soundd_selinux"  "8"  "soundd" "dwalsh@redhat.com" "soundd Selinux Policy documentation"
.SH "NAME"
soundd_selinux \- Security Enhanced Linux Policy for the soundd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the soundd processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux soundd policy is very flexible allowing users to setup their soundd processes in as secure a method as possible.
.PP 
The following file types are defined for soundd:


.EX
.B soundd_etc_t 
.EE

- Set files with the soundd_etc_t context, if you want to store soundd files in the /etc directories.

.br
Paths: 
/etc/yiff(/.*)?, /etc/nas(/.*)?

.EX
.B soundd_exec_t 
.EE

- Set files with the soundd_exec_t context, if you want to a executable to transition to the soundd_t domain.

.br
Paths: 
/usr/bin/gpe-soundserver, /usr/sbin/yiff, /usr/bin/nasd

.EX
.B soundd_initrc_exec_t 
.EE

- Set files with the soundd_initrc_exec_t context, if you want to a executable to transition to the soundd_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/nasd

.EX
.B soundd_state_t 
.EE

- Set files with the soundd_state_t context, if you want to treat the files as soundd state data.

.br
Path: 
/var/state/yiff(/.*)?

.EX
.B soundd_tmp_t 
.EE

- Set files with the soundd_tmp_t context, if you want to store soundd temporary files in the /tmp directories.


.EX
.B soundd_tmpfs_t 
.EE

- Set files with the soundd_tmpfs_t context, if you want to store soundd files on a tmpfs file system.


.EX
.B soundd_var_run_t 
.EE

- Set files with the soundd_var_run_t context, if you want to store the soundd files under the /run directory.

.br
Paths: 
/var/run/nasd(/.*)?, /var/run/yiff-[0-9]+\.pid
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), soundd(8), semanage(8), restorecon(8), chcon(1)
