.TH  "spamass_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "spamass Selinux Policy documentation"
.SH "NAME"
spamass_selinux \- Security Enhanced Linux Policy for the spamass processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the spamass processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux spamass policy is very flexible allowing users to setup their spamass processes in as secure a method as possible.
.PP 
The following file types are defined for spamass:


.EX
.B spamass_milter_data_t 
.EE

- Set files with the spamass_milter_data_t context, if you want to treat the files as spamass milter content.


.EX
.B spamass_milter_exec_t 
.EE

- Set files with the spamass_milter_exec_t context, if you want to a executable to transition to the spamass_milter_t domain.


.EX
.B spamass_milter_state_t 
.EE

- Set files with the spamass_milter_state_t context, if you want to treat the files as spamass milter state data.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  spamass policy is extremely flexible and has several booleans that allow you to manipulate the policy and run spamass with the tightest access possible.


.PP
If you want to allow user spamassassin clients to use the network., you must turn on the spamassassin_can_network boolean.

.EX
.B setsebool -P spamassassin_can_network 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), spamass(8), semanage(8), restorecon(8), chcon(1), setsebool(8)