.TH  "sshd_sandbox_selinux"  "8"  "13-01-16" "sshd_sandbox" "SELinux Policy documentation for sshd_sandbox"
.SH "NAME"
sshd_sandbox_selinux \- Security Enhanced Linux Policy for the sshd_sandbox processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the sshd_sandbox processes via flexible mandatory access control.

The sshd_sandbox processes execute with the sshd_sandbox_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep sshd_sandbox_t


.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux sshd_sandbox policy is very flexible allowing users to setup their sshd_sandbox processes in as secure a method as possible.
.PP
The following process types are defined for sshd_sandbox:

.EX
.B sshd_sandbox_t
.EE
.PP
Note:
.B semanage permissive -a sshd_sandbox_t
can be used to make the process type sshd_sandbox_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  sshd_sandbox policy is extremely flexible and has several booleans that allow you to manipulate the policy and run sshd_sandbox with the tightest access possible.


.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), sshd_sandbox(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), ssh_selinux(8), sshd_selinux(8), sshd_selinux(8)