.TH  "svc_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "svc Selinux Policy documentation"
.SH "NAME"
svc_selinux \- Security Enhanced Linux Policy for the svc processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the svc processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux svc policy is very flexible allowing users to setup their svc processes in as secure a method as possible.
.PP 
The following file types are defined for svc:


.EX
.B svc_conf_t 
.EE

- Set files with the svc_conf_t context, if you want to treat the files as svc configuration data, usually stored under the /etc directory.


.EX
.B svc_log_t 
.EE

- Set files with the svc_log_t context, if you want to treat the data as svc log data, usually stored under the /var/log directory.


.EX
.B svc_multilog_exec_t 
.EE

- Set files with the svc_multilog_exec_t context, if you want to a executable to transition to the svc_multilog_t domain.


.EX
.B svc_run_exec_t 
.EE

- Set files with the svc_run_exec_t context, if you want to a executable to transition to the svc_run_t domain.


.EX
.B svc_start_exec_t 
.EE

- Set files with the svc_start_exec_t context, if you want to a executable to transition to the svc_start_t domain.


.EX
.B svc_svc_t 
.EE

- Set files with the svc_svc_t context, if you want to treat the files as svc svc data.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), svc(8), semanage(8), restorecon(8), chcon(1)
