.TH  "svc_start_selinux"  "8"  "svc_start" "dwalsh@redhat.com" "svc_start SELinux Policy documentation"
.SH "NAME"
svc_start_selinux \- Security Enhanced Linux Policy for the svc_start processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the svc_start processes via flexible mandatory access control.

The svc_start processes execute with the svc_start_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep svc_start_t


.SH "ENTRYPOINTS"

The svc_start_t SELinux type can be entered via the "svc_start_exec_t" file type.  The default entrypoint paths for the svc_start_t domain are the following:"

/usr/bin/svok, /usr/bin/svscan, /usr/bin/svc, /usr/bin/svscanboot, /usr/bin/supervise
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux svc_start policy is very flexible allowing users to setup their svc_start processes in as secure a method as possible.
.PP 
The following process types are defined for svc_start:

.EX
.B svc_start_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux svc_start policy is very flexible allowing users to setup their svc_start processes in as secure a method as possible.
.PP 
The following file types are defined for svc_start:


.EX
.PP
.B svc_start_exec_t 
.EE

- Set files with the svc_start_exec_t type, if you want to transition an executable to the svc_start_t domain.

.br
.TP 5
Paths: 
/usr/bin/svok, /usr/bin/svscan, /usr/bin/svc, /usr/bin/svscanboot, /usr/bin/supervise

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type svc_start_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B svc_svc_t

	/service/.*
.br
	/var/axfrdns(/.*)?
.br
	/var/tinydns(/.*)?
.br
	/var/service/.*
.br
	/var/dnscache(/.*)?
.br
	/var/qmail/supervise(/.*)?
.br
	/service
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), svc_start(8), semanage(8), restorecon(8), chcon(1)
, svc_multilog_selinux(8), svc_run_selinux(8)