.TH  "swat_selinux"  "8"  "swat" "dwalsh@redhat.com" "swat SELinux Policy documentation"
.SH "NAME"
swat_selinux \- Security Enhanced Linux Policy for the swat processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the swat processes via flexible mandatory access control.

The swat processes execute with the swat_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep swat_t


.SH "ENTRYPOINTS"

The swat_t SELinux type can be entered via the "swat_exec_t" file type.  The default entrypoint paths for the swat_t domain are the following:"

/usr/sbin/swat
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux swat policy is very flexible allowing users to setup their swat processes in as secure a method as possible.
.PP 
The following process types are defined for swat:

.EX
.B swat_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux swat policy is very flexible allowing users to setup their swat processes in as secure a method as possible.
.PP 
The following file types are defined for swat:


.EX
.PP
.B swat_exec_t 
.EE

- Set files with the swat_exec_t type, if you want to transition an executable to the swat_t domain.


.EX
.PP
.B swat_tmp_t 
.EE

- Set files with the swat_tmp_t type, if you want to store swat temporary files in the /tmp directories.


.EX
.PP
.B swat_var_run_t 
.EE

- Set files with the swat_var_run_t type, if you want to store the swat files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux swat policy is very flexible allowing users to setup their swat processes in as secure a method as possible.
.PP 
The following port types are defined for swat:

.EX
.TP 5
.B swat_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 901
.EE
.SH "MANAGED FILES"

The SELinux process type swat_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B faillog_t

	/var/log/btmp.*
.br
	/var/run/faillock(/.*)?
.br
	/var/log/faillog
.br
	/var/log/tallylog
.br

.br
.B pcscd_var_run_t

	/var/run/pcscd(/.*)?
.br
	/var/run/pcscd\.events(/.*)?
.br
	/var/run/pcscd\.pid
.br
	/var/run/pcscd\.pub
.br
	/var/run/pcscd\.comm
.br

.br
.B samba_etc_t

	/etc/samba(/.*)?
.br

.br
.B samba_log_t

	/var/log/samba(/.*)?
.br

.br
.B samba_secrets_t

	/etc/samba/smbpasswd
.br
	/etc/samba/passdb\.tdb
.br
	/etc/samba/MACHINE\.SID
.br
	/etc/samba/secrets\.tdb
.br

.br
.B samba_var_t

	/var/lib/samba(/.*)?
.br
	/var/cache/samba(/.*)?
.br
	/var/spool/samba(/.*)?
.br

.br
.B swat_tmp_t


.br
.B swat_var_run_t


.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the swat_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the swat_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), swat(8), semanage(8), restorecon(8), chcon(1)
