.TH  "sysadm_selinux"  "8"  "sysadm" "mgrepl@redhat.com" "sysadm SELinux Policy documentation"
.SH "NAME"
sysadm_u \- \fBGeneral system administration role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

\fBsysadm_u\fP is an SELinux User defined in the SELinux
policy. SELinux users have default roles, \fBsysadm_r\fP.  The
default role has a default type, \fBsysadm_t\fP, associated with it.

The SELinux user will usually login to a system with a context that looks like:

.B sysadm_u:sysadm_r:sysadm_t:s0-s0:c0.c1023

Linux users are automatically assigned an SELinux users at login.  
Login programs use the SELinux User to assign initial context to the user's shell.

SELinux policy uses the context to control the user's access.

By default all users are assigned to the SELinux user via the \fB__default__\fP flag

On Targeted policy systems the \fB__default__\fP user is assigned to the \fBunconfined_u\fP SELinux user.

You can list all Linux User to SELinux user mapping using:

.B semanage login -l

If you wanted to change the default user mapping to use the sysadm_u user, you would execute:

.B semanage login -m -s sysadm_u __default__


If you want to map the one Linux user (joe) to the SELinux user sysadm, you would execute:

.B $ semanage login -a -s sysadm_u joe


.SH USER DESCRIPTION

The SELinux user sysadm_u is an admin user. It means that a mapped Linux user to this SELinux user is intended for administrative actions. Usually this is assigned to a root Linux user.  

.SH SUDO

The SELinux user sysadm can execute sudo. 

You can set up sudo to allow sysadm to transition to an administrative domain:

Add one or more of the following record to sudoers using visudo.


USERNAME ALL=(ALL) ROLE=auditadm_r TYPE=auditadm_t COMMAND
.br
sudo will run COMMAND as sysadm_u:auditadm_r:auditadm_t:LEVEL

You might also need to add one or more of these new roles to your SELinux user record.

List the SELinux roles your SELinux user can reach by executing:

.B $ semanage user -l |grep selinux_name

Modify the roles list and add sysadm_r to this list.

.B $ semanage user -m -R 'sysadm_r auditadm_r secadm_r staff_r user_r' sysadm_u 

For more details you can see semanage man page.


USERNAME ALL=(ALL) ROLE=secadm_r TYPE=secadm_t COMMAND
.br
sudo will run COMMAND as sysadm_u:secadm_r:secadm_t:LEVEL

You might also need to add one or more of these new roles to your SELinux user record.

List the SELinux roles your SELinux user can reach by executing:

.B $ semanage user -l |grep selinux_name

Modify the roles list and add sysadm_r to this list.

.B $ semanage user -m -R 'sysadm_r auditadm_r secadm_r staff_r user_r' sysadm_u 

For more details you can see semanage man page.


USERNAME ALL=(ALL) ROLE=staff_r TYPE=staff_t COMMAND
.br
sudo will run COMMAND as sysadm_u:staff_r:staff_t:LEVEL

You might also need to add one or more of these new roles to your SELinux user record.

List the SELinux roles your SELinux user can reach by executing:

.B $ semanage user -l |grep selinux_name

Modify the roles list and add sysadm_r to this list.

.B $ semanage user -m -R 'sysadm_r auditadm_r secadm_r staff_r user_r' sysadm_u 

For more details you can see semanage man page.


USERNAME ALL=(ALL) ROLE=user_r TYPE=user_t COMMAND
.br
sudo will run COMMAND as sysadm_u:user_r:user_t:LEVEL

You might also need to add one or more of these new roles to your SELinux user record.

List the SELinux roles your SELinux user can reach by executing:

.B $ semanage user -l |grep selinux_name

Modify the roles list and add sysadm_r to this list.

.B $ semanage user -m -R 'sysadm_r auditadm_r secadm_r staff_r user_r' sysadm_u 

For more details you can see semanage man page.


The SELinux type sysadm_t is not allowed to execute sudo. 

.SH X WINDOWS LOGIN

The SELinux user sysadm_u is able to X Windows login.

.SH NETWORK

.TP
The SELinux user sysadm_u is able to listen on the following tcp ports.

.B all ports with out defined types

.TP
The SELinux user sysadm_u is able to connect to the following tcp ports.

.B all ports

.TP
The SELinux user sysadm_u is able to listen on the following udp ports.

.B all ports with out defined types

.B ntp_port_t: 123

.TP
The SELinux user sysadm_u is able to connect to the following tcp ports.

.B all ports

.SH BOOLEANS
SELinux policy is customizable based on least access required.  sysadm policy is extremely flexible and has several booleans that allow you to manipulate the policy and run sysadm with the tightest access possible.


.PP
If you want to allow the graphical login program to login directly as sysadm_r:sysadm_t, you must turn on the xdm_sysadm_login boolean.

.EX
.B setsebool -P xdm_sysadm_login 1
.EE

.PP
If you want to allow ssh logins as sysadm_r:sysadm_t, you must turn on the ssh_sysadm_login boolean.

.EX
.B setsebool -P ssh_sysadm_login 1
.EE

.SH HOME_EXEC

The SELinux user sysadm_u is able execute home content files.

.SH TRANSITIONS

Three things can happen when sysadm_t attempts to execute a program.

\fB1.\fP SELinux Policy can deny sysadm_t from executing the program.

.TP

\fB2.\fP SELinux Policy can allow sysadm_t to execute the program in the current user type.

Execute the following to see the types that the SELinux user sysadm_t can execute without transitioning:

.B sesearch -A -s sysadm_t -c file -p execute_no_trans

.TP

\fB3.\fP SELinux can allow sysadm_t to execute the program and transition to a new type.

Execute the following to see the types that the SELinux user sysadm_t can execute and transition:

.B $ sesearch -A -s sysadm_t -c process -p transition


.SH "MANAGED FILES"

The SELinux user type sysadm_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B auditd_etc_t

	/etc/audit(/.*)?
.br

.br
.B auditd_log_t

	/var/log/audit(/.*)?
.br
	/var/log/audit\.log
.br

.br
.B boolean_type


.br
.B etc_runtime_t

	/[^/]+
.br
	/etc/mtab.*
.br
	/etc/blkid(/.*)?
.br
	/etc/nologin.*
.br
	/etc/\.fstab\.hal\..+
.br
	/halt
.br
	/fastboot
.br
	/poweroff
.br
	/etc/cmtab
.br
	/forcefsck
.br
	/\.autofsck
.br
	/\.suspended
.br
	/fsckoptions
.br
	/\.autorelabel
.br
	/etc/securetty
.br
	/etc/nohotplug
.br
	/etc/killpower
.br
	/etc/ioctl\.save
.br
	/etc/fstab\.REVOKE
.br
	/etc/network/ifstate
.br
	/etc/sysconfig/hwconf
.br
	/etc/ptal/ptal-printd-like
.br
	/etc/sysconfig/iptables\.save
.br
	/etc/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br
	/etc/X11/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br

.br
.B iceauth_home_t

	/root/\.DCOP.*
.br
	/root/\.ICEauthority.*
.br
	/home/[^/]*/\.DCOP.*
.br
	/home/[^/]*/\.ICEauthority.*
.br

.br
.B krb5_host_rcache_t

	/var/cache/krb5rcache(/.*)?
.br
	/var/tmp/nfs_0
.br
	/var/tmp/host_0
.br
	/var/tmp/imap_0
.br
	/var/tmp/HTTP_23
.br
	/var/tmp/HTTP_48
.br
	/var/tmp/ldap_55
.br
	/var/tmp/ldap_487
.br
	/var/tmp/ldapmap1_0
.br

.br
.B krb5_keytab_t

	/etc/krb5\.keytab
.br
	/etc/krb5kdc/kadm5\.keytab
.br
	/var/kerberos/krb5kdc/kadm5\.keytab
.br

.br
.B non_security_file_type


.br
.B noxattrfs

	all files on file systems which do not support extended attributes
.br

.br
.B screen_home_t

	/root/\.screen(/.*)?
.br
	/home/[^/]*/\.screen(/.*)?
.br
	/home/[^/]*/\.screenrc
.br

.br
.B sysctl_type


.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.br
.B systemd_unit_file_type


.br
.B usbfs_t


.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br

.br
.B user_fonts_t

	/root/\.fonts(/.*)?
.br
	/tmp/\.font-unix(/.*)?
.br
	/home/[^/]*/\.fonts(/.*)?
.br

.br
.B user_home_t

	/home/[^/]*/.+
.br

.br
.B user_home_type

	all user home files
.br

.br
.B user_tmp_type

	all user tmp files
.br

.br
.B user_tmpfs_type

	all user content in tmpfs file systems
.br

.br
.B xauth_home_t

	/root/\.xauth.*
.br
	/root/\.Xauth.*
.br
	/root/\.serverauth.*
.br
	/root/\.Xauthority.*
.br
	/var/lib/pqsql/\.xauth.*
.br
	/var/lib/pqsql/\.Xauthority.*
.br
	/var/lib/nxserver/home/\.xauth.*
.br
	/var/lib/nxserver/home/\.Xauthority.*
.br
	/home/[^/]*/\.xauth.*
.br
	/home/[^/]*/\.Xauth.*
.br
	/home/[^/]*/\.serverauth.*
.br
	/home/[^/]*/\.Xauthority.*
.br

.br
.B xserver_tmpfs_t


.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), sysadm(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)