.TH  "sysadm_selinux"  "8"  "sysadm" "mgrepl@redhat.com" "sysadm SELinux Policy documentation"
.SH "NAME"
sysadm_u \- \fBGeneral system administration role\fP - Security Enhanced Linux Policy

.SH DESCRIPTION

\fBsysadm_u\fP is an SELinux User defined in the SELinux
policy. SELinux users have default roles, \fBsysadm_r\fP.  The
default role has a default type, \fBsysadm_t\fP, associated with it.

The SELinux user will usually login to a system with a context that looks like:

.B sysadm_u:sysadm_r:sysadm_t:s0 - s0:c0.c1023

Linux users are automatically assigned an SELinux users at login.
Login programs use the SELinux User to assign initial context to the user's shell.

SELinux policy uses the context to control the user's access.

By default all users are assigned to the SELinux user via the \fB__default__\fP flag

On Targeted policy systems the \fB__default__\fP user is assigned to the \fBunconfined_u\fP SELinux user.

You can list all Linux User to SELinux user mapping using:

.B semanage login -l

If you wanted to change the default user mapping to use the sysadm_u user, you would execute:

.B semanage login -m -s sysadm_u __default__


If you want to map the one Linux user (joe) to the SELinux user sysadm, you would execute:

.B $ semanage login -a -s sysadm_u joe


.SH USER DESCRIPTION

The SELinux user sysadm_u is an admin user. It means that a mapped Linux user to this SELinux user is intended for administrative actions. Usually this is assigned to a root Linux user.

.SH SUDO

The SELinux user sysadm can execute sudo.

You can set up sudo to allow sysadm to transition to an administrative domain:

Add one or more of the following record to sudoers using visudo.


USERNAME ALL=(ALL) ROLE=auditadm_r TYPE=auditadm_t COMMAND
.br
sudo will run COMMAND as sysadm_u:auditadm_r:auditadm_t:LEVEL

You might also need to add one or more of these new roles to your SELinux user record.

List the SELinux roles your SELinux user can reach by executing:

.B $ semanage user -l |grep selinux_name

Modify the roles list and add sysadm_r to this list.

.B $ semanage user -m -R 'sysadm_r auditadm_r secadm_r staff_r user_r' sysadm_u

For more details you can see semanage man page.


USERNAME ALL=(ALL) ROLE=secadm_r TYPE=secadm_t COMMAND
.br
sudo will run COMMAND as sysadm_u:secadm_r:secadm_t:LEVEL

You might also need to add one or more of these new roles to your SELinux user record.

List the SELinux roles your SELinux user can reach by executing:

.B $ semanage user -l |grep selinux_name

Modify the roles list and add sysadm_r to this list.

.B $ semanage user -m -R 'sysadm_r auditadm_r secadm_r staff_r user_r' sysadm_u

For more details you can see semanage man page.


USERNAME ALL=(ALL) ROLE=staff_r TYPE=staff_t COMMAND
.br
sudo will run COMMAND as sysadm_u:staff_r:staff_t:LEVEL

You might also need to add one or more of these new roles to your SELinux user record.

List the SELinux roles your SELinux user can reach by executing:

.B $ semanage user -l |grep selinux_name

Modify the roles list and add sysadm_r to this list.

.B $ semanage user -m -R 'sysadm_r auditadm_r secadm_r staff_r user_r' sysadm_u

For more details you can see semanage man page.


USERNAME ALL=(ALL) ROLE=user_r TYPE=user_t COMMAND
.br
sudo will run COMMAND as sysadm_u:user_r:user_t:LEVEL

You might also need to add one or more of these new roles to your SELinux user record.

List the SELinux roles your SELinux user can reach by executing:

.B $ semanage user -l |grep selinux_name

Modify the roles list and add sysadm_r to this list.

.B $ semanage user -m -R 'sysadm_r auditadm_r secadm_r staff_r user_r' sysadm_u

For more details you can see semanage man page.


The SELinux type sysadm_t is not allowed to execute sudo.

.SH X WINDOWS LOGIN

The SELinux user sysadm_u is able to X Windows login.

.SH NETWORK

.TP
The SELinux user sysadm_u is able to listen on the following tcp ports.

.B all ports with out defined types

.B ephemeral_port_t: 32768-61000

.TP
The SELinux user sysadm_u is able to connect to the following tcp ports.

.B all ports

.TP
The SELinux user sysadm_u is able to listen on the following udp ports.

.B all ports with out defined types

.B ntp_port_t: 123

.B ephemeral_port_t: 32768-61000

.TP
The SELinux user sysadm_u is able to connect to the following tcp ports.

.B all ports

.SH BOOLEANS
SELinux policy is customizable based on least access required.  sysadm policy is extremely flexible and has several booleans that allow you to manipulate the policy and run sysadm with the tightest access possible.


.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd server, you must turn on the authlogin_nsswitch_use_ldap boolean. Disabled by default.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1

.EE

.PP
If you want to deny user domains applications to map a memory region as both executable and writable, this is dangerous and the executable should be reported in bugzilla, you must turn on the deny_execmem boolean. Enabled by default.

.EX
.B setsebool -P deny_execmem 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to determine whether calling user domains can execute Git daemon in the git_session_t domain, you must turn on the git_session_users boolean. Enabled by default.

.EX
.B setsebool -P git_session_users 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow confined applications to run with kerberos, you must turn on the kerberos_enabled boolean. Enabled by default.

.EX
.B setsebool -P kerberos_enabled 1

.EE

.PP
If you want to allow logging in and using the system from /dev/console, you must turn on the login_console_enabled boolean. Enabled by default.

.EX
.B setsebool -P login_console_enabled 1

.EE

.PP
If you want to allow system to run with NIS, you must turn on the nis_enabled boolean. Disabled by default.

.EX
.B setsebool -P nis_enabled 1

.EE

.PP
If you want to allow confined applications to use nscd shared memory, you must turn on the nscd_use_shm boolean. Disabled by default.

.EX
.B setsebool -P nscd_use_shm 1

.EE

.PP
If you want to determine whether calling user domains can execute Polipo daemon in the polipo_session_t domain, you must turn on the polipo_session_users boolean. Disabled by default.

.EX
.B setsebool -P polipo_session_users 1

.EE

.PP
If you want to allow database admins to execute DML statement, you must turn on the postgresql_selinux_unconfined_dbadm boolean. Enabled by default.

.EX
.B setsebool -P postgresql_selinux_unconfined_dbadm 1

.EE

.PP
If you want to disallow programs, such as newrole, from transitioning to administrative user domains, you must turn on the secure_mode boolean. Enabled by default.

.EX
.B setsebool -P secure_mode 1

.EE

.PP
If you want to boolean to determine whether the system permits loading policy, setting enforcing mode, and changing boolean values.  Set this to true and you have to reboot to set it back, you must turn on the secure_mode_policyload boolean. Enabled by default.

.EX
.B setsebool -P secure_mode_policyload 1

.EE

.PP
If you want to allow regular users direct dri device access, you must turn on the selinuxuser_direct_dri_enabled boolean. Enabled by default.

.EX
.B setsebool -P selinuxuser_direct_dri_enabled 1

.EE

.PP
If you want to allow unconfined executables to make their stack executable.  This should never, ever be necessary. Probably indicates a badly coded executable, but could indicate an attack. This executable should be reported in bugzilla, you must turn on the selinuxuser_execstack boolean. Enabled by default.

.EX
.B setsebool -P selinuxuser_execstack 1

.EE

.PP
If you want to allow users to connect to the local mysql server, you must turn on the selinuxuser_mysql_connect_enabled boolean. Disabled by default.

.EX
.B setsebool -P selinuxuser_mysql_connect_enabled 1

.EE

.PP
If you want to allow users to connect to PostgreSQL, you must turn on the selinuxuser_postgresql_connect_enabled boolean. Disabled by default.

.EX
.B setsebool -P selinuxuser_postgresql_connect_enabled 1

.EE

.PP
If you want to allow user to r/w files on filesystems that do not have extended attributes (FAT, CDROM, FLOPPY), you must turn on the selinuxuser_rw_noexattrfile boolean. Disabled by default.

.EX
.B setsebool -P selinuxuser_rw_noexattrfile 1

.EE

.PP
If you want to allow users to run TCP servers (bind to ports and accept connection from the same domain and outside users)  disabling this forces FTP passive mode and may change other protocols, you must turn on the selinuxuser_tcp_server boolean. Disabled by default.

.EX
.B setsebool -P selinuxuser_tcp_server 1

.EE

.PP
If you want to allow user  to use ssh chroot environment, you must turn on the selinuxuser_use_ssh_chroot boolean. Disabled by default.

.EX
.B setsebool -P selinuxuser_use_ssh_chroot 1

.EE

.PP
If you want to allow ssh logins as sysadm_r:sysadm_t, you must turn on the ssh_sysadm_login boolean. Disabled by default.

.EX
.B setsebool -P ssh_sysadm_login 1

.EE

.PP
If you want to support NFS home directories, you must turn on the use_nfs_home_dirs boolean. Enabled by default.

.EX
.B setsebool -P use_nfs_home_dirs 1

.EE

.PP
If you want to support SAMBA home directories, you must turn on the use_samba_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_samba_home_dirs 1

.EE

.PP
If you want to allow the graphical login program to login directly as sysadm_r:sysadm_t, you must turn on the xdm_sysadm_login boolean. Disabled by default.

.EX
.B setsebool -P xdm_sysadm_login 1

.EE

.PP
If you want to allows clients to write to the X server shared memory segments, you must turn on the xserver_clients_write_xshm boolean. Disabled by default.

.EX
.B setsebool -P xserver_clients_write_xshm 1

.EE

.PP
If you want to support X userspace object manager, you must turn on the xserver_object_manager boolean. Enabled by default.

.EX
.B setsebool -P xserver_object_manager 1

.EE

.SH HOME_EXEC

The SELinux user sysadm_u is able execute home content files.

.SH TRANSITIONS

Three things can happen when sysadm_t attempts to execute a program.

\fB1.\fP SELinux Policy can deny sysadm_t from executing the program.

.TP

\fB2.\fP SELinux Policy can allow sysadm_t to execute the program in the current user type.

Execute the following to see the types that the SELinux user sysadm_t can execute without transitioning:

.B search -A -s sysadm_t -c file -p execute_no_trans

.TP

\fB3.\fP SELinux can allow sysadm_t to execute the program and transition to a new type.

Execute the following to see the types that the SELinux user sysadm_t can execute and transition:

.B $ search -A -s sysadm_t -c process -p transition


.SH "MANAGED FILES"

The SELinux process type sysadm_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B auditd_etc_t

	/etc/audit(/.*)?
.br

.br
.B auditd_log_t

	/var/log/audit(/.*)?
.br
	/var/log/audit\.log
.br

.br
.B boolean_type


.br
.B cifs_t


.br
.B etc_runtime_t

	/[^/]+
.br
	/etc/mtab.*
.br
	/etc/blkid(/.*)?
.br
	/etc/nologin.*
.br
	/etc/\.fstab\.hal\..+
.br
	/halt
.br
	/fastboot
.br
	/poweroff
.br
	/etc/cmtab
.br
	/forcefsck
.br
	/\.autofsck
.br
	/\.suspended
.br
	/fsckoptions
.br
	/\.autorelabel
.br
	/etc/securetty
.br
	/etc/nohotplug
.br
	/etc/killpower
.br
	/etc/ioctl\.save
.br
	/etc/fstab\.REVOKE
.br
	/etc/network/ifstate
.br
	/etc/sysconfig/hwconf
.br
	/etc/ptal/ptal-printd-like
.br
	/etc/sysconfig/iptables\.save
.br
	/etc/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br
	/etc/X11/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br

.br
.B iceauth_home_t

	/root/\.DCOP.*
.br
	/root/\.ICEauthority.*
.br
	/home/[^/]*/\.DCOP.*
.br
	/home/[^/]*/\.ICEauthority.*
.br
	/home/pwalsh/\.DCOP.*
.br
	/home/pwalsh/\.ICEauthority.*
.br
	/home/dwalsh/\.DCOP.*
.br
	/home/dwalsh/\.ICEauthority.*
.br
	/var/lib/xguest/home/xguest/\.DCOP.*
.br
	/var/lib/xguest/home/xguest/\.ICEauthority.*
.br

.br
.B irc_home_t

	/home/[^/]*/\.irssi(/.*)?
.br
	/home/[^/]*/\.ircmotd
.br
	/home/pwalsh/\.irssi(/.*)?
.br
	/home/pwalsh/\.ircmotd
.br
	/home/dwalsh/\.irssi(/.*)?
.br
	/home/dwalsh/\.ircmotd
.br
	/var/lib/xguest/home/xguest/\.irssi(/.*)?
.br
	/var/lib/xguest/home/xguest/\.ircmotd
.br

.br
.B krb5_host_rcache_t

	/var/cache/krb5rcache(/.*)?
.br
	/var/tmp/nfs_0
.br
	/var/tmp/DNS_25
.br
	/var/tmp/host_0
.br
	/var/tmp/imap_0
.br
	/var/tmp/HTTP_23
.br
	/var/tmp/HTTP_48
.br
	/var/tmp/ldap_55
.br
	/var/tmp/ldap_487
.br
	/var/tmp/ldapmap1_0
.br

.br
.B krb5_keytab_t

	/etc/krb5\.keytab
.br
	/etc/krb5kdc/kadm5\.keytab
.br
	/var/kerberos/krb5kdc/kadm5\.keytab
.br

.br
.B non_security_file_type


.br
.B noxattrfs

	all files on file systems which do not support extended attributes
.br

.br
.B postfix_spool_type


.br
.B screen_home_t

	/root/\.screen(/.*)?
.br
	/home/[^/]*/\.screen(/.*)?
.br
	/home/[^/]*/\.screenrc
.br
	/home/pwalsh/\.screen(/.*)?
.br
	/home/pwalsh/\.screenrc
.br
	/home/dwalsh/\.screen(/.*)?
.br
	/home/dwalsh/\.screenrc
.br
	/var/lib/xguest/home/xguest/\.screen(/.*)?
.br
	/var/lib/xguest/home/xguest/\.screenrc
.br

.br
.B sysctl_type


.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.br
.B systemd_unit_file_type


.br
.B usbfs_t


.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br
	/home/pwalsh/\.fontconfig(/.*)?
.br
	/home/pwalsh/\.fonts/auto(/.*)?
.br
	/home/pwalsh/\.fonts\.cache-.*
.br
	/home/dwalsh/\.fontconfig(/.*)?
.br
	/home/dwalsh/\.fonts/auto(/.*)?
.br
	/home/dwalsh/\.fonts\.cache-.*
.br
	/var/lib/xguest/home/xguest/\.fontconfig(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts/auto(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts\.cache-.*
.br

.br
.B user_fonts_t

	/root/\.fonts(/.*)?
.br
	/tmp/\.font-unix(/.*)?
.br
	/home/[^/]*/\.fonts(/.*)?
.br
	/home/pwalsh/\.fonts(/.*)?
.br
	/home/dwalsh/\.fonts(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts(/.*)?
.br

.br
.B user_home_t

	/home/[^/]*/.+
.br
	/home/pwalsh/.+
.br
	/home/dwalsh/.+
.br
	/var/lib/xguest/home/xguest/.+
.br

.br
.B user_home_type

	all user home files
.br

.br
.B user_tmp_type

	all user tmp files
.br

.br
.B user_tmpfs_type

	all user content in tmpfs file systems
.br

.br
.B vmware_conf_t

	/home/[^/]*/\.vmware[^/]*/.*\.cfg
.br
	/home/pwalsh/\.vmware[^/]*/.*\.cfg
.br
	/home/dwalsh/\.vmware[^/]*/.*\.cfg
.br
	/var/lib/xguest/home/xguest/\.vmware[^/]*/.*\.cfg
.br

.br
.B vmware_tmp_t


.br
.B vmware_tmpfs_t


.br
.B xauth_home_t

	/root/\.xauth.*
.br
	/root/\.Xauth.*
.br
	/root/\.serverauth.*
.br
	/root/\.Xauthority.*
.br
	/var/lib/pqsql/\.xauth.*
.br
	/var/lib/pqsql/\.Xauthority.*
.br
	/var/lib/nxserver/home/\.xauth.*
.br
	/var/lib/nxserver/home/\.Xauthority.*
.br
	/home/[^/]*/\.xauth.*
.br
	/home/[^/]*/\.Xauth.*
.br
	/home/[^/]*/\.serverauth.*
.br
	/home/[^/]*/\.Xauthority.*
.br
	/home/pwalsh/\.xauth.*
.br
	/home/pwalsh/\.Xauth.*
.br
	/home/pwalsh/\.serverauth.*
.br
	/home/pwalsh/\.Xauthority.*
.br
	/home/dwalsh/\.xauth.*
.br
	/home/dwalsh/\.Xauth.*
.br
	/home/dwalsh/\.serverauth.*
.br
	/home/dwalsh/\.Xauthority.*
.br
	/var/lib/xguest/home/xguest/\.xauth.*
.br
	/var/lib/xguest/home/xguest/\.Xauth.*
.br
	/var/lib/xguest/home/xguest/\.serverauth.*
.br
	/var/lib/xguest/home/xguest/\.Xauthority.*
.br

.br
.B xserver_tmpfs_t


.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), sysadm(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8), sysadm_dbusd_selinux(8), sysadm_passwd_selinux(8), sysadm_screen_selinux(8), sysadm_seunshare_selinux(8), sysadm_ssh_agent_selinux(8), sysadm_su_selinux(8), sysadm_sudo_selinux(8)