.TH  "tcpd_selinux"  "8"  "tcpd" "dwalsh@redhat.com" "tcpd SELinux Policy documentation"
.SH "NAME"
tcpd_selinux \- Security Enhanced Linux Policy for the tcpd processes
.SH "DESCRIPTION"


SELinux Linux secures
.B tcpd
(Policy for TCP daemon)
processes via flexible mandatory access
control.  



.SH BOOLEANS
SELinux policy is customizable based on least access required.  tcpd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run tcpd with the tightest access possible.


.PP
If you want to allow the Telepathy connection managers to connect to any generic TCP port, you must turn on the telepathy_tcp_connect_generic_network_ports boolean.

.EX
.B setsebool -P telepathy_tcp_connect_generic_network_ports 1
.EE

.PP
If you want to allow all daemons to use tcp wrappers, you must turn on the allow_daemons_use_tcp_wrapper boolean.

.EX
.B setsebool -P allow_daemons_use_tcp_wrapper 1
.EE

.PP
If you want to allow users to run TCP servers (bind to ports and accept connection from the same domain and outside users)  disabling this forces FTP passive mode and may change other protocols, you must turn on the user_tcp_server boolean.

.EX
.B setsebool -P user_tcp_server 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux tcpd policy is very flexible allowing users to setup their tcpd processes in as secure a method as possible.
.PP 
The following file types are defined for tcpd:


.EX
.PP
.B tcpd_exec_t 
.EE

- Set files with the tcpd_exec_t type, if you want to transition an executable to the tcpd_t domain.


.EX
.PP
.B tcpd_tmp_t 
.EE

- Set files with the tcpd_tmp_t type, if you want to store tcpd temporary files in the /tmp directories.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux tcpd policy is very flexible allowing users to setup their tcpd processes in as secure a method as possible.
.PP 
The following process types are defined for tcpd:

.EX
.B tcpd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), tcpd(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)