.TH  "tgtd_selinux"  "8"  "tgtd" "dwalsh@redhat.com" "tgtd SELinux Policy documentation"
.SH "NAME"
tgtd_selinux \- Security Enhanced Linux Policy for the tgtd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the tgtd processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux tgtd policy is very flexible allowing users to setup their tgtd processes in as secure a method as possible.
.PP 
The following file types are defined for tgtd:


.EX
.B tgtd_exec_t 
.EE

- Set files with the tgtd_exec_t context, if you want to a executable to transition to the tgtd_t domain.

.br
Path: 
/usr/sbin/tgtd

.EX
.B tgtd_initrc_exec_t 
.EE

- Set files with the tgtd_initrc_exec_t context, if you want to a executable to transition to the tgtd_initrc_t domain.

.br
Path: 
/etc/rc\.d/init\.d/tgtd

.EX
.B tgtd_tmp_t 
.EE

- Set files with the tgtd_tmp_t context, if you want to store tgtd temporary files in the /tmp directories.


.EX
.B tgtd_tmpfs_t 
.EE

- Set files with the tgtd_tmpfs_t context, if you want to store tgtd files on a tmpfs file system.


.EX
.B tgtd_var_lib_t 
.EE

- Set files with the tgtd_var_lib_t context, if you want to store the tgtd files under the /var/lib directory.

.br
Path: 
/var/lib/tgtd(/.*)?

.EX
.B tgtd_var_run_t 
.EE

- Set files with the tgtd_var_run_t context, if you want to store the tgtd files under the /run directory.

.br
Path: 
/var/run/tgtd.*
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), tgtd(8), semanage(8), restorecon(8), chcon(1)
