.TH  "thumb_selinux"  "8"  "thumb" "dwalsh@redhat.com" "thumb SELinux Policy documentation"
.SH "NAME"
thumb_selinux \- Security Enhanced Linux Policy for the thumb processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the thumb processes via flexible mandatory access control.

The thumb processes execute with the thumb_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep thumb_t


.SH "ENTRYPOINTS"

The thumb_t SELinux type can be entered via the "thumb_exec_t" file type.  The default entrypoint paths for the thumb_t domain are the following:"

/usr/bin/whaaw-thumbnailer, /usr/lib/tumbler[^/]*/tumblerd, /usr/bin/raw-thumbnailer, /usr/bin/shotwell-video-thumbnailer, /usr/bin/evince-thumbnailer, /usr/bin/[^/]*thumbnailer, /usr/bin/ffmpegthumbnailer, /usr/bin/gsf-office-thumbnailer, /usr/bin/totem-video-thumbnailer, /usr/bin/gnome-thumbnail-font, /usr/bin/gnome-[^/]*-thumbnailer(.sh)?
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux thumb policy is very flexible allowing users to setup their thumb processes in as secure a method as possible.
.PP 
The following process types are defined for thumb:

.EX
.B thumb_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux thumb policy is very flexible allowing users to setup their thumb processes in as secure a method as possible.
.PP 
The following file types are defined for thumb:


.EX
.PP
.B thumb_exec_t 
.EE

- Set files with the thumb_exec_t type, if you want to transition an executable to the thumb_t domain.

.br
.TP 5
Paths: 
/usr/bin/whaaw-thumbnailer, /usr/lib/tumbler[^/]*/tumblerd, /usr/bin/raw-thumbnailer, /usr/bin/shotwell-video-thumbnailer, /usr/bin/evince-thumbnailer, /usr/bin/[^/]*thumbnailer, /usr/bin/ffmpegthumbnailer, /usr/bin/gsf-office-thumbnailer, /usr/bin/totem-video-thumbnailer, /usr/bin/gnome-thumbnail-font, /usr/bin/gnome-[^/]*-thumbnailer(.sh)?

.EX
.PP
.B thumb_home_t 
.EE

- Set files with the thumb_home_t type, if you want to store thumb files in the users home directory.


.EX
.PP
.B thumb_tmp_t 
.EE

- Set files with the thumb_tmp_t type, if you want to store thumb temporary files in the /tmp directories.


.EX
.PP
.B thumb_tmpfs_t 
.EE

- Set files with the thumb_tmpfs_t type, if you want to store thumb files on a tmpfs file system.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type thumb_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B gstreamer_home_t

	/var/run/user/[^/]*/\.orc(/.*)?
.br
	/root/\.gstreamer-.*
.br
	/home/[^/]*/\.orc(/.*)?
.br
	/home/[^/]*/\.gstreamer-.*
.br
	/home/[^/]*/\.grl-bookmarks
.br
	/home/[^/]*/\.grl-bookmarks
.br
	/home/[^/]*/\.grl-metadata-store
.br
	/home/dwalsh/\.orc(/.*)?
.br
	/home/dwalsh/\.gstreamer-.*
.br
	/home/dwalsh/\.grl-bookmarks
.br
	/home/dwalsh/\.grl-bookmarks
.br
	/home/dwalsh/\.grl-metadata-store
.br
	/var/lib/xguest/home/xguest/\.orc(/.*)?
.br
	/var/lib/xguest/home/xguest/\.gstreamer-.*
.br
	/var/lib/xguest/home/xguest/\.grl-bookmarks
.br
	/var/lib/xguest/home/xguest/\.grl-bookmarks
.br
	/var/lib/xguest/home/xguest/\.grl-metadata-store
.br

.br
.B thumb_home_t

	/home/[^/]*/\.thumbnails(/.*)?
.br
	/home/[^/]*/missfont\.log.*
.br
	/home/[^/]*/\.cache/thumbnails(/.*)?
.br
	/home/dwalsh/\.thumbnails(/.*)?
.br
	/home/dwalsh/missfont\.log.*
.br
	/home/dwalsh/\.cache/thumbnails(/.*)?
.br
	/var/lib/xguest/home/xguest/\.thumbnails(/.*)?
.br
	/var/lib/xguest/home/xguest/missfont\.log.*
.br
	/var/lib/xguest/home/xguest/\.cache/thumbnails(/.*)?
.br

.br
.B thumb_tmp_t


.br
.B thumb_tmpfs_t


.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br
	/home/dwalsh/\.fontconfig(/.*)?
.br
	/home/dwalsh/\.fonts/auto(/.*)?
.br
	/home/dwalsh/\.fonts\.cache-.*
.br
	/var/lib/xguest/home/xguest/\.fontconfig(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts/auto(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts\.cache-.*
.br

.br
.B user_tmp_t

	/var/run/user(/.*)?
.br
	/tmp/gconfd-.*
.br
	/tmp/gconfd-dwalsh
.br
	/tmp/gconfd-xguest
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the thumb_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the thumb_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), thumb(8), semanage(8), restorecon(8), chcon(1)
