.TH  "thumb_selinux"  "8"  "13-01-16" "thumb" "SELinux Policy documentation for thumb"
.SH "NAME"
thumb_selinux \- Security Enhanced Linux Policy for the thumb processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the thumb processes via flexible mandatory access control.

The thumb processes execute with the thumb_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep thumb_t


.SH "ENTRYPOINTS"

The thumb_t SELinux type can be entered via the \fBthumb_exec_t\fP file type.

The default entrypoint paths for the thumb_t domain are the following:

/usr/bin/[^/]*thumbnailer, /usr/bin/gnome-[^/]*-thumbnailer(.sh)?, /usr/lib/tumbler[^/]*/tumblerd, /usr/bin/raw-thumbnailer, /usr/bin/whaaw-thumbnailer, /usr/bin/ffmpegthumbnailer, /usr/bin/evince-thumbnailer, /usr/bin/gnome-thumbnail-font, /usr/bin/gsf-office-thumbnailer, /usr/bin/totem-video-thumbnailer, /usr/bin/shotwell-video-thumbnailer
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux thumb policy is very flexible allowing users to setup their thumb processes in as secure a method as possible.
.PP
The following process types are defined for thumb:

.EX
.B thumb_t
.EE
.PP
Note:
.B semanage permissive -a thumb_t
can be used to make the process type thumb_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  thumb policy is extremely flexible and has several booleans that allow you to manipulate the policy and run thumb with the tightest access possible.


.PP
If you want to deny user domains applications to map a memory region as both executable and writable, this is dangerous and the executable should be reported in bugzilla, you must turn on the deny_execmem boolean. Enabled by default.

.EX
.B setsebool -P deny_execmem 1

.EE

.PP
If you want to allow sysadm to debug or ptrace all processes, you must turn on the deny_ptrace boolean. Enabled by default.

.EX
.B setsebool -P deny_ptrace 1

.EE

.PP
If you want to allow all domains to use other domains file descriptors, you must turn on the domain_fd_use boolean. Enabled by default.

.EX
.B setsebool -P domain_fd_use 1

.EE

.PP
If you want to allow all domains to have the kernel load modules, you must turn on the domain_kernel_load_modules boolean. Disabled by default.

.EX
.B setsebool -P domain_kernel_load_modules 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.PP
If you want to enable reading of urandom for all domains, you must turn on the global_ssp boolean. Disabled by default.

.EX
.B setsebool -P global_ssp 1

.EE

.PP
If you want to allow all unconfined executables to use libraries requiring text relocation that are not labeled textrel_shlib_t, you must turn on the selinuxuser_execmod boolean. Enabled by default.

.EX
.B setsebool -P selinuxuser_execmod 1

.EE

.PP
If you want to support ecryptfs home directories, you must turn on the use_ecryptfs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_ecryptfs_home_dirs 1

.EE

.PP
If you want to support fusefs home directories, you must turn on the use_fusefs_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_fusefs_home_dirs 1

.EE

.PP
If you want to support NFS home directories, you must turn on the use_nfs_home_dirs boolean. Enabled by default.

.EX
.B setsebool -P use_nfs_home_dirs 1

.EE

.PP
If you want to support SAMBA home directories, you must turn on the use_samba_home_dirs boolean. Disabled by default.

.EX
.B setsebool -P use_samba_home_dirs 1

.EE

.SH "MANAGED FILES"

The SELinux process type thumb_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B cifs_t


.br
.B ecryptfs_t

	/home/[^/]*/\.Private(/.*)?
.br
	/home/[^/]*/\.ecryptfs(/.*)?
.br
	/home/pwalsh/\.Private(/.*)?
.br
	/home/pwalsh/\.ecryptfs(/.*)?
.br
	/home/dwalsh/\.Private(/.*)?
.br
	/home/dwalsh/\.ecryptfs(/.*)?
.br
	/var/lib/xguest/home/xguest/\.Private(/.*)?
.br
	/var/lib/xguest/home/xguest/\.ecryptfs(/.*)?
.br

.br
.B fusefs_t


.br
.B gstreamer_home_t

	/var/run/user/[^/]*/\.orc(/.*)?
.br
	/root/\.gstreamer-.*
.br
	/root/\.cache/gstreamer-.*
.br
	/home/[^/]*/\.orc(/.*)?
.br
	/home/[^/]*/\.gstreamer-.*
.br
	/home/[^/]*/\.cache/gstreamer-.*
.br
	/home/[^/]*/\.grl-bookmarks
.br
	/home/[^/]*/\.grl-bookmarks
.br
	/home/[^/]*/\.grl-metadata-store
.br
	/home/pwalsh/\.orc(/.*)?
.br
	/home/pwalsh/\.gstreamer-.*
.br
	/home/pwalsh/\.cache/gstreamer-.*
.br
	/home/pwalsh/\.grl-bookmarks
.br
	/home/pwalsh/\.grl-bookmarks
.br
	/home/pwalsh/\.grl-metadata-store
.br
	/home/dwalsh/\.orc(/.*)?
.br
	/home/dwalsh/\.gstreamer-.*
.br
	/home/dwalsh/\.cache/gstreamer-.*
.br
	/home/dwalsh/\.grl-bookmarks
.br
	/home/dwalsh/\.grl-bookmarks
.br
	/home/dwalsh/\.grl-metadata-store
.br
	/var/lib/xguest/home/xguest/\.orc(/.*)?
.br
	/var/lib/xguest/home/xguest/\.gstreamer-.*
.br
	/var/lib/xguest/home/xguest/\.cache/gstreamer-.*
.br
	/var/lib/xguest/home/xguest/\.grl-bookmarks
.br
	/var/lib/xguest/home/xguest/\.grl-bookmarks
.br
	/var/lib/xguest/home/xguest/\.grl-metadata-store
.br

.br
.B nfs_t


.br
.B thumb_home_t

	/home/[^/]*/\.thumbnails(/.*)?
.br
	/home/[^/]*/missfont\.log.*
.br
	/home/[^/]*/\.cache/thumbnails(/.*)?
.br
	/home/pwalsh/\.thumbnails(/.*)?
.br
	/home/pwalsh/missfont\.log.*
.br
	/home/pwalsh/\.cache/thumbnails(/.*)?
.br
	/home/dwalsh/\.thumbnails(/.*)?
.br
	/home/dwalsh/missfont\.log.*
.br
	/home/dwalsh/\.cache/thumbnails(/.*)?
.br
	/var/lib/xguest/home/xguest/\.thumbnails(/.*)?
.br
	/var/lib/xguest/home/xguest/missfont\.log.*
.br
	/var/lib/xguest/home/xguest/\.cache/thumbnails(/.*)?
.br

.br
.B thumb_tmp_t


.br
.B thumb_tmpfs_t


.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br
	/home/pwalsh/\.fontconfig(/.*)?
.br
	/home/pwalsh/\.fonts/auto(/.*)?
.br
	/home/pwalsh/\.fonts\.cache-.*
.br
	/home/dwalsh/\.fontconfig(/.*)?
.br
	/home/dwalsh/\.fonts/auto(/.*)?
.br
	/home/dwalsh/\.fonts\.cache-.*
.br
	/var/lib/xguest/home/xguest/\.fontconfig(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts/auto(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts\.cache-.*
.br

.br
.B user_tmp_t

	/var/run/user(/.*)?
.br
	/tmp/gconfd-.*
.br
	/tmp/gconfd-pwalsh
.br
	/tmp/gconfd-dwalsh
.br
	/tmp/gconfd-xguest
.br

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type.
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files.
SELinux thumb policy is very flexible allowing users to setup their thumb processes in as secure a method as possible.
.PP

.PP
.B STANDARD FILE CONTEXT

SELinux defines the file context types for the thumb, if you wanted to
store files with these types in a diffent paths, you need to execute the semanage command to sepecify alternate labeling and then use restorecon to put the labels on disk.

.B semanage fcontext -a -t thumb_exec_t '/srv/thumb/content(/.*)?'
.br
.B restorecon -R -v /srv/mythumb_content

Note: SELinux often uses regular expressions to specify labels that match multiple files.

.I The following file types are defined for thumb:


.EX
.PP
.B thumb_exec_t
.EE

- Set files with the thumb_exec_t type, if you want to transition an executable to the thumb_t domain.

.br
.TP 5
Paths:
/usr/bin/[^/]*thumbnailer, /usr/bin/gnome-[^/]*-thumbnailer(.sh)?, /usr/lib/tumbler[^/]*/tumblerd, /usr/bin/raw-thumbnailer, /usr/bin/whaaw-thumbnailer, /usr/bin/ffmpegthumbnailer, /usr/bin/evince-thumbnailer, /usr/bin/gnome-thumbnail-font, /usr/bin/gsf-office-thumbnailer, /usr/bin/totem-video-thumbnailer, /usr/bin/shotwell-video-thumbnailer

.EX
.PP
.B thumb_home_t
.EE

- Set files with the thumb_home_t type, if you want to store thumb files in the users home directory.

.br
.TP 5
Paths:
/home/[^/]*/\.thumbnails(/.*)?, /home/[^/]*/missfont\.log.*, /home/[^/]*/\.cache/thumbnails(/.*)?, /home/pwalsh/\.thumbnails(/.*)?, /home/pwalsh/missfont\.log.*, /home/pwalsh/\.cache/thumbnails(/.*)?, /home/dwalsh/\.thumbnails(/.*)?, /home/dwalsh/missfont\.log.*, /home/dwalsh/\.cache/thumbnails(/.*)?, /var/lib/xguest/home/xguest/\.thumbnails(/.*)?, /var/lib/xguest/home/xguest/missfont\.log.*, /var/lib/xguest/home/xguest/\.cache/thumbnails(/.*)?

.EX
.PP
.B thumb_tmp_t
.EE

- Set files with the thumb_tmp_t type, if you want to store thumb temporary files in the /tmp directories.


.EX
.PP
.B thumb_tmpfs_t
.EE

- Set files with the thumb_tmpfs_t type, if you want to store thumb files on a tmpfs file system.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage"
by Dan Walsh.

.SH "SEE ALSO"
selinux(8), thumb(8), semanage(8), restorecon(8), chcon(1), sepolicy(8)
, setsebool(8)