.TH  "udev_selinux"  "8"  "udev" "dwalsh@redhat.com" "udev SELinux Policy documentation"
.SH "NAME"
udev_selinux \- Security Enhanced Linux Policy for the udev processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the udev processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the udev_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the udev_t, you must turn on the kerberos_enabled boolean.

.EX
setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux udev policy is very flexible allowing users to setup their udev processes in as secure a method as possible.
.PP 
The following file types are defined for udev:


.EX
.PP
.B udev_etc_t 
.EE

- Set files with the udev_etc_t type, if you want to store udev files in the /etc directories.


.EX
.PP
.B udev_exec_t 
.EE

- Set files with the udev_exec_t type, if you want to transition an executable to the udev_t domain.

.br
.TP 5
Paths: 
/lib/udev/udevd, /usr/bin/udevinfo, /sbin/udevd, /sbin/udev, /usr/sbin/wait_for_sysfs, /sbin/udevsend, /usr/sbin/udevadm, /usr/bin/udevadm, /usr/sbin/start_udev, /usr/sbin/udev, /usr/sbin/udevsend, /sbin/start_udev, /sbin/udevstart, /bin/udevadm, /sbin/wait_for_sysfs, /lib/udev/udev-acl, /sbin/udevadm, /usr/sbin/udevd, /usr/lib/systemd/systemd-udevd, /usr/sbin/udevstart, /usr/lib/udev/udev-acl, /usr/lib/udev/udevd

.EX
.PP
.B udev_helper_exec_t 
.EE

- Set files with the udev_helper_exec_t type, if you want to transition an executable to the udev_helper_t domain.

.br
.TP 5
Paths: 
/etc/udev/scripts/.+, /etc/hotplug\.d/default/udev.*, /etc/dev\.d/.+

.EX
.PP
.B udev_rules_t 
.EE

- Set files with the udev_rules_t type, if you want to treat the files as udev rules data.


.EX
.PP
.B udev_var_run_t 
.EE

- Set files with the udev_var_run_t type, if you want to store the udev files under the /run directory.

.br
.TP 5
Paths: 
/var/run/udev(/.*)?, /dev/\.udevdb, /var/run/PackageKit/udev(/.*)?, /dev/\.udev(/.*)?, /dev/udev\.tbl, /var/run/libgpod(/.*)?

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux udev policy is very flexible allowing users to setup their udev processes in as secure a method as possible.
.PP 
The following process types are defined for udev:

.EX
.B udev_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), udev(8), semanage(8), restorecon(8), chcon(1)
