.TH  "unconfined_selinux"  "8"  "unconfined" "mgrepl@redhat.com" "unconfined SELinux Policy documentation"
.SH "NAME"
unconfined_r \- \fBUnconfiend user role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

SELinux supports Roles Based Access Control (RBAC), some Linux roles are login roles, while other roles need to be transition into. 

.I Note: 
Examples in this man page will use the 
.B staff_u 
SELinux user.

Non login roles are usually used for administrative tasks. For example, tasks that require root privileges.  Roles control which types a user can run processes with. Roles often have default types assigned to them. 

The default type for the unconfined_r role is unconfined_t.

The 
.B newrole 
program to transition directly to this role.

.B newrole -r unconfined_r -t unconfined_t

.B sudo 
is the preferred method to do transition from one role to another.  You setup sudo to transition to unconfined_r by adding a similar line to the /etc/sudoers file.

USERNAME ALL=(ALL) ROLE=unconfined_r TYPE=unconfined_t COMMAND

.br
sudo will run COMMAND as staff_u:unconfined_r:unconfined_t:LEVEL

When using a a non login role, you need to setup SELinux so that your SELinux user can reach unconfined_r role.

Execute the following to see all of the assigned SELinux roles:

.B semanage user -l

You need to add unconfined_r to the staff_u user.  You could setup the staff_u user to be able to use the unconfined_r role with a command like:

.B $ semanage user -m -R 'staff_r system_r unconfined_r' staff_u 


.SH BOOLEANS
SELinux policy is customizable based on least access required.  unconfined policy is extremely flexible and has several booleans that allow you to manipulate the policy and run unconfined with the tightest access possible.


.PP
If you want to allow unconfined users to transition to the Mozilla plugin domain when running xulrunner plugin-container, you must turn on the unconfined_mozilla_plugin_transition boolean.

.EX
.B setsebool -P unconfined_mozilla_plugin_transition 1
.EE

.PP
If you want to allow database admins to execute DML statement, you must turn on the postgresql_selinux_unconfined_dbadm boolean.

.EX
.B setsebool -P postgresql_selinux_unconfined_dbadm 1
.EE

.PP
If you want to allow a user to login as an unconfined domain, you must turn on the unconfined_login boolean.

.EX
.B setsebool -P unconfined_login 1
.EE

.PP
If you want to allow unconfined users to transition to the chrome sandbox domains when running chrome-sandbox, you must turn on the unconfined_chrome_sandbox_transition boolean.

.EX
.B setsebool -P unconfined_chrome_sandbox_transition 1
.EE

.PP
If you want to allow samba to run unconfined scripts, you must turn on the samba_run_unconfined boolean.

.EX
.B setsebool -P samba_run_unconfined 1
.EE

.PP
If you want to allow video playing tools to run unconfined, you must turn on the unconfined_mplayer boolean.

.EX
.B setsebool -P unconfined_mplayer 1
.EE

.SH "MANAGED FILES"

The SELinux process type unconfined_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B file_type

	all files on the system
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), unconfined(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)