.TH  "updfstab_selinux"  "8"  "updfstab" "dwalsh@redhat.com" "updfstab SELinux Policy documentation"
.SH "NAME"
updfstab_selinux \- Security Enhanced Linux Policy for the updfstab processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the updfstab processes via flexible mandatory access control.

The updfstab processes execute with the updfstab_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep updfstab_t


.SH "ENTRYPOINTS"

The updfstab_t SELinux type can be entered via the "updfstab_exec_t" file type.  The default entrypoint paths for the updfstab_t domain are the following:"

/usr/sbin/updfstab, /usr/sbin/fstab-sync
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux updfstab policy is very flexible allowing users to setup their updfstab processes in as secure a method as possible.
.PP 
The following process types are defined for updfstab:

.EX
.B updfstab_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux updfstab policy is very flexible allowing users to setup their updfstab processes in as secure a method as possible.
.PP 
The following file types are defined for updfstab:


.EX
.PP
.B updfstab_exec_t 
.EE

- Set files with the updfstab_exec_t type, if you want to transition an executable to the updfstab_t domain.

.br
.TP 5
Paths: 
/usr/sbin/updfstab, /usr/sbin/fstab-sync

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type updfstab_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B etc_t

	/etc/.*
.br
	/var/db/.*\.db
.br
	/usr/etc(/.*)?
.br
	/var/ftp/etc(/.*)?
.br
	/var/lib/stickshift/.limits.d(/.*)?
.br
	/var/lib/stickshift/.stickshift-proxy.d(/.*)?
.br
	/var/named/chroot/etc(/.*)?
.br
	/etc/ipsec\.d/examples(/.*)?
.br
	/var/spool/postfix/etc(/.*)?
.br
	/etc
.br
	/etc/localtime
.br
	/etc/cups/client\.conf
.br

.br
.B mnt_t

	/mnt(/[^/]*)
.br
	/mnt(/[^/]*)?
.br
	/rhev(/[^/]*)?
.br
	/media(/[^/]*)
.br
	/media(/[^/]*)?
.br
	/media/\.hal-.*
.br
	/var/run/media(/[^/]*)?
.br
	/net
.br
	/afs
.br
	/rhev
.br
	/misc
.br

.br
.B security_t

	/selinux
.br

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the updfstab_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the updfstab_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), updfstab(8), semanage(8), restorecon(8), chcon(1)
