.TH  "user_selinux"  "8"  "user" "mgrepl@redhat.com" "user SELinux Policy documentation"
.SH "NAME"
user_u \- Security Enhanced Linux Policy for the user SELinux user

.SH DESCRIPTION

\fBuser_u\fP is an SELinux User defined in the SELinux
policy. SELinux users have default roles, \fBuser_r\fP.  The
default role has a default type, \fBuser_t\fP, associated with it.

The SELinux user will usually login to a system with a context that looks like:

.B user_u:user_r:user_u:s0-s0:c0.c1023

Linux users are automatically assigned an SELinux users at login.  
Login programs use the SELinux User to assign initial context to the user's shell.

SELinux policy uses the context to control the user's access.

By default all users are assigned to the SELinux user via the \fB__default__\fP flag

On Targeted policy systems the \fB__default__\fP user is assigned to the \fBunconfined_u\fP SELinux user.

You can check your current Linux User to SELinux user mapping using

.B semanage login -l

If you want to just setup one linux user to be the SELinux user user_u, you would execute:

.B semanage login -m -s user_u USERNAME

If you wanted to change the default user mapping to use the user_u user, you would execute:

.B semanage login -m -s user_u __default__


.SH USER DESCRIPTION

The SELinux user user_u is defined in policy as a unpriviledged user. SELinux prevents unprivledged users from doing administration tasks without transitioning to a different role.

.SH SUDO

The SELinux type user_t is not allowed to execute sudo. 

.SH X WINDOWS LOGIN

The SELinux user user_u is able to X Windows login.

.SH NETWORK

.TP
The SELinux user user_u is able to listen on the following tcp ports.

.B xserver_port_t: 6000-6020

.TP
The SELinux user user_u is able to listen on the following udp ports.

.B all ports with out defined types

.TP
The SELinux user user_u is able to connect to the following tcp ports.

.B all ports

.SH BOOLEANS
SELinux policy is customizable based on least access required.  user_t policy is extremely flexible and has several booleans that allow you to manipulate the policy and run user_t with the tightest access possible.


.PP
If you want to allow users to connect to the local mysql serve, you must turn on the allow_user_mysql_connect boolean.

.EX
.B setsebool -P allow_user_mysql_connect 1
.EE

.PP
If you want to control users use of ping and tracerout, you must turn on the user_ping boolean.

.EX
.B setsebool -P user_ping 1
.EE

.PP
If you want to allow w to display everyon, you must turn on the user_ttyfile_stat boolean.

.EX
.B setsebool -P user_ttyfile_stat 1
.EE

.PP
If you want to allow user music sharin, you must turn on the user_share_music boolean.

.EX
.B setsebool -P user_share_music 1
.EE

.PP
If you want to allow regular users direct dri device acces, you must turn on the user_direct_dri boolean.

.EX
.B setsebool -P user_direct_dri 1
.EE

.PP
If you want to allow user to r/w files on filesystems that do not have extended attributes (FAT, CDROM, FLOPPY, you must turn on the user_rw_noexattrfile boolean.

.EX
.B setsebool -P user_rw_noexattrfile 1
.EE

.PP
If you want to allow users to run TCP servers (bind to ports and accept connection from the same domain and outside users)  disabling this forces FTP passive mode and may change other protocols, you must turn on the user_tcp_server boolean.

.EX
.B setsebool -P user_tcp_server 1
.EE

.PP
If you want to allow regular users direct mouse acces, you must turn on the user_direct_mouse boolean.

.EX
.B setsebool -P user_direct_mouse 1
.EE

.PP
If you want to allow user processes to change their priorit, you must turn on the user_setrlimit boolean.

.EX
.B setsebool -P user_setrlimit 1
.EE

.PP
If you want to allow users to connect to PostgreSQ, you must turn on the allow_user_postgresql_connect boolean.

.EX
.B setsebool -P allow_user_postgresql_connect 1
.EE

.PP
If you want to allow users to read system messages, you must turn on the user_dmesg boolean.

.EX
.B setsebool -P user_dmesg 1
.EE

.SH HOME_EXEC

The SELinux user user_u is able execute home content files.

.SH TRANSITIONS

Three things can happen when user_t attempts to execute a program.

\fB1.\fP SELinux Policy can deny user_t from executing the program.

.TP

\fB2.\fP SELinux Policy can allow user_t to execute the program in the current user type.

Execute the following to see the types that the SELinux user user_t can execute without transitioning:

.B sesearch -A -s user_t -c file -p execute_no_trans

.TP

\fB3.\fP SELinux can allow user_t to execute the program and transition to a new type.

Execue the following to see the types that the SELinux user user_t can execute and transition:

.B $ sesearch -A -s user_t -c process -p transition


.SH "COMMANDS"

.B semanage login
can also be used to manipulate the Linux User to SELinux User mappings

.B semanage user
can also be used to manipulate SELinux user definitions.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genuserman.py.

.SH "SEE ALSO"
selinux(8), semanage(8).
