.TH  "uucpd_selinux"  "8"  "uucpd" "dwalsh@redhat.com" "uucpd Selinux Policy documentation"
.SH "NAME"
uucpd_selinux \- Security Enhanced Linux Policy for the uucpd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the uucpd processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux uucpd policy is very flexible allowing users to setup their uucpd processes in as secure a method as possible.
.PP 
The following file types are defined for uucpd:


.EX
.B uucpd_exec_t 
.EE

- Set files with the uucpd_exec_t context, if you want to a executable to transition to the uucpd_t domain.

.br
Path: 
/usr/sbin/uucico

.EX
.B uucpd_lock_t 
.EE

- Set files with the uucpd_lock_t context, if you want to treat the files as uucpd lock data, stored under the /var/lock directory

.br
Path: 
/var/lock/uucp(/.*)?

.EX
.B uucpd_log_t 
.EE

- Set files with the uucpd_log_t context, if you want to treat the data as uucpd log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/uucp(/.*)?

.EX
.B uucpd_ro_t 
.EE

- Set files with the uucpd_ro_t context, if you want to treat the files as uucpd read/only content.


.EX
.B uucpd_rw_t 
.EE

- Set files with the uucpd_rw_t context, if you want to treat the files as uucpd read/write content.


.EX
.B uucpd_spool_t 
.EE

- Set files with the uucpd_spool_t context, if you want to store the uucpd files under the /var/spool directory.

.br
Paths: 
/var/spool/uucppublic(/.*)?, /var/spool/uucp(/.*)?

.EX
.B uucpd_tmp_t 
.EE

- Set files with the uucpd_tmp_t context, if you want to store uucpd temporary files in the /tmp directories.


.EX
.B uucpd_var_run_t 
.EE

- Set files with the uucpd_var_run_t context, if you want to store the uucpd files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), uucpd(8), semanage(8), restorecon(8), chcon(1)
