.TH  "varnishd_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "varnishd Selinux Policy documentation"
.SH "NAME"
varnishd_selinux \- Security Enhanced Linux Policy for the varnishd processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the varnishd processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux varnishd policy is very flexible allowing users to setup their varnishd processes in as secure a method as possible.
.PP 
The following file types are defined for varnishd:


.EX
.B varnishd_etc_t 
.EE

- Set files with the varnishd_etc_t context, if you want to store varnishd files in the /etc directories.


.EX
.B varnishd_exec_t 
.EE

- Set files with the varnishd_exec_t context, if you want to a executable to transition to the varnishd_t domain.


.EX
.B varnishd_initrc_exec_t 
.EE

- Set files with the varnishd_initrc_exec_t context, if you want to a executable to transition to the varnishd_initrc_t domain.


.EX
.B varnishd_tmp_t 
.EE

- Set files with the varnishd_tmp_t context, if you want to store varnishd temporary files in the /tmp directories.


.EX
.B varnishd_var_lib_t 
.EE

- Set files with the varnishd_var_lib_t context, if you want to store the varnishd files under the /var/lib directory.


.EX
.B varnishd_var_run_t 
.EE

- Set files with the varnishd_var_run_t context, if you want to store the varnishd files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  varnishd policy is extremely flexible and has several booleans that allow you to manipulate the policy and run varnishd with the tightest access possible.


.PP
If you want to allow varnishd to connect to all ports, not just HTTP., you must turn on the varnishd_connect_any boolean.

.EX
.B setsebool -P varnishd_connect_any 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), varnishd(8), semanage(8), restorecon(8), chcon(1), setsebool(8)