.TH  "vbetool_selinux"  "8"  "vbetool" "dwalsh@redhat.com" "vbetool Selinux Policy documentation"
.SH "NAME"
vbetool_selinux \- Security Enhanced Linux Policy for the vbetool processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the vbetool processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux vbetool policy is very flexible allowing users to setup their vbetool processes in as secure a method as possible.
.PP 
The following file types are defined for vbetool:


.EX
.B vbetool_exec_t 
.EE

- Set files with the vbetool_exec_t context, if you want to a executable to transition to the vbetool_t domain.

.br
Path: 
/usr/sbin/vbetool
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  vbetool policy is extremely flexible and has several booleans that allow you to manipulate the policy and run vbetool with the tightest access possible.


.PP
If you want to ignore vbetool mmap_zero errors, you must turn on the vbetool_mmap_zero_ignore boolean.

.EX
.B setsebool -P vbetool_mmap_zero_ignore 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), vbetool(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)