.TH  "virt_bridgehelper_selinux"  "8"  "virt_bridgehelper" "dwalsh@redhat.com" "virt_bridgehelper SELinux Policy documentation"
.SH "NAME"
virt_bridgehelper_selinux \- Security Enhanced Linux Policy for the virt_bridgehelper processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the virt_bridgehelper processes via flexible mandatory access control.

The virt_bridgehelper processes execute with the virt_bridgehelper_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier. 

For example:

.B ps -eZ | grep virt_bridgehelper_t


.SH "ENTRYPOINTS"

The virt_bridgehelper_t SELinux type can be entered via the "virt_bridgehelper_exec_t" file type.  The default entrypoint paths for the virt_bridgehelper_t domain are the following:"

/usr/libexec/qemu-bridge-helper
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux virt_bridgehelper policy is very flexible allowing users to setup their virt_bridgehelper processes in as secure a method as possible.
.PP 
The following process types are defined for virt_bridgehelper:

.EX
.B virt_bridgehelper_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux virt_bridgehelper policy is very flexible allowing users to setup their virt_bridgehelper processes in as secure a method as possible.
.PP 
The following file types are defined for virt_bridgehelper:


.EX
.PP
.B virt_bridgehelper_exec_t 
.EE

- Set files with the virt_bridgehelper_exec_t type, if you want to transition an executable to the virt_bridgehelper_t domain.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "MANAGED FILES"

The SELinux process type virt_bridgehelper_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B svirt_home_t

	/home/[^/]*/\.libvirt/qemu(/.*)?
.br
	/home/[^/]*/\.cache/libvirt/qemu(/.*)?
.br
	/home/[^/]*/\.config/libvirt/qemu(/.*)?
.br
	/home/[^/]*/\.local/share/gnome-boxes/images(/.*)?
.br
	/home/dwalsh/\.libvirt/qemu(/.*)?
.br
	/home/dwalsh/\.cache/libvirt/qemu(/.*)?
.br
	/home/dwalsh/\.config/libvirt/qemu(/.*)?
.br
	/home/dwalsh/\.local/share/gnome-boxes/images(/.*)?
.br
	/var/lib/xguest/home/xguest/\.libvirt/qemu(/.*)?
.br
	/var/lib/xguest/home/xguest/\.cache/libvirt/qemu(/.*)?
.br
	/var/lib/xguest/home/xguest/\.config/libvirt/qemu(/.*)?
.br
	/var/lib/xguest/home/xguest/\.local/share/gnome-boxes/images(/.*)?
.br

.SH NSSWITCH DOMAIN

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), virt_bridgehelper(8), semanage(8), restorecon(8), chcon(1)
, virt_qmf_selinux(8), virtd_selinux(8), virtd_lxc_selinux(8)