.TH  "vmware_selinux"  "8"  "vmware" "dwalsh@redhat.com" "vmware SELinux Policy documentation"
.SH "NAME"
vmware_selinux \- Security Enhanced Linux Policy for the vmware processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the vmware processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux vmware policy is very flexible allowing users to setup their vmware processes in as secure a method as possible.
.PP 
The following file types are defined for vmware:


.EX
.B vmware_conf_t 
.EE

- Set files with the vmware_conf_t context, if you want to treat the files as vmware configuration data, usually stored under the /etc directory.


.EX
.B vmware_exec_t 
.EE

- Set files with the vmware_exec_t context, if you want to a executable to transition to the vmware_t domain.

.br
Paths: 
/usr/lib/vmware/bin/vmware-mks, /usr/lib/vmware/bin/vmplayer, /usr/bin/vmware-ping, /usr/lib/vmware/bin/vmware-ui, /usr/sbin/vmware-serverd, /usr/bin/vmware, /usr/bin/vmware-wizard

.EX
.B vmware_file_t 
.EE

- Set files with the vmware_file_t context, if you want to treat the files as vmware content.


.EX
.B vmware_host_exec_t 
.EE

- Set files with the vmware_host_exec_t context, if you want to a executable to transition to the vmware_host_t domain.

.br
Paths: 
/usr/bin/vmware-smbpasswd\.bin, /usr/bin/vmware-smbd, /usr/lib/vmware-tools/sbin64/vmware.*, /usr/bin/vmnet-dhcpd, /usr/bin/vmnet-bridge, /usr/bin/vmware-nmbd, /usr/bin/vmnet-netifup, /usr/sbin/vmware-guest.*, /usr/bin/vmnet-natd, /usr/bin/vmware-vmx, /usr/bin/vmware-network, /usr/bin/vmnet-sniffer, /usr/bin/vmware-smbpasswd, /usr/lib/vmware-tools/sbin32/vmware.*, /usr/lib/vmware/bin/vmware-vmx

.EX
.B vmware_host_pid_t 
.EE

- Set files with the vmware_host_pid_t context, if you want to store the vmware host files under the /run directory.


.EX
.B vmware_host_tmp_t 
.EE

- Set files with the vmware_host_tmp_t context, if you want to store vmware host temporary files in the /tmp directories.


.EX
.B vmware_log_t 
.EE

- Set files with the vmware_log_t context, if you want to treat the data as vmware log data, usually stored under the /var/log directory.

.br
Paths: 
/var/log/vmware.*, /var/log/vnetlib.*

.EX
.B vmware_pid_t 
.EE

- Set files with the vmware_pid_t context, if you want to store the vmware files under the /run directory.


.EX
.B vmware_sys_conf_t 
.EE

- Set files with the vmware_sys_conf_t context, if you want to treat the files as vmware sys configuration data, usually stored under the /etc directory.

.br
Paths: 
/usr/lib/vmware/config, /etc/vmware.*(/.*)?

.EX
.B vmware_tmp_t 
.EE

- Set files with the vmware_tmp_t context, if you want to store vmware temporary files in the /tmp directories.


.EX
.B vmware_tmpfs_t 
.EE

- Set files with the vmware_tmpfs_t context, if you want to store vmware files on a tmpfs file system.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), vmware(8), semanage(8), restorecon(8), chcon(1)
