.TH  "vmware_host_selinux"  "8"  "vmware_host" "dwalsh@redhat.com" "vmware_host SELinux Policy documentation"
.SH "NAME"
vmware_host_selinux \- Security Enhanced Linux Policy for the vmware_host processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the vmware_host processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux vmware_host policy is very flexible allowing users to setup their vmware_host processes in as secure a method as possible.
.PP 
The following file types are defined for vmware_host:


.EX
.PP
.B vmware_host_exec_t 
.EE

- Set files with the vmware_host_exec_t type, if you want to transition an executable to the vmware_host_t domain.

.br
.TP 5
Paths: 
/usr/bin/vmware-smbpasswd\.bin, /usr/bin/vmware-smbd, /usr/lib/vmware-tools/sbin64/vmware.*, /usr/bin/vmnet-dhcpd, /usr/bin/vmnet-bridge, /usr/bin/vmware-nmbd, /usr/bin/vmnet-netifup, /usr/sbin/vmware-guest.*, /usr/bin/vmnet-natd, /usr/bin/vmware-vmx, /usr/bin/vmware-network, /usr/bin/vmnet-sniffer, /usr/bin/vmware-smbpasswd, /usr/lib/vmware-tools/sbin32/vmware.*, /usr/lib/vmware/bin/vmware-vmx

.EX
.PP
.B vmware_host_pid_t 
.EE

- Set files with the vmware_host_pid_t type, if you want to store the vmware host files under the /run directory.


.EX
.PP
.B vmware_host_tmp_t 
.EE

- Set files with the vmware_host_tmp_t type, if you want to store vmware host temporary files in the /tmp directories.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux vmware_host policy is very flexible allowing users to setup their vmware_host processes in as secure a method as possible.
.PP 
The following process types are defined for vmware_host:

.EX
.B vmware_host_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type vmware_host_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.br
.B vmware_host_pid_t


.br
.B vmware_host_tmp_t


.br
.B vmware_log_t

	/var/log/vmware.*
.br
	/var/log/vnetlib.*
.br

.br
.B vmware_sys_conf_t

	/etc/vmware.*(/.*)?
.br
	/usr/lib/vmware/config
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), vmware_host(8), semanage(8), restorecon(8), chcon(1)
, vmware_selinux(8)