.TH  "vpnc_selinux"  "8"  "16 Feb 2012" "dwalsh@redhat.com" "vpnc Selinux Policy documentation"
.SH "NAME"
vpnc_selinux \- Security Enhanced Linux Policy for the vpnc processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the vpnc processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux vpnc policy is very flexible allowing users to setup their vpnc processes in as secure a method as possible.
.PP 
The following file types are defined for vpnc:


.EX
.B vpnc_exec_t 
.EE

- Set files with the vpnc_exec_t context, if you want to a executable to transition to the vpnc_t domain.


.EX
.B vpnc_tmp_t 
.EE

- Set files with the vpnc_tmp_t context, if you want to store vpnc temporary files in the /tmp directories.


.EX
.B vpnc_var_run_t 
.EE

- Set files with the vpnc_var_run_t context, if you want to store the vpnc files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  vpnc policy is extremely flexible and has several booleans that allow you to manipulate the policy and run vpnc with the tightest access possible.


.PP
If you want to allow openvpn to read home directories, you must turn on the openvpn_enable_homedirs boolean.

.EX
.B setsebool -P openvpn_enable_homedirs 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), vpnc(8), semanage(8), restorecon(8), chcon(1), setsebool(8)