.TH  "vpnc_selinux"  "8"  "vpnc" "dwalsh@redhat.com" "vpnc Selinux Policy documentation"
.SH "NAME"
vpnc_selinux \- Security Enhanced Linux Policy for the vpnc processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the vpnc processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux vpnc policy is very flexible allowing users to setup their vpnc processes in as secure a method as possible.
.PP 
The following file types are defined for vpnc:


.EX
.B vpnc_exec_t 
.EE

- Set files with the vpnc_exec_t context, if you want to a executable to transition to the vpnc_t domain.

.br
Paths: 
/usr/sbin/vpnc, /usr/bin/openconnect, /sbin/vpnc

.EX
.B vpnc_tmp_t 
.EE

- Set files with the vpnc_tmp_t context, if you want to store vpnc temporary files in the /tmp directories.


.EX
.B vpnc_var_run_t 
.EE

- Set files with the vpnc_var_run_t context, if you want to store the vpnc files under the /run directory.

.br
Path: 
/var/run/vpnc(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), vpnc(8), semanage(8), restorecon(8), chcon(1)
