.TH  "webadm_selinux"  "8"  "webadm" "mgrepl@redhat.com" "webadm SELinux Policy documentation"
.SH "NAME"
webadm_r \- \fBWeb administrator role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

SELinux supports Roles Based Access Control (RBAC), some Linux roles are login roles, while other roles need to be transition into. 

.I Note: 
Examples in this man page will use the 
.B staff_u 
SELinux user.

Non login roles are usually used for administrative tasks. For example, tasks that require root privileges.  Roles control which types a user can run processes with. Roles often have default types assigned to them. 

The default type for the webadm_r role is webadm_t.

The 
.B newrole 
program to transition directly to this role.

.B newrole -r webadm_r -t webadm_t

.B sudo 
is the preferred method to do transition from one role to another.  You setup sudo to transition to webadm_r by adding a similar line to the /etc/sudoers file.

USERNAME ALL=(ALL) ROLE=webadm_r TYPE=webadm_t COMMAND

.br
sudo will run COMMAND as staff_u:webadm_r:webadm_t:LEVEL

When using a a non login role, you need to setup SELinux so that your SELinux user can reach webadm_r role.

Execute the following to see all of the assigned SELinux roles:

.B semanage user -l

You need to add webadm_r to the staff_u user.  You could setup the staff_u user to be able to use the webadm_r role with a command like:

.B $ semanage user -m -R 'staff_r system_r webadm_r' staff_u 



SELinux policy also controls which roles can transition to a different role.  
You can list these rules using the following command.

.B sesearch --role_allow

SELinux policy allows the staff_r, unconfined_r roles can transition to the webadm_r role.


.SH BOOLEANS
SELinux policy is customizable based on least access required.  webadm policy is extremely flexible and has several booleans that allow you to manipulate the policy and run webadm with the tightest access possible.


.PP
If you want to allow webadm to read files in users home directories, you must turn on the webadm_read_user_files boolean.

.EX
.B setsebool -P webadm_read_user_files 1
.EE

.PP
If you want to allow webadm to manage files in users home directories, you must turn on the webadm_manage_user_files boolean.

.EX
.B setsebool -P webadm_manage_user_files 1
.EE

.SH "MANAGED FILES"

The SELinux user type webadm_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B httpd_config_t

	/etc/httpd(/.*)?
.br
	/etc/apache(2)?(/.*)?
.br
	/etc/cherokee(/.*)?
.br
	/etc/lighttpd(/.*)?
.br
	/etc/apache-ssl(2)?(/.*)?
.br
	/var/lib/stickshift/.httpd.d(/.*)?
.br
	/etc/vhosts
.br

.br
.B httpd_lock_t


.br
.B httpd_log_t

	/var/www(/.*)?/logs(/.*)?
.br
	/var/log/cacti(/.*)?
.br
	/var/log/httpd(/.*)?
.br
	/var/log/apache(2)?(/.*)?
.br
	/var/log/cherokee(/.*)?
.br
	/var/log/lighttpd(/.*)?
.br
	/var/log/suphp\.log.*
.br
	/var/log/apache-ssl(2)?(/.*)?
.br
	/var/log/cgiwrap\.log.*
.br
	/var/log/roundcubemail(/.*)?
.br
	/var/log/dirsrv/admin-serv(/.*)?
.br
	/etc/httpd/logs
.br

.br
.B httpd_modules_t

	/usr/lib/httpd(/.*)?
.br
	/usr/lib/apache(/.*)?
.br
	/usr/lib/cherokee(/.*)?
.br
	/usr/lib/lighttpd(/.*)?
.br
	/usr/lib/apache2/modules(/.*)?
.br
	/etc/httpd/modules
.br

.br
.B httpd_php_tmp_t


.br
.B httpd_script_exec_type


.br
.B httpd_suexec_tmp_t


.br
.B httpd_tmp_t

	/var/run/user/apache(/.*)?
.br

.br
.B httpd_unit_file_t

	/usr/lib/systemd/system/httpd.*
.br
	/usr/lib/systemd/system/jetty.*
.br

.br
.B httpd_var_run_t

	/var/run/mod_.*
.br
	/var/run/wsgi.*
.br
	/var/run/httpd.*
.br
	/var/run/apache.*
.br
	/var/run/lighttpd(/.*)?
.br
	/var/lib/php/session(/.*)?
.br
	/var/run/dirsrv/admin-serv.*
.br
	/opt/dirsrv/var/run/dirsrv/dsgw/cookies(/.*)?
.br
	/var/run/gcache_port
.br
	/var/run/cherokee\.pid
.br

.br
.B httpdcontent


.br
.B public_content_rw_t

	/var/spool/abrt-upload(/.*)?
.br

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.br
.B var_lock_t

	/var/lock(/.*)?
.br
	/run/lock(/.*)?
.br
	/var/lock
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), webadm(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)