.TH  "xdm_selinux"  "8"  "xdm" "dwalsh@redhat.com" "xdm SELinux Policy documentation"
.SH "NAME"
xdm_selinux \- Security Enhanced Linux Policy for the xdm processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the xdm processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  xdm policy is extremely flexible and has several booleans that allow you to manipulate the policy and run xdm with the tightest access possible.


.PP
If you want to allow the graphical login program to login directly as sysadm_r:sysadm_t, you must turn on the xdm_sysadm_login boolean.

.EX
.B setsebool -P xdm_sysadm_login 1
.EE

.PP
If you want to allow the graphical login program to execute bootloader, you must turn on the xdm_exec_bootloader boolean.

.EX
.B setsebool -P xdm_exec_bootloader 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the xdm_dbusd_t, xdm_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the xdm_dbusd_t, xdm_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux xdm policy is very flexible allowing users to setup their xdm processes in as secure a method as possible.
.PP 
The following file types are defined for xdm:


.EX
.PP
.B xdm_etc_t 
.EE

- Set files with the xdm_etc_t type, if you want to store xdm files in the /etc directories.


.EX
.PP
.B xdm_exec_t 
.EE

- Set files with the xdm_exec_t type, if you want to transition an executable to the xdm_t domain.

.br
.TP 5
Paths: 
/usr/bin/slim, /usr/(s)?bin/lightdm*, /usr/(s)?bin/[mxgkw]dm, /usr/sbin/mdm-binary, /usr/(s)?bin/lxdm(-binary)?, /usr/X11R6/bin/[xgkw]dm, /usr/(s)?bin/gdm-binary, /usr/bin/gpe-dm, /opt/kde3/bin/kdm

.EX
.PP
.B xdm_home_t 
.EE

- Set files with the xdm_home_t type, if you want to store xdm files in the users home directory.

.br
.TP 5
Paths: 
/root/\.xsession-errors.*, /root/\.dmrc.*

.EX
.PP
.B xdm_lock_t 
.EE

- Set files with the xdm_lock_t type, if you want to treat the files as xdm lock data, stored under the /var/lock directory


.EX
.PP
.B xdm_log_t 
.EE

- Set files with the xdm_log_t type, if you want to treat the data as xdm log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/log/slim\.log, /var/log/lxdm\.log.*, /var/log/[mg]dm(/.*)?, /var/log/[mkwx]dm\.log.*

.EX
.PP
.B xdm_rw_etc_t 
.EE

- Set files with the xdm_rw_etc_t type, if you want to store xdm rw files in the /etc directories.

.br
.TP 5
Paths: 
/etc/opt/VirtualGL(/.*)?, /etc/X11/wdm(/.*)?

.EX
.PP
.B xdm_spool_t 
.EE

- Set files with the xdm_spool_t type, if you want to store the xdm files under the /var/spool directory.


.EX
.PP
.B xdm_tmp_t 
.EE

- Set files with the xdm_tmp_t type, if you want to store xdm temporary files in the /tmp directories.

.br
.TP 5
Paths: 
/tmp/\.X0-lock, /tmp/\.X11-unix(/.*)?, /tmp/\.ICE-unix(/.*)?

.EX
.PP
.B xdm_tmpfs_t 
.EE

- Set files with the xdm_tmpfs_t type, if you want to store xdm files on a tmpfs file system.


.EX
.PP
.B xdm_unconfined_exec_t 
.EE

- Set files with the xdm_unconfined_exec_t type, if you want to transition an executable to the xdm_unconfined_t domain.

.br
.TP 5
Paths: 
/etc/[mg]dm/Init(/.*)?, /etc/[mg]dm/PreSession(/.*)?, /etc/[mg]dm/PostLogin(/.*)?, /etc/[mg]dm/PostSession(/.*)?

.EX
.PP
.B xdm_var_lib_t 
.EE

- Set files with the xdm_var_lib_t type, if you want to store the xdm files under the /var/lib directory.

.br
.TP 5
Paths: 
/var/lib/lightdm(/.*)?, /var/cache/lightdm(/.*)?, /var/lib/[mxkwg]dm(/.*)?, /var/lib/lxdm(/.*)?, /var/cache/[mg]dm(/.*)?

.EX
.PP
.B xdm_var_run_t 
.EE

- Set files with the xdm_var_run_t type, if you want to store the xdm files under the /run directory.

.br
.TP 5
Paths: 
/etc/kde[34]?/kdm/backgroundrc, /var/run/slim.*, /var/run/lxdm(/.*)?, /usr/lib/qt-.*/etc/settings(/.*)?, /var/run/lxdm\.auth, /var/run/systemd/multi-session-x(/.*)?, /var/run/xauth(/.*)?, /var/run/xdmctl(/.*)?, /var/run/[gx]dm\.pid, /var/run/[kgm]dm(/.*)?, /var/run/slim(/.*)?, /var/run/gdm_socket, /var/run/lxdm\.pid, /var/run/lightdm(/.*)?

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux xdm policy is very flexible allowing users to setup their xdm processes in as secure a method as possible.
.PP 
The following port types are defined for xdm:

.EX
.TP 5
.B xdmcp_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 177
.EE
udp 177
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux xdm policy is very flexible allowing users to setup their xdm processes in as secure a method as possible.
.PP 
The following process types are defined for xdm:

.EX
.B xdm_t, xdm_dbusd_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type xdm_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B anon_inodefs_t


.br
.B auth_cache_t

	/var/cache/coolkey(/.*)?
.br

.br
.B auth_home_t

	/root/\.google_authenticator
.br
	/root/\.google_authenticator~
.br
	/home/[^/]*/\.google_authenticator
.br
	/home/[^/]*/\.google_authenticator~
.br

.br
.B cgroup_t

	/cgroup
.br
	/sys/fs/cgroup
.br

.br
.B etc_runtime_t

	/[^/]+
.br
	/etc/mtab.*
.br
	/etc/blkid(/.*)?
.br
	/etc/nologin.*
.br
	/etc/\.fstab\.hal\..+
.br
	/halt
.br
	/fastboot
.br
	/poweroff
.br
	/etc/cmtab
.br
	/forcefsck
.br
	/\.autofsck
.br
	/\.suspended
.br
	/fsckoptions
.br
	/\.autorelabel
.br
	/etc/securetty
.br
	/etc/nohotplug
.br
	/etc/killpower
.br
	/etc/ioctl\.save
.br
	/etc/fstab\.REVOKE
.br
	/etc/network/ifstate
.br
	/etc/sysconfig/hwconf
.br
	/etc/ptal/ptal-printd-like
.br
	/etc/sysconfig/iptables\.save
.br
	/etc/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br
	/etc/X11/xorg\.conf\.d/00-system-setup-keyboard\.conf
.br

.br
.B faillog_t

	/var/log/btmp.*
.br
	/var/run/faillock(/.*)?
.br
	/var/log/faillog
.br
	/var/log/tallylog
.br

.br
.B fonts_cache_t

	/var/cache/fontconfig(/.*)?
.br

.br
.B gconf_home_t

	/root/\.local.*
.br
	/root/\.gconf(d)?(/.*)?
.br
	/home/[^/]*/\.local.*
.br
	/home/[^/]*/\.gconf(d)?(/.*)?
.br

.br
.B gnome_home_type


.br
.B initrc_var_run_t

	/var/run/utmp
.br
	/var/run/random-seed
.br
	/var/run/runlevel\.dir
.br
	/var/run/setmixer_flag
.br

.br
.B krb5_host_rcache_t

	/var/cache/krb5rcache(/.*)?
.br
	/var/tmp/nfs_0
.br
	/var/tmp/host_0
.br
	/var/tmp/imap_0
.br
	/var/tmp/HTTP_23
.br
	/var/tmp/HTTP_48
.br
	/var/tmp/ldap_55
.br
	/var/tmp/ldap_487
.br
	/var/tmp/ldapmap1_0
.br

.br
.B lastlog_t

	/var/log/lastlog
.br

.br
.B locale_t

	/etc/locale.conf
.br
	/usr/lib/locale(/.*)?
.br
	/usr/share/locale(/.*)?
.br
	/usr/share/zoneinfo(/.*)?
.br
	/usr/share/X11/locale(/.*)?
.br
	/etc/timezone
.br
	/etc/localtime
.br
	/etc/sysconfig/clock
.br
	/etc/avahi/etc/localtime
.br
	/var/empty/sshd/etc/localtime
.br
	/var/spool/postfix/etc/localtime
.br

.br
.B pam_var_console_t

	/var/run/console(/.*)?
.br

.br
.B pam_var_run_t

	/var/(db|lib|adm)/sudo(/.*)?
.br
	/var/run/sudo(/.*)?
.br
	/var/run/sepermit(/.*)?
.br
	/var/run/pam_mount(/.*)?
.br

.br
.B pcscd_var_run_t

	/var/run/pcscd(/.*)?
.br
	/var/run/pcscd\.events(/.*)?
.br
	/var/run/pcscd\.pid
.br
	/var/run/pcscd\.pub
.br
	/var/run/pcscd\.comm
.br

.br
.B security_t

	/selinux
.br

.br
.B sysfs_t

	/sys(/.*)?
.br

.br
.B systemd_passwd_var_run_t

	/var/run/systemd/ask-password(/.*)?
.br
	/var/run/systemd/ask-password-block(/.*)?
.br

.br
.B user_fonts_t

	/root/\.fonts(/.*)?
.br
	/tmp/\.font-unix(/.*)?
.br
	/home/[^/]*/\.fonts(/.*)?
.br

.br
.B user_tmp_t

	/var/run/user(/.*)?
.br

.br
.B user_tmpfs_type

	all user content in tmpfs file systems
.br

.br
.B var_auth_t

	/var/ace(/.*)?
.br
	/var/rsa(/.*)?
.br
	/var/lib/abl(/.*)?
.br
	/var/lib/rsa(/.*)?
.br
	/var/lib/pam_ssh(/.*)?
.br
	/var/run/pam_ssh(/.*)?
.br
	/var/lib/pam_shield(/.*)?
.br
	/var/lib/google-authenticator(/.*)?
.br

.br
.B wtmp_t

	/var/log/wtmp.*
.br

.br
.B xauth_home_t

	/root/\.xauth.*
.br
	/root/\.Xauth.*
.br
	/root/\.serverauth.*
.br
	/root/\.Xauthority.*
.br
	/var/lib/pqsql/\.xauth.*
.br
	/var/lib/pqsql/\.Xauthority.*
.br
	/var/lib/nxserver/home/\.xauth.*
.br
	/var/lib/nxserver/home/\.Xauthority.*
.br
	/home/[^/]*/\.xauth.*
.br
	/home/[^/]*/\.Xauth.*
.br
	/home/[^/]*/\.serverauth.*
.br
	/home/[^/]*/\.Xauthority.*
.br

.br
.B xdm_home_t

	/root/\.dmrc.*
.br
	/root/\.xsession-errors.*
.br
	/home/[^/]*/\.dmrc.*
.br
	/home/[^/]*/\.cache/gdm(/.*)?
.br
	/home/[^/]*/\.xsession-errors.*
.br

.br
.B xdm_lock_t


.br
.B xdm_log_t

	/var/log/[mg]dm(/.*)?
.br
	/var/log/[mkwx]dm\.log.*
.br
	/var/log/lxdm\.log.*
.br
	/var/log/slim\.log
.br

.br
.B xdm_rw_etc_t

	/etc/X11/wdm(/.*)?
.br
	/etc/opt/VirtualGL(/.*)?
.br

.br
.B xdm_spool_t

	/var/spool/[mg]dm(/.*)?
.br

.br
.B xdm_tmp_t

	/tmp/\.X11-unix(/.*)?
.br
	/tmp/\.ICE-unix(/.*)?
.br
	/tmp/\.X0-lock
.br

.br
.B xdm_tmpfs_t


.br
.B xdm_var_lib_t

	/var/lib/[mxkwg]dm(/.*)?
.br
	/var/cache/[mg]dm(/.*)?
.br
	/var/lib/lxdm(/.*)?
.br
	/var/lib/lightdm(/.*)?
.br
	/var/cache/lightdm(/.*)?
.br

.br
.B xdm_var_run_t

	/etc/kde[34]?/kdm/backgroundrc
.br
	/var/run/[gx]dm\.pid
.br
	/var/run/[kgm]dm(/.*)?
.br
	/usr/lib/qt-.*/etc/settings(/.*)?
.br
	/var/run/slim.*
.br
	/var/run/lxdm(/.*)?
.br
	/var/run/slim(/.*)?
.br
	/var/run/xauth(/.*)?
.br
	/var/run/xdmctl(/.*)?
.br
	/var/run/lightdm(/.*)?
.br
	/var/run/systemd/multi-session-x(/.*)?
.br
	/var/run/lxdm\.pid
.br
	/var/run/lxdm\.auth
.br
	/var/run/gdm_socket
.br

.br
.B xkb_var_lib_t

	/var/lib/xkb(/.*)?
.br
	/usr/X11R6/lib/X11/xkb/.*
.br
	/usr/X11R6/lib/X11/xkb
.br

.br
.B xserver_log_t

	/var/[xgkw]dm(/.*)?
.br
	/usr/var/[xgkw]dm(/.*)?
.br
	/var/log/Xorg.*
.br
	/var/log/XFree86.*
.br
	/var/log/lightdm(/.*)?
.br
	/var/log/nvidia-installer\.log.*
.br

.br
.B xserver_tmpfs_t


.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), xdm(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)