.TH  "xdm_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "xdm Selinux Policy documentation"
.SH "NAME"
xdm_selinux \- Security Enhanced Linux Policy for the xdm processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the xdm processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux xdm policy is very flexible allowing users to setup their xdm processes in as secure a method as possible.
.PP 
The following file types are defined for xdm:


.EX
.B xdm_etc_t 
.EE

- Set files with the xdm_etc_t context, if you want to store xdm files in the /etc directories.


.EX
.B xdm_exec_t 
.EE

- Set files with the xdm_exec_t context, if you want to a executable to transition to the xdm_t domain.


.EX
.B xdm_home_t 
.EE

- Set files with the xdm_home_t context, if you want to store xdm files in the users home directory.


.EX
.B xdm_lock_t 
.EE

- Set files with the xdm_lock_t context, if you want to treat the files as xdm lock data, stored under the /var/lock directory


.EX
.B xdm_log_t 
.EE

- Set files with the xdm_log_t context, if you want to treat the data as xdm log data, usually stored under the /var/log directory.


.EX
.B xdm_rw_etc_t 
.EE

- Set files with the xdm_rw_etc_t context, if you want to store xdm rw files in the /etc directories.


.EX
.B xdm_spool_t 
.EE

- Set files with the xdm_spool_t context, if you want to store the xdm files under the /var/spool directory.


.EX
.B xdm_tmp_t 
.EE

- Set files with the xdm_tmp_t context, if you want to store xdm temporary files in the /tmp directories.


.EX
.B xdm_tmpfs_t 
.EE

- Set files with the xdm_tmpfs_t context, if you want to store xdm files on a tmpfs file system.


.EX
.B xdm_var_lib_t 
.EE

- Set files with the xdm_var_lib_t context, if you want to store the xdm files under the /var/lib directory.


.EX
.B xdm_var_run_t 
.EE

- Set files with the xdm_var_run_t context, if you want to store the xdm files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  xdm policy is extremely flexible and has several booleans that allow you to manipulate the policy and run xdm with the tightest access possible.


.PP
If you want to allow the graphical login program to login directly as sysadm_r:sysadm_, you must turn on the xdm_sysadm_login boolean.

.EX
.B setsebool -P xdm_sysadm_login 1
.EE

.PP
If you want to allow the graphical login program to execute bootloade, you must turn on the xdm_exec_bootloader boolean.

.EX
.B setsebool -P xdm_exec_bootloader 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), xdm(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)