.TH  "xend_selinux"  "8"  "xend" "dwalsh@redhat.com" "xend SELinux Policy documentation"
.SH "NAME"
xend_selinux \- Security Enhanced Linux Policy for the xend processes
.SH "DESCRIPTION"




.SH BOOLEANS
SELinux policy is customizable based on least access required.  xend policy is extremely flexible and has several booleans that allow you to manipulate the policy and run xend with the tightest access possible.


.PP
If you want to allow xen to manage nfs file, you must turn on the xen_use_nfs boolean.

.EX
.B setsebool -P xen_use_nfs 1
.EE

.PP
If you want to allow xend to run qemu-dm. Not required if using paravirt and no vfb, you must turn on the xend_run_qemu boolean.

.EX
.B setsebool -P xend_run_qemu 1
.EE

.PP
If you want to allow xend to run blktapctrl/tapdisk. Not required if using dedicated logical volumes for disk images, you must turn on the xend_run_blktap boolean.

.EX
.B setsebool -P xend_run_blktap 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux xend policy is very flexible allowing users to setup their xend processes in as secure a method as possible.
.PP 
The following file types are defined for xend:


.EX
.PP
.B xen_devpts_t 
.EE

- Set files with the xen_devpts_t type, if you want to treat the files as xen devpts data.


.EX
.PP
.B xen_image_t 
.EE

- Set files with the xen_image_t type, if you want to treat the files as xen image data.

.br
.TP 5
Paths: 
/xen(/.*)?, /var/lib/xen/images(/.*)?

.EX
.PP
.B xend_exec_t 
.EE

- Set files with the xend_exec_t type, if you want to transition an executable to the xend_t domain.


.EX
.PP
.B xend_tmp_t 
.EE

- Set files with the xend_tmp_t type, if you want to store xend temporary files in the /tmp directories.


.EX
.PP
.B xend_var_lib_t 
.EE

- Set files with the xend_var_lib_t type, if you want to store the xend files under the /var/lib directory.

.br
.TP 5
Paths: 
/var/lib/xen(/.*)?, /var/lib/xend(/.*)?

.EX
.PP
.B xend_var_log_t 
.EE

- Set files with the xend_var_log_t type, if you want to treat the data as xend var log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/log/xen(/.*)?, /var/log/xen-hotplug\.log, /var/log/xend\.log, /var/log/xend-debug\.log

.EX
.PP
.B xend_var_run_t 
.EE

- Set files with the xend_var_run_t type, if you want to store the xend files under the /run directory.

.br
.TP 5
Paths: 
/var/run/xenner(/.*)?, /var/run/xend(/.*)?, /var/run/xend\.pid

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux xend policy is very flexible allowing users to setup their xend processes in as secure a method as possible.
.PP 
The following port types are defined for xend:

.EX
.TP 5
.B xen_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 8021
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux xend policy is very flexible allowing users to setup their xend processes in as secure a method as possible.
.PP 
The following process types are defined for xend:

.EX
.B xend_t, xenstored_t, xenconsoled_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), xend(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)