.TH  "xguest_selinux"  "8"  "xguest" "mgrepl@redhat.com" "xguest SELinux Policy documentation"
.SH "NAME"
xguest_u \- \fBLeast privledge xwindows user role\fP - Security Enhanced Linux Policy 

.SH DESCRIPTION

\fBxguest_u\fP is an SELinux User defined in the SELinux
policy. SELinux users have default roles, \fBxguest_r\fP.  The
default role has a default type, \fBxguest_t\fP, associated with it.

The SELinux user will usually login to a system with a context that looks like:

.B xguest_u:xguest_r:xguest_t:s0-s0:c0.c1023

Linux users are automatically assigned an SELinux users at login.  
Login programs use the SELinux User to assign initial context to the user's shell.

SELinux policy uses the context to control the user's access.

By default all users are assigned to the SELinux user via the \fB__default__\fP flag

On Targeted policy systems the \fB__default__\fP user is assigned to the \fBunconfined_u\fP SELinux user.

You can list all Linux User to SELinux user mapping using:

.B semanage login -l

If you wanted to change the default user mapping to use the xguest_u user, you would execute:

.B semanage login -m -s xguest_u __default__


If you want to map the one Linux user (joe) to the SELinux user xguest, you would execute:

.B $ semanage login -a -s xguest_u joe


.SH USER DESCRIPTION

The SELinux user xguest_u is defined in policy as a unprivileged user. SELinux prevents unprivileged users from doing administration tasks without transitioning to a different role.

.SH SUDO

.SH X WINDOWS LOGIN

The SELinux user xguest_u is able to X Windows login.

.SH NETWORK

.TP
The SELinux user xguest_u is able to connect to the following tcp ports.

.B dns_port_t: 53

.B http_cache_port_t: 8080,8118,10001-10010

.B http_port_t: 80,81,443,488,8008,8009,8443

.B ocsp_port_t: 9080

.B squid_port_t: 3128,3401,4827

.B ephemeral_port_t: 32768-61000

.B kerberos_port_t: 88,750,4444

.B pulseaudio_port_t: 4713

.B flash_port_t: 843,1935

.B soundd_port_t: 8000,9433,16001

.B commplex_port_t: 5001

.B ipp_port_t: 631,8610-8614

.B transproxy_port_t: 8081

.B all ports with out defined types

.B ftp_port_t: 21,990

.B speech_port_t: 8036

.TP
The SELinux user xguest_u is able to connect to the following tcp ports.

.B dns_port_t: 53

.B http_cache_port_t: 8080,8118,10001-10010

.B http_port_t: 80,81,443,488,8008,8009,8443

.B ocsp_port_t: 9080

.B squid_port_t: 3128,3401,4827

.B ephemeral_port_t: 32768-61000

.B kerberos_port_t: 88,750,4444

.B pulseaudio_port_t: 4713

.B flash_port_t: 843,1935

.B soundd_port_t: 8000,9433,16001

.B commplex_port_t: 5001

.B ipp_port_t: 631,8610-8614

.B transproxy_port_t: 8081

.B all ports with out defined types

.B ftp_port_t: 21,990

.B speech_port_t: 8036

.SH BOOLEANS
SELinux policy is customizable based on least access required.  xguest policy is extremely flexible and has several booleans that allow you to manipulate the policy and run xguest with the tightest access possible.


.PP
If you want to allow xguest users to configure Network Manager and connect to apache ports, you must turn on the xguest_connect_network boolean.

.EX
.B setsebool -P xguest_connect_network 1
.EE

.PP
If you want to allow xguest users to mount removable media, you must turn on the xguest_mount_media boolean.

.EX
.B setsebool -P xguest_mount_media 1
.EE

.PP
If you want to allow xguest to use blue tooth devices, you must turn on the xguest_use_bluetooth boolean.

.EX
.B setsebool -P xguest_use_bluetooth 1
.EE

.SH HOME_EXEC

The SELinux user xguest_u is able execute home content files.

.SH TRANSITIONS

Three things can happen when xguest_t attempts to execute a program.

\fB1.\fP SELinux Policy can deny xguest_t from executing the program.

.TP

\fB2.\fP SELinux Policy can allow xguest_t to execute the program in the current user type.

Execute the following to see the types that the SELinux user xguest_t can execute without transitioning:

.B sesearch -A -s xguest_t -c file -p execute_no_trans

.TP

\fB3.\fP SELinux can allow xguest_t to execute the program and transition to a new type.

Execute the following to see the types that the SELinux user xguest_t can execute and transition:

.B $ sesearch -A -s xguest_t -c process -p transition


.SH "MANAGED FILES"

The SELinux process type xguest_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B anon_inodefs_t


.br
.B auth_cache_t

	/var/cache/coolkey(/.*)?
.br

.br
.B chrome_sandbox_tmpfs_t


.br
.B httpd_user_content_t

	/home/[^/]*/((www)|(web)|(public_html))(/.+)?
.br
	/home/dwalsh/((www)|(web)|(public_html))(/.+)?
.br
	/var/lib/xguest/home/xguest/((www)|(web)|(public_html))(/.+)?
.br

.br
.B httpd_user_htaccess_t

	/home/[^/]*/((www)|(web)|(public_html))(/.*)?/\.htaccess
.br
	/home/dwalsh/((www)|(web)|(public_html))(/.*)?/\.htaccess
.br
	/var/lib/xguest/home/xguest/((www)|(web)|(public_html))(/.*)?/\.htaccess
.br

.br
.B httpd_user_ra_content_t

	/home/[^/]*/((www)|(web)|(public_html))(/.*)?/logs(/.*)?
.br
	/home/dwalsh/((www)|(web)|(public_html))(/.*)?/logs(/.*)?
.br
	/var/lib/xguest/home/xguest/((www)|(web)|(public_html))(/.*)?/logs(/.*)?
.br

.br
.B httpd_user_rw_content_t


.br
.B httpd_user_script_exec_t

	/home/[^/]*/((www)|(web)|(public_html))/cgi-bin(/.+)?
.br
	/home/dwalsh/((www)|(web)|(public_html))/cgi-bin(/.+)?
.br
	/var/lib/xguest/home/xguest/((www)|(web)|(public_html))/cgi-bin(/.+)?
.br

.br
.B noxattrfs

	all files on file systems which do not support extended attributes
.br

.br
.B usbfs_t


.br
.B user_fonts_cache_t

	/root/\.fontconfig(/.*)?
.br
	/root/\.fonts/auto(/.*)?
.br
	/root/\.fonts\.cache-.*
.br
	/home/[^/]*/\.fontconfig(/.*)?
.br
	/home/[^/]*/\.fonts/auto(/.*)?
.br
	/home/[^/]*/\.fonts\.cache-.*
.br
	/home/dwalsh/\.fontconfig(/.*)?
.br
	/home/dwalsh/\.fonts/auto(/.*)?
.br
	/home/dwalsh/\.fonts\.cache-.*
.br
	/var/lib/xguest/home/xguest/\.fontconfig(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts/auto(/.*)?
.br
	/var/lib/xguest/home/xguest/\.fonts\.cache-.*
.br

.br
.B user_home_type

	all user home files
.br

.br
.B user_tmp_type

	all user tmp files
.br

.br
.B user_tmpfs_type

	all user content in tmpfs file systems
.br

.br
.B xdm_tmp_t

	/tmp/\.X11-unix(/.*)?
.br
	/tmp/\.ICE-unix(/.*)?
.br
	/tmp/\.X0-lock
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), xguest(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)