.TH  "xserver_selinux"  "8"  "xserver" "dwalsh@redhat.com" "xserver SELinux Policy documentation"
.SH "NAME"
xserver_selinux \- Security Enhanced Linux Policy for the xserver processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the xserver processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  xserver policy is extremely flexible and has several booleans that allow you to manipulate the policy and run xserver with the tightest access possible.


.PP
If you want to support X userspace object manage, you must turn on the xserver_object_manager boolean.

.EX
.B setsebool -P xserver_object_manager 1
.EE

.PP
If you want to allows XServer to execute writable memor, you must turn on the xserver_execmem boolean.

.EX
.B setsebool -P xserver_execmem 1
.EE

.PP
If you want to allow confined virtual guests to interact with the xserve, you must turn on the virt_use_xserver boolean.

.EX
.B setsebool -P virt_use_xserver 1
.EE

.PP
If you want to allows clients to write to the X server shared memory segments, you must turn on the xserver_clients_write_xshm boolean.

.EX
.B setsebool -P xserver_clients_write_xshm 1
.EE

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the xserver_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the xserver_t, you must turn on the kerberos_enabled boolean.

.EX
setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux xserver policy is very flexible allowing users to setup their xserver processes in as secure a method as possible.
.PP 
The following file types are defined for xserver:


.EX
.PP
.B xserver_exec_t 
.EE

- Set files with the xserver_exec_t type, if you want to transition an executable to the xserver_t domain.

.br
.TP 5
Paths: 
/usr/bin/Xair, /usr/X11R6/bin/Xwrapper, /usr/X11R6/bin/XFree86, /etc/init\.d/xfree86-common, /usr/X11R6/bin/Xorg, /usr/X11R6/bin/Xipaq, /usr/bin/Xephyr, /usr/bin/Xorg, /usr/X11R6/bin/X

.EX
.PP
.B xserver_log_t 
.EE

- Set files with the xserver_log_t type, if you want to treat the data as xserver log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/log/lightdm(/.*)?, /usr/var/[xgkw]dm(/.*)?, /var/log/nvidia-installer\.log.*, /var/[xgkw]dm(/.*)?, /var/log/XFree86.*, /var/log/Xorg.*

.EX
.PP
.B xserver_tmpfs_t 
.EE

- Set files with the xserver_tmpfs_t type, if you want to store xserver files on a tmpfs file system.


.EX
.PP
.B xserver_var_lib_t 
.EE

- Set files with the xserver_var_lib_t type, if you want to store the xserver files under the /var/lib directory.


.EX
.PP
.B xserver_var_run_t 
.EE

- Set files with the xserver_var_run_t type, if you want to store the xserver files under the /run directory.

.br
.TP 5
Paths: 
/var/run/xorg(/.*)?, /var/run/video.rom

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux xserver policy is very flexible allowing users to setup their xserver processes in as secure a method as possible.
.PP 
The following port types are defined for xserver:

.EX
.TP 5
.B xserver_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 6000-6020
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux xserver policy is very flexible allowing users to setup their xserver processes in as secure a method as possible.
.PP 
The following process types are defined for xserver:

.EX
.B xserver_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), xserver(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)