.TH  "zarafa_selinux"  "8"  "zarafa" "dwalsh@redhat.com" "zarafa SELinux Policy documentation"
.SH "NAME"
zarafa_selinux \- Security Enhanced Linux Policy for the zarafa processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the zarafa processes via flexible mandatory access
control.  
.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux zarafa policy is very flexible allowing users to setup their zarafa processes in as secure a method as possible.
.PP 
The following file types are defined for zarafa:


.EX
.B zarafa_deliver_exec_t 
.EE

- Set files with the zarafa_deliver_exec_t context, if you want to a executable to transition to the zarafa_deliver_t domain.

.br
Path: 
/usr/bin/zarafa-dagent

.EX
.B zarafa_deliver_log_t 
.EE

- Set files with the zarafa_deliver_log_t context, if you want to treat the data as zarafa deliver log data, usually stored under the /var/log directory.


.EX
.B zarafa_deliver_tmp_t 
.EE

- Set files with the zarafa_deliver_tmp_t context, if you want to store zarafa deliver temporary files in the /tmp directories.


.EX
.B zarafa_deliver_var_run_t 
.EE

- Set files with the zarafa_deliver_var_run_t context, if you want to store the zarafa deliver files under the /run directory.


.EX
.B zarafa_etc_t 
.EE

- Set files with the zarafa_etc_t context, if you want to store zarafa files in the /etc directories.

.br
Path: 
/etc/zarafa(/.*)?

.EX
.B zarafa_gateway_exec_t 
.EE

- Set files with the zarafa_gateway_exec_t context, if you want to a executable to transition to the zarafa_gateway_t domain.

.br
Path: 
/usr/bin/zarafa-gateway

.EX
.B zarafa_gateway_log_t 
.EE

- Set files with the zarafa_gateway_log_t context, if you want to treat the data as zarafa gateway log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/zarafa/gateway\.log

.EX
.B zarafa_gateway_var_run_t 
.EE

- Set files with the zarafa_gateway_var_run_t context, if you want to store the zarafa gateway files under the /run directory.

.br
Path: 
/var/run/zarafa-gateway\.pid

.EX
.B zarafa_ical_exec_t 
.EE

- Set files with the zarafa_ical_exec_t context, if you want to a executable to transition to the zarafa_ical_t domain.

.br
Path: 
/usr/bin/zarafa-ical

.EX
.B zarafa_ical_log_t 
.EE

- Set files with the zarafa_ical_log_t context, if you want to treat the data as zarafa ical log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/zarafa/ical\.log

.EX
.B zarafa_ical_var_run_t 
.EE

- Set files with the zarafa_ical_var_run_t context, if you want to store the zarafa ical files under the /run directory.

.br
Path: 
/var/run/zarafa-ical\.pid

.EX
.B zarafa_indexer_exec_t 
.EE

- Set files with the zarafa_indexer_exec_t context, if you want to a executable to transition to the zarafa_indexer_t domain.

.br
Path: 
/usr/bin/zarafa-indexer

.EX
.B zarafa_indexer_log_t 
.EE

- Set files with the zarafa_indexer_log_t context, if you want to treat the data as zarafa indexer log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/zarafa/indexer\.log

.EX
.B zarafa_indexer_tmp_t 
.EE

- Set files with the zarafa_indexer_tmp_t context, if you want to store zarafa indexer temporary files in the /tmp directories.


.EX
.B zarafa_indexer_var_run_t 
.EE

- Set files with the zarafa_indexer_var_run_t context, if you want to store the zarafa indexer files under the /run directory.

.br
Path: 
/var/run/zarafa-indexer

.EX
.B zarafa_monitor_exec_t 
.EE

- Set files with the zarafa_monitor_exec_t context, if you want to a executable to transition to the zarafa_monitor_t domain.

.br
Path: 
/usr/bin/zarafa-monitor

.EX
.B zarafa_monitor_log_t 
.EE

- Set files with the zarafa_monitor_log_t context, if you want to treat the data as zarafa monitor log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/zarafa/monitor\.log

.EX
.B zarafa_monitor_var_run_t 
.EE

- Set files with the zarafa_monitor_var_run_t context, if you want to store the zarafa monitor files under the /run directory.

.br
Path: 
/var/run/zarafa-monitor\.pid

.EX
.B zarafa_server_exec_t 
.EE

- Set files with the zarafa_server_exec_t context, if you want to a executable to transition to the zarafa_server_t domain.

.br
Path: 
/usr/bin/zarafa-server

.EX
.B zarafa_server_log_t 
.EE

- Set files with the zarafa_server_log_t context, if you want to treat the data as zarafa server log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/zarafa/server\.log

.EX
.B zarafa_server_tmp_t 
.EE

- Set files with the zarafa_server_tmp_t context, if you want to store zarafa server temporary files in the /tmp directories.


.EX
.B zarafa_server_var_run_t 
.EE

- Set files with the zarafa_server_var_run_t context, if you want to store the zarafa server files under the /run directory.

.br
Paths: 
/var/run/zarafa, /var/run/zarafa-server\.pid

.EX
.B zarafa_share_t 
.EE

- Set files with the zarafa_share_t context, if you want to treat the files as zarafa share data.


.EX
.B zarafa_spooler_exec_t 
.EE

- Set files with the zarafa_spooler_exec_t context, if you want to a executable to transition to the zarafa_spooler_t domain.

.br
Path: 
/usr/bin/zarafa-spooler

.EX
.B zarafa_spooler_log_t 
.EE

- Set files with the zarafa_spooler_log_t context, if you want to treat the data as zarafa spooler log data, usually stored under the /var/log directory.

.br
Path: 
/var/log/zarafa/spooler\.log

.EX
.B zarafa_spooler_var_run_t 
.EE

- Set files with the zarafa_spooler_var_run_t context, if you want to store the zarafa spooler files under the /run directory.

.br
Path: 
/var/run/zarafa-spooler\.pid

.EX
.B zarafa_var_lib_t 
.EE

- Set files with the zarafa_var_lib_t context, if you want to store the zarafa files under the /var/lib directory.

.br
Paths: 
/var/lib/zarafa-webaccess(/.*)?, /var/lib/zarafa(/.*)?
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), zarafa(8), semanage(8), restorecon(8), chcon(1)
