.TH  "zarafa_selinux"  "8"  "zarafa" "dwalsh@redhat.com" "zarafa SELinux Policy documentation"
.SH "NAME"
zarafa_selinux \- Security Enhanced Linux Policy for the zarafa processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the zarafa processes via flexible mandatory access
control.  

.SH NSSWITCH DOMAIN

.PP
If you want to allow users to resolve user passwd entries directly from ldap rather then using a sssd serve for the zarafa_deliver_t, zarafa_spooler_t, zarafa_gateway_t, zarafa_ical_t, zarafa_server_t, zarafa_monitor_t, zarafa_indexer_t, you must turn on the authlogin_nsswitch_use_ldap boolean.

.EX
.B setsebool -P authlogin_nsswitch_use_ldap 1
.EE

.PP
If you want to allow confined applications to run with kerberos for the zarafa_deliver_t, zarafa_spooler_t, zarafa_gateway_t, zarafa_ical_t, zarafa_server_t, zarafa_monitor_t, zarafa_indexer_t, you must turn on the kerberos_enabled boolean.

.EX
.B setsebool -P kerberos_enabled 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux zarafa policy is very flexible allowing users to setup their zarafa processes in as secure a method as possible.
.PP 
The following file types are defined for zarafa:


.EX
.PP
.B zarafa_deliver_exec_t 
.EE

- Set files with the zarafa_deliver_exec_t type, if you want to transition an executable to the zarafa_deliver_t domain.


.EX
.PP
.B zarafa_deliver_log_t 
.EE

- Set files with the zarafa_deliver_log_t type, if you want to treat the data as zarafa deliver log data, usually stored under the /var/log directory.


.EX
.PP
.B zarafa_deliver_tmp_t 
.EE

- Set files with the zarafa_deliver_tmp_t type, if you want to store zarafa deliver temporary files in the /tmp directories.


.EX
.PP
.B zarafa_deliver_var_run_t 
.EE

- Set files with the zarafa_deliver_var_run_t type, if you want to store the zarafa deliver files under the /run directory.


.EX
.PP
.B zarafa_etc_t 
.EE

- Set files with the zarafa_etc_t type, if you want to store zarafa files in the /etc directories.


.EX
.PP
.B zarafa_gateway_exec_t 
.EE

- Set files with the zarafa_gateway_exec_t type, if you want to transition an executable to the zarafa_gateway_t domain.


.EX
.PP
.B zarafa_gateway_log_t 
.EE

- Set files with the zarafa_gateway_log_t type, if you want to treat the data as zarafa gateway log data, usually stored under the /var/log directory.


.EX
.PP
.B zarafa_gateway_var_run_t 
.EE

- Set files with the zarafa_gateway_var_run_t type, if you want to store the zarafa gateway files under the /run directory.


.EX
.PP
.B zarafa_ical_exec_t 
.EE

- Set files with the zarafa_ical_exec_t type, if you want to transition an executable to the zarafa_ical_t domain.


.EX
.PP
.B zarafa_ical_log_t 
.EE

- Set files with the zarafa_ical_log_t type, if you want to treat the data as zarafa ical log data, usually stored under the /var/log directory.


.EX
.PP
.B zarafa_ical_var_run_t 
.EE

- Set files with the zarafa_ical_var_run_t type, if you want to store the zarafa ical files under the /run directory.


.EX
.PP
.B zarafa_indexer_exec_t 
.EE

- Set files with the zarafa_indexer_exec_t type, if you want to transition an executable to the zarafa_indexer_t domain.


.EX
.PP
.B zarafa_indexer_log_t 
.EE

- Set files with the zarafa_indexer_log_t type, if you want to treat the data as zarafa indexer log data, usually stored under the /var/log directory.


.EX
.PP
.B zarafa_indexer_tmp_t 
.EE

- Set files with the zarafa_indexer_tmp_t type, if you want to store zarafa indexer temporary files in the /tmp directories.


.EX
.PP
.B zarafa_indexer_var_run_t 
.EE

- Set files with the zarafa_indexer_var_run_t type, if you want to store the zarafa indexer files under the /run directory.

.br
.TP 5
Paths: 
/var/run/zarafa-indexer\.pid, /var/run/zarafa-indexer

.EX
.PP
.B zarafa_monitor_exec_t 
.EE

- Set files with the zarafa_monitor_exec_t type, if you want to transition an execut