.TH  "zebra_selinux"  "8"  "zebra" "dwalsh@redhat.com" "zebra SELinux Policy documentation"
.SH "NAME"
zebra_selinux \- Security Enhanced Linux Policy for the zebra processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the zebra processes via flexible mandatory access
control.  

.SH BOOLEANS
SELinux policy is customizable based on least access required.  zebra policy is extremely flexible and has several booleans that allow you to manipulate the policy and run zebra with the tightest access possible.


.PP
If you want to allow zebra daemon to write it configuration files, you must turn on the zebra_write_config boolean.

.EX
.B setsebool -P zebra_write_config 1
.EE

.SH NSSWITCH DOMAIN

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux zebra policy is very flexible allowing users to setup their zebra processes in as secure a method as possible.
.PP 
The following file types are defined for zebra:


.EX
.PP
.B zebra_conf_t 
.EE

- Set files with the zebra_conf_t type, if you want to treat the files as zebra configuration data, usually stored under the /etc directory.

.br
.TP 5
Paths: 
/etc/zebra(/.*)?, /etc/quagga(/.*)?

.EX
.PP
.B zebra_exec_t 
.EE

- Set files with the zebra_exec_t type, if you want to transition an executable to the zebra_t domain.

.br
.TP 5
Paths: 
/usr/sbin/zebra, /usr/sbin/rip.*, /usr/sbin/bgpd, /usr/sbin/ospf.*

.EX
.PP
.B zebra_initrc_exec_t 
.EE

- Set files with the zebra_initrc_exec_t type, if you want to transition an executable to the zebra_initrc_t domain.

.br
.TP 5
Paths: 
/etc/rc\.d/init\.d/ripd, /etc/rc\.d/init\.d/ripngd, /etc/rc\.d/init\.d/zebra, /etc/rc\.d/init\.d/bgpd, /etc/rc\.d/init\.d/ospf6d, /etc/rc\.d/init\.d/ospfd

.EX
.PP
.B zebra_log_t 
.EE

- Set files with the zebra_log_t type, if you want to treat the data as zebra log data, usually stored under the /var/log directory.

.br
.TP 5
Paths: 
/var/log/quagga(/.*)?, /var/log/zebra(/.*)?

.EX
.PP
.B zebra_tmp_t 
.EE

- Set files with the zebra_tmp_t type, if you want to store zebra temporary files in the /tmp directories.


.EX
.PP
.B zebra_var_run_t 
.EE

- Set files with the zebra_var_run_t type, if you want to store the zebra files under the /run directory.

.br
.TP 5
Paths: 
/var/run/\.zserv, /var/run/\.zebra, /var/run/quagga(/.*)?

.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanently change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PORT TYPES
SELinux defines port types to represent TCP and UDP ports. 
.PP
You can see the types associated with a port by using the following command: 

.B semanage port -l

.PP
Policy governs the access confined processes have to these ports. 
SELinux zebra policy is very flexible allowing users to setup their zebra processes in as secure a method as possible.
.PP 
The following port types are defined for zebra:

.EX
.TP 5
.B zebra_port_t 
.TP 10
.EE


Default Defined Ports:
tcp 2600-2604,2606
.EE
udp 2600-2604,2606
.EE
.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux zebra policy is very flexible allowing users to setup their zebra processes in as secure a method as possible.
.PP 
The following process types are defined for zebra:

.EX
.B zebra_t 
.EE
.PP
Note: 
.B semanage permissive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "MANAGED FILES"

The SELinux user type zebra_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B zebra_log_t

	/var/log/zebra(/.*)?
.br
	/var/log/quagga(/.*)?
.br

.br
.B zebra_var_run_t

	/var/run/quagga(/.*)?
.br
	/var/run/\.zebra
.br
	/var/run/\.zserv
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage port
can also be used to manipulate the port definitions

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was auto-generated by genman.py.

.SH "SEE ALSO"
selinux(8), zebra(8), semanage(8), restorecon(8), chcon(1)
, setsebool(8)