.TH  "zebra_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "zebra Selinux Policy documentation"
.SH "NAME"
zebra_selinux \- Security Enhanced Linux Policy for the zebra processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the zebra processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux zebra policy is very flexible allowing users to setup their zebra processes in as secure a method as possible.
.PP 
The following file types are defined for zebra:


.EX
.B zebra_conf_t 
.EE

- Set files with the zebra_conf_t context, if you want to treat the files as zebra configuration data.


.EX
.B zebra_exec_t 
.EE

- Set files with the zebra_exec_t context, if you want to a executable to transition to the zebra_t domain.


.EX
.B zebra_initrc_exec_t 
.EE

- Set files with the zebra_initrc_exec_t context, if you want to a executable to transition to the zebra_initrc_t domain.


.EX
.B zebra_log_t 
.EE

- Set files with the zebra_log_t context, if you want to treat the data as zebra log data, usually stored in /var/log.


.EX
.B zebra_tmp_t 
.EE

- Set files with the zebra_tmp_t context, if you want to store zebra temporary files in the /tmp directories.


.EX
.B zebra_var_run_t 
.EE

- Set files with the zebra_var_run_t context, if you want to store the zebra files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  zebra policy is extremely flexible and has several booleans that allow you to manipulate the policy and run zebra with the tightest access possible.


.PP
If you want to allow zebra daemon to write it configuration file, you must turn on the allow_zebra_write_config boolean.

.EX
.B setsebool -P allow_zebra_write_config 1
.EE

.SH "COMMANDS"

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), zebra(8), semanage(8), restorecon(8), chcon(1), setsebool(8)