.TH  "zoneminder_selinux"  "8"  "20 Feb 2012" "dwalsh@redhat.com" "zoneminder Selinux Policy documentation"
.SH "NAME"
zoneminder_selinux \- Security Enhanced Linux Policy for the zoneminder processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the zoneminder processes via flexible mandatory access
control.  
.SH FILE_CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
Policy governs the access confined processes have to these files. 
SELinux zoneminder policy is very flexible allowing users to setup their zoneminder processes in as secure a method as possible.
.PP 
The following file types are defined for zoneminder:


.EX
.B zoneminder_exec_t 
.EE

- Set files with the zoneminder_exec_t context, if you want to a executable to transition to the zoneminder_t domain.


.EX
.B zoneminder_initrc_exec_t 
.EE

- Set files with the zoneminder_initrc_exec_t context, if you want to a executable to transition to the zoneminder_initrc_t domain.


.EX
.B zoneminder_log_t 
.EE

- Set files with the zoneminder_log_t context, if you want to treat the data as zoneminder log data, usually stored in /var/log.


.EX
.B zoneminder_spool_t 
.EE

- Set files with the zoneminder_spool_t context, if you want to store the zoneminder files in the /var/spool directories.


.EX
.B zoneminder_tmpfs_t 
.EE

- Set files with the zoneminder_tmpfs_t context, if you want to store zoneminder files on a tmpfs file system.


.EX
.B zoneminder_var_lib_t 
.EE

- Set files with the zoneminder_var_lib_t context, if you want to store the zoneminder files under the /var/lib directory.


.EX
.B zoneminder_var_run_t 
.EE

- Set files with the zoneminder_var_run_t context, if you want to store the zoneminder files under the /run directory.

Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow zoneminder servers to read the /var/zoneminder directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/zoneminder(/.*)?"
.TP
.B
restorecon -F -R -v /var/zoneminder
.pp
.TP
Allow zoneminder servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_zoneminderd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/zoneminder/incoming(/.*)?"
.TP
.B
restorecon -F -R -v /var/zoneminder/incoming


.PP
If you want to allow ZoneMinder to modify public files used for public file transfer services., you must turn on the zoneminder_anon_write boolean.

.EX
.B setsebool -P zoneminder_anon_write 1
.EE

.SH "COMMANDS"

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
selinux(8), zoneminder(8), semanage(8), restorecon(8), chcon(1)