.TH  "zoneminder_selinux"  "8"  "zoneminder" "dwalsh@redhat.com" "zoneminder SELinux Policy documentation"
.SH "NAME"
zoneminder_selinux \- Security Enhanced Linux Policy for the zoneminder processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the zoneminder processes via flexible mandatory access
control.  

.SH SHARING FILES
If you want to share files with multiple domains (Apache, FTP, rsync, Samba), you can set a file context of public_content_t and public_content_rw_t.  These context allow any of the above domains to read the content.  If you want a particular domain to write to the public_content_rw_t domain, you must set the appropriate boolean.
.TP
Allow zoneminder servers to read the /var/zoneminder directory by adding the public_content_t file type to the directory and by restoring the file type.
.PP
.B
semanage fcontext -a -t public_content_t "/var/zoneminder(/.*)?"
.br
.B restorecon -F -R -v /var/zoneminder
.pp
.TP
Allow zoneminder servers to read and write /var/tmp/incoming by adding the public_content_rw_t type to the directory and by restoring the file type.  This also requires the allow_zoneminderd_anon_write boolean to be set.
.PP
.B
semanage fcontext -a -t public_content_rw_t "/var/zoneminder/incoming(/.*)?"
.br
.B restorecon -F -R -v /var/zoneminder/incoming


.PP
If you want to allow ZoneMinder to modify public files used for public file transfer services., you must turn on the zoneminder_anon_write boolean.

.EX
.B setsebool -P zoneminder_anon_write 1
.EE

.SH FILE CONTEXTS
SELinux requires files to have an extended attribute to define the file type. 
.PP
You can see the context of a file using the \fB\-Z\fP option to \fBls\bP
.PP
Policy governs the access confined processes have to these files. 
SELinux zoneminder policy is very flexible allowing users to setup their zoneminder processes in as secure a method as possible.
.PP 
The following file types are defined for zoneminder:


.EX
.PP
.B zoneminder_exec_t 
.EE

- Set files with the zoneminder_exec_t type, if you want to transition an executable to the zoneminder_t domain.


.EX
.PP
.B zoneminder_initrc_exec_t 
.EE

- Set files with the zoneminder_initrc_exec_t type, if you want to transition an executable to the zoneminder_initrc_t domain.


.EX
.PP
.B zoneminder_log_t 
.EE

- Set files with the zoneminder_log_t type, if you want to treat the data as zoneminder log data, usually stored under the /var/log directory.


.EX
.PP
.B zoneminder_spool_t 
.EE

- Set files with the zoneminder_spool_t type, if you want to store the zoneminder files under the /var/spool directory.


.EX
.PP
.B zoneminder_tmpfs_t 
.EE

- Set files with the zoneminder_tmpfs_t type, if you want to store zoneminder files on a tmpfs file system.


.EX
.PP
.B zoneminder_var_lib_t 
.EE

- Set files with the zoneminder_var_lib_t type, if you want to store the zoneminder files under the /var/lib directory.


.EX
.PP
.B zoneminder_var_run_t 
.EE

- Set files with the zoneminder_var_run_t type, if you want to store the zoneminder files under the /run directory.


.PP
Note: File context can be temporarily modified with the chcon command.  If you want to permanantly change the file context you need to use the 
.B semanage fcontext 
command.  This will modify the SELinux labeling database.  You will need to use
.B restorecon
to apply the labels.

.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files. 
SELinux zoneminder policy is very flexible allowing users to setup their zoneminder processes in as secure a method as possible.
.PP 
The following process types are defined for zoneminder:

.EX
.B zoneminder_t 
.EE
.PP
Note: 
.B semanage permississive -a PROCESS_TYPE 
can be used to make a process type permissive. Permissive process types are not denied access by SELinux. AVC messages will still be generated.

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules

.PP
.B system-config-selinux 
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR	
This manual page was autogenerated by genman.py.

.SH "SEE ALSO"
selinux(8), zoneminder(8), semanage(8), restorecon(8), chcon(1)
