.TH "sedispatch" "8" "20100915" "" ""
.SH "NAME"
sedispatch \- setroubleshoot audit dispatcher for SELinux Messages

.SH "SYNOPSIS"
.B sedispatch

.SH "DESCRIPTION"
This manual page describes the
.BR sedispatch
program.
.P
sedispatch is audit dispatcher.  It scans audit messages for SELinux AVC messages, formats them into a dbus message and sends it to setroubleshootd
.SH "AUTHOR"
This man page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
.BR audispd (8), auditd (8),
