.TH "setroubleshootd" "8" "20100520" "" ""
.SH "NAME"
setroubleshootd \- setroubleshoot daemon

.SH "SYNOPSIS"
.B setroubleshootd
.I [\-b] [-\f] [\-h] [\H] [\-s] [-S] [\-l id] [\-a file] [-v] [-V] [-u] [-p]

.SH "DESCRIPTION"
This manual page describes the
.BR setroubleshootd
program.
.P
setroubleshootd is the dbus service in the setroubleshoot system. 
setroubleshoot is used to diagnose SELinux denials and attempts to 
provide user friendly explanations for a SELinux denial (e.g. AVC) 
and recommendations for how one might adjust the system to prevent 
the denial in the future.
.P
In a standard configuration setroubleshoot is composed of two
components, sealert and setroubleshootd.
.P
setroubleshootd is a system daemon which runs with root privileges and
listens for audit events emitted from the kernel related to
SELinux. When the setroubleshootd daemon sees an SELinux AVC denial it
runs a series of analysis plugins which examines the audit data
related to the AVC. It records the results of the analysis and signals
any clients which have attached to the setroubleshootd daemon that a
new alert has been seen.

.SH "OPTIONS"
.TP 
.B \-b \-\-browser        
Launch the browser
.TP 
.B \-f \-\-nofork
Do not fork the daemon
.TP 
.B \-h \-\-help           
Show this message
.TP 
.B \-c \-\-config
section.option=value	set a configuration value
.TP 
.B \-v \-\-verbose
log INFO level and higher messages to console
.TP 
.B \-V \-\-debug
log DEBUG level and higher messages to console

.SH "AUTHOR"
This man page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
.BR sealert(8), selinux (8)
