name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v2
      - run: dnf install --nogpgcheck -y git-core checkpolicy policycoreutils-devel make m4 findutils
      - run: git clone --depth=1 https://github.com/containers/container-selinux.git /tmp/container-selinux
      - run: cp /tmp/container-selinux/container.* policy/modules/contrib
      - run: make -j $(nproc) policy
      - run: make -j $(nproc) validate
      - run: make -j $(nproc) container.pp
  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
      options: --security-opt seccomp=unconfined
    steps:
      - run: dnf install --nogpgcheck -y make git-core rpm-build 'dnf-command(builddep)'
      - uses: actions/checkout@v2
      - run: make -C .copr srpm outdir="$PWD"
      - name: Store the SRPM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: srpm
          path: "*.src.rpm"
      - run: dnf builddep --nogpgcheck --repofrompath 'koji,https://kojipkgs.fedoraproject.org/repos/$releasever/latest/$arch/' -y --srpm *.src.rpm
      - run: rpmbuild --define "_topdir $PWD/rpmbuild" -rb *.src.rpm
      - name: Store binary RPMs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rpms
          path: rpmbuild/RPMS
  selint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y uthash-dev libconfuse-dev autoconf-archive m4
      - name: Build templated .if and .te files
        run: make generate
      - name: Clone the SELint repo
        run: git clone https://github.com/TresysTechnology/selint /tmp/selint
      - name: Build SELint
        run: |
          cd /tmp/selint
          git checkout d939a02e7528e623c8f8a091c392ed021047dba4
          autoreconf -i
          ./configure --without-check
          make -j $(nproc)
          sudo make -j $(nproc) install
      - name: Run SELint
        run: |
          selint -s -r . -F \
            -d W-001 -d W-002 -d W-003 -d W-004 -d W-005 -d W-006 -d W-008 -d W-011 \
            -d S-001 -d S-002 -d S-009 -d S-010 \
            -d C-001 -d C-005 -d C-006
